from __future__ import annotations

import hashlib
import platform
import random
import re
import zlib
from typing import Any, Callable

import openpyxl
from openpyxl import Workbook

from .e2_r17_controlled_suite_schema import answer_range

PROCEDURAL = "PROCEDURAL_TRANSFORMATION"
BINDING = "INSTANCE_BINDING_LOCALIZATION"
SEMANTIC_TYPES = (PROCEDURAL, BINDING)

SKELETONS = (
    "cross_join_ledger",
    "cross_measure_panel",
    "cross_snapshot_bundle",
    "cross_group_window",
    "cross_lookup_reconcile",
)

SKELETON_CODES = {
    "cross_join_ledger": "cjl",
    "cross_measure_panel": "cmp",
    "cross_snapshot_bundle": "csb",
    "cross_group_window": "cgw",
    "cross_lookup_reconcile": "clr",
}

SEMANTIC_CODES = {PROCEDURAL: "p", BINDING: "b"}

# XLSX payload bytes depend on both openpyxl serialization and the zlib runtime.
# Freeze the exact generation stack used by the content-addressed V3 suite so a
# rebuild under a different compression runtime fails closed instead of being
# misdiagnosed as scientific task drift.
EXPECTED_GENERATION_RUNTIME = {
    "python_implementation": "CPython",
    "python_version": "3.12.3",
    "openpyxl_version": "3.1.5",
    "zlib_compile_version": "1.3",
    "zlib_runtime_version": "1.3",
}


def generation_runtime_fingerprint() -> dict[str, str]:
    return {
        "python_implementation": platform.python_implementation(),
        "python_version": platform.python_version(),
        "openpyxl_version": openpyxl.__version__,
        "zlib_compile_version": zlib.ZLIB_VERSION,
        "zlib_runtime_version": getattr(zlib, "ZLIB_RUNTIME_VERSION", zlib.ZLIB_VERSION),
    }


def require_generation_runtime() -> dict[str, str]:
    actual = generation_runtime_fingerprint()
    if actual != EXPECTED_GENERATION_RUNTIME:
        raise RuntimeError(
            "semantic-transfer V3 generation runtime drift: "
            f"expected={EXPECTED_GENERATION_RUNTIME} actual={actual}"
        )
    return actual


# These labels are experimental strata only. They are never valid inputs to the
# deployable router. Each skeleton is generated by one function accepting the
# semantic cell, so the semantic contrast is crossed inside a common template.
CELL_SPECS: dict[tuple[str, str], dict[str, Any]] = {
    (skeleton, semantic): {
        "matched_skeleton": skeleton,
        "semantic_type": semantic,
        "experimental_reusable_transform_steps": 3 if semantic == PROCEDURAL else 1,
        "experimental_binding_candidate_count": 1 if semantic == PROCEDURAL else 3,
    }
    for skeleton in SKELETONS
    for semantic in SEMANTIC_TYPES
}

ALT_WORDS = ("candidate", "previous", "estimate", "legacy", "forecast")
_STEP_RE = re.compile(r"\bStep\s+([1-9][0-9]*)\s*:", re.IGNORECASE)


def visible_router_features(instruction: str) -> dict[str, int]:
    """Compute router features from the exact actor-visible instruction only.

    This function deliberately has no task/family/skeleton/semantic arguments.
    Hidden generator metadata therefore cannot enter automatic routing.
    """

    steps = {int(match.group(1)) for match in _STEP_RE.finditer(instruction)}
    lower = instruction.lower()
    alternatives = sum(1 for word in ALT_WORDS if re.search(rf"\b{re.escape(word)}\b", lower))
    cross_sheet = len(set(re.findall(r"\b(?:Ledger|Lookup|Measures|Snapshot|Corrections|Events|Rules|Reference|Result)\b", instruction)))
    return {
        "visible_operation_clause_count": len(steps),
        "visible_binding_alternative_count": alternatives,
        "visible_cross_sheet_reference_count": cross_sheet,
    }


def observable_route(instruction: str) -> str:
    f = visible_router_features(instruction)
    if f["visible_operation_clause_count"] >= 3 and f["visible_binding_alternative_count"] <= 1:
        return "MRW4"
    if f["visible_binding_alternative_count"] >= 2 and f["visible_operation_clause_count"] <= 2:
        return "WIN-C"
    return "UNCLASSIFIED"


def paired_seed_key(*, block: int, skeleton: str, profile_index: int) -> str:
    return f"semantic-transfer-v3-pair|b{block}|{skeleton}|p{profile_index}"


def paired_rng(*, block: int, skeleton: str, profile_index: int) -> random.Random:
    key = paired_seed_key(block=block, skeleton=skeleton, profile_index=profile_index)
    seed = int(hashlib.sha256(key.encode("utf-8")).hexdigest()[:16], 16)
    return random.Random(seed)


def _finish(
    semantic: str,
    instruction: str,
    payload: dict[str, Any],
    *,
    last_row: int = 4,
) -> tuple[str, str, dict[str, Any]]:
    features = visible_router_features(instruction)
    route = observable_route(instruction)
    expected_route = "MRW4" if semantic == PROCEDURAL else "WIN-C"
    if route != expected_route:
        raise RuntimeError(f"observable router mismatch: semantic={semantic} route={route} features={features}")
    return instruction, answer_range(last_row), {
        **payload,
        "observable_router_features": features,
        "observable_router_route": route,
    }


def build_cross_join_ledger(
    wb: Workbook, rng: random.Random, depth: int, ambiguity: int, semantic: str
) -> tuple[str, str, dict[str, Any]]:
    ledger = wb.create_sheet("Ledger")
    lookup = wb.create_sheet("Lookup")
    ledger.append([
        "row_id", "current_key", "candidate_key", "previous_key", "current_amount", "candidate_amount",
        "previous_amount", "units", "discount_rate", "status",
    ])
    lookup.append(["current_key", "candidate_key", "previous_key", "multiplier"])
    keys = [f"K{i:02d}" for i in range(1, 7)]
    mult = {key: round(0.85 + 0.06 * i, 2) for i, key in enumerate(keys)}
    for i, key in enumerate(keys):
        lookup.append([key, f"C{i:02d}", f"P{i:02d}", mult[key]])
    rows: list[dict[str, Any]] = []
    for i in range(14 + depth * 3):
        key = keys[(i * 3 + ambiguity) % len(keys)]
        amount = float(rng.randint(20, 180))
        units = 1 + (i % 4)
        discount = (i % 3) * 0.05
        status = "active" if i % 4 else "inactive"
        row = {
            "key": key,
            "amount": amount,
            "units": units,
            "discount": discount,
            "status": status,
        }
        rows.append(row)
        ledger.append([
            f"L{i+1:03d}", key, f"C{(i+1)%len(keys):02d}", f"P{(i+2)%len(keys):02d}", amount,
            amount + 400, amount + 800, units, discount, status,
        ])
    result = wb["Result"]
    if semantic == PROCEDURAL:
        values = [round(r["amount"] * r["units"] * mult[r["key"]] * (1.0 - r["discount"]), 2) for r in rows if r["status"] == "active"]
        result["B2"] = round(sum(values), 2)
        result["B3"] = len(values)
        result["B4"] = max(values) if values else 0.0
        instruction = (
            "Use Ledger.current_key and Ledger.current_amount. Step 1: retain rows whose status is active. "
            "Step 2: join current_key to Lookup.current_key and multiply current_amount by units and Lookup.multiplier. "
            "Step 3: apply discount_rate as value * (1 - discount_rate). Step 4: aggregate the transformed rows. "
            "Write the sum to Result!B2, row count to Result!B3, maximum to Result!B4, and save as output.xlsx."
        )
        return _finish(semantic, instruction, {"values": values})
    values = [r["amount"] * mult[r["key"]] for r in rows]
    result["B2"] = round(sum(values), 2)
    result["B3"] = len(values)
    result["B4"] = max(values) if values else 0.0
    instruction = (
        "In Ledger and Lookup, identify the authoritative current key and current amount; do not use candidate or previous "
        "keys/amounts. Step 1: bind the authoritative Ledger key to the authoritative Lookup key. Step 2: multiply the "
        "authoritative amount by the matched multiplier and aggregate it. Write the sum to Result!B2, row count to Result!B3, "
        "maximum to Result!B4, and save as output.xlsx."
    )
    return _finish(semantic, instruction, {"values": values})


def build_cross_measure_panel(
    wb: Workbook, rng: random.Random, depth: int, ambiguity: int, semantic: str
) -> tuple[str, str, dict[str, Any]]:
    ws = wb.create_sheet("Measures")
    ws.append(["item_id", "current_value", "estimate_value", "previous_value", "scale", "status", "group"])
    rows: list[dict[str, Any]] = []
    for i in range(12 + depth * 2):
        value = float(rng.randint(60, 900))
        scale = (1, 10, 100)[(i + ambiguity) % 3]
        status = "active" if i % 5 else "inactive"
        group = ("A", "B", "C")[i % 3]
        rows.append({"value": value, "scale": scale, "status": status, "group": group})
        ws.append([f"M{i+1:03d}", value, value + 500, value + 900, scale, status, group])
    result = wb["Result"]
    if semantic == PROCEDURAL:
        values = [round(r["value"] / r["scale"], 2) for r in rows if r["status"] == "active"]
        selected = sorted(values, reverse=True)[:3]
        result["B2"] = round(sum(selected), 2)
        result["B3"] = max(selected) if selected else 0.0
        result["B4"] = len(selected)
        instruction = (
            "Use Measures.current_value. Step 1: normalize each value by dividing by scale. Step 2: retain only active rows. "
            "Step 3: rank normalized values from largest to smallest and keep the top three. Step 4: aggregate the selected values. "
            "Write their sum to Result!B2, maximum to Result!B3, count to Result!B4, and save as output.xlsx."
        )
        return _finish(semantic, instruction, {"selected": selected})
    values = [r["value"] for r in rows]
    result["B2"] = round(sum(values), 2)
    result["B3"] = round(sum(values) / len(values), 2)
    result["B4"] = len(values)
    instruction = (
        "In Measures, choose the authoritative current value rather than the estimate or previous value. Step 1: select that "
        "authoritative field. Step 2: aggregate it over all rows. Write the sum to Result!B2, mean rounded to 2 decimals to "
        "Result!B3, row count to Result!B4, and save as output.xlsx."
    )
    return _finish(semantic, instruction, {"values": values})


def build_cross_snapshot_bundle(
    wb: Workbook, rng: random.Random, depth: int, ambiguity: int, semantic: str
) -> tuple[str, str, dict[str, Any]]:
    snap = wb.create_sheet("Snapshot")
    corr = wb.create_sheet("Corrections")
    snap.append(["record_id", "current_amount", "candidate_amount", "previous_amount", "status"])
    corr.append(["record_id", "current_replacement", "candidate_replacement", "previous_replacement", "apply_flag"])
    state: dict[str, tuple[float, str]] = {}
    n = 11 + depth * 2
    for i in range(n):
        rid = f"S{i+1:03d}"
        amount = float(rng.randint(25, 230))
        status = "active" if i % 4 else "inactive"
        state[rid] = (amount, status)
        snap.append([rid, amount, amount + 450, amount + 850, status])
    corrections: list[tuple[str, float, int]] = []
    for i in range(0, n, 3):
        rid = f"S{i+1:03d}"
        replacement = state[rid][0] + 10 + ambiguity
        flag = 1 if i % 6 != 3 else 0
        corrections.append((rid, replacement, flag))
        corr.append([rid, replacement, replacement + 500, replacement + 900, flag])
    result = wb["Result"]
    if semantic == PROCEDURAL:
        work = dict(state)
        for rid, replacement, flag in corrections:
            if flag:
                work[rid] = (replacement, work[rid][1])
        values = [amount for amount, status in work.values() if status == "active" and amount >= 80]
        result["B2"] = round(sum(values), 2)
        result["B3"] = len(values)
        result["B4"] = max(values) if values else 0.0
        instruction = (
            "Use Snapshot.current_amount and Corrections.current_replacement. Step 1: apply Corrections rows whose apply_flag is 1 "
            "by record_id. Step 2: retain active records after reconciliation. Step 3: retain reconciled amounts at least 80. "
            "Step 4: aggregate the retained amounts. Write sum to Result!B2, count to Result!B3, maximum to Result!B4, and save as output.xlsx."
        )
        return _finish(semantic, instruction, {"values": values})
    values = [amount for amount, _ in state.values()]
    result["B2"] = round(sum(values), 2)
    result["B3"] = len(values)
    result["B4"] = max(values) if values else 0.0
    instruction = (
        "In Snapshot and Corrections, identify the authoritative current amount/replacement fields; do not use candidate or previous "
        "versions. Step 1: select the authoritative Snapshot amount field. Step 2: aggregate it without applying alternative replacement "
        "fields. Write sum to Result!B2, count to Result!B3, maximum to Result!B4, and save as output.xlsx."
    )
    return _finish(semantic, instruction, {"values": values})


def build_cross_group_window(
    wb: Workbook, rng: random.Random, depth: int, ambiguity: int, semantic: str
) -> tuple[str, str, dict[str, Any]]:
    events = wb.create_sheet("Events")
    events.append([
        "event_id", "current_group", "candidate_group", "previous_group", "current_value", "estimate_value",
        "previous_value", "event_order", "status",
    ])
    rows: list[dict[str, Any]] = []
    groups = ("North", "South", "West")
    for i in range(15 + depth * 3):
        group = groups[(i + ambiguity) % len(groups)]
        value = float(rng.randint(20, 190))
        status = "active" if i % 5 else "inactive"
        row = {"group": group, "value": value, "order": i + 1, "status": status}
        rows.append(row)
        events.append([
            f"E{i+1:03d}", group, groups[(i+1)%3], groups[(i+2)%3], value, value + 300, value + 700, i + 1, status,
        ])
    result = wb["Result"]
    if semantic == PROCEDURAL:
        active = [r for r in rows if r["status"] == "active"]
        selected: list[float] = []
        for group in groups:
            group_rows = sorted((r for r in active if r["group"] == group), key=lambda r: r["order"], reverse=True)[:2]
            selected.extend(r["value"] for r in group_rows)
        result["B2"] = round(sum(selected), 2)
        result["B3"] = len(selected)
        result["B4"] = max(selected) if selected else 0.0
        instruction = (
            "Use Events.current_group and Events.current_value. Step 1: retain active events. Step 2: partition events by current_group. "
            "Step 3: order each group by event_order descending and keep the latest two events. Step 4: aggregate all retained current_value entries. "
            "Write sum to Result!B2, count to Result!B3, maximum to Result!B4, and save as output.xlsx."
        )
        return _finish(semantic, instruction, {"selected": selected})
    values = [r["value"] for r in rows]
    result["B2"] = round(sum(values), 2)
    result["B3"] = len(values)
    result["B4"] = max(values) if values else 0.0
    instruction = (
        "In Events, choose the authoritative current group/value fields rather than candidate, estimate, or previous fields. "
        "Step 1: bind each row to its authoritative current_group/current_value pair. Step 2: aggregate the authoritative values. "
        "Write sum to Result!B2, count to Result!B3, maximum to Result!B4, and save as output.xlsx."
    )
    return _finish(semantic, instruction, {"values": values})


def build_cross_lookup_reconcile(
    wb: Workbook, rng: random.Random, depth: int, ambiguity: int, semantic: str
) -> tuple[str, str, dict[str, Any]]:
    facts = wb.create_sheet("Ledger")
    rules = wb.create_sheet("Rules")
    facts.append([
        "row_id", "current_category", "candidate_category", "previous_category", "current_amount", "estimate_amount",
        "previous_amount", "status",
    ])
    rules.append(["current_category", "candidate_category", "previous_category", "adjustment"])
    categories = ("A", "B", "C", "D")
    adjustment = {cat: round(0.9 + idx * 0.08, 2) for idx, cat in enumerate(categories)}
    for idx, cat in enumerate(categories):
        rules.append([cat, categories[(idx+1)%4], categories[(idx+2)%4], adjustment[cat]])
    rows: list[dict[str, Any]] = []
    for i in range(14 + depth * 2):
        cat = categories[(i + ambiguity) % len(categories)]
        amount = float(rng.randint(30, 240))
        status = "active" if i % 4 else "inactive"
        rows.append({"category": cat, "amount": amount, "status": status})
        facts.append([
            f"R{i+1:03d}", cat, categories[(i+1)%4], categories[(i+2)%4], amount, amount + 350, amount + 750, status,
        ])
    result = wb["Result"]
    if semantic == PROCEDURAL:
        values = [round(r["amount"] * adjustment[r["category"]], 2) for r in rows if r["status"] == "active"]
        result["B2"] = round(sum(values), 2)
        result["B3"] = len(values)
        result["B4"] = max(values) if values else 0.0
        instruction = (
            "Use Ledger.current_category and Ledger.current_amount. Step 1: retain active Ledger rows. Step 2: join current_category "
            "to Rules.current_category. Step 3: multiply current_amount by the matched adjustment. Step 4: aggregate the adjusted values. "
            "Write sum to Result!B2, count to Result!B3, maximum to Result!B4, and save as output.xlsx."
        )
        return _finish(semantic, instruction, {"values": values})
    values = [r["amount"] for r in rows]
    result["B2"] = round(sum(values), 2)
    result["B3"] = len(values)
    result["B4"] = max(values) if values else 0.0
    instruction = (
        "In Ledger and Rules, choose the authoritative current category/amount fields rather than candidate, estimate, or previous "
        "fields. Step 1: select the authoritative Ledger category and amount. Step 2: aggregate the authoritative amounts. "
        "Write sum to Result!B2, count to Result!B3, maximum to Result!B4, and save as output.xlsx."
    )
    return _finish(semantic, instruction, {"values": values})


BUILDERS: dict[str, Callable[[Workbook, random.Random, int, int, str], tuple[str, str, dict[str, Any]]]] = {
    "cross_join_ledger": build_cross_join_ledger,
    "cross_measure_panel": build_cross_measure_panel,
    "cross_snapshot_bundle": build_cross_snapshot_bundle,
    "cross_group_window": build_cross_group_window,
    "cross_lookup_reconcile": build_cross_lookup_reconcile,
}
