from __future__ import annotations

from collections import Counter
from typing import Any


POLICY: dict[str, Any] = {
    "schema_version": "1.0",
    "external_design_requires_primary_or_official_source": True,
    "component_name_similarity_is_not_adoption_evidence": True,
    "every_candidate_design_requires_local_gap_test": True,
    "redundant_designs_merge_into_existing_component": True,
    "adoption_requires_named_failure_mode_and_machine_check": True,
    "external_system_never_overrides_local_scientific_authority": True,
}

SYSTEM_DESIGNS = [
    {"system": "Qiushi Discovery Engine", "design": "Meta-Trace + nonlinear research phases", "gap": "long raw traces can outgrow coherent scientific state", "local_mapping": "scientific_meta_trace", "status": "adopted"},
    {"system": "Kosmos", "design": "structured world model shared between literature and analysis agents; statement-level code/literature provenance", "gap": "literature and experiment evidence can fragment into separate contexts", "local_mapping": "scientific_meta_trace + evidence provenance", "status": "adopted"},
    {"system": "MLEvolve", "design": "cross-branch reference edges + retrospective memory + progressive exploration/exploitation", "gap": "branch isolation and greedy local optimization", "local_mapping": "meta-trace + value scheduler + failure assets", "status": "adopted"},
    {"system": "InternAgent-1.5", "design": "generation / verification / evolution subsystems plus reproduction mode", "gap": "new ideas can outrun independent verification", "local_mapping": "principle/evidence gates + replay benchmark", "status": "merged-existing"},
    {"system": "BioMedAgent / Biomni", "design": "declarative tool metadata, tool-aware routing, and reusable workflow memory", "gap": "tool choice can be implicit and hard to audit", "local_mapping": "research capability registry", "status": "adopted"},
    {"system": "AutoResearchClaw", "design": "failure-to-safeguard cross-run learning + verified result registry + targeted HITL", "gap": "failures may be repaired once but not become reusable launch constraints", "local_mapping": "failure assets + protocol validity + AI clinic", "status": "adopted"},
    {"system": "ResearchClawBench", "design": "protocol mismatch / evidence mismatch / missing scientific core as separate error classes", "gap": "method quality can be confounded with invalid research protocol", "local_mapping": "protocol validity + replay benchmark", "status": "adopted"},
    {"system": "HackDetect", "design": "audit benchmark exposure, shortcut use, and score inflation", "gap": "agent may succeed through evaluator leakage or unintended shortcuts", "local_mapping": "protocol validity", "status": "adopted"},
    {"system": "ScienceAgentBench verified split", "design": "verify evaluation artifacts to reduce benchmark false negatives", "gap": "evaluation bugs can masquerade as agent/method failure", "local_mapping": "protocol validity + replay benchmark", "status": "adopted"},
    {"system": "AutoResearchBench", "design": "separate deep target-finding from wide comprehensive literature discovery", "gap": "literature retrieval quality is not one scalar capability", "local_mapping": "literature retrieval audit", "status": "adopted"},
    {"system": "PaperQA2", "design": "separate paper search, evidence gathering, and answer synthesis with grounded citations and redundant metadata", "gap": "retrieval and synthesis can collapse into one opaque step", "local_mapping": "literature retrieval audit + capability registry", "status": "adopted"},
    {"system": "SciNetBench", "design": "ego/pair/path relation-aware scientific retrieval", "gap": "content-similarity retrieval misses support, conflict, and lineage structure", "local_mapping": "literature relation-aware audit", "status": "adopted"},
    {"system": "SciRet", "design": "compute-aware retriever/reranker comparison with domain-mismatch qualification", "gap": "stronger rerankers can be worse on scientific domains", "local_mapping": "retrieval qualification contract", "status": "adopted"},
    {"system": "Citation Faithfulness Audit", "design": "calibrate the citation verifier itself against human gold", "gap": "citation failure rates can move when only the verifier changes", "local_mapping": "citation verifier contract", "status": "adopted"},
    {"system": "ScientistOne", "design": "claim-type-specific Chain-of-Evidence audit for numeric, citation, and method claims", "gap": "professional-looking reports can diverge from logs, sources, or implementation", "local_mapping": "claim-evidence routing", "status": "adopted"},
    {"system": "SAGE", "design": "co-design subqueries and retrievers for reasoning-intensive scientific search", "gap": "keyword-oriented agent subqueries can nullify sophisticated retrievers", "local_mapping": "capability-registry retrieval router + simple-first retriever promotion gate", "status": "adopted"},
    {"system": "ReplicationBench", "design": "paper-scale author-validated replication tasks", "gap": "component-level replay does not yet test full paper replication fidelity", "local_mapping": "research-system replay paper-scale reproduction contract", "status": "adopted"},
    {"system": "SCION", "design": "Research Execution Plan compiles scientific intent into objectives, dependencies, checkpoints, tool requirements, artifacts, and fallbacks", "gap": "a scientifically sound principle can still reach runtime as an underspecified execution request", "local_mapping": "derived Research Execution Plan in Pre-Experiment Compiler", "status": "adopted"},
    {"system": "AutoSci", "design": "separate Active Research Memory from Long-Term Knowledge Memory and version memory/workflow evolution", "gap": "current-project truth and reusable cross-project lessons can otherwise contaminate each other", "local_mapping": "Scientific Meta-Trace memory scopes + institutional Failure Assets", "status": "adopted"},
    {"system": "EvoScientist", "design": "separate ideation and experimentation memory with explicit evolution over repeated research cycles", "gap": "historical lessons need scope and reuse-effectiveness tracking rather than permanent authority", "local_mapping": "institutional memory lifecycle metadata", "status": "merged-existing"},
    {"system": "Agent Operating System (AOS)", "design": "separate Control & Governance Plane from Runtime & Coordination Plane", "gap": "policy and authority decisions should not become implicit side effects of runtime routing", "local_mapping": "existing scientific-control vs research-runtime architecture", "status": "merged-existing"},
    {"system": "Exploration-breadth studies / IDEAgent / Heuresis / SwarmResearch", "design": "measure and actively preserve quality-diversity-novelty breadth across a portfolio rather than optimizing isolated ideas", "gap": "pairwise collision checks do not detect portfolio-wide collapse toward seed literature or one high-level approach", "local_mapping": "cross-cutting exploration-frontier control owned by wide-search ideation", "status": "adopted"},
    {"system": "Agent-experiment preregistration / stochastic experimental design / Search-Time Contamination", "design": "freeze researcher degrees of freedom before outcomes, plan repeated runs for stochastic agents, and audit web/tool access for benchmark metadata, question-context, and answer leakage", "gap": "cheap adaptive iteration and open-web retrieval can silently turn confirmatory experiments into outcome-contingent or contaminated analyses", "local_mapping": "cross-cutting experimental-design-integrity control owned by protocol-and-replay", "status": "adopted"},
    {"system": "ARA / Artisan / ArtifactCopilot", "design": "reconstruct dependency-aware scientific workflows and require independent re-execution rather than treating trace presence as reproducibility", "gap": "claim provenance can be correct while the result-generating workflow remains impossible for a third party to reconstruct and rerun", "local_mapping": "cross-cutting reproducibility-readiness control owned by Evidence Integrity", "status": "adopted"},
    {"system": "EurekAgent", "design": "permissions, artifact, budget, and human-in-the-loop environment engineering", "gap": "logical authorization is insufficient if a low-level runtime capability can be acquired without the controller-owned authority token", "local_mapping": "Runtime & Authority layer: experiment authority is now verified by the GPU lease capability itself; lease provenance stores authority id/epoch and plan hash", "status": "merged-existing", "local_gap_test": {"before": "unauthorized low-level GPU lease succeeded without experiment authority", "after": "the identical low-level acquisition is rejected with GPU lease requires active experiment authority", "verdict": "gap-confirmed-and-closed", "remaining_boundary": "evaluator/result filesystem isolation still requires its own runtime canary before claiming complete environment-level permission enforcement"}},
    {"system": "The AI Scientist / AI Scientist-v2", "design": "treat plotting as an experiment artifact and stage experiment search through checkpointed branches before manuscript synthesis", "gap": "our evidence compiler could certify tables while leaving reviewer-critical mechanism/failure evidence visually opaque, while runner-specific branch search could also blur scheduling preference with scientific evidence selection", "local_mapping": "FigureClaimGraph + ExperimentTree: visual claims bind to completed evidence, while branch scores schedule attention only and every completed result remains visible", "status": "adopted", "source": "https://www.nature.com/articles/s41586-026-10265-5", "local_gap_test": {"before": "figure QA and experiment branching existed in separate paper/runner-specific paths without one reusable evidence-selection boundary", "after": "FigureClaimGraph blocks missing evidence/required uncertainty and ExperimentTree marks branch scores as scheduling-only with evidence_selected_by_score=false on every node", "verdict": "gap-confirmed-and-closed"}},
    {"system": "PaperVizAgent", "design": "generate academic figures from source context plus explicit communicative intent, then iteratively critique faithfulness, conciseness, readability, and aesthetics", "gap": "a figure-generation script alone does not specify what scientific question the figure must answer or whether its caption matches the claim", "local_mapping": "reviewer-question -> claim -> evidence -> data/script/figure/caption binding with figure-review checks", "status": "adopted", "source": "https://research.google/blog/improving-the-academic-workflow-introducing-two-ai-agents-for-better-figures-and-peer-review/"},
    {"system": "Agent Laboratory", "design": "visualize multi-dimensional human evaluation and auto-vs-human reviewer distributions rather than reporting one aggregate score", "gap": "aggregate paper or system scores can hide topic/model heterogeneity and evaluator bias", "local_mapping": "failure/stratified/human-evaluation visual roles and negative-regime visibility", "status": "adopted", "source": "https://arxiv.org/abs/2501.04227"},
    {"system": "ERA / AI co-scientist / Kosmos", "design": "pair system-overview figures with progression/scaling, heldout performance, uncertainty, breakthrough/search trajectories, and human or experimental validation", "gap": "a research-system paper can look complete while showing only terminal scores and no evidence of how quality changes with compute, cycles, or search depth", "local_mapping": "system archetype requires overview + scaling/progression + comparison + failure + sensitivity visual evidence", "status": "adopted", "source": "https://www.nature.com/articles/s41586-026-10658-6"},
    {"system": "Science One Framework", "design": "bind manuscript claims to evidence chains and audit score, reference, and method-code alignment", "gap": "a paper-completion agent could previously satisfy generic evidence completion with plausible-looking artifact path strings or cite an unregistered evidence ID even when the underlying file was missing or stale", "local_mapping": "Paper Evidence Quality content-addressed completion now binds every completed baseline/ablation/analysis/output and quantitative visual to in-root files with SHA256 receipts; claim adjudications may cite only registered completed evidence IDs", "status": "adopted", "source": "https://research.google/blog/science-one-framework-a-verifiable-autonomous-research-framework-via-chain-of-evidence/", "local_gap_test": {"before": "synthetic completion passed with nonexistent generated/*.json and paper/*.pdf path strings", "after": "the same completion fails unless every referenced artifact/data/script exists under the project root and matches its frozen SHA256; fake claim evidence IDs are rejected", "verdict": "gap-confirmed-and-closed"}},
    {"system": "ARIS / Auto-Research-In-Sleep", "design": "separate breadth fan-out from cross-model adjudication, persist research artifacts across stages, prevent executor self-acquittal, separate search effort from assurance, and feed failed/open research memory back into later work through a bounded wiki context", "gap": "the local system already had typed search closure, Failure Assets, Meta-Trace, and strict scientific gates, but failure/success/open-question memory was fragmented and Failure Assets were not generically injected into later evidence design", "local_mapping": "fan-out->jury invariants + persistent candidate portfolio + search-funnel telemetry + claim ledger + compiled Research Memory Wiki; IDEA_SEARCH and EXPERIMENT_DESIGN get distinct content-addressed Query Packs, transient operational noise is excluded, and every selected memory id is receipted without changing scientific authority", "status": "adopted", "source": "https://github.com/wanshuiyin/Auto-claude-code-research-in-sleep", "paper": "arXiv:2605.03042", "local_gap_test": {"before": "search closure memory reached ideation, but Failure Assets/success evidence/open questions had no single bounded query-pack interface and evidence design could proceed without proving that historical failures were read", "after": "research_memory_wiki compiles canonical memory with lint and durability classes; v18 Idea Search and bounded Evidence Design receive purpose-specific Query Packs with wiki/query hashes and selected-memory receipts", "verdict": "gap-confirmed-and-closed"}},
    {"system": "ScienceFlow", "design": "represent long-horizon research progress as recoverable executable states and re-anchor from live or archived states", "gap": "atomic progress existed in individual runners, but the system lacked a shared ResearchState/ExperimentManifest identity contract and a fail-closed scientific-reopen rule for archived states", "local_mapping": "Recoverable Research Execution Kernel: ResearchState + frozen execution identity + exact resume + reopen-gated re-anchor", "status": "adopted", "source": "https://arxiv.org/abs/2608.14354", "local_gap_test": {"before": "resume semantics were runner-specific and archive rollback had no common machine-checkable boundary against HOLD/STOP scientific state", "after": "shared ResearchState and ExperimentManifest contracts reject identity drift and forbid execution resume from HOLD/STOP/MERGED/PAPER_READY until the recorded reopen condition has new evidence and independent scientific review", "verdict": "gap-confirmed-and-closed"}},
    {"system": "AutoResearchEval / ARFT", "design": "diagnose complete autoresearch trajectories with a process-level failure taxonomy and a metacognitive loop that checks produced output against evidence and path validity", "gap": "typed failure layers existed, but there was no generic stage-transition receipt comparing scientific intent, protocol, validated evidence, and outgoing claim", "local_mapping": "MetaCognitionReceipt + Failure Taxonomy v2 compatibility layer in the Recoverable Research Execution Kernel", "status": "adopted", "source": "https://arxiv.org/abs/2608.14905", "local_gap_test": {"before": "a downstream component could consume a structurally valid artifact without a common check that its metric, protocol, evidence references, and claim still matched the frozen intent", "after": "MetaCognitionReceipt emits PASS/REVISE and blocks transition on intent drift, protocol deviation, unsupported inference, or unvalidated evidence reference", "verdict": "gap-confirmed-and-closed"}},
    {"system": "TeLLAgent", "design": "decouple global scientific planning from precise local tool execution and recover through supervisor-visible execution feedback", "gap": "the repository had authority separation, but no shared immutable Planner->Executor scientific-contract digest and executor receipt validator", "local_mapping": "PlannerExecutorJobReceipt contract; executor may execute units but cannot change hypothesis/primary metric or self-acquit scientific validity", "status": "adopted", "source": "https://pubs.rsc.org/en/content/articlehtml/2026/sc/d5sc09883a", "local_gap_test": {"before": "planner/executor responsibility was policy-level and runner-specific", "after": "a content-addressed execution job freezes the scientific contract; mismatched or self-validating executor receipts fail closed", "verdict": "gap-confirmed-and-closed"}},
    {"system": "Claw AI Lab", "design": "artifact inspection, rollback/resume, and distinct explore/discuss/reproduce operating modes", "gap": "checkpoint/resume was runner-specific and the system had no common mode contract or read-only artifact inspector that preserved authority boundaries", "local_mapping": "AtomicCheckpoint + ResumeCursor + DISCOVERY/DEBATE/REPRODUCTION/PAPER modes + read-only content-addressed Artifact Inspector", "status": "adopted", "source": "https://arxiv.org/abs/2605.22662", "local_gap_test": {"before": "checkpoint/restart behavior was duplicated and mode semantics were implicit", "after": "shared per-unit checkpoints are paired with explicit research modes; PAPER cannot write validated evidence, REPRODUCTION execution still requires external authority, and artifact inspection blocks path traversal/SHA drift", "verdict": "gap-confirmed-and-closed"}},
    {"system": "Replica / Faraday", "design": "turn paper replication into a scalable scored scientific task rather than treating code availability as reproducibility", "gap": "paper-scale replay existed as a specification, but closest-work qualification did not require a minimal local reproduction when implementation details were load-bearing for novelty", "local_mapping": "ReproductionGate between closest-work qualification and ResearchItem promotion, selecting source inspection, minimal execution, or full replication according to the scientific question", "status": "adopted", "source": "https://arxiv.org/abs/2608.13331", "local_gap_test": {"before": "closest-work qualification could remain paper-only even when the released implementation changed the effective intervention", "after": "three canonical cases matched prior adjudication: Skill-SP and ComfyClaw source-faithful inspection materially sharpened the collision boundary, while LOPD failed closed as a support HOLD because the trained source object is unavailable; 3/3 matched and 0 cases required full retraining", "verdict": "gap-confirmed-and-closed"}},
    {"system": "AHOIS", "design": "Socratic critic performs causal questioning, constraint checks, counterexample generation, and explicit falsification-criterion formulation", "gap": "ProblemGate and simplification challenge were strong, but candidates did not emit one compact plain-language + counterexample + boundary + falsifier certificate before ProblemGate", "local_mapping": "Feynman-Socratic Gate as a zero-authority pre-ProblemGate compression and attack pass", "status": "adopted", "source": "https://arxiv.org/abs/2606.26722", "local_gap_test": {"before": "pre-ProblemGate review could rely on structurally complete but hard-to-compress candidate prose", "after": "a canonical 20-case retrospective regression alerted on all 6 typed problem-novelty reductions with 0 false mature-reduction alerts across 14 HOLD/historically advanced controls; later method/support failures are excluded to prevent hindsight leakage", "verdict": "gap-confirmed-and-closed", "boundary": "retrospective regression validates the gate invariant but is not predictive scientific evidence"}},
    {"system": "Google AI co-scientist", "design": "separate proximity analysis and meta-review from generation/ranking so nearest prior objects and reviewer disagreement are explicitly examined", "gap": "local collision checks and Mock-PC existed, but nearest-object projection and claim-level reviewer disagreement were not reusable zero-authority contracts", "local_mapping": "ProximityProjection + ReviewerIssueGraph MetaReview", "status": "adopted", "source": "https://www.nature.com/articles/s41586-026-10644-y", "local_gap_test": {"before": "nearest prior work/STOP/failure objects and reviewer disagreement were represented in different artifacts", "after": "ProximityProjection returns nearest prior/local/failure/STOP references with novelty_verdict=NOT_AUTHORIZED; MetaReview clusters evidence/action disagreement without voting or granting experiment authority", "verdict": "gap-confirmed-and-closed"}},
    {"system": "Robin", "design": "route broad shallow literature search separately from deep candidate-specific review and use independent analysis trajectories only where interpretation is underdetermined", "gap": "deep/wide retrieval and multi-trajectory analysis were not exposed through one reusable research-reasoning contract", "local_mapping": "LiteratureDepthRouter + AnalysisAmbiguityRouter", "status": "adopted", "source": "https://www.nature.com/articles/s41586-026-10652-y", "local_gap_test": {"before": "analysis ensemble use and literature depth were workflow-specific choices", "after": "DEEP_REVIEW triggers only for collision/reopen/decisive-baseline cases; deterministic metrics remain single-path while analyses with researcher degrees of freedom route to at least three independent trajectories, and consensus has zero scientific authority", "verdict": "gap-confirmed-and-closed"}},
    {"system": "Notes2Skills", "design": "extract reusable scientific skills from lab notes while preserving certainty so tentative judgments do not become firm instructions", "gap": "Research Memory tracked durability and authority boundaries but had 93/93 authority tags and 0/93 certainty tags, so supported interpretations and unresolved states could not be distinguished at the reusable-memory interface", "local_mapping": "Research Memory v1.2 certainty + authority typing; CONFIRMED/SUPPORTED/TENTATIVE/SPECULATIVE/REFUTED/NOT_APPLICABLE are scope-bound, only selected durable prechecks may become zero-authority SkillCandidates, and automatic skill installation is forbidden", "status": "adopted", "source": "https://arxiv.org/abs/2606.11897", "local_gap_test": {"before": "93 current memory entries had explicit scientific-authority boundaries but no certainty field", "after": "93/93 current entries are certainty-typed; a stratified 30-entry replay typed 30/30 with zero unsafe SkillCandidates and zero automatic promotions; legacy v1.1 memory remains readable", "verdict": "gap-confirmed-and-closed"}},
    {"system": "SGHA", "design": "corpus-first research-problem discovery through typed evidence structure and unresolved structural-gap detection before proposal formulation", "gap": "the local discovery engine is strong on reductions and anomaly lanes but its live search prior can still overproduce method-shaped proposals instead of explicitly scheduling under-explained important phenomena", "local_mapping": "zero-authority Problem-First Shadow Prior with 120-candidate contribution-balanced generation targets; it normalizes into existing live lanes and does not change the discovery operator/provider budget until prospective validation", "status": "merged-existing", "source": "https://arxiv.org/abs/2608.17501", "local_gap_test": {"before": "no explicit corpus-first under-explained-phenomenon prior was represented in the canonical discovery contract", "after": "four problem-first shadow primitives and a 30/25/20/15/15/10/5 generation prior are installed without changing live discovery authority", "verdict": "shadow-gap-closed-live-migration-pending", "boundary": "shadow scheduling is not evidence that problem-first candidates outperform the current generator"}},
    {"system": "FirstResearch", "design": "make the first research question auditable through a structured certificate containing assumptions, mechanism, falsifier, and minimal decisive test", "gap": "the Feynman-Socratic certificate captured problem/counterexample/boundary/falsifier but did not explicitly separate problem importance, under-explained observation, missing insight, minimal decisive test, and minimal sufficient intervention", "local_mapping": "Problem-Insight shadow extension of the existing Feynman-Socratic Gate; no new authority center", "status": "merged-existing", "source": "https://arxiv.org/abs/2607.05682", "local_gap_test": {"before": "a candidate could be compressible yet still fail to state where the primary contribution and minimal sufficient intervention live", "after": "future candidates may bind primary contribution, problem importance, under-explained observation, missing insight, minimal decisive test/intervention, and predictions while the legacy live clearance remains unchanged", "verdict": "shadow-gap-closed-live-migration-pending"}},
    {"system": "Scideator", "design": "decompose papers and ideas into purpose, mechanism, and evaluation facets so novelty can be inspected at a finer granularity than the whole idea", "gap": "the local Scientific Object Matrix represented failure/intervention/substrate/observable but did not explicitly attribute novelty and simplification by contribution layer", "local_mapping": "Contribution Attribution over problem/phenomenon/insight/mechanism/method/evaluation/theory/system plus Simplification Attribution", "status": "merged-existing", "source": "https://arxiv.org/abs/2409.14634", "local_gap_test": {"before": "matched simplification could be interpreted as a whole-paper weakness even when only the method layer was reproduced", "after": "a canonical 40-case retrospective regression preserves all typed controls, catches all current problem-novelty reductions, and produces zero wrong whole-paper stops from method-only reductions", "verdict": "gap-confirmed-in-shadow", "boundary": "retrospective replay validates attribution logic, not future paper acceptance"}},
    {"system": "Research skill ecosystems (Academic Research Skills / Scientific Agent Skills / Auto-Empirical / AI-Research-SKILLs)", "design": "large domain skill libraries expose specialized literature, statistics, causal inference, scientific-computing, and ML practice", "gap": "the first local integration still left eight external packs as a future install catalog rather than owning the useful invariants locally", "local_mapping": "distilled into the Research Capability Registry as canonical internal skills for source evidence, statistics, causal empirical analysis, AI/ML experiment engineering, signal/scientific computing, formal math verification, and evidence-first manuscript work; external packs are provenance only", "status": "merged-existing", "local_gap_test": {"before": "eight reviewed skill packs were catalogued-not-installed and would still be runtime dependencies if later activated", "after": "all eight are resolved through an explicit keep/discard ledger into seven local typed skills; autoresearch/install-all and unrelated/duplicate surfaces are discarded, remaining external runtime dependencies=0", "verdict": "gap-confirmed-and-closed", "automatic_skill_installation": False, "external_runtime_dependencies": 0, "scientific_authority": False}},
    {"system": "Manuscript integrity skill ecosystems (Claude Scholar / nature-skills / Research Paper Writing Skills)", "design": "separate reference checking, evidence-first writing, editorial polishing, and independent manuscript review", "gap": "the local Paper Acceptance CI already named citation/numeric/table/claim checks but could accept boolean check results without one reusable content-addressed post-draft provenance receipt", "local_mapping": "merged into Paper Acceptance as Post-Draft Integrity: deterministic fact/citation/number/table/claim/reader/prose audit before independent model review, then findings enter ReviewerIssueGraph and are re-audited after repair", "status": "merged-existing", "local_gap_test": {"before": "manuscript CI checks were named but their lower-level provenance could be runner-specific", "after": "Post-Draft Integrity binds manuscript SHA, content inventory, citation dimensions, numeric artifacts, table cells/source fields, claim evidence, first-use definitions, and editorial lint; legacy ledgers remain valid", "verdict": "gap-confirmed-and-closed", "experiment_authority": False, "scientific_authority": False}},
    {"system": "SAGE-MHFA", "design": "retain and rank multiple competing evidence-grounded failure explanations before routing repair to formulation, experiment design, or execution", "gap": "the existing post-screen differential-diagnosis checkpoint asks for one typed failure layer, but there was no prospective pre-adjudication registry that could later test whether retaining top-k explanations improves attribution without hindsight leakage", "local_mapping": "merged into the existing post_screen_differential_diagnosis checkpoint + Failure Asset Library as a zero-authority prospective FailureDifferentialRegistry; no new gate or authority center", "status": "merged-existing", "local_gap_test": {"historical_terminalized_failure_labels": 27, "minimum_prospective_replay_cases": 15, "prospective_scored_cases": 0, "historical_labels_can_backfill_hypotheses": False, "verdict": "shadow-registry-installed-prospective-replay-pending", "falsifier": "freeze top-k hypotheses before final adjudication on at least 15 future failed/nonpositive traces, then compare top-1 versus top-k correct-layer attribution and unnecessary-pivot rate at identical evidence/reviewer budget; historical final labels may inventory support but cannot be used to generate retrospective hypotheses"}},
]


def build_external_system_learning_state() -> dict[str, Any]:
    counts = Counter(str(row["status"]) for row in SYSTEM_DESIGNS)
    return {
        "schema_version": "1.0",
        "policy": POLICY,
        "summary": {
            "systems_reviewed": len(SYSTEM_DESIGNS),
            "adopted": counts.get("adopted", 0),
            "merged_existing": counts.get("merged-existing", 0),
            "next_backlog": counts.get("next", 0),
        },
        "designs": SYSTEM_DESIGNS,
        "next_backlog": [row for row in SYSTEM_DESIGNS if row["status"] == "next"],
    }
