from __future__ import annotations

from collections import Counter
from typing import Any


POLICY: dict[str, Any] = {
    "schema_version": "1.0",
    "external_design_requires_primary_or_official_source": True,
    "component_name_similarity_is_not_adoption_evidence": True,
    "every_candidate_design_requires_local_gap_test": True,
    "redundant_designs_merge_into_existing_component": True,
    "adoption_requires_named_failure_mode_and_machine_check": True,
    "external_system_never_overrides_local_scientific_authority": True,
}

SYSTEM_DESIGNS = [
    {"system": "Qiushi Discovery Engine", "design": "Meta-Trace + nonlinear research phases", "gap": "long raw traces can outgrow coherent scientific state", "local_mapping": "scientific_meta_trace", "status": "adopted"},
    {"system": "Kosmos", "design": "structured world model shared between literature and analysis agents; statement-level code/literature provenance", "gap": "literature and experiment evidence can fragment into separate contexts", "local_mapping": "scientific_meta_trace + evidence provenance", "status": "adopted"},
    {"system": "MLEvolve", "design": "cross-branch reference edges + retrospective memory + progressive exploration/exploitation", "gap": "branch isolation and greedy local optimization", "local_mapping": "meta-trace + value scheduler + failure assets", "status": "adopted"},
    {"system": "InternAgent-1.5", "design": "generation / verification / evolution subsystems plus reproduction mode", "gap": "new ideas can outrun independent verification", "local_mapping": "principle/evidence gates + replay benchmark", "status": "merged-existing"},
    {"system": "BioMedAgent / Biomni", "design": "declarative tool metadata, tool-aware routing, and reusable workflow memory", "gap": "tool choice can be implicit and hard to audit", "local_mapping": "research capability registry", "status": "adopted"},
    {"system": "AutoResearchClaw", "design": "failure-to-safeguard cross-run learning + verified result registry + targeted HITL", "gap": "failures may be repaired once but not become reusable launch constraints", "local_mapping": "failure assets + protocol validity + AI clinic", "status": "adopted"},
    {"system": "ResearchClawBench", "design": "protocol mismatch / evidence mismatch / missing scientific core as separate error classes", "gap": "method quality can be confounded with invalid research protocol", "local_mapping": "protocol validity + replay benchmark", "status": "adopted"},
    {"system": "HackDetect", "design": "audit benchmark exposure, shortcut use, and score inflation", "gap": "agent may succeed through evaluator leakage or unintended shortcuts", "local_mapping": "protocol validity", "status": "adopted"},
    {"system": "ScienceAgentBench verified split", "design": "verify evaluation artifacts to reduce benchmark false negatives", "gap": "evaluation bugs can masquerade as agent/method failure", "local_mapping": "protocol validity + replay benchmark", "status": "adopted"},
    {"system": "AutoResearchBench", "design": "separate deep target-finding from wide comprehensive literature discovery", "gap": "literature retrieval quality is not one scalar capability", "local_mapping": "literature retrieval audit", "status": "adopted"},
    {"system": "PaperQA2", "design": "separate paper search, evidence gathering, and answer synthesis with grounded citations and redundant metadata", "gap": "retrieval and synthesis can collapse into one opaque step", "local_mapping": "literature retrieval audit + capability registry", "status": "adopted"},
    {"system": "SciNetBench", "design": "ego/pair/path relation-aware scientific retrieval", "gap": "content-similarity retrieval misses support, conflict, and lineage structure", "local_mapping": "literature relation-aware audit", "status": "adopted"},
    {"system": "SciRet", "design": "compute-aware retriever/reranker comparison with domain-mismatch qualification", "gap": "stronger rerankers can be worse on scientific domains", "local_mapping": "retrieval qualification contract", "status": "adopted"},
    {"system": "Citation Faithfulness Audit", "design": "calibrate the citation verifier itself against human gold", "gap": "citation failure rates can move when only the verifier changes", "local_mapping": "citation verifier contract", "status": "adopted"},
    {"system": "ScientistOne", "design": "claim-type-specific Chain-of-Evidence audit for numeric, citation, and method claims", "gap": "professional-looking reports can diverge from logs, sources, or implementation", "local_mapping": "claim-evidence routing", "status": "adopted"},
    {"system": "SAGE", "design": "co-design subqueries and retrievers for reasoning-intensive scientific search", "gap": "keyword-oriented agent subqueries can nullify sophisticated retrievers", "local_mapping": "capability-registry retrieval router + simple-first retriever promotion gate", "status": "adopted"},
    {"system": "ReplicationBench", "design": "paper-scale author-validated replication tasks", "gap": "component-level replay does not yet test full paper replication fidelity", "local_mapping": "research-system replay paper-scale reproduction contract", "status": "adopted"},
    {"system": "SCION", "design": "Research Execution Plan compiles scientific intent into objectives, dependencies, checkpoints, tool requirements, artifacts, and fallbacks", "gap": "a scientifically sound principle can still reach runtime as an underspecified execution request", "local_mapping": "derived Research Execution Plan in Pre-Experiment Compiler", "status": "adopted"},
    {"system": "AutoSci", "design": "separate Active Research Memory from Long-Term Knowledge Memory and version memory/workflow evolution", "gap": "current-project truth and reusable cross-project lessons can otherwise contaminate each other", "local_mapping": "Scientific Meta-Trace memory scopes + institutional Failure Assets", "status": "adopted"},
    {"system": "EvoScientist", "design": "separate ideation and experimentation memory with explicit evolution over repeated research cycles", "gap": "historical lessons need scope and reuse-effectiveness tracking rather than permanent authority", "local_mapping": "institutional memory lifecycle metadata", "status": "merged-existing"},
    {"system": "Agent Operating System (AOS)", "design": "separate Control & Governance Plane from Runtime & Coordination Plane", "gap": "policy and authority decisions should not become implicit side effects of runtime routing", "local_mapping": "existing scientific-control vs research-runtime architecture", "status": "merged-existing"},
    {"system": "Exploration-breadth studies / IDEAgent / Heuresis / SwarmResearch", "design": "measure and actively preserve quality-diversity-novelty breadth across a portfolio rather than optimizing isolated ideas", "gap": "pairwise collision checks do not detect portfolio-wide collapse toward seed literature or one high-level approach", "local_mapping": "cross-cutting exploration-frontier control owned by wide-search ideation", "status": "adopted"},
    {"system": "Agent-experiment preregistration / stochastic experimental design / Search-Time Contamination", "design": "freeze researcher degrees of freedom before outcomes, plan repeated runs for stochastic agents, and audit web/tool access for benchmark metadata, question-context, and answer leakage", "gap": "cheap adaptive iteration and open-web retrieval can silently turn confirmatory experiments into outcome-contingent or contaminated analyses", "local_mapping": "cross-cutting experimental-design-integrity control owned by protocol-and-replay", "status": "adopted"},
    {"system": "ARA / Artisan / ArtifactCopilot", "design": "reconstruct dependency-aware scientific workflows and require independent re-execution rather than treating trace presence as reproducibility", "gap": "claim provenance can be correct while the result-generating workflow remains impossible for a third party to reconstruct and rerun", "local_mapping": "cross-cutting reproducibility-readiness control owned by Evidence Integrity", "status": "adopted"},
    {"system": "EurekAgent", "design": "permissions, artifact, budget, and human-in-the-loop environment engineering", "gap": "logical authorization is insufficient if a low-level runtime capability can be acquired without the controller-owned authority token", "local_mapping": "Runtime & Authority layer: experiment authority is now verified by the GPU lease capability itself; lease provenance stores authority id/epoch and plan hash", "status": "merged-existing", "local_gap_test": {"before": "unauthorized low-level GPU lease succeeded without experiment authority", "after": "the identical low-level acquisition is rejected with GPU lease requires active experiment authority", "verdict": "gap-confirmed-and-closed", "remaining_boundary": "evaluator/result filesystem isolation still requires its own runtime canary before claiming complete environment-level permission enforcement"}},
    {"system": "The AI Scientist / AI Scientist-v2", "design": "treat plotting as an experiment artifact, generate figures after experimental nodes, and critique figure legibility/misleading presentation before paper writing", "gap": "our evidence compiler could certify tables while leaving reviewer-critical mechanism, failure, and uncertainty evidence visually opaque", "local_mapping": "Paper Evidence Quality v2.1 Visual Evidence Contract + manuscript figure QA", "status": "adopted", "source": "https://www.nature.com/articles/s41586-026-10265-5"},
    {"system": "PaperVizAgent", "design": "generate academic figures from source context plus explicit communicative intent, then iteratively critique faithfulness, conciseness, readability, and aesthetics", "gap": "a figure-generation script alone does not specify what scientific question the figure must answer or whether its caption matches the claim", "local_mapping": "reviewer-question -> claim -> evidence -> data/script/figure/caption binding with figure-review checks", "status": "adopted", "source": "https://research.google/blog/improving-the-academic-workflow-introducing-two-ai-agents-for-better-figures-and-peer-review/"},
    {"system": "Agent Laboratory", "design": "visualize multi-dimensional human evaluation and auto-vs-human reviewer distributions rather than reporting one aggregate score", "gap": "aggregate paper or system scores can hide topic/model heterogeneity and evaluator bias", "local_mapping": "failure/stratified/human-evaluation visual roles and negative-regime visibility", "status": "adopted", "source": "https://arxiv.org/abs/2501.04227"},
    {"system": "ERA / AI co-scientist / Kosmos", "design": "pair system-overview figures with progression/scaling, heldout performance, uncertainty, breakthrough/search trajectories, and human or experimental validation", "gap": "a research-system paper can look complete while showing only terminal scores and no evidence of how quality changes with compute, cycles, or search depth", "local_mapping": "system archetype requires overview + scaling/progression + comparison + failure + sensitivity visual evidence", "status": "adopted", "source": "https://www.nature.com/articles/s41586-026-10658-6"},
    {"system": "Science One Framework", "design": "bind manuscript claims to evidence chains and audit score, reference, and method-code alignment", "gap": "a paper-completion agent could previously satisfy generic evidence completion with plausible-looking artifact path strings or cite an unregistered evidence ID even when the underlying file was missing or stale", "local_mapping": "Paper Evidence Quality content-addressed completion now binds every completed baseline/ablation/analysis/output and quantitative visual to in-root files with SHA256 receipts; claim adjudications may cite only registered completed evidence IDs", "status": "adopted", "source": "https://research.google/blog/science-one-framework-a-verifiable-autonomous-research-framework-via-chain-of-evidence/", "local_gap_test": {"before": "synthetic completion passed with nonexistent generated/*.json and paper/*.pdf path strings", "after": "the same completion fails unless every referenced artifact/data/script exists under the project root and matches its frozen SHA256; fake claim evidence IDs are rejected", "verdict": "gap-confirmed-and-closed"}},
    {"system": "ARIS / Auto-Research-In-Sleep", "design": "separate breadth fan-out from cross-model adjudication; persist bounded research memory; count repeated zero-finding iterations and force structural pivots; audit producer-to-consumer integration; separate meta-optimization proposal from independently reviewed application", "gap": "after the first ARIS alignment, the local system still lacked a mechanical stall-to-pivot heartbeat, a generic orphan-writer/integration lint, and a review-gated harness self-improvement proposal path", "local_mapping": "fan-out->jury invariants + Research Memory Wiki + persistent candidate portfolio + search-funnel telemetry + research integration lint + stall-to-pivot heartbeat + read-only harness meta-optimization proposals with a separate landing gate", "status": "adopted", "source": "https://github.com/wanshuiyin/Auto-claude-code-research-in-sleep", "paper": "arXiv:2605.03042", "local_gap_test": {"before": "the system could diagnose repeated reduction basins but could keep rerunning the same search frame; policies could also exist without a machine-verifiable consumer, and harness improvements had no explicit propose-vs-apply authority boundary", "after": "required producer/consumer contracts are release-linted; two same-frame zero-new-finding observations force a structural pivot and four require human replanning; the meta optimizer emits only unapplied proposals and a separate landing gate requires human approval, cross-family review, tests, diff hash, and unchanged assurance thresholds", "verdict": "gap-confirmed-and-closed"}},
    {"system": "SAGE-MHFA", "design": "retain and rank multiple competing evidence-grounded failure explanations before routing repair to formulation, experiment design, or execution", "gap": "the current experiment node collapses to one diagnosis before the differential AI clinic has accumulated a replayable competing-hypothesis state", "local_mapping": "candidate extension to post-screen differential diagnosis + Failure Asset Library; no scientific or execution authority", "status": "next", "local_gap_test": {"available_individual_failure_assets": 6, "available_unique_signatures": 3, "minimum_replay_cases": 15, "current_differential_cases": 0, "verdict": "support-insufficient", "falsifier": "after 15-20 terminal/failed traces have independently known final failure layers, compare current single diagnosis against top-k competing diagnoses at identical evidence and reviewer budget; require better correct-layer attribution without more unnecessary hypothesis pivots"}},
]


def build_external_system_learning_state() -> dict[str, Any]:
    counts = Counter(str(row["status"]) for row in SYSTEM_DESIGNS)
    return {
        "schema_version": "1.0",
        "policy": POLICY,
        "summary": {
            "systems_reviewed": len(SYSTEM_DESIGNS),
            "adopted": counts.get("adopted", 0),
            "merged_existing": counts.get("merged-existing", 0),
            "next_backlog": counts.get("next", 0),
        },
        "designs": SYSTEM_DESIGNS,
        "next_backlog": [row for row in SYSTEM_DESIGNS if row["status"] == "next"],
    }
