from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .config import PROJECT_ROOT

DEFAULT_JSON = PROJECT_ROOT / "generated" / "idea-discovery-v3.json"
DEFAULT_JS = PROJECT_ROOT / "generated" / "idea-discovery-v3.js"
DEFAULT_EXTERNAL_JSON = PROJECT_ROOT / "generated" / "idea-discovery-v3-external-reviews.json"


def bi(zh: str, en: str) -> dict[str, str]:
    return {"zh": zh.strip(), "en": en.strip()}


REPOSITORY_PATTERNS: tuple[dict[str, Any], ...] = (
    {"system":"ResearchAgent","official_repo":"https://github.com/JinheonBaek/ResearchAgent","pattern":bi("多维 Reviewer 只修复低分维度，并保留迭代历史。","Multi-dimensional reviewers repair low-scoring aspects while preserving iteration history."),"adopted_as":"reviewer-vector-repair"},
    {"system":"MOOSE-Chem","official_repo":"https://github.com/ZonglinY/MOOSE-Chem","pattern":bi("将问题背景与灵感语料分开，先检索机制灵感，再组合和排序假设。","Separates problem background from inspiration corpus before mechanism composition and ranking."),"adopted_as":"mechanism-inspiration-retrieval"},
    {"system":"SciAgents","official_repo":"https://github.com/lamm-mit/SciAgentsDiscovery","pattern":bi("从知识图谱采样非显然概念路径，并由多角色扩展、批判和检查新颖性。","Samples non-obvious concept paths from a knowledge graph and uses specialized roles to expand and critique them."),"adopted_as":"concept-path-bridging"},
    {"system":"Deep Ideation / OmniScientist","official_repo":"https://github.com/tsinghua-fib-lab/OmniScientist","pattern":bi("通过科学概念网络建立新连接，并检索代码、数据集和工具使 Idea 可执行。","Builds new links in a scientific concept network and retrieves code, datasets, and tools for execution."),"adopted_as":"concept-path-bridging + resource-grounded-design"},
    {"system":"AI Scientist-v2","official_repo":"https://github.com/SakanaAI/AI-Scientist-v2","pattern":bi("用渐进式 Agentic Tree Search 保留多个方法／实验分支并由 Experiment Manager 剪枝。","Uses progressive agentic tree search with an experiment manager to retain and prune branches."),"adopted_as":"method-tree-search"},
    {"system":"RD-Agent","official_repo":"https://github.com/microsoft/RD-Agent","pattern":bi("分离 Research 与 Development，并用真实执行反馈、Idea Pool 和历史知识继续提出假设。","Separates research from development and uses execution feedback, an idea pool, and history for new proposals."),"adopted_as":"experiment-feedback-induction"},
    {"system":"SciPIP","official_repo":"https://github.com/cheerss/SciPIP","pattern":bi("使用文献图数据库、多个 Brainstorm Mode 和灵感检索增加机制多样性。","Uses a literature graph, multiple brainstorming modes, and inspiration retrieval for diversity."),"adopted_as":"multi-route-diversity-seeding"},
)

SOLUTION_GATES: tuple[dict[str,str], ...] = (
    {"id":"persistent-object","zh":"必须学习新的持久对象，而不是只输出审计分数、预测或接受／拒绝。","en":"Must learn a new persistent object, not only an audit score, prediction, or accept/reject decision."},
    {"id":"irreducibility","zh":"必须声明容量匹配的通用方法基线，并证明同一数据不能直接复现。","en":"Must name a capacity-matched generic-method baseline and show the same data cannot directly reproduce the result."},
    {"id":"independent-supervision","zh":"候选生成、准入和最终评测不能由同一验证器闭环完成。","en":"Candidate generation, admission, and final evaluation cannot close the loop through the same verifier."},
    {"id":"deployment-effect","zh":"冻结后必须改变未来任务行为；只改善诊断或校准不算自进化方法。","en":"After freezing, the method must change future-task behavior; diagnosis or calibration alone is insufficient."},
    {"id":"guarantee-resolution","zh":"风险或 conformal 保证必须有足够独立校准单元和可检验的交换性／支持假设。","en":"Risk or conformal guarantees need enough independent calibration units and testable exchangeability/support assumptions."},
)


WORKFLOW_STAGES: tuple[dict[str, Any], ...] = (
    {"id":"P","name":bi("问题胶囊","Problem capsule"),"output":bi("失败现象、因果变量、受影响任务、最近工作和主张边界。","Failure, causal variable, affected tasks, nearest work, and claim boundary.")},
    {"id":"I","name":bi("机制灵感独立检索","Independent mechanism inspiration"),"output":bi("同题机制、跨域机制、概念桥接路径和不可迁移原因。","Direct mechanisms, cross-domain mechanisms, bridge paths, and non-transport reasons.")},
    {"id":"B","name":bi("多分支方法生成","Multi-branch method generation"),"output":bi("每个问题至少三个机制不同的子节点。","At least three mechanism-distinct children per problem.")},
    {"id":"C","name":bi("解决方案具体化","Solution concretization"),"output":bi("变化假设、精确更新表面、学习信号、决策规则和独立真值。","Changed assumption, exact update surface, learning signal, decision rule, and independent ground truth.")},
    {"id":"G","name":bi("机制不可归约性门槛","Mechanism irreducibility gate"),"output":bi("使用相同输入、日志和容量的标准 predictor／gate／bandit／offline RL／rule learner 若能复现，则直接阻断。","Block when a capacity-matched standard predictor, gate, bandit, offline-RL learner, or rule learner can reproduce the mechanism from the same inputs and logs.")},
    {"id":"S","name":bi("Pareto 分支筛选","Pareto branch selection"),"output":bi("在新颖性、机制明确性、可识别性、可行性、迁移和成本上保留非支配分支。","Keep non-dominated branches over novelty, specificity, identifiability, feasibility, transfer, and cost.")},
    {"id":"R","name":bi("Reviewer 向量修订","Reviewer-vector repair"),"output":bi("把最高风险维度转成新的方法子节点。","Turn the highest-risk review dimensions into new method children.")},
    {"id":"X","name":bi("资源与 Pilot 落地","Resource and pilot grounding"),"output":bi("公开代码、数据集、验证器、P0/P1/P2、最强对照和 Stop 条件。","Public code, datasets, verifier, P0/P1/P2, strongest baseline, and Stop rule.")},
    {"id":"F","name":bi("实验反馈归纳","Experiment-feedback induction"),"output":bi("失败签名、替代解释和下一轮机制修订。","Failure signature, alternative explanation, and next mechanism revision.")},
)


def child(id: str, parent: str, title: dict[str,str], decision: str, problem: dict[str,str], changed: dict[str,str], mechanism: dict[str,str], surface: str, signal: dict[str,str], truth: dict[str,str], baseline: dict[str,str], pilot: dict[str,str], stop: dict[str,str], assets: tuple[str,...], operators: tuple[str,...], scores: tuple[int,int,int,int,int,int]) -> dict[str,Any]:
    keys=("novelty","specificity","identifiability","feasibility","transfer","cost_efficiency")
    return {"id":id,"parent_id":parent,"title":title,"internal_decision":decision,"problem":problem,"changed_assumption":changed,"exact_mechanism":mechanism,"update_surface":surface,"learning_signal":signal,"independent_ground_truth":truth,"strongest_baseline":baseline,"decisive_pilot":pilot,"stop_condition":stop,"public_assets":list(assets),"generation_mechanisms":list(operators),"scores":dict(zip(keys,scores,strict=True)),"mean_score":round(sum(scores)/len(scores),3),"external_review_status":"pending"}


CHILDREN: tuple[dict[str,Any], ...] = (
    child("replicated-effect-memory-gate","retrieval-interference-auditor",bi("重复效应记忆门控","Replicated-Effect Memory Gate"),"shortlist",bi("记忆条目平均有益，但会在少数未来任务上造成强干扰。","Memory entries help on average but can severely harm a minority of future tasks."),bi("三臂重放不再只是审计，而是条目准入的唯一训练信号。","Three-arm replay becomes the sole admission signal rather than an audit only."),bi("对候选条目执行检索／打乱／无记忆 matched replay，用分层效应模型估计任务模式条件下的帮助与伤害后验，再学习带弃权的准入、隔离或删除策略。","Run retrieved/shuffled/no-memory matched replay, estimate motif-conditioned benefit and harm with a hierarchical effect model, and learn admission, quarantine, or deletion with abstention."),"bounded external memory registry",bi("条目×任务模式的重复处理效应后验。","Replicated treatment-effect posteriors for each entry-by-task motif."),bi("按时间留出的未来任务上的可复现帮助或伤害。","Replicated benefit or harm on chronological held-out tasks."),bi("写入全部成功经验、置信度门控、A-MAC／SCORE 类选择。","Write-all success memory, confidence gating, and A-MAC/SCORE-style selection."),bi("在 ALFWorld 与 WebArena-Lite 时间任务流上匹配重放与存储预算，比较未来回退、收益和弃权率。","Use chronological ALFWorld and WebArena-Lite streams with matched replay/storage budgets."),bi("第二模型上不能降低未来伤害，或成本—收益不优于无记忆时停止。","Stop if future harm does not fall on a second model or the frontier does not beat no-memory."),("ALFWorld","WebArena-Lite","Qwen2.5-7B-Instruct","Llama-3.1-8B-Instruct"),("reviewer-vector-repair","experiment-feedback-induction"),(4,5,5,4,4,4)),
    child("simulator-distilled-risk-memory","irreversible-action-counterfactuals",bi("模拟器蒸馏的不可逆风险记忆","Simulator-Distilled Irreversibility Memory"),"shortlist",bi("不可逆动作需要反事实后果，但在线持续调用模拟器只是增加推理。","Irreversible actions need counterfactual consequences, but online simulation is extra inference."),bi("模拟器只在发现阶段使用；部署时只能读取持久风险记忆。","Use the simulator only during discovery; deployment may consult only persistent risk memory."),bi("通过可验证状态替换生成动作后果对，蒸馏为带前置条件、风险等级和禁用动作的最小谓词库，冻结后关闭模拟器。","Generate verified action-consequence pairs via state substitutions and distill a minimal predicate library with preconditions, risk levels, and forbidden actions; disable the simulator after freezing."),"versioned risk-predicate memory",bi("独立转移验证器提供的反事实后果。","Counterfactual outcomes from an independent transition verifier."),bi("模拟器关闭时未见状态上的不可逆错误率。","Irreversible-error rate on unseen states with the simulator disabled."),bi("在线模拟器、自然语言反思、规则记忆、固定安全 Prompt。","Online simulator, verbal reflection, rule memory, and fixed safety prompts."),bi("在一个精确转移环境中先发现后冻结，匹配模拟器调用预算，评测时彻底关闭模拟器。","Use discovery-then-freeze in one exact-transition environment with matched simulator calls and evaluate with the simulator off."),bi("关闭模拟器后收益消失，或风险召回不能跨 seed 保持时停止。","Stop if gains vanish without the simulator or risk recall is unstable across seeds."),("ALFWorld/PDDL verifier","Qwen2.5-7B-Instruct"),("mechanism-inspiration-retrieval","resource-grounded-design"),(4,5,5,4,3,4)),
    child("actor-evaluator-residual-gate","evaluator-coadaptation-guard",bi("执行者—评价器交互残差门控","Actor–Evaluator Interaction-Residual Gate"),"shortlist",bi("执行者与评价器共同进化时，高分可能来自版本配对偏差。","When actor and evaluator co-evolve, high scores may reflect version-pair bias."),bi("显式学习版本交互残差，而不是只冻结评价器或比较新旧评价器。","Explicitly learn version interaction residuals rather than only freezing or pairing evaluators."),bi("将 actor×evaluator 评分矩阵分解为任务难度、actor 能力、evaluator 偏置和交互残差，用未来留出轮次校准异常门控。","Factor the actor-by-evaluator matrix into task difficulty, actor ability, evaluator bias, and interaction residual; calibrate the residual gate on held-out future rounds."),"evolution commit gate",bi("跨版本交叉评分矩阵与独立锚点任务。","Cross-version score matrix and independent anchor tasks."),bi("冻结外部验证器上的真实能力变化。","True capability change under a frozen external verifier."),bi("冻结 Reward、最新版本配对、Reward Ensemble、当前轮一致性。","Frozen reward, latest-version pairing, reward ensemble, and current-round consistency."),bi("构造 5–8 轮 actor/evaluator 更新，匹配评价调用，在未来轮次预测伪改进和真实回退。","Construct 5–8 rounds with matched evaluator calls and predict pseudo-improvement and true regression."),bi("交互残差不能比冻结 Reward 或 Ensemble 更好预测外部真值时停止。","Stop if interaction residuals do not beat frozen rewards or ensembles on external ground truth."),("frozen verifier tasks","open-weight actor/evaluator pairs"),("reviewer-vector-repair","method-tree-search"),(4,5,4,4,4,3)),
    child("future-reuse-harm-predictor","recovery-conditioned-experience",bi("未来复用伤害预测器","Future-Reuse Harm Predictor"),"shortlist",bi("一次恢复成功的轨迹可能在未来被错误检索并放大残余错误。","A trajectory that recovers once may later be mis-retrieved and amplify residual error."),bi("恢复完整度由未来复用时的真实帮助／伤害学习，不再由手工轨迹条件定义。","Learn recovery completeness from future reuse harm instead of hand-coded trajectory conditions."),bi("在容量受限经验记忆中，输入失败类型、恢复点、残余状态和检索上下文，预测条目未来复用风险并选择写入、摘要或隔离。","In capacity-bounded experience memory, predict future reuse risk from failure type, recovery point, residual state, and retrieval context, then choose write, summarize, or quarantine."),"bounded recovery-experience memory",bi("未来任务 matched replay 的条目级净效应。","Entry-level net effects from matched replay on future tasks."),bi("独立时间留出任务上的复用伤害与帮助。","Reuse harm and benefit on chronological held-out tasks."),bi("成功即写入、终点规则、摘要记忆、检索置信度门控。","Success-only admission, endpoint rules, summary memory, and retrieval-confidence gating."),bi("两个任务域中冻结记忆容量和检索次数，比较负迁移、成功率和存储成本。","Freeze memory capacity and retrieval count in two domains and compare negative transfer, success, and storage cost."),bi("不能跨任务域迁移，或简单成功／失败标签同样有效时停止。","Stop if it does not transfer across domains or simple success/failure labels are equally effective."),("ALFWorld","ToolBench subset","Qwen2.5-7B-Instruct"),("experiment-feedback-induction","resource-grounded-design"),(4,5,5,4,4,4)),
    child("precommit-workflow-transfer-certificate","workflow-generalization-certificate",bi("提交前工作流迁移证书","Pre-Commit Workflow Transfer Certificate"),"shortlist",bi("工作流在发现任务上成功，但更换工具 API 或任务图模式后会静默失效。","Workflows can succeed on discovery tasks yet silently fail on unseen APIs or task-graph motifs."),bi("证书是候选提交前的校准风险预测器，不是事后泛化分数。","The certificate is a calibrated pre-commit risk predictor, not a post-hoc score."),bi("把工作流表示为带工具语义和控制流的图，学习候选图编辑对未见 API／图模式失败概率的影响，并在不确定时拒绝提交。","Represent workflows as graphs with tool semantics and control flow; learn how candidate edits change failure probability on unseen APIs/motifs and abstain under uncertainty."),"workflow commit certificate",bi("独立生成候选的图编辑、发现集表现和未来失败标签。","Graph edits, discovery performance, and future failure labels for independently generated candidates."),bi("未见 API 和任务图模式上的提交后成功率。","Post-commit success on unseen APIs and task-graph motifs."),bi("发现集成功率、图复杂度、随机测试、固定回归集。","Discovery success, graph complexity, random tests, and fixed regression suites."),bi("独立生成 200–500 个小工作流，固定总测试预算，比较风险覆盖与错误提交率。","Generate 200–500 small workflows independently under a fixed test budget and compare risk coverage and bad-commit rate."),bi("第二工具族上不能校准，或固定小回归集更优时停止。","Stop if uncalibrated on a second tool family or a fixed small regression suite is better."),("WebArena-Lite","ToolBench subset","workflow graph extractor"),("resource-grounded-design","method-tree-search"),(4,5,4,4,4,4)),
    child("counterfactual-evolution-decision-controller","budgeted-evolution-controller",bi("反事实进化决策控制器","Counterfactual Evolution Decision Controller"),"shortlist",bi("继续搜索、提交、回滚或停止通常基于不同候选序列，无法公平学习决策。","Continue, commit, rollback, and stop are usually compared on different candidate sequences."),bi("固定同一进化状态和候选序列，为四种决策构建反事实结果。","Freeze the same evolution state and candidate sequence and construct counterfactual outcomes for all four decisions."),bi("在一个持久更新表面上建立可反事实重放数据集，用保守离线策略学习在预算和回退约束下选择 continue／commit／rollback／stop。","Build a counterfactually replayable dataset for one persistent update surface and learn a conservative offline policy over continue/commit/rollback/stop under budget and regression constraints."),"memory or prompt evolution controller",bi("同一状态下四种动作的验证收益、未来回退和额外成本。","Validation gain, future regression, and extra cost for four actions from the same state."),bi("冻结测试流上的累计效用和最坏回退。","Cumulative utility and worst regression on a frozen test stream."),bi("固定轮数、阈值提交、Bandit、失败即回滚。","Fixed rounds, threshold commit, bandit control, and rollback-on-failure."),bi("先在小型离线重放环境中匹配候选和调用预算，再冻结策略跨模型评测。","Match candidate and call budgets in an offline replay environment, then freeze the controller across models."),bi("第二模型上不优于简单阈值，或需要重新生成候选才能成立时停止。","Stop if it does not beat a simple threshold on a second model or requires regenerated candidates."),("frozen replay dataset","Qwen2.5-7B-Instruct","Llama-3.1-8B-Instruct"),("experiment-feedback-induction","method-tree-search"),(4,5,5,3,4,3)),
    child("active-causal-minimal-rollback","lineage-aware-rollback",bi("主动因果最小回滚","Active Causal Minimal Rollback"),"shortlist",bi("多个更新组合后出现回退时，按时间或谱系回滚会撤销无害更新。","Chronological or lineage rollback removes harmless updates when composed updates regress."),bi("谱系只作为依赖先验，真正回滚集合由预算受限干预识别。","Lineage is only a dependency prior; the rollback set is identified by budgeted interventions."),bi("把更新原子建成依赖图，主动选择最有信息量的启用／禁用组合，学习交互项并输出恢复回归测试的最小集合。","Build an update-atom dependency graph, actively select informative enable/disable combinations, learn interactions, and output the smallest rollback set restoring regressions."),"versioned update set",bi("组件启用／禁用干预对失败的因果效应。","Causal effects of component enable/disable interventions on failure."),bi("合成与真实更新序列中的最小故障集合。","Minimal fault sets in synthetic and real update sequences."),bi("最后更新回滚、逐个消融、Delta Debugging、Shapley 归因。","Last-update rollback, one-at-a-time ablation, delta debugging, and Shapley attribution."),bi("在 4–8 个 Prompt／记忆／工作流更新中注入单点和双点交互故障，固定干预次数。","Inject single and pairwise faults into 4–8 prompt/memory/workflow updates under a fixed intervention budget."),bi("不能比 Delta Debugging 用更少测试找到同样小的集合，或真实序列无收益时停止。","Stop if it cannot match delta debugging with fewer tests or offers no gain on real sequences."),("ALFWorld","WebArena-Lite","versioned update harness"),("concept-path-bridging","resource-grounded-design"),(4,5,5,4,4,4)),
    child("cross-task-effect-transport-certificate","causally-verified-experience-admission",bi("跨任务效应迁移证书","Cross-Task Effect Transport Certificate"),"shortlist",bi("经验在源任务上有因果收益，不代表跨任务族后仍有效。","A lesson can be causally useful on its source task yet fail after task-family shift."),bi("准入目标从源任务有效性改为效应可迁移性。","Change admission from source-task efficacy to effect transportability."),bi("从多任务 matched replay 学习经验效应表示，寻找跨环境稳定的状态—约束特征，并输出带校准弃权的迁移证书。","Learn lesson-effect representations from multi-task matched replay, identify stable state-constraint features, and output a calibrated transport certificate with abstention."),"experience admission certificate",bi("源任务和目标任务上的条目级处理效应及环境描述。","Entry-level treatment effects and environment descriptors on source and target tasks."),bi("完全留出任务族上的效应符号和幅度。","Effect sign and magnitude on fully held-out task families."),bi("源任务因果准入、语义相似度、SkillCAT、A-MAC、SCORE。","Source causal admission, semantic similarity, SkillCAT, A-MAC, and SCORE."),bi("三任务族训练、一任务族留出；相同记忆容量与重放预算，测量负迁移和有效覆盖。","Train on three task families and hold out one under equal memory and replay budgets; measure negative transfer and coverage."),bi("效应符号预测不优于语义相似度，或覆盖率过低时停止。","Stop if effect-sign prediction does not beat semantic similarity or coverage is too low."),("ALFWorld","WebArena-Lite","ToolBench subset","AgentBench subset"),("mechanism-inspiration-retrieval","concept-path-bridging"),(4,5,5,3,5,3)),
    child("version-differential-active-diagnosis","version-differential-failure-localization",bi("版本差分主动诊断","Version-Differential Active Diagnosis"),"shortlist",bi("新版本失败时，逐组件穷举替换成本高，双点交互故障更难定位。","Exhaustive component swapping is costly and pairwise faults are hard to localize."),bi("从历史版本故障学习下一次最有信息量的组件替换，而不是固定 Delta Debugging 顺序。","Learn the next informative component substitution from historical faults rather than using a fixed delta-debugging order."),bi("把 Prompt、记忆、技能、工作流和小模块视为故障变量；策略根据后验选择最小替换实验，更新单点和交互故障概率并输出最小解释集合。","Treat prompt, memory, skill, workflow, and small modules as fault variables; select minimal substitutions, update single/interacting fault posteriors, and output the smallest explanation set."),"diagnostic intervention policy",bi("历史版本中的组件替换结果和已知故障集合。","Component-substitution outcomes and known fault sets from prior versions."),bi("未见模型、版本和故障组合上的真实故障集合。","True fault sets on unseen models, versions, and fault compositions."),bi("Delta Debugging、逐组件消融、日志归因、随机替换。","Delta debugging, one-component ablation, log attribution, and random substitution."),bi("在 ALFWorld／WebArena-Lite 注入单点与双点故障，限制最多 6 次干预并跨模型冻结策略。","Inject single and pairwise faults in ALFWorld/WebArena-Lite, cap interventions at six, and freeze across models."),bi("双点故障上不能用更少干预超过 Delta Debugging 时停止。","Stop if it cannot beat delta debugging on pairwise faults with fewer interventions."),("ALFWorld","WebArena-Lite","versioned agent harness"),("method-tree-search","experiment-feedback-induction"),(4,5,5,4,4,4)),
    child("asset-level-model-swap-certificate","model-swap-compatibility-certificate",bi("资产级模型替换兼容证书","Asset-Level Model-Swap Compatibility Certificate"),"shortlist",bi("更换基础模型时，Prompt、记忆、技能和工作流会以不同方式静默失效。","Prompts, memories, skills, and workflows can silently fail differently after a model swap."),bi("证书单位从整个 Agent 改为单个持久资产，并带不确定性和弃权。","Change the certificate unit from the whole agent to each persistent asset with uncertainty and abstention."),bi("用小型行为 Probe 和资产结构特征预测负迁移、适配成本和失败类型，同时在目标模型家族和资产类别上双重留出。","Use small behavioral probes and asset-structure features to predict negative transfer, adaptation cost, and failure type with double-held-out model-family and asset-class tests."),"asset portability registry",bi("迁移前 Probe、资产表示和迁移后真实性能。","Pre-migration probes, asset representations, and post-migration ground truth."),bi("留出模型家族×留出资产类别上的负迁移。","Negative transfer on held-out model families and asset classes."),bi("全量迁移测试、语义相似度、MASA、SkCC、源模型成功率。","Full migration tests, semantic similarity, MASA, SkCC, and source success."),bi("三开放模型家族、四类资产和两个任务域，冻结模型并匹配 Probe 预算。","Use three open model families, four asset classes, and two domains with frozen models and matched probe budgets."),bi("双重留出校准失败，或成本接近全量迁移时停止。","Stop if double-held-out calibration fails or cost approaches full migration testing."),("three open model families","ALFWorld","WebArena-Lite"),("resource-grounded-design","mechanism-inspiration-retrieval"),(4,5,4,3,5,3)),
    child("adjacent-checkpoint-discrimination-curriculum","failure-frontier-curriculum",bi("相邻 Checkpoint 判别课程","Adjacent-Checkpoint Discrimination Curriculum"),"repair",bi("按难度或失败率选任务，不能保证它们能区分相邻版本的真实改进。","Difficulty or failure-rate curricula need not distinguish real improvement between adjacent versions."),bi("课程价值改为相邻 Checkpoint 的可重复判别力。","Define curriculum value as replicated discrimination between adjacent checkpoints."),bi("估计每个任务对相邻版本的效应量和不确定性，选择最大化未来版本区分度的任务，并保留随机审计。","Estimate task-level adjacent-version effects and uncertainty, select tasks maximizing future checkpoint discrimination, and retain random audits."),"curriculum registry",bi("相邻版本 paired replay 的标准化差异。","Standardized differences from paired replay of adjacent versions."),bi("留出版本上对真实能力增长的预测。","Prediction of true capability growth on held-out versions."),bi("失败率课程、难度课程、学习进度、随机采样。","Failure-rate, difficulty, learning-progress, and random curricula."),bi("至少需要两条真实多轮版本流；当前无实验结果，因此先列为 repair。","Requires at least two real multi-round version streams and remains repair without them."),bi("只有合成版本流，或判别分数不能预测圈外改进时停止。","Stop if only synthetic streams exist or discrimination does not predict out-of-loop improvement."),("multi-round version logs",),("reviewer-vector-repair","experiment-feedback-induction"),(3,4,4,2,3,4)),
    child("intervention-certified-reward-update","reward-invariance-audit",bi("干预认证的 Reward 更新","Intervention-Certified Reward Update"),"repair",bi("Reward 漂移审计能发现问题，但不会产生更好的持久评价器。","Reward-drift audits identify problems but do not create a better persistent evaluator."),bi("把独立认证的因果／中性干预作为 Reward 更新监督。","Use independently certified causal and neutral interventions as reward-update supervision."),bi("训练小型 Reward 修正头，使因果干预按已知方向改变排序、中性干预保持排序，并用校准约束限制更新幅度。","Train a small reward-correction head so causal interventions move rankings in certified directions, neutral interventions preserve rankings, and calibration limits update size."),"small reward correction head",bi("独立生成并认证的因果／中性干预对。","Independently generated and certified causal/neutral intervention pairs."),bi("下游候选策略选择的独立成功真值。","Independent success ground truth for downstream policy selection."),bi("冻结 Reward、CROME、PRISM、普通 Pairwise Fine-tuning。","Frozen reward, CROME, PRISM, and ordinary pairwise fine-tuning."),bi("先在可程序验证环境和开放权重 Reward 上验证；仍需补足直接碰撞审查。","First test in a programmatically verifiable environment with an open reward model; direct collision audit is still required."),bi("只提高干预集而不提高冻结下游选择，或破坏中性校准时停止。","Stop if it improves only the intervention set, not frozen downstream selection, or harms neutral calibration."),("programmatic verifier","open-weight reward model"),("reviewer-vector-repair","resource-grounded-design"),(3,5,5,3,3,3)),
    child("monotone-applicability-specializer","local-counterexample-memory-repair",bi("单调适用集合专化器","Monotone Applicability-Set Specializer"),"repair",bi("反例修复记忆时，自由文本编辑会破坏原本正确的适用区域。","Free-text counterexample repair can damage regions where the original lesson was correct."),bi("每次反例只允许缩小适用集合，不允许任意改写经验含义。","Each counterexample may only shrink the applicability set, not arbitrarily rewrite semantics."),bi("把经验表示为可执行前置条件和例外集合；反例触发最小约束添加，保存可回放例外谱系并验证未受影响正例。","Represent lessons with executable preconditions and exception sets; counterexamples add minimal constraints, preserve replayable lineage, and verify unaffected positives."),"structured lesson with exception lineage",bi("约束删除得到的最小反例和未受影响正例。","Constraint-deletion minimal counterexamples and unaffected positives."),bi("规则适用真值与正例保持率。","Rule applicability ground truth and positive-retention rate."),bi("SkillTracer、SkillAdaptor、自由文本重写、全部弃用。","SkillTracer, SkillAdaptor, free-text rewriting, and full deletion."),bi("在规则可执行的工具环境中做 matched edits；仍需证明不是已有技能专化的直接实现。","Use matched edits in an executable-rule environment and prove separation from existing skill specialization."),bi("单调限制导致过度收缩，或与 SkillAdaptor 等价时停止。","Stop if monotonicity causes excessive shrinkage or the method is equivalent to SkillAdaptor."),("executable tool rules","counterexample replay harness"),("concept-path-bridging","reviewer-vector-repair"),(3,5,5,4,3,4)),
    child("update-permission-impact-model","update-aware-permission-downgrade",bi("更新—权限影响模型","Update-to-Permission Impact Model"),"repair",bi("Agent 更新后沿用旧权限可能引入新越权，永久最低权限又损害效用。","Reusing old permissions can create overreach, while permanent minimum privilege harms utility."),bi("临时权限集合由更新 diff 的风险预测产生，而不是每次统一降权。","Derive temporary permission from update-diff risk rather than uniform downgrade."),bi("编码 Prompt／记忆／技能／工作流 diff，预测受影响权限、必要重新授权 Probe 和不确定性；通过独立 Canary 后恢复。","Encode prompt/memory/skill/workflow diffs to predict affected permissions, required reauthorization probes, and uncertainty; restore after independent canaries."),"versioned permission state",bi("更新 diff、Canary 结果、越权和任务效用标签。","Update diffs, canary outcomes, overreach, and utility labels."),bi("训练中未见更新算子上的安全—效用结果。","Safety-utility outcomes on update operators absent from training."),bi("静态最小权限、统一降权、ABAC/MAC、完整重认证。","Static least privilege, uniform downgrade, ABAC/MAC, and full reauthorization."),bi("在 ToolPrivBench/AuthBench 风格环境中训练三类更新、留出第四类；当前需确认数据覆盖。","Train on three update types and hold out a fourth in ToolPrivBench/AuthBench-style tasks; data coverage must be confirmed."),bi("未见更新算子上不能校准，或安全收益来自永久禁权时停止。","Stop if calibration fails on unseen update operators or safety gains come from permanent denial."),("ToolPrivBench-style tasks","AuthBench-style tasks"),("resource-grounded-design","reviewer-vector-repair"),(3,5,4,3,4,4))
)


def _pareto_front(rows: list[dict[str,Any]]) -> list[str]:
    keys=("novelty","specificity","identifiability","feasibility","transfer","cost_efficiency")
    front=[]
    for row in rows:
        if row["internal_decision"]=="stop": continue
        if not any(other is not row and other["internal_decision"]!="stop" and all(other["scores"][k]>=row["scores"][k] for k in keys) and any(other["scores"][k]>row["scores"][k] for k in keys) for other in rows): front.append(row["id"])
    return front


def _load_external_reviews(path: Path = DEFAULT_EXTERNAL_JSON) -> dict[str,list[dict[str,Any]]]:
    if not path.exists(): return {}
    try: payload=json.loads(path.read_text(encoding="utf-8"))
    except (OSError,json.JSONDecodeError): return {}
    reviews=payload.get("reviews",{})
    return reviews if isinstance(reviews,dict) else {}


def build_idea_discovery_v3() -> dict[str,Any]:
    external=_load_external_reviews()
    rows=[]
    for item in CHILDREN:
        row=dict(item)
        reviews=external.get(row["id"],[])
        latest=reviews[-1] if reviews else {}
        row["external_reviews"]=reviews
        row["external_review_status"]="reviewed" if reviews else "pending"
        row["external_verdict"]=latest.get("verdict","pending")
        row["external_confidence"]=latest.get("confidence","")
        rows.append(row)
    order={"shortlist":0,"repair":1,"stop":2}
    rows.sort(key=lambda item:(order[item["internal_decision"]],-item["mean_score"],item["id"]))
    for rank,row in enumerate(rows,1): row["internal_rank"]=rank
    shortlist=[row for row in rows if row["internal_decision"]=="shortlist"]
    repair=[row for row in rows if row["internal_decision"]=="repair"]
    stopped=[row for row in rows if row["internal_decision"]=="stop"]
    latest_verdicts=[row["external_verdict"] for row in shortlist if row["external_review_status"]=="reviewed"]
    return {"schema_version":"1.0","generated_at":datetime.now(timezone.utc).replace(microsecond=0).isoformat(),"target_venue":"ICLR","status":"external-reviewed" if len(latest_verdicts)==len(shortlist) else "internal-solution-screen","policy":{"main_bank_unchanged":True,"external_review_required_before_merge":True,"minimum_children_per_problem":3,"diversity_unit":"mechanism + learning signal + independent ground truth","automatic_final_selection_forbidden":True},"summary":{"repository_patterns":len(REPOSITORY_PATTERNS),"workflow_stages":len(WORKFLOW_STAGES),"mechanism_gates":len(SOLUTION_GATES),"raw_children":len(rows),"internal_shortlist":len(shortlist),"repair":len(repair),"stop":len(stopped),"external_reviewed":len(latest_verdicts),"external_pending":len(shortlist)-len(latest_verdicts),"external_pass":latest_verdicts.count("pass"),"external_revise":latest_verdicts.count("revise"),"external_block":latest_verdicts.count("block")},"repository_patterns":list(REPOSITORY_PATTERNS),"workflow_stages":list(WORKFLOW_STAGES),"solution_gates":list(SOLUTION_GATES),"pareto_front_ids":_pareto_front(rows),"shortlist":shortlist,"repair":repair,"stopped":stopped,"all_children":rows}


def validate(payload: dict[str,Any]) -> list[str]:
    errors=[]; rows=payload.get("all_children") or []
    if len(rows)<12: errors.append("solution-first child pool is too small")
    if len({row.get("id") for row in rows})!=len(rows): errors.append("duplicate child ids")
    if payload.get("summary",{}).get("internal_shortlist",0)<8: errors.append("shortlist is too small")
    for row in rows:
        for field in ("changed_assumption","exact_mechanism","learning_signal","independent_ground_truth","strongest_baseline","decisive_pilot","stop_condition"):
            value=row.get(field)
            if not isinstance(value,dict) or not value.get("zh") or not value.get("en"): errors.append(f"missing bilingual {field}: {row.get('id')}")
        if not row.get("update_surface"): errors.append(f"missing update surface: {row.get('id')}")
        if not row.get("public_assets"): errors.append(f"missing public assets: {row.get('id')}")
    return errors


def write_idea_discovery_v3(json_path:Path=DEFAULT_JSON,js_path:Path=DEFAULT_JS)->dict[str,Any]:
    payload=build_idea_discovery_v3(); errors=validate(payload)
    if errors: raise ValueError("Invalid idea discovery v3:\n- "+"\n- ".join(errors))
    json_path.parent.mkdir(parents=True,exist_ok=True)
    json_path.write_text(json.dumps(payload,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    js_path.write_text("window.IDEA_DISCOVERY_V3 = "+json.dumps(payload,ensure_ascii=False,separators=(",",":"))+";\n",encoding="utf-8")
    return payload


if __name__=="__main__": print(json.dumps(write_idea_discovery_v3()["summary"],ensure_ascii=False))
