from __future__ import annotations

MACHINE_SCHOOL_ENGLISH: dict[str, dict[str, str]] = {
    "cross-form-capability-transfer-gap": {
        "purpose": "The same semantic task may succeed in multiple-choice form yet fail in free generation or tool execution, while aggregate accuracy hides the missing capability.",
        "core_idea": "Build semantics-preserving task groups, estimate a cross-form transfer matrix, and use the gap signature to choose no update, prompt, memory, or a small adapter.",
        "collision_boundary": "Fine-grained capability benchmarks expose profile differences, but generally do not use those differences to select a persistent update surface.",
        "hypothesis": "A cross-form gap signature should predict the best update surface better than aggregate confidence.",
        "strongest_baseline": "Fixed prompts, form-specific prompts, confidence routing, uniform memory updates, and exhaustive oracle routing.",
        "pilot": "Render GSM8K, AgentBench, and tool tasks as classification, generation, and execution forms; evaluate two open models, three seeds, and matched calls.",
        "stop_condition": "Stop if the gap signature fails to predict the best update surface across models or gains come only from extra calls.",
    },
    "cross-form-update-allocator": {
        "purpose": "Different response-form failures may have different causes, yet systems often apply one fixed update surface.",
        "core_idea": "Route updates among prompts, memory, tool templates, and small modules using cross-form failure features.",
        "collision_boundary": "This substantially overlaps Update-Surface Router unless labels can be obtained without exhaustive execution of every surface.",
        "hypothesis": "Cross-form features should reduce update-routing regret.",
        "strongest_baseline": "Rule routing, random routing, one fixed surface, and exhaustive oracle routing.",
        "pilot": "Run a synthetic three-surface failure pilot with known causes and equal update capacity.",
        "stop_condition": "Merge into Cross-Form Capability Transfer Gap if supervision still requires enumerating all update surfaces.",
    },
    "living-capability-report-card": {
        "purpose": "A single aggregate score hides which capabilities are weak or unstable.",
        "core_idea": "Maintain a longitudinal multidimensional capability profile across model versions.",
        "collision_boundary": "JudgeAgent, Reflection-Bench, and competency-gap benchmarks already occupy this diagnostic space.",
        "hypothesis": "Capability profiles are more diagnostic than a single score.",
        "strongest_baseline": "Standard benchmark reports with aggregate scores.",
        "pilot": "Analyze multiple models across several benchmarks and capability axes.",
        "stop_condition": "Keep this as a website analysis module rather than a standalone paper.",
    },
    "specialist-spillover-guard": {
        "purpose": "Repairing a weak capability may degrade already strong capability axes.",
        "core_idea": "Constrain an update to improve its target axis without regressing non-target axes.",
        "collision_boundary": "The proposal is close to Regression-Gated Self-Evolution, update trust regions, and selective unlearning.",
        "hypothesis": "Axis-level constraints should reduce spillover regressions from specialized repair.",
        "strongest_baseline": "Global non-regression gating, fixed regularization, and unconstrained updates.",
        "pilot": "Apply prompt or LoRA updates to one capability axis while testing two explicitly unrelated axes.",
        "stop_condition": "Merge into Regression-Gated Self-Evolution if global non-regression gating is equally effective.",
    },
    "change-triggered-regression-exams": {
        "purpose": "Fixed regression suites are expensive and do not target the prompt, memory, skill, or workflow change being committed.",
        "core_idea": "Select probes from the update diff, dependency graph, and historical flips, while retaining a random audit subset.",
        "collision_boundary": "Dynamic evaluation typically selects by performance or item difficulty rather than by semantic update diffs, although predictive test selection is a strong collision.",
        "hypothesis": "A 20% test budget should capture at least 90% of regressions found by the full suite.",
        "strongest_baseline": "Fixed small suites, random subsets, IRT-adaptive testing, predictive test selection, and the full suite.",
        "pilot": "Inject prompt, memory, and workflow regressions on ALFWorld and WebArena-Lite with two models and three seeds.",
        "stop_condition": "Downgrade to a testing tool if recall fails on a held-out update type or second model.",
    },
    "delayed-regression-exams": {
        "purpose": "An update may pass at commit time yet become harmful only after interacting with later updates.",
        "core_idea": "Maintain delayed probes for committed updates and learn when to retest them from update provenance and time-to-regression risk.",
        "collision_boundary": "Existing work measures delayed regression and replays prior behavior; novelty requires a learned provenance-aware hazard scheduler.",
        "hypothesis": "Hazard-scheduled replay should reduce missed cumulative regressions and improve worst-round utility at a fixed test budget.",
        "strongest_baseline": "Commit-time-only testing, every-round full replay, and fixed-period replay.",
        "pilot": "Construct four-to-six-round prompt, memory, and skill update sequences with delayed interaction failures and held-out orderings.",
        "stop_condition": "Stop if hazard scheduling does not improve the cost-recall frontier over fixed-period replay on unseen update orderings.",
    },
    "regression-probe-half-life": {
        "purpose": "Old regression probes may stop predicting failures as agent versions evolve while continuing to consume evaluation budget.",
        "core_idea": "Learn a probe-specific decay or survival model and use it to refresh, merge, or retire tests in a persistent registry.",
        "collision_boundary": "AgingBench studies deployed-agent degradation, while PACE and AutoJudger select compact evaluations; none directly models each probe's out-of-version predictive-value hazard.",
        "hypothesis": "Half-life scheduling should improve future-regression recall under the same probe budget.",
        "strongest_baseline": "Retain-all subsampling, recency, IRT, PACE-style selection, and random retirement.",
        "pilot": "Fit probe utilities on early versions of two chronological release streams and evaluate future-regression recall and AUPRC on held-out versions using a hidden full suite.",
        "stop_condition": "Stop if missed future regressions are not reduced by at least 10% over the strongest equal-budget baseline on both release streams.",
    },
    "adaptive-exam-scheduler": {
        "purpose": "Full benchmark evaluation is expensive.",
        "core_idea": "Select informative items using live performance and item-response theory.",
        "collision_boundary": "AutoJudger and JudgeAgent directly cover adaptive evaluation and compact test selection.",
        "hypothesis": "Adaptive selection can reduce evaluation cost while preserving rankings.",
        "strongest_baseline": "Random subsets and full evaluation.",
        "pilot": "Recover model rankings across multiple benchmarks at reduced item budgets.",
        "stop_condition": "Reject as a new paper and use it only as a baseline for change-triggered exams.",
    },
    "multi-surface-change-attribution": {
        "purpose": "Behavioral changes may arise jointly from weights, data, prompts, memory, and workflows.",
        "core_idea": "Attribute a regression across all changed surfaces in one unified analysis.",
        "collision_boundary": "ExPLAIND, TRACE, and existing provenance or lineage systems already cover broad training and risk attribution.",
        "hypothesis": "Joint attribution should outperform isolated per-source attribution.",
        "strongest_baseline": "Per-source ablation and whole-version rollback.",
        "pilot": "Inject synthetic changes across multiple components and evaluate source recovery.",
        "stop_condition": "Reject because the scope is too broad and the attribution space is already crowded.",
    },
    "version-differential-failure-localization": {
        "purpose": "Whole-version rollback shows that a new version is faulty but not whether the prompt, memory, skill, workflow, or small module caused the failure.",
        "core_idea": "Learn a budgeted intervention policy that swaps minimal components between adjacent versions, localizes interacting faults, and restricts repair to the implicated surface.",
        "collision_boundary": "Software delta debugging localizes code and TRACE or ExPLAIND attribute training factors; amortized multi-surface agent localization across versions remains distinct if it transfers.",
        "hypothesis": "A learned swap policy should localize single- and double-surface faults more accurately and with fewer calls than rollback, logs, or ddmin.",
        "strongest_baseline": "Whole-version rollback, log-only attribution, ddmin, AgentLocate-style trajectory localization, SkillAdaptor, and exhaustive oracle localization.",
        "pilot": "Inject single- and double-surface faults in adjacent ALFWorld and WebArena-Lite releases; test on held-out models, versions, and fault compositions.",
        "stop_condition": "Stop or merge if exact double-fault recovery does not beat ddmin by at least 10 points at the same call budget on the second model.",
    },
    "update-responsibility-graph": {
        "purpose": "When individually valid updates interact and regress, the system needs to trace responsibility through their dependencies.",
        "core_idea": "Build an update-dependency and interaction graph to assign blame and minimize rollback scope.",
        "collision_boundary": "This substantially overlaps Compositional Update Compatibility and lineage-aware rollback.",
        "hypothesis": "Responsibility graphs should reduce unnecessary rollback.",
        "strongest_baseline": "Per-update rollback, Shapley attribution, and dependency logs.",
        "pilot": "Create three-update composition failures and compare exact blame and rollback scope.",
        "stop_condition": "Use only as a follow-up mechanism for Compositional Update Compatibility, not a standalone project.",
    },
    "data-policy-drift-decomposition": {
        "purpose": "Performance changes may come from covariate shift or from instability introduced by a policy update.",
        "core_idea": "Decompose observed risk changes into data-shift and policy-update components.",
        "collision_boundary": "TRACE directly proposes this decomposition objective.",
        "hypothesis": "Risk decomposition should improve update gating.",
        "strongest_baseline": "Aggregate risk difference without decomposition.",
        "pilot": "Evaluate on controlled distribution and policy shifts.",
        "stop_condition": "Reject as a direct collision.",
    },
    "retry-to-one-shot-distillation": {
        "purpose": "Multi-round retries may succeed while one-shot execution remains unreliable.",
        "core_idea": "Distill successful retry trajectories into a one-shot policy.",
        "collision_boundary": "SCoRe, RePrompt, Guided Sampling, and multi-agent reflection already cover retry internalization.",
        "hypothesis": "Distillation should reduce the need for retries.",
        "strongest_baseline": "Fixed two-pass correction, offline SFT, and resampling.",
        "pilot": "Evaluate reasoning and tool tasks under matched inference and training budgets.",
        "stop_condition": "Reject because the core mechanism is already crowded.",
    },
    "retry-signal-distillation-gate": {
        "purpose": "Retry traces mix reusable repair information with luck from extra sampling.",
        "core_idea": "Use matched retries, step permutation, and no-retry controls to identify which fragments deserve persistent memory or policy updates.",
        "collision_boundary": "The idea overlaps correction credit, intervention-validated self-correction, and causal experience admission.",
        "hypothesis": "A gate should preserve repair gains while reducing harmful commits from lucky retries.",
        "strongest_baseline": "Write-all, success-only admission, confidence gating, and random fragments.",
        "pilot": "Use two models, three retry-failure families, and matched calls to compare persistent update quality.",
        "stop_condition": "Keep only as a component if it cannot establish a mechanism boundary from existing correction-credit methods.",
    },
    "retry-dependence-index": {
        "purpose": "Final success rate hides how much a system depends on repeated prompting and extra samples.",
        "core_idea": "Measure the performance drop without retries, retry depth, and residual gain after removing persistent state.",
        "collision_boundary": "This is a useful Reality-of-Evolution metric rather than a standalone learning mechanism.",
        "hypothesis": "The index should identify pseudo-evolution driven by extra inference.",
        "strongest_baseline": "Success rate and average model-call count.",
        "pilot": "Reuse P0 results from the existing idea bank and compare persistent versus retry-only gains.",
        "stop_condition": "Adopt as a common backend metric rather than a standalone submission.",
    },
    "recurrent-failure-contract-compilation": {
        "purpose": "When the same failure recurs, systems keep appending verbal reflections, creating overlapping rules and growing inference cost.",
        "core_idea": "Compile repeated failures into executable contracts with applicability, forbidden actions, validators, and expiry, replacing raw reflections only after out-of-loop replay.",
        "collision_boundary": "Trace2Skill, SkillOpt, behavioral contracts, and reflection-hint distillation already cover most of this combination.",
        "hypothesis": "Contract compilation should reduce recurrent failures and rule conflicts at the same context budget and transfer across models.",
        "strongest_baseline": "Append-all reflection, summarized reflection, Trace2Skill, SkillOpt, and behavioral-contract baselines.",
        "pilot": "Create recurrent ALFWorld and tool failures, freeze the backbone, and compare contract size, conflict rate, recurrence, and second-model transfer.",
        "stop_condition": "Stop if gains disappear after matching context length and verifier access; merge expiry validation into a broader skill or contract project.",
    },
    "model-swap-compatibility-certificate": {
        "purpose": "After a foundation-model swap, prompts, memories, skills, and workflows may silently fail, often discovered only after full migration.",
        "core_idea": "Train a calibrated asset-level certificate that predicts negative transfer, uncertainty, and adaptation cost before migration.",
        "collision_boundary": "PromptBridge, SkillRT or SkVM, and MASA cover prompt or skill transfer; novelty requires asset-agnostic prediction across the composed agent state and unseen asset classes.",
        "hypothesis": "Small probe profiles should predict asset-level migration failures and avoid full migrations or unnecessary rewrites.",
        "strongest_baseline": "Budget-matched shadow migration, source success, semantic similarity, PromptBridge, SkillRT, and MASA profiles.",
        "pilot": "Train on two source-target model families and three asset classes; test calibration and negative-transfer recall on an unseen target family and held-out fourth asset class.",
        "stop_condition": "Stop if recall is below 90% on the unseen target family or full migration trials and rewrites are not reduced by at least 25%.",
    },
    "cross-model-skill-portability-gate": {
        "purpose": "The same stored skill can help one backbone and harm another.",
        "core_idea": "Filter or rewrite skills for each target model.",
        "collision_boundary": "MASA and SkCC directly cover model-aware skill adaptation and cross-framework compilation.",
        "hypothesis": "Model-aware skills should outperform one-size-fits-all skills.",
        "strongest_baseline": "Universal skills and target-model rewriting.",
        "pilot": "Evaluate a multi-model skill benchmark.",
        "stop_condition": "Reject and use as a strong baseline for the broader compatibility-certificate idea.",
    },
    "provider-migration-adapter": {
        "purpose": "Provider-specific formats, tool protocols, and refusal behavior can break an agent migration.",
        "core_idea": "Learn a lightweight intermediate representation that rewrites system prompts, tool schemas, and skills.",
        "collision_boundary": "SkCC already proposes cross-framework intermediate representations and MASA handles model-aware rewriting.",
        "hypothesis": "An adapter should preserve pre-migration behavior.",
        "strongest_baseline": "Manual rewriting, SkCC, and MASA.",
        "pilot": "Evaluate two proprietary APIs and two open models under matched migration budgets.",
        "stop_condition": "Merge into Model-Swap Compatibility Certificate unless a new behavior-preservation constraint is established.",
    },
    "swap-aware-regression-localization": {
        "purpose": "After a model swap, failure may reflect an intrinsic backbone gap or incompatibility in old prompts, memory, skills, or tool assumptions.",
        "core_idea": "Run factorial backbone-by-asset substitutions to identify the smallest repair.",
        "collision_boundary": "The factorial ablation is itself the strongest diagnostic baseline and is better used as oracle labels for the compatibility-certificate idea.",
        "hypothesis": "Localized repair should beat full rewriting while preserving already compatible assets.",
        "strongest_baseline": "Exhaustive factorial ablation, full rewrite, prompt-only repair, skill-only repair, and semantic similarity.",
        "pilot": "Inject compatibility faults across source and target model families and measure attribution, repair calls, success, and preserved assets.",
        "stop_condition": "Discontinue as a standalone idea unless a learned localizer matches oracle labels with at most half the calls and lower post-repair regression.",
    },
    "behavior-triggered-privilege-lease": {
        "purpose": "Static permission ignores changing agent versions and competence; one reliable run does not justify permanent high authority.",
        "core_idea": "Learn a version-conditioned controller that leases task-scoped privileges and updates duration or scope from independently verified behavioral evidence.",
        "collision_boundary": "Dynamic capability scoping, least-privilege inference, and temporary authority already exist; novelty requires persistent learned renewal across future versions.",
        "hypothesis": "A learned lease controller should reduce attacks and over-privilege at matched task utility and transfer to unseen agent versions.",
        "strongest_baseline": "Static least privilege, task-conditioned dynamic scoping, MAC enforcement, and commit-time reauthorization.",
        "pilot": "Run three chronological agent versions on held-out authorization tasks with executable utility and attack validators under identical permission ceilings.",
        "stop_condition": "Stop if task-conditioned dynamic scoping Pareto-dominates the learned lease or gains vanish with an external validator.",
    },
    "privilege-recovery-curriculum": {
        "purpose": "After permission downgrade, systems often remain permanently conservative or restore authority in one step.",
        "core_idea": "Learn a failure-conditioned requalification policy that selects minimal probes and the smallest safe permission increment.",
        "collision_boundary": "Progressive trust escalation already exists; novelty requires learned probe selection, persistent permission state, and held-out failure-family transfer.",
        "hypothesis": "Learned requalification should reduce permanent over-restriction without increasing unauthorized actions.",
        "strongest_baseline": "Permanent downgrade, one-shot restoration, fixed staged escalation, fixed waiting periods, and human approval.",
        "pilot": "Use sequential ToolPrivBench or AuthBench-derived episodes, holding out one failure family and one task domain under equal probe and tool-call budgets.",
        "stop_condition": "Stop if fixed staged escalation matches held-out task success at no higher unauthorized-action rate.",
    },
    "update-aware-permission-downgrade": {
        "purpose": "Prompt, memory, skill, workflow, or model updates can change tool behavior while permissions are inherited from the previous version.",
        "core_idea": "Learn an update-to-permission impact model that maps the exact diff to temporary authority and change-conditioned reauthorization probes.",
        "collision_boundary": "Static least privilege and generic regression gating exist separately; novelty requires calibrated update-specific reauthorization that transfers to unseen update operators.",
        "hypothesis": "Update-aware downgrade should prevent newly introduced overreach while preserving more utility than permanent minimum privilege.",
        "strongest_baseline": "Unchanged permissions, permanent least privilege, SEAgent plus full regression, fixed staged restoration, and ABAC or MAC.",
        "pilot": "Run sequential prompt, memory, and skill updates with hidden permission-relevant effects under matched test, tool-call, and token budgets.",
        "stop_condition": "Stop if SEAgent plus full regression matches safety and utility at the same total budget or gains come only from withholding high-risk permissions.",
    },
    "least-privilege-skill-graduation": {
        "purpose": "New skills often receive full tool authority immediately.",
        "core_idea": "Graduate a skill from read-only to sandboxed, supervised, and full authority after staged evidence.",
        "collision_boundary": "Agent-skill lifecycle governance and least-privilege benchmarks already provide closely related staged controls.",
        "hypothesis": "Skill graduation should reduce high-privilege exposure.",
        "strongest_baseline": "Fixed skill permissions and static four-tier governance.",
        "pilot": "Evaluate staged authority on AgentSkills-style tasks with external safety validators.",
        "stop_condition": "Use as a privilege-lease component unless learned evidence updates and cross-version recovery establish a distinct mechanism.",
    }
}
