from __future__ import annotations

from typing import Any

from .method_details_common import bi


def fresh(summary_zh: str, summary_en: str, sources: list[dict[str, str]]) -> dict[str, Any]:
    return {"review_date": "2026-08-10", "summary": bi(summary_zh, summary_en), "sources": sources}


DETAILS: dict[str, dict[str, Any]] = {
    "workflow-generalization-certificate": {
        "title": bi("成对编辑效应工作流更新策略", "Paired Edit-Effect Workflow Update Policy"),
        "purpose": bi("WorkflowPerturb、Agentic Predictor、FLORA 已覆盖 workflow 扰动/性能预测，CE-Graph 也已根据 failure distribution 做 targeted graph edits；因此不能再做 certificate。剩下的问题是：能否从历史 before/after 编辑试验中学出一个冻结后可跨 workflow 直接选 edit 的持久 update policy。", "WorkflowPerturb, Agentic Predictor, and FLORA cover workflow perturbation/performance prediction, while CE-Graph already applies failure-driven targeted graph edits. A certificate is no longer enough. The remaining question is whether paired before/after edit interventions can train a persistent update policy that directly chooses edits on unseen workflows after freezing."),
        "core_idea": bi("固定 typed edit library，把每次历史试验记录成 (W, e, W⊕e, ΔU)。学习 conditional edit-effect 或直接的 π(e|local graph context, API types, failure signature)。进入 hidden workflow 后策略冻结，只能一次选择并 commit edit，禁止先试跑候选。", "Fix a typed edit library and record each historical trial as (W, e, W⊕e, ΔU). Learn conditional edit effect or directly π(e | local graph context, API types, failure signature). On hidden workflows the policy is frozen and must choose and commit one edit without trial-running candidates first."),
        "core_intuition": bi("绝对 workflow score 只能告诉我们哪个图好；真正可迁移的学习对象应是‘在什么局部上下文里，哪种 edit 的因果增量通常为正’。", "Absolute workflow scores only say which graph is good; the transferable object should be which edit has positive causal effect in which local context."),
        "concrete_example": bi("历史上 40 次 workflow edit 包含 insert verifier、replace API、add retry edge。模型学到‘tool schema 不稳定 + single-path branch’时 insert verifier 通常带来正 ΔU。测试一个未见 API workflow 时不先试 10 个图，而直接提交这一 edit。", "Forty historical workflow edits include insert-verifier, replace-API, and add-retry-edge operations. The model learns that insert-verifier tends to have positive ΔU under unstable tool schemas plus single-path branches. On an unseen API workflow it directly commits that edit rather than trying ten candidate graphs."),
        "method_logic": bi("1) 冻结 typed edit library；2) source workflows 上做 matched before/after 单编辑干预；3) 用真实 execution ΔU 监督 edit-effect policy；4) 控制 edit type/frequency 和 execution budget；5) 冻结 policy；6) hidden workflow 上禁止 candidate trials，只允许一次 edit 选择+commit；7) 最终在未见 API/graph motif 测 persistent benefit。", "1) Freeze a typed edit library; 2) run matched before/after single-edit interventions on source workflows; 3) supervise the edit-effect policy with true execution ΔU; 4) control edit type/frequency and execution budget; 5) freeze the policy; 6) forbid candidate trials on hidden workflows and allow one edit choice+commit; 7) measure persistent benefit on unseen APIs/graph motifs."),
        "comparative_advantage": bi("Agentic Predictor 预测完整 workflow 的绝对性能；CE-Graph 在当前 failure pool 上 propose-and-verify。这里必须证明历史 edit-effect 能被 amortize 成冻结 editor，在 hidden workflow 零搜索直接修改。", "Agentic Predictor estimates absolute workflow performance, while CE-Graph proposes and verifies edits on the current failure pool. This idea must show historical edit effects can be amortized into a frozen editor that modifies hidden workflows with zero search."),
        "strongest_baseline": bi("Agentic Predictor + threshold/selection：相同 source execution 数据与模型容量，预测候选完整 workflow score；hidden 阶段同样禁止试跑，只按 predictor 选择一个 edit。", "Agentic Predictor plus threshold/selection: same source execution data and model capacity, predicts full candidate-workflow scores; hidden stage likewise forbids trials and selects one edit via the predictor."),
        "pilot": bi("40–60 个 source workflow edits，4–6 种 typed operators；hidden 20–30 个 workflow/API graph。比较 nearest-neighbor edit reuse、Agentic Predictor、CE-Graph-style failure editor、paired edit-effect policy；hidden 阶段全部限制为单次 edit commit。", "Use 40–60 source workflow edits across 4–6 typed operators and 20–30 hidden workflows/API graphs. Compare nearest-neighbor edit reuse, Agentic Predictor, a CE-Graph-style failure editor, and the paired edit-effect policy; hidden-stage methods are all restricted to one edit commit."),
        "metric": bi("hidden post-edit success Δ、负 edit 率、零搜索 edit precision、执行次数、跨 API/graph motif transfer。", "Hidden post-edit success delta, harmful-edit rate, zero-search edit precision, execution count, and transfer across APIs/graph motifs."),
        "stop": bi("若 Agentic Predictor、nearest-neighbor edit reuse 或 failure-signature heuristic 在相同 source/hidden execution 预算下等效，则停止 update-policy 主张。", "Stop if Agentic Predictor, nearest-neighbor edit reuse, or a failure-signature heuristic matches under the same source/hidden execution budget."),
        "persistent_update_object": bi("冻结后跨 workflow 复用的 typed workflow-edit policy/conditional edit-effect model，以及实际提交后的版本化 workflow。", "A frozen typed workflow-edit policy/conditional edit-effect model reused across workflows, plus the versioned committed workflow."),
        "learning_signal": bi("source workflow 单编辑 before/after 的真实 execution utility ΔU。", "True execution-utility ΔU from single-edit before/after interventions on source workflows."),
        "independent_truth": bi("程序化 workflow success、tool/API execution 与任务金标；predictor/edit-effect 自己的分数不作为标签。", "Programmatic workflow success, tool/API execution, and task gold labels; predictor/edit-effect scores never serve as truth."),
        "collision_boundary": bi("WorkflowPerturb 已覆盖 controlled perturbation，Agentic Predictor/FLORA 已覆盖 performance prediction，CE-Graph 已覆盖 failure-driven propose-and-verify。只保留 paired edit interventions → frozen zero-search editor 这一边界。", "WorkflowPerturb covers controlled perturbation, Agentic Predictor/FLORA cover performance prediction, and CE-Graph covers failure-driven propose-and-verify. The surviving boundary is paired edit interventions yielding a frozen zero-search editor."),
        "nearest_work": ["Agentic Predictor", "FLORA", "Failure-Driven Workflow Refinement / CE-Graph", "WorkflowPerturb"],
        "fresh_reducibility_check": fresh("旧 certificate/predictor 版本已碰撞；新版本只有在 hidden workflow 零搜索 edit 上赢过 absolute predictor 才成立。", "The old certificate/predictor form is collided; the redesign survives only if zero-search edits on hidden workflows beat absolute prediction.", [
            {"title": "Agentic Predictor: Performance Prediction for Agentic Workflows via Multi-View Encoding", "url": "https://arxiv.org/abs/2505.19764"},
            {"title": "GNNs as Predictors of Agentic Workflow Performances", "url": "https://arxiv.org/abs/2503.11301"},
            {"title": "Failure-Driven Workflow Refinement", "url": "https://openreview.net/forum?id=IqxucrBy2z"},
            {"title": "WorkflowPerturb: Calibrated Stress Tests for Evaluating Multi-Agent Workflow Metrics", "url": "https://arxiv.org/abs/2602.17990"},
        ]),
        "redesign_iteration": {"round": "2026-08-10", "verdict": "fresh-collision-recheck", "summary": bi("certificate 版彻底停止；改成 paired edit-effect → frozen zero-search editor。只有 hidden workflow 直接 commit edit 仍优于 predictor/heuristic 才重新解锁。", "The certificate version is stopped. Redesign: paired edit effects → frozen zero-search editor; re-unlock only if direct hidden-workflow edits beat predictors/heuristics.")},
    },
    "workflow-branch-credit": {
        "title": bi("故障模式因果重写语法", "Failure-Motif Causal Rewrite Grammar"),
        "purpose": bi("CE-Graph 已经会从 failure distribution 定位 recurring mode 并 propose-and-verify graph edit，因此单纯 branch credit 不足。剩余问题是：能否用少量 group intervention 找到真正致因子图，并把跨 workflow 重复的 cause→rewrite 编译成冻结 grammar，后续不再搜索。", "CE-Graph already identifies recurring failure modes and propose-and-verifies graph edits, so branch credit alone is insufficient. The remaining problem is whether sparse group interventions can identify causal subgraphs and compile recurring cause→rewrite mappings into a frozen grammar reusable without search."),
        "core_idea": bi("先用单轨迹执行图/surrogate 给节点边分组，再对少量 group 做 disable/replace intervention，自适应下钻到最小 causal subgraph。把多次验证得到的 (failure motif, local graph context)→typed rewrite 编译成 grammar；hidden workflow 只允许 grammar 直接重写一次。", "Use single-trajectory execution graphs/surrogates to group nodes/edges, then apply disable/replace interventions to a few groups and adaptively descend to a minimal causal subgraph. Compile repeatedly validated (failure motif, local graph context)→typed rewrite rules into a grammar; hidden workflows allow only one direct grammar rewrite."),
        "core_intuition": bi("搜索知道‘哪次 edit 得分高’，但如果不同 workflow 的失败由同一种局部结构造成，真正应该学习的是可复用的 cause→rewrite rule。", "Search knows which edit scored well, but if different workflows fail for the same local structural reason, the reusable object should be a cause→rewrite rule."),
        "concrete_example": bi("多个 workflow 都在 parallel tool branches 后丢失状态合并。group intervention 反复定位到 merge node 及其两条 incoming edges；grammar 学到该 motif 下插入 typed state-merge verifier，而不是每个新 workflow 重跑 MCTS。", "Several workflows lose state after parallel tool branches. Group interventions repeatedly localize the merge node and two incoming edges; the grammar learns to insert a typed state-merge verifier for that motif instead of rerunning MCTS for each new workflow."),
        "method_logic": bi("1) 冻结 failure traces/workflow graphs；2) surrogate 只做廉价 group ranking；3) 对 top groups 做 matched intervention 并自适应下钻；4) verifier/任务 truth 确认 minimal causal subgraph；5) 跨 workflow 聚合同类 motif；6) 编译 typed rewrite grammar；7) hidden workflow 零搜索应用一次。", "1) Freeze failure traces/workflow graphs; 2) use a surrogate only for cheap group ranking; 3) run matched interventions on top groups and adaptively descend; 4) verify a minimal causal subgraph with task truth; 5) aggregate recurring motifs across workflows; 6) compile a typed rewrite grammar; 7) apply once with zero search on hidden workflows."),
        "comparative_advantage": bi("与 CE-Graph 的当前 failure-pool propose-and-verify 相比，唯一新增价值是 intervention-confirmed cause→rewrite grammar 能否跨 workflow 复用；如果不能，就应并回 E-1/CE-Graph。", "Relative to CE-Graph propose-and-verify on the current failure pool, the only added value is whether intervention-confirmed cause→rewrite grammar transfers across workflows; otherwise merge back into E-1/CE-Graph."),
        "strongest_baseline": bi("CE-Graph-style failure-driven editor：同 failure pool、同 typed edit library、同 intervention/execution 总预算，但每个 hidden workflow 重新按 failure signature propose-and-verify，不复用 grammar。", "CE-Graph-style failure-driven editor: same failure pool, typed edit library, and total intervention/execution budget, but re-proposes/verifies from each hidden workflow's failure signature instead of reusing a grammar."),
        "pilot": bi("source 12–20 个 workflow，每类 failure motif 至少出现 3 次；编译 3–6 条 rewrite rules。hidden workflows 上比较 CE-Graph-style editor、E-1 edit-effect policy、grammar direct rewrite，调用严格匹配。", "Use 12–20 source workflows with each failure motif recurring at least three times and compile 3–6 rewrite rules. On hidden workflows compare a CE-Graph-style editor, the E-1 edit-effect policy, and direct grammar rewrite with matched calls."),
        "metric": bi("causal subgraph precision、hidden direct-rewrite success、搜索/执行节省、错误 rewrite 率、跨 workflow motif transfer。", "Causal-subgraph precision, hidden direct-rewrite success, search/execution savings, harmful-rewrite rate, and cross-workflow motif transfer."),
        "stop": bi("若 CE-Graph-style editor 或 E-1 edit-effect policy 在同预算下等效，或 grammar 只能记住具体 node names/API，则并入 E-1，不独立保留。", "Merge into E-1 if a CE-Graph-style editor or E-1 edit-effect policy matches at equal budget, or if the grammar only memorizes concrete node names/APIs."),
        "persistent_update_object": bi("跨 workflow 持久保存的 failure-motif → typed local rewrite grammar。", "A persistent cross-workflow failure-motif → typed local rewrite grammar."),
        "learning_signal": bi("group disable/replace intervention 后独立任务 truth 的改善，定位 causal subgraph 并监督 rewrite。", "Independent task-truth improvement after group disable/replace interventions localizes causal subgraphs and supervises rewrites."),
        "independent_truth": bi("workflow 执行结果/程序 checker；surrogate 与 failure signature 只用于选干预，不提供最终因果标签。", "Workflow execution/program checkers provide truth; surrogates and failure signatures only select interventions and do not define causal labels."),
        "parent_id": "workflow-generalization-certificate",
        "parent_merge_rule": bi("若 E-1 paired edit-effect policy 在相同 edit library/execution 预算下达到同等 hidden direct-edit success，E-2 必须作为 E-1 的 attribution/grammar 子组件合并。", "If the E-1 paired edit-effect policy matches hidden direct-edit success under the same edit library/execution budget, E-2 must merge as an attribution/grammar component of E-1."),
        "collision_boundary": bi("CE-Graph 已把 recurring failure distribution→targeted graph edit 做成方法；因此不能主张 failure-guided refinement。只保留 intervention-confirmed minimal causal subgraph → reusable rewrite grammar。", "CE-Graph already maps recurring failure distributions to targeted graph edits, so failure-guided refinement is not novel. The surviving claim is intervention-confirmed minimal causal subgraph → reusable rewrite grammar."),
        "nearest_work": ["Failure-Driven Workflow Refinement / CE-Graph", "AFlow", "Agentic Predictor"],
        "fresh_reducibility_check": fresh("E-2 是严格 parent-merge 方向：只有 rewrite grammar 的跨 workflow 复用价值不能被 E-1/CE-Graph 解释时才独立。", "E-2 is a strict parent-merge direction: it survives independently only if cross-workflow rewrite-grammar transfer cannot be explained by E-1/CE-Graph.", [
            {"title": "Failure-Driven Workflow Refinement", "url": "https://openreview.net/forum?id=IqxucrBy2z"},
            {"title": "Agentic Predictor", "url": "https://arxiv.org/abs/2505.19764"},
        ]),
        "redesign_iteration": {"round": "2026-08-10", "verdict": "parent-merge-test", "summary": bi("从 branch credit 收窄为 intervention-confirmed failure motif rewrite grammar；若 E-1 同预算 editor 等效，就作为 E-1 子组件合并。", "Narrowed from branch credit to intervention-confirmed failure-motif rewrite grammar; merge as an E-1 component if the equal-budget editor matches.")},
    },
}
