from __future__ import annotations

from typing import Any

from .method_details_common import bi


def fresh(summary_zh: str, summary_en: str, sources: list[dict[str, str]]) -> dict[str, Any]:
    return {"review_date": "2026-08-10", "summary": bi(summary_zh, summary_en), "sources": sources}


DETAILS: dict[str, dict[str, Any]] = {
    "causally-verified-experience-admission": {
        "title": bi("影响范围路由的经验准入", "Influence-Routed Experience Admission"),
        "purpose": bi("generic pre-commit gate 已经有直接工作；memory-specific 方向只剩一个更窄问题：在完全固定的 Probe 数量下，能否利用 lesson 的触发条件与适用范围，把有限 sentinel 预算更准确地分给真正可能受影响的任务。", "Generic pre-commit gates now have direct prior work. The memory-specific question that remains is whether lesson triggers and applicability scope can route a strictly fixed sentinel budget toward tasks actually likely to be affected."),
        "core_idea": bi("每条 lesson 固定只允许 6 个 sentinel。scope router 根据触发条件、检索位置、tool/API 类型和任务结构，分配 2 个预计受影响、2 个边界、2 个预计不受影响任务；做 paired before/after 后才准入。A-3 使用完全相同 6 个 Probe 与真值作为 parent control。", "Each lesson receives exactly six sentinels. A scope router uses trigger conditions, retrieval position, tool/API type, and task structure to allocate two predicted-affected, two boundary, and two predicted-unaffected tasks; admission follows paired before/after testing. A-3 receives the exact same six-probe budget and truth as the parent control."),
        "core_intuition": bi("如果一条 memory 的影响范围有结构，固定预算应该花在‘哪里可能被它改变’上，而不是均匀或全局地抽 Probe。", "If a memory has structured influence scope, a fixed audit budget should be spent where that memory is likely to change behavior rather than on uniform/global probes."),
        "concrete_example": bi("一条关于 429 API 错误的 lesson 不应把 6 个 Probe 平均花在完全无 API 的任务上。scope router 选择 2 个相同 API family、2 个边界 tool-use、2 个明显无关任务；若相关 family 回退就拒绝写入。", "A lesson about API 429 errors should not spend six probes uniformly on tasks with no API use. The scope router selects two same-API-family tasks, two boundary tool-use tasks, and two clearly unrelated tasks; regression in the related family blocks admission."),
        "method_logic": bi("1) discovery lesson 用真实 before/after 影响拟合轻量 scope router；2) 新 lesson 固定 K=6；3) router 只负责 sentinel 分配，不决定 truth；4) source task + 6 sentinel 做 paired replay；5) 冻结 router 后在未见 task family 测试；6) 同一 6 Probe 交给 A-3 predictive panel 做 parent-merge 对照。", "1) Fit a lightweight scope router from true before/after influence of discovery lessons; 2) fix K=6 for every new lesson; 3) the router only allocates sentinels and never defines truth; 4) run paired replay on the source task plus six sentinels; 5) freeze before unseen task families; 6) give the same six probes to the A-3 predictive panel for the parent-merge control."),
        "comparative_advantage": bi("与 generic gate 的唯一区别是 memory-specific scope routing；critic、K、阈值、truth 和候选完全匹配。", "The only difference from the generic gate is memory-specific scope routing; critics, K, thresholds, truth, and candidates are matched."),
        "strongest_baseline": bi("A-3 通用 predictive regression panel：同样 K=6、同候选 lesson、同 hidden truth 与调用预算，但不使用 memory trigger/applicability 特征分配 Probe。", "A-3 generic predictive regression panel: same K=6, candidate lessons, hidden truth, and call budget, but no memory trigger/applicability features for probe allocation."),
        "pilot": bi("20–30 个冻结 lesson，6-sentinel 硬预算；比较随机、全局历史敏感度、A-3 learned panel、scope-routed panel。hidden task family 在 router 和阈值冻结后才打开。", "Use 20–30 frozen lessons with a hard six-sentinel budget; compare random, global historical sensitivity, the A-3 learned panel, and scope-routed selection. Hidden task families open only after router/threshold freeze."),
        "metric": bi("matched accepted-count 下 harmful admission、受影响任务 recall、边界任务 false alarm、source gain、每条 lesson 固定 6 Probe。", "Harmful admission at matched accepted count, affected-task recall, boundary-task false alarms, source gain, with exactly six probes per lesson."),
        "stop": bi("若 A-3 通用面板在同 6-Probe 预算下等效，立即并入 A-3；若 scope 只有通过更多 replay 才获胜，也停止。", "Immediately merge into A-3 if the generic panel matches at the same six-probe budget; also stop if scope wins only through extra replay."),
        "persistent_update_object": bi("跨轮保存的 memory influence-scope router 与 lesson 准入状态。", "A cross-round memory influence-scope router and lesson admission state."),
        "learning_signal": bi("discovery lesson 对不同任务的真实 paired before/after 影响，监督 scope allocation。", "True paired before/after impact of discovery lessons across tasks supervises scope allocation."),
        "independent_truth": bi("sentinel 和 hidden 原任务的环境/程序结果；scope router 只选样，不提供标签。", "Environment/program outcomes on sentinel and hidden original tasks; the scope router only selects samples and never supplies labels."),
        "parent_id": "regression-gated-self-evolution",
        "parent_merge_rule": bi("若相同 K=6 的 A-3 predictive panel 在 harmful-admission、source gain 和 hidden regression 上与 scope router 的 CI 重叠，则 B-4 必须并入 A-3。", "If the A-3 predictive panel with identical K=6 overlaps the scope router in CI on harmful admission, source gain, and hidden regression, B-4 must merge into A-3."),
        "collision_boundary": bi("VaG 已覆盖 pre-commit skill gate，CMI/ReMe 已覆盖 memory utility；因此 B-4 不能主张 generic causal admission，只剩 memory-specific influence scope 是否能在固定 sentinel 预算下优于 A-3 通用面板。", "VaG covers pre-commit skill gating and CMI/ReMe cover memory utility, so B-4 cannot claim generic causal admission. The only surviving variable is whether memory-specific influence scope beats the A-3 generic panel under a fixed sentinel budget."),
        "nearest_work": ["When Self-Evolution Backfires / VaG", "Causal Memory Intervention", "ReMe"],
        "fresh_reducibility_check": fresh("这是严格 parent-merge 题；独立价值完全取决于 memory-specific scope routing 是否赢过 A-3。", "This is a strict parent-merge question; standalone value depends entirely on memory-specific scope routing beating A-3.", [
            {"title": "When Self-Evolution Backfires: Pre-Commit Gating against Skill Contamination in LLM Agents", "url": "https://arxiv.org/abs/2608.05810"},
            {"title": "Causal Intervention-Based Memory Selection for Long-Horizon LLM Agents", "url": "https://arxiv.org/abs/2605.17641"},
            {"title": "Remember Me, Refine Me", "url": "https://aclanthology.org/2026.findings-acl.829/"},
        ]),
        "redesign_iteration": {"round": "2026-08-10", "verdict": "parent-merge-test", "summary": bi("只保留固定 6 Probe 下的 memory-specific scope routing；同预算 A-3 若等效，直接合并，不再单列。", "Only memory-specific scope routing under a fixed six-probe budget survives; merge directly into A-3 if the equal-budget parent matches.")},
    },
    "local-counterexample-memory-repair": {
        "title": bi("最小单调适用边界修复", "Minimal Monotone Applicability Repair"),
        "purpose": bi("遇到反例时整条删除或重写 procedural memory 会损失仍然有效的主体；但 counterexample-driven skill refinement 已有工作，因此新变量必须是‘skill body 完全冻结，只允许 external applicability gate 最小且单调地收缩’。", "Deleting or rewriting a procedural memory after a counterexample destroys still-valid content. Because counterexample-driven skill refinement already exists, the new variable must be a fully frozen skill body with only a minimally and monotonically shrinking external applicability gate."),
        "core_idea": bi("冻结 skill body 和预定义 predicate vocabulary。每个验证反例只允许向 external gate 增加最小 distinguishing predicate，使该反例被排除；gate 不得重新扩张，且每次收缩都必须通过旧正例保持测试。", "Freeze the skill body and a predefined predicate vocabulary. Each verified counterexample may only add the minimal distinguishing predicate to an external gate that excludes that counterexample; the gate cannot re-expand, and every shrink must preserve old positives."),
        "core_intuition": bi("反例通常只说明‘这条规则在这里不适用’，并不等于规则主体错误；把修复限制为最小适用集合收缩可以避免过度遗忘。", "A counterexample often means the rule does not apply here, not that the rule body is wrong. Restricting repair to minimal applicability shrinkage can avoid over-forgetting."),
        "concrete_example": bi("skill 是‘看到可打开容器先 open 再取物’。一个反例来自容器已经 open 的状态。方法不改 skill 文本，只给 gate 增加 predicate `container_closed=true`；旧的 closed-container 正例必须继续成功。", "A skill says 'open an openable container before taking the object.' A counterexample occurs when the container is already open. The method does not rewrite the skill; it adds `container_closed=true` to the gate, while previous closed-container positives must still succeed."),
        "method_logic": bi("1) 冻结 skill body/predicate vocabulary；2) verifier 确认 counterexample；3) 搜索能区分反例与旧正例的最小 predicate conjunction；4) 只收缩 applicability gate；5) 每次修复做 old-positive preservation；6) 跨第二 task family 前冻结 gate learner。", "1) Freeze skill body/predicate vocabulary; 2) verify the counterexample; 3) find the minimal predicate conjunction separating it from old positives; 4) shrink only the applicability gate; 5) test old-positive preservation after every repair; 6) freeze the gate learner before a second task family."),
        "comparative_advantage": bi("与 CEDAR/MemoRepair 的整体 skill/provenance 修复不同，这里把可修改表面压到 external applicability gate，并用 monotonicity + minimality 限制修复自由度。", "Unlike CEDAR/MemoRepair-style skill/provenance repair, this restricts the update surface to an external applicability gate and constrains repair with monotonicity and minimality."),
        "strongest_baseline": bi("容量匹配的 applicability classifier：同 predicate、同 counterexample/positive 数据，允许任意重新拟合边界而不要求单调收缩。", "Capacity-matched applicability classifier: same predicates and counterexample/positive data, but free to refit arbitrary boundaries without monotone shrinkage."),
        "pilot": bi("冻结 10–15 个 procedural skills，每个注入 2–4 个可验证边界反例；比较 delete、full rewrite、free classifier、minimal monotone gate，旧正例与新反例 paired 测试。", "Freeze 10–15 procedural skills with 2–4 verifiable boundary counterexamples each; compare delete, full rewrite, free classifier, and minimal monotone gates on paired old-positive and new-counterexample tests."),
        "metric": bi("counterexample repair rate、old-positive preservation、gate predicate 数、未来 boundary generalization 和无效 skill activation。", "Counterexample repair rate, old-positive preservation, number of gate predicates, future-boundary generalization, and invalid skill activations."),
        "stop": bi("若 free classifier/full rewrite 在同容量下同时达到相同修复率和旧正例保持，或最小单调约束导致明显欠拟合，则降级为实现选择。", "Demote to an implementation choice if a free classifier/full rewrite matches repair and old-positive preservation at equal capacity, or if monotone minimality materially underfits."),
        "persistent_update_object": bi("冻结 skill body 外部的单调 applicability predicate gate 及其修订谱系。", "A monotone applicability predicate gate and revision lineage external to the frozen skill body."),
        "learning_signal": bi("验证反例需要被排除，同时历史正例必须保持可用；目标是最小 predicate 增量。", "Verified counterexamples must be excluded while historical positives remain valid, with minimal predicate additions."),
        "independent_truth": bi("环境/程序 verifier 判定 skill 在具体状态是否应成功；LLM 提出的 predicate 只是假设。", "Environment/program verifiers determine whether the skill should succeed in a state; LLM-proposed predicates are only hypotheses."),
        "collision_boundary": bi("CEDAR 已用 counterexample 持续修 skill/formal specification，MemoRepair 已做 provenance cascade repair；因此本方向不主张 counterexample repair 本身，只主张 frozen skill body 下的 minimal monotone applicability shrinkage。", "CEDAR already refines skills/specifications with counterexamples and MemoRepair handles provenance cascade repair. The claim is not counterexample repair itself, only minimal monotone applicability shrinkage around a frozen skill body."),
        "nearest_work": ["CEDAR", "MEMOREPAIR", "StateAuditor / STALE"],
        "fresh_reducibility_check": fresh("counterexample repair 已存在；可识别变量是冻结 skill body 后的 minimal monotone external gate。", "Counterexample repair exists; the identifiable variable is a minimal monotone external gate around a frozen skill body.", [
            {"title": "CEDAR: A Counter-Example Driven Agent with Regular Restriction", "url": "https://openreview.net/forum?id=IyMoawG676"},
            {"title": "MEMOREPAIR: Barrier-First Cascade Repair in Agentic Memory", "url": "https://arxiv.org/abs/2605.07242"},
            {"title": "When Memory Updates but Behavior Does Not", "url": "https://arxiv.org/abs/2608.01619"},
        ]),
        "redesign_iteration": {"round": "2026-08-10", "verdict": "pilot-candidate-after-recheck", "summary": bi("把反例修复自由度压到 external gate：skill body 不动、边界只最小单调收缩。若自由 classifier 等效则不单列。", "Repair freedom is restricted to the external gate: skill body frozen, boundary only minimally and monotonically shrinks. Do not keep standalone if a free classifier is equivalent.")},
    },
    "memory-half-life": {
        "title": bi("复用机会驱动的记忆效用复验", "Reuse-Opportunity Memory Utility Revalidation"),
        "purpose": bi("stale memory、utility refinement 和 shift recovery 都已有直接工作；剩下的问题不是‘会不会过期’，而是在固定审计预算下，何时值得重新做一次 memory-on/off 干预来确认局部效用已经漂移。", "Stale memory, utility refinement, and shift recovery now have direct prior work. The remaining problem is not whether memory becomes stale, but when a fixed audit budget should trigger a new memory-on/off intervention because local utility has drifted."),
        "core_idea": bi("采用两阶段触发。第一阶段完全廉价：memory 每次被激活就打标，只用最近使用时间、激活频率、复用间隔和局部 API/schema 变化给所有 memory 排审计优先级；很久没用、局部环境变化大或复用模式异常的 memory 先进入候选。第二阶段才消耗真实预算：只对固定比例候选做 memory-on/off paired replay，用真实边际效用决定继续保留、缩短复验间隔或隔离。历史干预效用只学习‘下一次该审谁’，不替代最终真值。", "Use a two-stage trigger. Stage one is cheap: mark every activation and rank memories for audit using recency, activation frequency, reuse interval, and local API/schema change; long-unused memories, strong local changes, or unusual reuse patterns become candidates. Stage two spends real budget only on a fixed fraction of candidates via paired memory-on/off replay, whose true marginal utility decides retain, shorten the next audit interval, or quarantine. Historical intervention utility learns only whom to audit next and never replaces final truth."),
        "core_intuition": bi("记忆寿命不是时间长度，而是‘经历多少次类似使用机会后，局部环境发生了足以改变它效用的变化’。", "Memory lifetime is not elapsed time but how many relevant reuse opportunities occur before local environment change is sufficient to alter utility."),
        "concrete_example": bi("一条 API retry memory 半年没调用但 schema 未变，仍可能有效；另一条今天被调用 20 次，但 endpoint 行为改变后立刻有害。方法按 reuse state 和少量 on/off replay 判断后者应立即复验。", "An API retry memory unused for months may remain valid if the schema is unchanged; another used twenty times today may become harmful immediately after endpoint behavior changes. Reuse state plus sparse on/off replay should prioritize the latter for revalidation."),
        "method_logic": bi("1) 每次 memory 激活时记录 last-used、frequency、reuse interval、task/API/schema/local-state；2) 用这些零额外 Agent 调用的局部性特征形成 cheap trigger/ranking；3) 预注册固定 audit fraction K，只审计排名前 K 或按校准概率抽样的 memory；4) 审计时做 memory OFF/ON paired replay得到真实边际效用；5) 用历史 audit 结果学习下一轮审计调度，但 pruning/quarantine 必须由真实 replay 结果触发；6) shift 前冻结；7) 与 TTL/LRU/LFU/纯 recency+frequency 在完全相同 audit replay 数下比较。", "1) On each activation record last-used time, frequency, reuse interval, task/API/schema/local state; 2) form a cheap trigger/ranking from these locality features with no extra agent calls; 3) preregister a fixed audit fraction K and audit only top-K or calibrated-sampled memories; 4) obtain true marginal utility with paired memory OFF/ON replay; 5) learn next-round audit scheduling from historical audits, while pruning/quarantine must be triggered by real replay outcomes; 6) freeze before shift; 7) compare with TTL/LRU/LFU/pure recency+frequency using exactly the same audit replay count."),
        "comparative_advantage": bi("与 ReMe 的 utility-based refinement 不同，所有方法得到相同数量的真实 utility audits；唯一变量是审计机会的条件调度。", "Unlike ReMe utility-based refinement, every method receives the same number of true utility audits; the only variable is conditional scheduling of audit opportunities."),
        "strongest_baseline": bi("纯 locality trigger：相同 activation log、相同固定 audit replay 数，只按 last-used + frequency + reuse interval（LRU/LFU 风格）排序并触发复验；不利用历史 memory-on/off 效用学习下一轮审计调度。", "Pure locality trigger: same activation logs and identical fixed audit replay count, ranking and triggering revalidation only by last-used + frequency + reuse interval (LRU/LFU style), without using historical memory-on/off utility to learn the next audit schedule."),
        "pilot": bi("构造可控 API/schema shift 或使用自然 shift 段；固定 20% audit fraction，比较 TTL、LRU/LFU、recency+frequency、utility-hazard，所有方法相同 on/off replay 总数。", "Use controlled API/schema shifts or natural shift segments; fix a 20% audit fraction and compare TTL, LRU/LFU, recency+frequency, and utility hazard with identical total on/off replay."),
        "metric": bi("harmful activation exposure、Recovery@T、审计次数、false invalidation、保留有效 memory 比例。", "Harmful-activation exposure, Recovery@T, audit count, false invalidation, and retained-valid-memory fraction."),
        "stop": bi("若纯 last-used/frequency/reuse-interval 触发、TTL 或 LRU/LFU 在同 audit 预算下等效，说明程序局部性启发已经足够，本方法降级为缓存调度组件；若真实 memory-on/off 效用不能改善下一次该审谁的排序，也停止 learned hazard 主张。", "If pure last-used/frequency/reuse-interval triggering, TTL, or LRU/LFU matches at the same audit budget, the locality heuristic is already sufficient and the method is demoted to cache scheduling. Also stop the learned-hazard claim if true memory-on/off utility does not improve whom to audit next."),
        "persistent_update_object": bi("每条 memory 的 reuse-local utility hazard、下一次复验状态和隔离状态。", "Per-memory reuse-local utility hazard, next-revalidation state, and quarantine state."),
        "learning_signal": bi("固定比例 audit activation 上的真实 memory-on/off 边际效用。", "True memory-on/off marginal utility on a fixed fraction of audited activations."),
        "independent_truth": bi("paired environment/program outcome；hazard 只调度审计，不循环作为 utility 标签。", "Paired environment/program outcomes; the hazard schedules audits but is never recycled as the utility label."),
        "collision_boundary": bi("ReMe 已做 utility-based memory lifecycle，ShiftBench 已测 shift 后 memory recovery，STALE/StateAuditor 已处理 stale dependency。因此 novelty 只能是同审计预算下、基于 activation-level intervention utility 的复验调度。", "ReMe covers utility-based memory lifecycle, ShiftBench evaluates post-shift recovery, and STALE/StateAuditor addresses stale dependencies. Novelty is limited to activation-level intervention-utility scheduling under the same audit budget."),
        "nearest_work": ["ReMe", "ShiftBench", "StateAuditor / STALE"],
        "fresh_reducibility_check": fresh("泛化 stale-memory 处理已碰撞；只保留固定 audit budget 下的 intervention-utility scheduling。", "Generic stale-memory handling is collided; only intervention-utility scheduling under a fixed audit budget remains.", [
            {"title": "Remember Me, Refine Me", "url": "https://aclanthology.org/2026.findings-acl.829/"},
            {"title": "ShiftBench: Measuring Recovery of Agent Memory Under Distribution Shift", "url": "https://openreview.net/forum?id=CCSztIjmOy"},
            {"title": "When Memory Updates but Behavior Does Not", "url": "https://arxiv.org/abs/2608.01619"},
        ]),
        "redesign_iteration": {"round": "2026-08-10", "verdict": "same-budget-simplification-test", "summary": bi("从‘memory half-life’收窄成同审计预算下的 intervention-utility 复验调度；若 recency/frequency 等效，降级为缓存组件。", "Narrowed from memory half-life to intervention-utility revalidation scheduling at matched audit budget; demote to a cache component if recency/frequency is equivalent.")},
    },
}
