from __future__ import annotations

from typing import Any

from .method_details_common import bi


def fresh(summary_zh: str, summary_en: str, sources: list[dict[str, str]]) -> dict[str, Any]:
    return {"review_date": "2026-08-10", "summary": bi(summary_zh, summary_en), "sources": sources}


DETAILS: dict[str, dict[str, Any]] = {
    "self-label-confidence-flow": {
        "title": bi("谱系去相关的自标注准入", "Lineage-Decorrelation for Self-Label Admission"),
        "purpose": bi("multi-agent agreement、pairwise validator 和 uncertainty-aware self-labeling 已经能提高单轮伪标签质量；剩下的问题是跨轮自进化时，同一个早期错误经同源 evaluator/父标签反复派生后被当成多份独立证据。", "Multi-agent agreement, pairwise validators, and uncertainty-aware labeling can improve one-round pseudo-label quality. The remaining problem is cross-round dependence: one early error can spawn many descendant labels through the same evaluator lineage and be mistakenly counted as independent evidence."),
        "core_idea": bi("为 label-event 建 provenance DAG，记录 generation、producer/evaluator family、parent label 和 update lineage；用少量冻结独立 anchors 估计来源可靠度与 lineage covariance，把共享祖先/同源后代折算成 effective evidence count，再决定 Prompt/Memory/Rubric 更新是否准入。", "Build a provenance DAG for label events with generation, producer/evaluator family, parent labels, and update lineage. Use a small frozen independent anchor set to estimate source reliability and lineage covariance, convert correlated descendants into an effective evidence count, then gate persistent prompt/memory/rubric updates."),
        "core_intuition": bi("十个来自同一错误祖先的‘一致标签’并不等于十个独立证据；真正需要校准的是证据相关性，不只是置信度。", "Ten agreeing labels descended from one erroneous ancestor are not ten independent observations. The missing calibration target is evidence correlation, not just confidence."),
        "concrete_example": bi("第 1 轮 evaluator 错把某类 tool failure 标成‘策略错误’，后续 4 轮都引用这个标签生成新 rubric/self-label。普通 majority 会看到 12 个一致标签；provenance DAG 会把它们压成接近 1 个有效来源。", "A round-1 evaluator wrongly labels a tool failure as a policy error; four later rounds reuse that label to generate new rubrics/self-labels. Majority voting sees 12 agreeing labels, while the provenance DAG discounts them toward one effective source."),
        "method_logic": bi("0) 先测真实日志中跨轮 label inheritance/同源复用是否存在；1) 记录 4–6 轮 label-event DAG；2) 冻结独立 anchors；3) 估计 producer family reliability 与 shared-ancestry covariance；4) 计算 effective evidence weight；5) 权重只控制轻量持久更新准入；6) 第二 evaluator family 前冻结。", "0) First verify cross-round label inheritance/source reuse in real logs; 1) record a 4–6 round label-event DAG; 2) freeze independent anchors; 3) estimate producer-family reliability and shared-ancestry covariance; 4) compute effective evidence weights; 5) use them only to gate lightweight persistent updates; 6) freeze before a second evaluator family."),
        "comparative_advantage": bi("与 SERM agreement 或 pairwise validator 的区别是：当前标签与调用完全相同，只改变共享祖先/来源是否被当成独立票。", "Unlike SERM agreement or pairwise validators, labels and calls are identical; only whether shared ancestry/source counts as independent votes changes."),
        "strongest_baseline": bi("独立 anchor 阈值：完全相同 anchors、labels、calls 和候选更新，只按当前候选的 anchor pass-rate 用冻结阈值准入，不建 provenance DAG。", "Independent-anchor threshold: identical anchors, labels, calls, and candidate updates, gated only by current anchor pass rate with a frozen threshold and no provenance DAG."),
        "pilot": bi("先用公开/真实 4–6 轮自标注日志做 reality check；若 lineage error enrichment 存在，再构造 ancestry-blind、source-count、anchor-threshold、lineage-decorrelated 四臂，最后两轮冻结测试。", "First run a reality check on public/real 4–6 round self-label logs. If lineage error enrichment exists, compare ancestry-blind, source-count, anchor-threshold, and lineage-decorrelated arms with the final two rounds frozen for testing."),
        "metric": bi("false-admission rate、有效样本数校准、谱系错误富集、hidden update regression、同预算 accepted useful updates。", "False-admission rate, effective-sample-size calibration, lineage-error enrichment, hidden update regression, and useful accepted updates at matched budget."),
        "stop": bi("若真实日志几乎没有跨轮继承/同源复用，或简单 anchor 阈值/source-count 在同预算下等效，则停止独立方法。", "Stop if real logs show little cross-round inheritance/source reuse, or if simple anchor thresholds/source counts match at equal budget."),
        "persistent_update_object": bi("跨轮保存的 label provenance DAG、来源可靠度/协方差校准状态和更新准入权重。", "A persistent label-provenance DAG, source reliability/covariance calibration state, and update-admission weights."),
        "learning_signal": bi("冻结独立 anchor 上 producer family 的错误率与共享祖先标签的协同错误。", "Producer-family error rates and co-errors among shared-ancestry labels on frozen independent anchors."),
        "independent_truth": bi("独立 anchor 的已有金标/程序 truth；自标签自身不能再作为 lineage reliability 真值。", "Existing gold/program truth on independent anchors; self-labels cannot be recycled as lineage-reliability truth."),
        "collision_boundary": bi("SERM 已用 multi-agent agreement 处理 pseudo-label noise，Reward-Free Evolving Agents 用 pairwise validator 替代 scalar reward；因此本方向只保留跨轮 label-event lineage correlation 去重。", "SERM uses multi-agent agreement for pseudo-label noise and Reward-Free Evolving Agents uses pairwise validation instead of scalar rewards; the surviving claim is cross-round label-event lineage-correlation discounting."),
        "nearest_work": ["SERM", "Reward-Free Evolving Agents via Pairwise Validator"],
        "fresh_reducibility_check": fresh("单轮 label reliability 已有强方法；只有跨轮 lineage dependence 仍是独立变量。", "Strong methods exist for one-round label reliability; cross-round lineage dependence remains the independent variable.", [
            {"title": "SERM: Self-Evolving Relevance Model with Agent-Driven Learning from Massive Query Streams", "url": "https://openreview.net/forum?id=o3oZwbsM3X"},
            {"title": "Reward-Free Evolving Agents via Pairwise Validator", "url": "https://arxiv.org/abs/2607.14408"},
        ]),
        "redesign_iteration": {"round": "2026-08-10", "verdict": "reality-check-first", "summary": bi("保留的变量是跨轮 label lineage 相关性，不是更复杂的 confidence。先证明确有谱系错误传播，否则直接停止。", "The surviving variable is cross-round label-lineage dependence, not richer confidence. First prove lineage error propagation exists or stop.")},
    },
    "evaluator-coadaptation-guard": {
        "title": bi("跨版本 Rubric 干预修复", "Cross-Version Rubric Intervention Repair"),
        "purpose": bi("policy 与 internal reward 共进化已经有直接方法；真正难的是 reward 上升时判断究竟是 actor 变好，还是 evaluator/rubric 自己漂向 actor 的捷径。", "Direct methods already co-evolve policy and internal reward. The unresolved problem is attribution: when reward rises, did the actor improve or did the evaluator/rubric drift toward the actor's shortcut?"),
        "core_idea": bi("保存 actor/evaluator 版本矩阵。对固定 anchor trajectories 做跨版本交叉评分，先用 actor-fixed/evaluator-changed 的 delta 定位 evaluator drift；再对可疑 rubric 维度做 neutral/counterfactual rubric intervention，只允许小型 rubric/calibrator patch，且该 evidence batch 上 actor 保持冻结。", "Maintain an actor/evaluator version matrix. Cross-score fixed anchor trajectories across versions and localize evaluator drift using actor-fixed/evaluator-changed deltas; then apply neutral/counterfactual rubric interventions to suspicious rubric dimensions, allowing only small rubric/calibrator patches while the actor remains frozen on that evidence batch."),
        "core_intuition": bi("共适应无法靠当前 evaluator 自己证明；需要把 actor 版本和 evaluator 版本解耦，问‘同一条行为为什么在 evaluator 更新后突然更高分’。", "A co-adapting evaluator cannot certify itself. Actor and evaluator versions must be decoupled: why did the same behavior suddenly score higher after the evaluator changed?"),
        "concrete_example": bi("Actor-v3 产生固定工具轨迹。Reward-v2 给 0.4，Reward-v3 给 0.9，但程序成功率未变；把‘工具调用简洁度’ rubric neutralize 后分数回落，说明 drift 在 evaluator。方法只修 Reward/rubric，不用这批证据同时训练 Actor。", "Actor-v3 produces a fixed tool trajectory. Reward-v2 scores 0.4 and Reward-v3 scores 0.9 while program success is unchanged; neutralizing the 'tool-call concision' rubric drops the score, localizing drift to the evaluator. The method repairs reward/rubric only and never trains the actor on the same evidence batch."),
        "method_logic": bi("1) 每轮保留 actor/evaluator snapshot；2) 冻结独立 anchors；3) 构造 cross-version score matrix；4) 分解 actor-change 与 evaluator-change；5) 对 evaluator-side drift 做 rubric neutralization/counterfactual intervention；6) 仅训练稀疏 calibrator/rubric patch；7) 下一轮 actor 更新使用不同 evidence。", "1) Retain actor/evaluator snapshots each round; 2) freeze independent anchors; 3) build a cross-version score matrix; 4) separate actor-change from evaluator-change; 5) perform rubric neutralization/counterfactual intervention on evaluator-side drift; 6) train only a sparse calibrator/rubric patch; 7) the next actor update uses different evidence."),
        "comparative_advantage": bi("与 self-evolving reward/REFORM 的区别是：不让 reward 用自己的当前 failure 直接同时训练 actor 和自己，而用跨版本固定行为做归因后再修 evaluator。", "Unlike self-evolving reward/REFORM, the reward does not use its current failures to update both actor and itself; attribution is first performed on fixed behaviors across versions, then the evaluator is repaired."),
        "strongest_baseline": bi("独立 anchor 定期校准：同 anchors、同 evaluator capacity、同人工/程序 truth，只对当前 evaluator 做标量 calibration，不保留 cross-version matrix 或 rubric intervention。", "Periodic independent-anchor calibration: same anchors, evaluator capacity, and human/program truth, but only scalar-calibrates the current evaluator without a cross-version matrix or rubric intervention."),
        "pilot": bi("4 个 actor×4 个 evaluator 版本，固定 100–200 anchor trajectories；注入或自然产生 2–3 类 shortcut drift，比较 frozen reward、scalar calibration、multi-judge、cross-version rubric repair。", "Use four actor by four evaluator versions and 100–200 fixed anchor trajectories; induce or observe 2–3 shortcut-drift types and compare frozen reward, scalar calibration, multi-judge, and cross-version rubric repair."),
        "metric": bi("外部/program truth reward correlation、reward-hacking admission、actor-fixed score drift、修复后 original reward quality、跨版本 attribution accuracy。", "Correlation with external/program truth, reward-hacking admission, actor-fixed score drift, retained original reward quality, and cross-version attribution accuracy."),
        "stop": bi("若简单独立 anchor calibration 或 frozen reward 在同预算下等效，或 cross-version matrix 无法可靠区分 actor/evaluator drift，则停止。", "Stop if simple independent-anchor calibration or a frozen reward matches at equal budget, or if the cross-version matrix cannot reliably distinguish actor from evaluator drift."),
        "persistent_update_object": bi("持久 evaluator/rubric calibrator patch 与跨版本 evaluator-state。", "A persistent evaluator/rubric calibrator patch and cross-version evaluator state."),
        "learning_signal": bi("actor 固定时不同 evaluator 版本对独立 anchors 的评分差，以及 rubric intervention 后的程序/外部 truth 变化。", "Score differences across evaluator versions on actor-fixed independent anchors, plus program/external-truth changes under rubric interventions."),
        "independent_truth": bi("程序 checker、环境结果或冻结异构 Judge/人工小样本；当前 evaluator 的 reward 不能循环充当 truth。", "Program checkers, environment outcomes, or frozen heterogeneous judges/small human samples; the current evaluator reward cannot serve as truth."),
        "collision_boundary": bi("Self-Guide 已直接共进化 policy/internal reward，REFORM 也让 reward model 自发现 failure 并修复。因此 novelty 不能是 reward self-improvement，而是 cross-version actor-fixed attribution + rubric intervention 后的 evaluator-only sparse repair。", "Self-Guide directly co-evolves policy/internal reward and REFORM lets reward models discover and repair their own failures. Novelty is not reward self-improvement, but actor-fixed cross-version attribution plus rubric intervention followed by evaluator-only sparse repair."),
        "nearest_work": ["Self-Guide", "REFORM", "CUARewardBench"],
        "fresh_reducibility_check": fresh("reward self-improvement 已有；边界收窄为跨版本 attribution 与 evaluator-only rubric repair。", "Reward self-improvement is covered; the boundary narrows to cross-version attribution and evaluator-only rubric repair.", [
            {"title": "Co-Evolution of Policy and Internal Reward for Language Agents", "url": "https://arxiv.org/abs/2604.03098"},
            {"title": "Teach a Reward Model to Correct Itself: Reward Guided Adversarial Failure Discovery", "url": "https://openreview.net/forum?id=F8RVIIdkkY"},
            {"title": "CUARewardBench", "url": "https://openreview.net/forum?id=Xj7V0wKlE5"},
        ]),
        "redesign_iteration": {"round": "2026-08-10", "verdict": "pilot-candidate-after-recheck", "summary": bi("从‘guard actor/reward 共适应’改成 actor-fixed cross-version attribution，再做 evaluator-only rubric repair；简单 anchor calibration 是必须打赢的对照。", "Reframed from generic co-adaptation guarding to actor-fixed cross-version attribution followed by evaluator-only rubric repair; simple anchor calibration is the required control.")},
    },
    "counterexample-generating-curriculum": {
        "title": bi("1-Minimal 边界反例课程", "1-Minimal Boundary-Counterexample Curriculum"),
        "purpose": bi("counterexample-guided learning、formal counterexample generation 和 CEDAR 已经证明 verifier 反例能驱动学习；剩下的问题只是在完全相同 verifier/训练预算下，1-minimality 本身是否让课程更高信息、更少 shortcut。", "Counterexample-guided learning, formal counterexample generation, and CEDAR already show verifier counterexamples can drive learning. The remaining question is whether 1-minimality itself creates a more informative, less shortcut-prone curriculum under identical verifier/training budget."),
        "core_idea": bi("强模型只提候选边界任务，程序/环境 verifier 判真。对验证反例逐约束 delta-debug，直到任何进一步删除都会使任务失效或不再反驳当前规则；只把 1-minimal 反例送入固定 token 的下一轮 Prompt/LoRA/skill 更新。", "A stronger model only proposes candidate boundary tasks and a program/environment verifier supplies truth. Delta-debug each verified counterexample until any further constraint removal makes it invalid or no longer refutes the current rule; only 1-minimal counterexamples enter the next fixed-token prompt/LoRA/skill update."),
        "core_intuition": bi("难题不一定有信息；最小反例把失败原因压到最少必要条件，更可能精确暴露当前规则的真正边界。", "Harder tasks are not necessarily more informative. A minimal counterexample reduces failure to the fewest necessary conditions and may expose the true boundary of the current rule."),
        "concrete_example": bi("一个工具任务同时包含 5 个异常条件导致当前规则失败。delta-debug 发现只需‘schema 改名 + optional field 缺失’两个条件就足以失败；课程只保留这两个必要条件，而不是整套复杂任务。", "A tool task contains five abnormal conditions and breaks the current rule. Delta debugging finds that 'schema rename + missing optional field' alone is sufficient; the curriculum retains only those necessary conditions instead of the whole complex task."),
        "method_logic": bi("1) 从当前轨迹抽取可执行规则/任务模板；2) proposer 固定预算提候选；3) verifier 判合法和是否反例；4) delta-debug 到 1-minimal；5) 最终训练样本/token 与 non-minimal baseline 严格匹配；6) 更新后在独立模板/seed 边界集测试。", "1) Extract an executable rule/task template from current trajectories; 2) use a fixed-budget proposer; 3) verifier checks legality and counterexample status; 4) delta-debug to 1-minimality; 5) strictly match final training sample/token count with the non-minimal baseline; 6) test the update on independent templates/seeds."),
        "comparative_advantage": bi("不主张 counterexample learning 或 delta debugging 新颖，只检验 verifier-confirmed 1-minimality 是否作为 curriculum selection variable 带来额外圈外学习增益。", "The claim is not counterexample learning or delta debugging, only whether verifier-confirmed 1-minimality as a curriculum-selection variable yields extra out-of-loop learning gain."),
        "strongest_baseline": bi("Verifier-filtered non-minimal：同 proposer、同 verifier 调用、同最终训练样本数/token、同更新器，只取首个合法反例而不最小化。", "Verifier-filtered non-minimal: same proposer, verifier calls, final sample/token count, and updater, retaining the first valid counterexample without minimization."),
        "pilot": bi("每轮冻结 20–30 个 verified counterexamples，一半做 delta-debug 到 1-minimal；最终两臂训练 token 完全相同。P0 只看一轮更新后的独立 boundary set。", "Freeze 20–30 verified counterexamples per round, delta-debug half to 1-minimality, and match final training tokens exactly across arms. P0 evaluates only one update on an independent boundary set."),
        "metric": bi("independent boundary success、规则修复率、shortcut transfer、每个有效更新所需 verifier 调用、原任务回退。", "Independent-boundary success, rule-repair rate, shortcut transfer, verifier calls per useful update, and original-task regression."),
        "stop": bi("若 non-minimal baseline 在相同 verifier/训练预算下等效，或 minimality 只减少 token 而不改善独立边界泛化，则停止。", "Stop if the non-minimal baseline matches at identical verifier/training budget, or if minimality only reduces tokens without improving independent-boundary generalization."),
        "persistent_update_object": bi("由 1-minimal counterexamples 驱动后持久保存的 Prompt/LoRA/skill 更新，以及冻结 curriculum selection rule。", "The persisted prompt/LoRA/skill update driven by 1-minimal counterexamples plus a frozen curriculum-selection rule."),
        "learning_signal": bi("程序/环境 verifier 确认的反例状态与 delta-debug 后的 1-minimality。", "Counterexample validity from program/environment verifiers and 1-minimality after delta debugging."),
        "independent_truth": bi("verifier 只判任务/规则，最终学习增益由从未参与生成/最小化的独立 boundary set 判断。", "The verifier only judges tasks/rules; final learning gain is measured on an independent boundary set never used in generation/minimization."),
        "collision_boundary": bi("Counterexample Guided Learning in the Large、CEDAR、Learning to Disprove 已覆盖 verifier counterexample learning；因此唯一剩余主张是 1-minimality 作为 curriculum selection variable 的独立价值。", "Counterexample Guided Learning in the Large, CEDAR, and Learning to Disprove already cover verifier counterexample learning. The only surviving claim is the independent value of 1-minimality as a curriculum-selection variable."),
        "nearest_work": ["Counterexample Guided Learning in the Large", "CEDAR", "Learning to Disprove"],
        "fresh_reducibility_check": fresh("把 novelty 压到最窄：同 verifier/训练预算下 minimality 是否有额外泛化收益。", "Novelty is narrowed to the strictest form: whether minimality adds generalization under identical verifier/training budget.", [
            {"title": "Counterexample Guided Learning in the Large using Reasoning Agents", "url": "https://arxiv.org/abs/2606.11521"},
            {"title": "CEDAR: A Counter-Example Driven Agent with Regular Restriction", "url": "https://openreview.net/forum?id=IyMoawG676"},
            {"title": "Learning to Disprove: Formal Counterexample Generation with Large Language Models", "url": "https://openreview.net/forum?id=EBa52sye9K"},
        ]),
        "redesign_iteration": {"round": "2026-08-10", "verdict": "decisive-simplification-test", "summary": bi("不再主张反例学习本身，只测试 1-minimality 是否是有价值的 curriculum variable；non-minimal 同预算若等效就停止。", "No claim on counterexample learning itself; only test 1-minimality as a curriculum variable, and stop if the equal-budget non-minimal control matches.")},
    },
}
