from __future__ import annotations

from typing import Any

from .method_details_common import bi


def fresh(summary_zh: str, summary_en: str, sources: list[dict[str, str]]) -> dict[str, Any]:
    return {"review_date": "2026-08-10", "summary": bi(summary_zh, summary_en), "sources": sources}


DETAILS: dict[str, dict[str, Any]] = {
    "world-model-error-gated-learning": {
        "title": bi("决策翻转驱动的转移准入", "Decision-Switch Transition Admission"),
        "purpose": bi("AAWM 已经把 world-model supervision 改成 policy decision needs，因此不能再主张‘decision-aware world model target’。剩下的问题是更新预算：真实 transition 很多时，哪些 transition 值得被持久写入/训练，才能以更少更新改变后续决策。", "AAWM already makes world-model supervision decision-oriented, so 'decision-aware world-model targets' are no longer enough. The remaining problem is update budgeting: among many real transitions, which ones deserve persistent storage/training because correcting them would change later decisions?"),
        "core_idea": bi("对每条真实 transition 先计算当前 world model 的预测；再做 counterfactual decision test：把该 transition 的预测替换成真实 next state/关键属性，重新求一次当前 policy 的 action/risk/recovery decision。只有 correction 会导致 action switch、risk threshold crossing 或 recovery choice 改变的 transition 才进入固定容量的持久 transition memory/adapter 更新。", "For each real transition, compare the current world-model prediction with truth, then run a counterfactual decision test: replace only that prediction with the true next state/critical attributes and recompute the current policy's action/risk/recovery decision. Admit the transition to fixed-capacity persistent memory/adapter training only if the correction causes an action switch, risk-threshold crossing, or recovery-choice change."),
        "core_intuition": bi("预测误差大不代表对 policy 有用；真正值得付更新成本的是‘如果我早知道真相，当前决策会不会改变’。", "Large prediction error does not imply policy value. Update cost should be spent when knowing the truth would actually change the current decision."),
        "concrete_example": bi("机器人把一个物体位置预测错 10cm，但抓取动作不变，这条 transition 不学；另一个误差只有 2cm，却让碰撞风险从阈值下变阈值上，policy 会改用绕行，这条 transition 优先写入。", "A robot mispredicts an object position by 10 cm but the grasp action is unchanged, so the transition is not learned. Another error is only 2 cm but moves collision risk across a threshold and changes the policy to a detour; that transition is prioritized."),
        "method_logic": bi("0) 先确认持续适应场景真实存在；1) 冻结 policy/world-model snapshot；2) 收集真实 transition 与预测；3) 对每条 transition 做 one-factor prediction→truth replacement；4) 标 action/risk/recovery decision switch；5) 固定 update budget 下训练 transition memory/adapter；6) 测试时冻结 gate 与 updater；7) 第二环境/模型前再冻结一次。", "0) First confirm the continual-adaptation setting is real; 1) freeze policy/world-model snapshots; 2) collect real transitions and predictions; 3) replace one transition prediction with truth at a time; 4) label action/risk/recovery decision switches; 5) train transition memory/adapter under a fixed update budget; 6) freeze gate/updater at test time; 7) freeze again before a second environment/model."),
        "comparative_advantage": bi("与 AAWM 的区别是 supervision target 可以完全相同，唯一变量是哪些真实 transition 获得有限更新预算；与 largest-error baseline 直接匹配。", "AAWM may use the same supervision targets; the only changed variable is which real transitions receive the limited update budget, directly matched against largest-error selection."),
        "strongest_baseline": bi("AAWM-style/all decision-oriented transitions + uniform subsampling：相同 target representation、相同 updater、相同训练 transition 数，只随机/均匀选样，不做 decision-switch test。", "AAWM-style decision-oriented transitions with uniform subsampling: same target representation, updater, and number of training transitions, but random/uniform selection without decision-switch tests."),
        "pilot": bi("在 exact-transition 或程序可核对环境收集 300–500 transitions；固定只允许 25–50% 进入更新。比较 random、largest prediction error、uncertainty、AAWM/uniform、decision-switch admission。", "Collect 300–500 transitions in an exact-transition or program-checkable environment and allow only 25–50% into updates. Compare random, largest prediction error, uncertainty, AAWM/uniform, and decision-switch admission."),
        "metric": bi("相同 transition-update 数下 task success、action regret、risk/recovery errors、最坏原任务回退和每次有效决策改进所需 transition 数。", "Task success, action regret, risk/recovery errors, worst original-task regression, and transitions per useful decision improvement at matched update count."),
        "stop": bi("若 AAWM/uniform、largest-error 或 uncertainty 在相同 transition/update 预算下等效，或 decision-switch 标签对未来 policy 没预测力，则停止。", "Stop if AAWM/uniform, largest-error, or uncertainty matches at the same transition/update budget, or if decision-switch labels do not predict future policy benefit."),
        "persistent_update_object": bi("固定容量的 world-transition memory/轻量 adapter 及 transition admission gate。", "A fixed-capacity world-transition memory/lightweight adapter plus a transition-admission gate."),
        "learning_signal": bi("将单条预测替换成真实 transition 后，冻结 policy 的 action/risk/recovery decision 是否发生翻转。", "Whether replacing one prediction with the true transition flips the frozen policy's action/risk/recovery decision."),
        "independent_truth": bi("真实环境 transition 或程序状态差；decision-switch test 使用冻结 policy，最终任务收益由独立执行判断。", "True environment transitions or program-state differences; the decision-switch test uses a frozen policy and final task benefit is judged by independent execution."),
        "collision_boundary": bi("AAWM 已直接用 policy decision needs 构造 world-model supervision，因此 F-1 不再主张 decision-aware target。只保留 fixed update budget 下的 decision-switch transition selection。", "AAWM directly constructs world-model supervision from policy decision needs, so F-1 no longer claims decision-aware targets. The surviving variable is decision-switch transition selection under a fixed update budget."),
        "nearest_work": ["Agent-Authored World Modeling (AAWM)", "WMA", "Action Semantics Learning"],
        "fresh_reducibility_check": fresh("decision-aware target 已碰撞；只剩 transition admission under fixed update budget，且仍需先确认真实持续适应场景。", "Decision-aware targets are collided; only transition admission under a fixed update budget remains, and the continual-adaptation setting must still be confirmed first.", [
            {"title": "Beyond Next-Observation Prediction: Agent-Authored World Modeling for Sequential Decision Making", "url": "https://arxiv.org/abs/2606.25421"},
            {"title": "BEYOND SYNTAX: ACTION SEMANTICS LEARNING FOR APP AGENTS", "url": "https://openreview.net/forum?id=MJc5jzu8A2"},
        ]),
        "redesign_iteration": {"round": "2026-08-10", "verdict": "scenario-check-then-recheck", "summary": bi("主动删掉 AAWM 已覆盖的 decision-aware target；改成 fixed update budget 下的 decision-switch transition admission。仍需先确认真实持续适应场景。", "Removed the AAWM-collided decision-aware target claim; redesigned as decision-switch transition admission under fixed update budget. Real continual adaptation must still be confirmed first.")},
    },
    "irreversible-action-counterfactuals": {
        "title": bi("可验证不可逆效应条款记忆", "Verified Irreversibility-Clause Memory"),
        "purpose": bi("test-time counterfactual planning、act/refuse safety 和 recovery 已经有大量工作；真正可能形成持续学习的是把少量可验证的‘状态条件 + 动作 → 不可逆效应’编译成跨 episode 复用的条款，从而后续无需重复模拟就能提前排除风险动作。", "Test-time counterfactual planning, act/refuse safety, and recovery already have substantial prior work. A plausible persistent-learning problem is compiling a small set of verified 'state condition + action → irreversible effect' clauses that can be reused across episodes to prune risky actions without repeated simulation."),
        "core_idea": bi("只在有 simulator/程序规则可验证的环境生成未执行 action counterfactual。若某动作跨越预定义的不可逆 state-equivalence boundary（例如资源永久耗尽、关键对象销毁、权限不可恢复改变），把最小 precondition + action + verified effect 编译成 typed risk clause。后续 episode 先查 clause，再决定是否需要 planner。", "Generate unexecuted-action counterfactuals only where a simulator/program rule can verify them. If an action crosses a predefined irreversible state-equivalence boundary (permanent resource depletion, destruction of a key object, non-recoverable permission change), compile the minimal precondition + action + verified effect into a typed risk clause. Later episodes consult clauses before invoking a planner."),
        "core_intuition": bi("counterfactual 如果每次都重新 rollout 只是昂贵规划；只有把已验证的不可逆规律压成可复用条款，才构成持久学习。", "Counterfactuals rerun every time are just expensive planning. Persistent learning appears only if verified irreversible regularities are compressed into reusable clauses."),
        "concrete_example": bi("模拟器证明在 `only_key=true` 时执行 `discard key` 会永久失去开门能力。方法保存 `only_key ∧ discard(key) → irreversible(lockout)`，后续相似任务先用条款排除该动作，不再重新 rollout 这个反事实。", "The simulator proves that when `only_key=true`, `discard key` permanently removes the ability to open a door. The method stores `only_key ∧ discard(key) → irreversible(lockout)` and prunes the action in later tasks without rerunning that counterfactual."),
        "method_logic": bi("1) 预定义可程序判定的 irreversible state predicates；2) source states 生成少量 candidate unexecuted actions；3) simulator/program verifier 判 effect；4) delta-minimize precondition；5) 编译 typed clause；6) hidden episode 中 clause 先 prune，再允许普通 planner 处理剩余动作；7) clause learner 测试前冻结。", "1) Predefine program-checkable irreversible state predicates; 2) generate a few candidate unexecuted actions on source states; 3) verify effects with simulator/program truth; 4) delta-minimize preconditions; 5) compile typed clauses; 6) in hidden episodes use clauses to prune before the ordinary planner handles remaining actions; 7) freeze the clause learner before testing."),
        "comparative_advantage": bi("与 EvoCF/MOSAIC 的 test-time counterfactual/risk decision 不同，hidden test 不允许为已学 clause 再付 counterfactual rollout；收益必须来自持久 clause 的 amortization。", "Unlike EvoCF/MOSAIC test-time counterfactual/risk decisions, hidden tests may not repay counterfactual rollout for learned clauses; benefit must come from amortized persistent clauses."),
        "strongest_baseline": bi("同 simulator-call 总预算的 test-time planner：不保存 clauses，每个 hidden episode 允许把同等数量的 counterfactual calls 用在当前动作选择。", "Test-time planner with the same total simulator-call budget: stores no clauses and spends an equal number of counterfactual calls directly on current hidden-episode action selection."),
        "pilot": bi("在 exact-state simulator 中学习 10–20 条 verified clauses；hidden tasks 比较 no-memory、hand rules、test-time counterfactual planner、persistent clauses，累计 simulator calls 严格匹配。", "Learn 10–20 verified clauses in an exact-state simulator; on hidden tasks compare no memory, hand rules, test-time counterfactual planning, and persistent clauses with strictly matched cumulative simulator calls."),
        "metric": bi("irreversible error rate、benign over-pruning、task success、hidden simulator calls、clause precision/coverage 和每条 clause 的复用次数。", "Irreversible-error rate, benign over-pruning, task success, hidden simulator calls, clause precision/coverage, and reuse count per clause."),
        "stop": bi("若 hand rules 或同总 simulator-call 的 test-time planner 在 hidden success/风险上等效，或 clause 只能记住具体对象名，停止独立方法。", "Stop if hand rules or a test-time planner with the same total simulator calls matches hidden success/risk, or if clauses only memorize concrete object names."),
        "persistent_update_object": bi("跨 episode 保存的 typed irreversibility clauses 与最小 precondition。", "Typed irreversibility clauses and minimal preconditions persisted across episodes."),
        "learning_signal": bi("simulator/program verifier 对未执行 action 是否跨越 irreversible state boundary 的确定性结果。", "Deterministic simulator/program verification of whether an unexecuted action crosses an irreversible state boundary."),
        "independent_truth": bi("精确 simulator/程序规则；LLM world-model proposal 只能提出候选，不可给 clause 自证。", "Exact simulator/program rules; an LLM world-model may propose candidates but cannot self-certify clauses."),
        "collision_boundary": bi("MOSAIC 已学习 act/refuse，EvoCF 已做 evolutionary counterfactual planning，Human-Guided Harm Recovery 也覆盖后果恢复。因此只保留 verified counterfactual effect → persistent reusable irreversibility clause，而不是 test-time planning/safety。", "MOSAIC learns act/refuse decisions, EvoCF performs evolutionary counterfactual planning, and Human-Guided Harm Recovery covers aftermath recovery. The surviving claim is verified counterfactual effect → persistent reusable irreversibility clause, not test-time planning/safety."),
        "nearest_work": ["MOSAIC", "EvoCF", "Human-Guided Harm Recovery"],
        "fresh_reducibility_check": fresh("test-time counterfactual/safety 已拥挤；只有可验证 effect 的持久 clause amortization 仍可单独检验。", "Test-time counterfactual/safety is crowded; only amortization through persistent verified-effect clauses remains separately testable.", [
            {"title": "Learning When to Act or Refuse: Guarding Agentic Reasoning Models for Safe Multi-Step Tool Use", "url": "https://openreview.net/forum?id=RbTD3hustR"},
            {"title": "EvoCF: Multi-Agent Collaboration via Agentic Memory-Driven Evolutionary Counterfactual Planning", "url": "https://openreview.net/forum?id=zGKkewtb2w"},
            {"title": "Human-Guided Harm Recovery for Computer Use Agents", "url": "https://openreview.net/forum?id=hHR39fUK3u"},
        ]),
        "redesign_iteration": {"round": "2026-08-10", "verdict": "reality-and-simplification-check", "summary": bi("从泛化 counterfactual risk 改成 simulator-verifiable irreversibility clause memory；必须证明跨 episode 复用比同总调用 test-time planner 更省且不更保守。", "Reframed from generic counterfactual risk to simulator-verifiable irreversibility-clause memory; cross-episode reuse must beat an equal-total-call test-time planner without extra conservatism.")},
    },
}
