from __future__ import annotations

from typing import Any

from .method_details_common import bi


def fresh(summary_zh: str, summary_en: str, sources: list[dict[str, str]]) -> dict[str, Any]:
    return {"review_date": "2026-08-10", "summary": bi(summary_zh, summary_en), "sources": sources}


DETAILS: dict[str, dict[str, Any]] = {
    "regression-gated-self-evolution": {
        "title": bi("预算校准的预测性回归面板", "Budget-Calibrated Predictive Regression Panel"),
        "purpose": bi("预提交 gate 已经成为自进化 Agent 的直接研究对象；剩下的问题不是再叠一个 critic，而是在固定很小的 Probe 预算下，哪些 Probe 真能预测隐藏原任务回退，以及它们何时应该退役。", "Pre-commit gating is now a direct research topic in self-evolving agents. The remaining problem is not adding another critic, but learning which probes actually predict hidden original-task regression under a fixed small budget and when those probes should retire."),
        "core_idea": bi("维护固定 K 的 core/reserve Probe 面板。用历史已提交/拒绝更新在独立隐藏原任务上的真实 before/after 回退，学习每个 Probe 的预测价值和冗余度；每个 epoch 只允许少量 reserve 替换低价值 core Probe，并用序贯停止决定何时已经收集到足够证据。", "Maintain a fixed-K core/reserve probe panel. Use true before/after regression on independent hidden original tasks from past accepted/rejected updates to learn each probe's predictive value and redundancy; at each epoch only a few reserve probes may replace low-value core probes, with sequential stopping when enough evidence is collected."),
        "core_intuition": bi("真正稀缺的是回归测试预算，不是 critic 数量；如果少量 Probe 对隐藏回退具有稳定预测力，就应该学习测试面板本身，而不是无限扩大验证集。", "The scarce resource is regression-testing budget, not the number of critics. If a small set of probes stably predicts hidden regressions, the system should learn the panel itself rather than continuously expand validation."),
        "concrete_example": bi("例如固定 K=8 个 ALFWorld Probe。过去 30 个 Prompt/Memory 更新都在另外的隐藏原任务上有独立真值；面板只根据这些历史更新学习哪 8 个 Probe 最能提前预警回退。测试新更新时仍只跑 8 个 Probe，隐藏原任务只用于最终审计。", "For example, freeze K=8 ALFWorld probes. Thirty prior prompt/memory updates have independent hidden-original-task truth; the panel learns which eight probes best anticipate regression. A new update still receives only eight probe executions, while hidden original tasks are used only for final audit."),
        "method_logic": bi("1) 冻结候选更新流和隐藏原任务；2) 记录每个 Probe 对每次历史更新的 paired before/after 变化；3) 用隐藏原任务是否真实回退监督 Probe 的 predictive utility，并惩罚 Probe 间冗余；4) 固定 K，分 core/reserve；5) 每个 epoch 只替换低 utility core；6) 新更新只看当前面板并序贯停止；7) 面板策略在第二更新表面前冻结。", "1) Freeze the candidate-update stream and hidden original tasks; 2) record paired before/after changes for every probe on past updates; 3) supervise probe predictive utility with true hidden-task regression while penalizing redundancy; 4) keep fixed K with core/reserve pools; 5) replace only low-utility core probes each epoch; 6) gate new updates with the current panel and sequential stopping; 7) freeze the panel policy before a second update surface."),
        "comparative_advantage": bi("与 VaG 式固定异构 gate 的区别是：critic/gate 类型和 K 都匹配，唯一新增变量是‘哪些 Probe 值得占用固定预算’以及它们的生命周期。", "Unlike a VaG-style fixed heterogeneous gate, critic types and K are matched; the only added variable is which probes deserve the fixed budget and their lifecycle."),
        "strongest_baseline": bi("VaG 风格固定异构 gate + 固定 K Probe：相同候选、相同 K、相同隐藏真值和阈值预算，但不学习 Probe utility/退役。", "VaG-style fixed heterogeneous gate plus fixed-K probes: same candidates, K, hidden truth, and threshold budget, but no learned probe utility or retirement."),
        "pilot": bi("冻结 30–40 个历史轻量更新和 8-Probe 预算，比较固定面板、随机轮换、历史敏感度面板与学习面板；最终只在从未用于面板学习的隐藏原任务上统计 harmful-commit rate。", "Freeze 30–40 historical lightweight updates and an 8-probe budget; compare fixed panels, random rotation, historical-sensitivity panels, and the learned panel; harmful-commit rate is measured only on hidden original tasks never used to learn the panel."),
        "metric": bi("matched accepted-count 下 harmful-commit rate、hidden regression AUPRC、最坏回退、Probe 替换率和每次更新平均 Probe 数。", "Harmful-commit rate at matched accepted count, hidden-regression AUPRC, worst regression, probe replacement rate, and mean probes per update."),
        "stop": bi("若固定 VaG-style gate 或简单历史敏感度排序在同 K 预算内匹配 learned panel，或面板只在同一更新表面有效，则停止独立方法主张。", "Stop if a fixed VaG-style gate or simple historical-sensitivity ranking matches the learned panel at the same K budget, or if the panel does not transfer across update surfaces."),
        "persistent_update_object": bi("跨轮保存并更新的 Probe 选择/退役策略与固定 K core/reserve 面板。", "A cross-round probe-selection/retirement policy and fixed-K core/reserve panel."),
        "learning_signal": bi("历史候选更新在独立隐藏原任务上的真实回退标签，监督每个 Probe 对未来回退的边际预测价值。", "True regression labels on independent hidden original tasks from historical updates supervise each probe's marginal predictive value."),
        "independent_truth": bi("隐藏原任务环境/程序真值与面板 Probe 完全分离；隐藏标签从不用于当前更新的 gate 输入。", "Environment/program truth on hidden original tasks is disjoint from the probe panel and never enters the gate for the current update."),
        "collision_boundary": bi("2026-08-06 的 Verifier-as-Gatekeeper 已直接证明 skill admission 需要 pre-commit gate，因此 novelty 不能再是‘提交前检查’或‘多 critic’。本方向只保留固定预算下可学习 Probe fidelity/lifecycle 这一变量。", "Verifier-as-Gatekeeper (2026-08-06) directly establishes pre-commit skill gating, so novelty cannot be pre-commit checking or multiple critics. The surviving variable is learnable probe fidelity/lifecycle under a fixed budget."),
        "nearest_work": ["When Self-Evolution Backfires / VaG", "Reward-Free Evolving Agents via Pairwise Validator", "GLEAN"],
        "fresh_reducibility_check": fresh("直接碰撞已把 generic gate 吃掉；只有 predictive probe lifecycle 还能独立检验。", "Direct collisions consume generic gating; predictive probe lifecycle remains independently testable.", [
            {"title": "When Self-Evolution Backfires: Pre-Commit Gating against Skill Contamination in LLM Agents", "url": "https://arxiv.org/abs/2608.05810"},
            {"title": "Reward-Free Evolving Agents via Pairwise Validator", "url": "https://arxiv.org/abs/2607.14408"},
            {"title": "GLEAN: Guideline-Grounded Evidence Accumulation for High-Stakes Agent Verification", "url": "https://openreview.net/forum?id=FP23eFYhAy"},
        ]),
        "redesign_iteration": {"round": "2026-08-10", "verdict": "reducibility-check", "summary": bi("generic pre-commit gate 已碰撞；本轮收窄为固定 K 下学习 Probe fidelity 与 lifecycle。先做同 K 对照，只有 learned panel 独立减少隐藏回退才重新升 P0。", "Generic pre-commit gating is collided. This round narrows the idea to learning probe fidelity and lifecycle under fixed K; only an equal-K win on hidden regression can re-unlock P0.")},
    },
    "compositional-update-compatibility": {
        "title": bi("异构更新交互修复编译器", "Heterogeneous Update Interaction Repair Compiler"),
        "purpose": bi("Prompt、Memory、Tool、Workflow 等更新单独有效，并不代表顺序组合后仍兼容；已有 compositional model editing 已覆盖同类知识编辑的组合，因此需要研究异构 Agent 更新表面之间可复用的交互规则。", "Prompt, memory, tool, and workflow updates may each work alone yet fail when composed in sequence. Compositional model editing already covers same-family knowledge edits, leaving heterogeneous agent-update surfaces as the relevant problem."),
        "core_idea": bi("对冻结的异构更新对做 A→B、B→A、A-only、B-only 四格干预，抽取 typed interaction clause（兼容、优先序、互斥、局部 restoration）。把反复出现的 clause 编译成小型修复程序，在未见三元组合上直接决定排序或插入 restoration，而不是重新搜索。", "Run A→B, B→A, A-only, and B-only interventions on frozen heterogeneous update pairs to extract typed interaction clauses (compatible, precedence, exclusion, local restoration). Compile recurring clauses into a small repair program that orders or restores unseen triples without re-searching."),
        "core_intuition": bi("真正可迁移的不是某一组参数向量的几何，而是‘哪类更新在什么顺序/条件下会破坏哪类能力’这一离散交互结构。", "What may transfer is not the geometry of one parameter delta, but the discrete structure of which update types break which capabilities under which order and conditions."),
        "concrete_example": bi("例如一个 Memory lesson 单独提高 WebShop，另一个 Tool API adapter 单独也提高；A→B 后 hidden tool task 回退而 B→A 不回退。方法学习‘memory-after-tool 需要 restoration clause’，并在未见第三个 workflow edit 加入时直接应用。", "For example, a memory lesson and a tool API adapter each help alone, yet A→B regresses hidden tool tasks while B→A does not. The method learns a memory-after-tool restoration clause and applies it when an unseen third workflow edit is later composed."),
        "method_logic": bi("1) 冻结异构更新对和原任务；2) 做 2×2 顺序/存在干预；3) 用独立原任务真值标出 non-commutativity；4) 将重复模式归纳为 typed clauses；5) 只允许小型 clause compiler 输出 reorder/exclude/restore；6) 在未见 update triples 和第二 update-surface 组合前冻结。", "1) Freeze heterogeneous update pairs and original tasks; 2) run 2×2 order/presence interventions; 3) label non-commutativity with independent original-task truth; 4) induce typed clauses from recurring patterns; 5) let a small clause compiler output only reorder/exclude/restore actions; 6) freeze before unseen update triples and a second surface combination."),
        "comparative_advantage": bi("A³E、O-Edit 和 composable interventions 主要处理同类模型编辑/干预；这里必须证明 typed cross-surface clause 在未见组合上比‘每次重新评测所有顺序’更省执行且不损正确性。", "A3E, O-Edit, and composable interventions mainly address same-family model edits/interventions; this idea must show typed cross-surface clauses transfer to unseen compositions and reduce re-evaluation cost without losing correctness."),
        "strongest_baseline": bi("等预算 pairwise conflict predictor + greedy ordering：同样看到所有 pair 结果，但只预测冲突分数并逐次选择最优顺序，不学习可复用 clause/repair grammar。", "Equal-budget pairwise conflict predictor plus greedy ordering: sees the same pair results but only scores conflicts and greedily orders updates, with no reusable clause/repair grammar."),
        "pilot": bi("选 Prompt×Memory×Tool 三类各 6–8 个冻结更新；用 pair 数据训练 clause compiler，测试从未一起出现过的 triples。四格容量、调用和 hidden-task truth 全匹配。", "Use 6–8 frozen updates from each of prompt, memory, and tool surfaces; train the clause compiler on pairs and test never-before-seen triples, with matched 2×2 capacity, calls, and hidden-task truth."),
        "metric": bi("未见组合 harmful-regression rate、正确排序率、restoration 后保留收益、每个组合所需执行次数。", "Harmful-regression rate on unseen compositions, correct-order rate, retained gain after restoration, and executions per composition."),
        "stop": bi("若简单 pairwise conflict score、最近更新优先或穷举顺序在匹配预算下等效，或 clause 不能跨 update surface 迁移，则停止。", "Stop if simple pairwise conflict scores, recency ordering, or exhaustive ordering match at equal budget, or if clauses fail to transfer across update surfaces."),
        "persistent_update_object": bi("版本化的 typed interaction clause 库与冻结 repair compiler。", "A versioned typed-interaction clause library and frozen repair compiler."),
        "learning_signal": bi("顺序/存在干预后独立隐藏原任务上的收益与回退差，监督 clause 类型和 repair action。", "Gain/regression differences on independent hidden tasks after order/presence interventions supervise clause types and repair actions."),
        "independent_truth": bi("组合正确性只由隐藏原任务和工具执行真值决定；compiler 自己的 conflict score 不能作为标签。", "Composition correctness is determined only by hidden original tasks and tool execution truth; the compiler's own conflict score is never the label."),
        "collision_boundary": bi("A³E 已系统提出 compositional model editing，Composable Interventions 也研究多干预交互；因此 novelty 不能是‘编辑会相互作用’。只保留 heterogeneous Agent update surfaces 上可冻结、可复用的 typed repair clauses。", "A3E formalizes compositional model editing and Composable Interventions studies multi-intervention interactions, so novelty cannot be that edits interact. The surviving claim is frozen reusable typed repair clauses across heterogeneous agent-update surfaces."),
        "nearest_work": ["A3E: Towards Compositional Model Editing", "Composable Interventions for Language Models", "O-Edit"],
        "fresh_reducibility_check": fresh("同类编辑组合已被覆盖，边界必须落到异构 update surface 的可复用 repair grammar。", "Same-family edit composition is covered; the boundary must be a reusable repair grammar across heterogeneous update surfaces.", [
            {"title": "A3E: Towards Compositional Model Editing", "url": "https://openreview.net/forum?id=OwU0mgfKUi"},
            {"title": "Composable Interventions for Language Models", "url": "https://openreview.net/forum?id=tu3qwNjrtw"},
            {"title": "O-Edit: Orthogonal Subspace Editing for Language Model Sequential Editing", "url": "https://openreview.net/forum?id=vx1vJIFvd5"},
        ]),
        "redesign_iteration": {"round": "2026-08-10", "verdict": "method-redesign", "summary": bi("从泛化的‘组合冲突’收窄为异构更新表面的 typed interaction repair compiler；必须用未见 triples 证明 clause 能迁移。", "Narrowed from generic composition conflict to a typed interaction repair compiler across heterogeneous update surfaces; unseen triples must demonstrate clause transfer.")},
    },
    "lineage-aware-rollback": {
        "title": bi("回滚等价的更新历史压缩", "Rollback-Equivalent Update-History Compaction"),
        "purpose": bi("长版本链真正的问题不是同时定位很多祖先，而是完整保存每个版本越来越贵；压缩历史又可能让未来 rollback 无法恢复原行为。", "The real long-version-chain problem is not locating many ancestors at once, but the growing cost of retaining every version; compressing history can destroy future rollback semantics."),
        "core_idea": bi("定期把顺序更新链压成 checkpoint + dependency/restoration clauses。压缩目标不是重构参数相似度，而是对一组冻结 rollback query 保持行为等价：撤销任意授权更新子集后，压缩历史应恢复与 full-history replay 相同的任务行为。", "Periodically compress sequential update history into checkpoints plus dependency/restoration clauses. The objective is not parameter similarity but behavioral rollback equivalence: for frozen rollback queries, undoing authorized update subsets should match full-history replay behavior."),
        "core_intuition": bi("历史压缩是否正确，应该由未来‘能不能回到该回的行为状态’定义，而不是由摘要看起来是否相似。", "History compression should be judged by whether future rollbacks recover the intended behavior, not by whether the compressed representation looks similar."),
        "concrete_example": bi("连续提交 40 个 Prompt/Memory 更新后，不保留 40 个完整快照，只保留每 8 次一个 checkpoint 和少量顺序依赖 clause。测试撤销第 7/18/29 个更新或一个允许的子集时，与 full-history replay 做 paired task comparison。", "After 40 prompt/memory commits, retain one checkpoint every eight edits plus sparse order-dependency clauses rather than 40 full snapshots. Roll back edit 7/18/29 or an allowed subset and compare paired task behavior to full-history replay."),
        "method_logic": bi("1) 顺序记录更新和小型影响签名；2) 用 disable/replay 在 discovery rollback queries 上估计依赖；3) 压缩为周期 checkpoint + sparse dependency/restoration clauses；4) 冻结 compactor；5) 在未见 rollback queries 上恢复；6) full history 仅作为 oracle，不参与压缩训练。", "1) Record sequential updates and compact influence signatures; 2) estimate dependencies with disable/replay on discovery rollback queries; 3) compact into periodic checkpoints plus sparse dependency/restoration clauses; 4) freeze the compactor; 5) recover unseen rollback queries; 6) full history is an oracle only, not a training shortcut."),
        "comparative_advantage": bi("与 MemoRepair 的 descendant cascade repair、CleanEdit 的 harmful-edit pruning 不同，这里测的是压缩后 rollback 语义是否与完整历史等价。", "Unlike MemoRepair descendant cascade repair or CleanEdit harmful-edit pruning, this tests whether compressed history preserves rollback semantics equivalent to full history."),
        "strongest_baseline": bi("周期 checkpoint + 最近版本回退：相同存储预算，不学习 dependency/restoration clause。", "Periodic checkpoints plus nearest-checkpoint rollback at the same storage budget, with no learned dependency/restoration clauses."),
        "pilot": bi("构造 30–50 个顺序轻量更新、12 个冻结 rollback query；比较 full-history oracle、周期 checkpoint、文本摘要和 clause compactor，存储字节与 replay 调用严格匹配。", "Create 30–50 sequential lightweight updates and 12 frozen rollback queries; compare full-history oracle, periodic checkpoints, textual summaries, and the clause compactor with matched storage bytes and replay calls."),
        "metric": bi("rollback behavioral fidelity、保留未撤销收益、存储压缩率、恢复执行次数和最坏 query 回退。", "Rollback behavioral fidelity, retained non-reverted gain, storage compression ratio, recovery executions, and worst-query regression."),
        "stop": bi("若简单周期 checkpoint 在同存储预算下达到相同 rollback fidelity，或必须保存接近完整历史才能正确恢复，则降级为工程组件。", "Stop or demote to an engineering component if simple periodic checkpoints match rollback fidelity at equal storage, or if correctness requires nearly full history."),
        "persistent_update_object": bi("跨轮维护的压缩 checkpoint、dependency/restoration clause 与 rollback map。", "Cross-round compact checkpoints, dependency/restoration clauses, and a rollback map."),
        "learning_signal": bi("discovery rollback queries 中压缩恢复与 full-history replay 的行为差。", "Behavioral difference between compact recovery and full-history replay on discovery rollback queries."),
        "independent_truth": bi("最终 fidelity 用未见 rollback query 上的原任务环境/程序结果判断；full-history replay 仅作 oracle。", "Final fidelity is judged on unseen rollback queries using original-task environment/program outcomes; full-history replay serves only as the oracle."),
        "collision_boundary": bi("MemoRepair 已解决 provenance 完整时的 descendant cascade repair，CleanEdit/顺序编辑工作也处理 harmful edit maintenance；本方向只保留‘在固定存储预算下保持未来 rollback 行为等价’这一压缩问题。", "MemoRepair handles descendant cascade repair with complete provenance, while CleanEdit and sequential editing methods maintain harmful edits. The surviving problem is preserving future rollback behavioral equivalence under a fixed storage budget."),
        "nearest_work": ["MEMOREPAIR", "CleanEdit", "SPHERE sequential editing"],
        "fresh_reducibility_check": fresh("cascade repair 和 harmful-edit pruning 已存在；只有 rollback-equivalent compaction 还能形成不同问题。", "Cascade repair and harmful-edit pruning already exist; rollback-equivalent compaction remains a distinct problem.", [
            {"title": "MEMOREPAIR: Barrier-First Cascade Repair in Agentic Memory", "url": "https://arxiv.org/abs/2605.07242"},
            {"title": "CleanEdit: Retention-Aware Pruning and Bounded Replay for Lifelong Model Editing", "url": "https://openreview.net/forum?id=pguFq8hyd4"},
            {"title": "Energy-Regularized Sequential Model Editing on Hyperspheres", "url": "https://openreview.net/forum?id=CHsdtzCip6"},
        ]),
        "redesign_iteration": {"round": "2026-08-10", "verdict": "pilot-candidate-after-recheck", "summary": bi("从弱现实的祖先定位改成 rollback-equivalent history compaction；如果周期 checkpoint 不能等效，该问题有独立 P0 价值。", "Reframed from weak ancestor localization to rollback-equivalent history compaction; it has a standalone P0 only if periodic checkpoints fail to match it.")},
    },
}
