from __future__ import annotations

from typing import Any

from .method_details_common import bi


def fresh(summary_zh: str, summary_en: str, sources: list[dict[str, str]]) -> dict[str, Any]:
    return {"review_date": "2026-08-10", "summary": bi(summary_zh, summary_en), "sources": sources}


DETAILS: dict[str, dict[str, Any]] = {
    "outcome-equivalent-trajectory-contrast": {
        "title": bi("跨过程验证经验蒸馏", "Cross-Process Validated Experience Distillation"),
        "purpose": bi("多条成功轨迹做交集、共识或 contrast 已经不足以形成新方法；真正的问题是：同一成功结果可由不同有效过程获得时，哪条经验在改变未来行为后仍跨过程稳定有益。", "Intersection, consensus, or contrast over multiple successful trajectories is no longer enough. The real problem is identifying lessons whose behavioral intervention remains beneficial across distinct valid processes that reach the same successful outcome."),
        "core_idea": bi("冻结同一任务、同一成功终点的多种 process family。一个冻结 extractor 从每条成功轨迹提 candidate lesson；随后对 lesson 做 memory-OFF / memory-ON matched intervention，并采用 leave-one-process-family-out 验证。只有平均效用为正、worst-process 不为负且跨 process 方差低的 lesson 才持久写入。", "Freeze multiple process families for the same task and same successful outcome. A frozen extractor proposes candidate lessons from each success; each lesson then receives matched memory-OFF/memory-ON interventions with leave-one-process-family-out validation. Persist only lessons with positive mean utility, non-negative worst-process effect, and low cross-process variance."),
        "core_intuition": bi("文字上反复出现不等于真正可迁移；如果一条经验不是偶然绑定某一种成功路径，那么把它写入 memory 后应在不同成功过程来源下都保持正效用。", "Repeated wording is not transfer. If a lesson is not accidentally tied to one successful route, using it as memory should retain positive utility across different successful process sources."),
        "concrete_example": bi("同一个 ALFWorld 目标有三种成功方式：先定位容器、先取物、或先处理阻塞对象。三条轨迹都可能总结出‘先检查 receptacle 状态’。方法不看出现次数，而把这条 lesson 分别写入后在其他 process family 的 held-out tasks 上做 memory-on/off；只有跨 family 都有帮助才晋升。", "The same ALFWorld goal may be solved by locating the receptacle first, collecting the object first, or clearing a blocker first. All may suggest 'check receptacle state first.' The method ignores frequency and tests the lesson via memory-on/off on held-out tasks sourced from other process families; only cross-family benefit permits promotion."),
        "method_logic": bi("1) 固定 task/outcome，按 action/tool graph 划分 3–4 个有效 process family；2) 冻结 extractor 和候选 lesson；3) 每个 lesson 的生成 family 与验证 family 严格分离；4) 在相同 future-task pool 上做 memory OFF/ON paired replay；5) 估计 mean、worst-process 和 effect variance；6) 只晋升跨过程效用稳定 lesson；7) 测试时直接复用，不再做多轨迹推理。", "1) Fix task/outcome and partition 3–4 valid process families by action/tool graph; 2) freeze extractor and candidate lessons; 3) separate lesson-generation families from validation families; 4) run memory OFF/ON paired replay on the same future-task pool; 5) estimate mean, worst-process, and effect variance; 6) promote only cross-process stable lessons; 7) reuse directly at test time with no multi-trajectory reasoning."),
        "comparative_advantage": bi("SkillCAT/Trace2Skill 已覆盖多轨迹 contrast/抽象；本方法只主张 process-invariant intervention utility，而不是‘多看轨迹’本身。", "SkillCAT/Trace2Skill already cover multi-trajectory contrast/abstraction; this method claims only process-invariant intervention utility, not the generic benefit of seeing multiple trajectories."),
        "strongest_baseline": bi("Utility-only admission：同 candidate lesson、同 memory-on/off replay 数、同 future tasks，只按跨所有轨迹的平均效用排序，不区分 process family。", "Utility-only admission: same candidate lessons, memory-on/off replay count, and future tasks, ranked by mean utility across all trajectories without process-family structure."),
        "pilot": bi("每个 discovery task 收集至少 3 个成功 process family；冻结 20–30 个 candidate lesson。四臂比较 single-success、consensus、utility-only、cross-process validated，memory 数量和 replay 预算严格匹配。", "Collect at least three successful process families per discovery task and freeze 20–30 candidate lessons. Compare single-success, consensus, utility-only, and cross-process validated arms with matched memory count and replay budget."),
        "metric": bi("hidden future-task success、negative-transfer rate、worst-process effect、lesson retention、同预算每条有效 lesson 的 replay 成本。", "Hidden future-task success, negative-transfer rate, worst-process effect, lesson retention, and replay cost per useful lesson at matched budget."),
        "stop": bi("若 simple consensus 或 utility-only 在同 replay 预算下与 process-invariant admission 的 CI 重叠，或 process family 划分对结果不稳定，则停止 process-invariance 主张。", "Stop the process-invariance claim if simple consensus or utility-only overlaps within CI at the same replay budget, or if results are unstable to process-family partitioning."),
        "persistent_update_object": bi("被晋升的持久 lesson 及其跨过程效用证据/准入状态。", "Persisted lessons plus their cross-process utility evidence and admission state."),
        "learning_signal": bi("leave-one-process-family-out 的 memory-on/off 边际效用，而不是文本共识或最终 success 本身。", "Leave-one-process-family-out memory-on/off marginal utility, not textual consensus or final success itself."),
        "independent_truth": bi("future-task 环境/程序成功率提供真值；process family 仅来自冻结 action/tool graph，不使用 future labels。", "Future-task environment/program success provides truth; process families come only from frozen action/tool graphs and never use future labels."),
        "collision_boundary": bi("SkillCAT 已对同任务多轨迹做 contrastive extraction，Trace2Skill 与 ACL 2026 memory survey 已覆盖 cross-trajectory abstraction，Mem2Evolve/ReMe 已做经验蒸馏与 utility refinement。因此只保留‘同 outcome 不同过程下的干预效用不变性’这一独立变量。", "SkillCAT contrasts same-task trajectories; Trace2Skill and the ACL 2026 memory survey cover cross-trajectory abstraction; Mem2Evolve/ReMe cover experience distillation and utility refinement. The surviving variable is intervention-utility invariance across different valid processes with the same outcome."),
        "nearest_work": ["SkillCAT", "Trace2Skill", "ReMe", "Mem2Evolve"],
        "fresh_reducibility_check": fresh("多轨迹抽象已拥挤；process-invariant intervention utility 仍能用 utility-only 对照单独证伪。", "Multi-trajectory abstraction is crowded; process-invariant intervention utility remains separately falsifiable against utility-only admission.", [
            {"title": "SkillCAT: Contrastive Assessment and Topology-Aware Skill Self-Evolution for LLM Agents", "url": "https://arxiv.org/abs/2606.13317"},
            {"title": "Trace2Skill: Distill Trajectory-Local Lessons into Transferable Agent Skills", "url": "https://arxiv.org/abs/2603.25158"},
            {"title": "From Storage to Experience: A Survey on the Evolution of LLM Agent Memory Mechanisms", "url": "https://aclanthology.org/2026.findings-acl.2069/"},
            {"title": "Remember Me, Refine Me: A Dynamic Procedural Memory Framework for Experience-Driven Agent Evolution", "url": "https://aclanthology.org/2026.findings-acl.829/"},
        ]),
        "redesign_iteration": {"round": "2026-08-10", "verdict": "fresh-collision-recheck", "summary": bi("旧版 consensus/交集已不够新；改成 leave-one-process-family-out 的 memory-on/off 干预效用稳定性。若 utility-only 等效，立即停止。", "Consensus/intersection is no longer novel. The redesign uses leave-one-process-family-out memory-on/off utility stability; stop immediately if utility-only is equivalent.")},
    },
    "contradiction-preserving-consolidation": {
        "title": bi("证据保真的矛盾核心巩固", "Evidence-Preserving Contradiction-Core Consolidation"),
        "purpose": bi("最新结果表明 LLM 持续 consolidation 本身可能把有用轨迹压坏；因此不能默认‘摘要更好’，必须让每条 consolidated rule 始终可追溯到原始支持与反证，并证明压缩后的规则优于保留原始 episode。", "Recent evidence shows LLM consolidation itself can corrupt useful trajectories. Summarization cannot be assumed beneficial; every consolidated rule must remain traceable to raw support and counterevidence, and consolidation must beat retaining raw episodes."),
        "core_idea": bi("原始 episodes 永不被 consolidation 覆盖。每条规则维护 support set 与 contradiction core；通过删除干预寻找‘去掉后会改变规则结论/适用边界’的最小证据集合。只有在固定 context/storage 预算下，规则+证据 core 比 episodic-only 更好，才持久发布 consolidated memory。", "Raw episodes are never overwritten. Each rule maintains a support set and contradiction core; deletion interventions identify the minimal evidence whose removal changes the rule conclusion or applicability. Publish consolidated memory only if rule-plus-evidence-core beats episodic-only memory under fixed context/storage budget."),
        "core_intuition": bi("可靠 consolidation 的关键不是摘要写得像不像，而是压缩后仍保留足以推翻自己的原始证据。", "Reliable consolidation is not about a plausible summary; the compressed memory must retain enough original evidence to falsify itself."),
        "concrete_example": bi("10 条轨迹中 8 条支持‘打开 fridge 前先 look’，2 条在特殊状态下反例。普通摘要可能只保留多数规则；本方法保留规则外，还保存两条中真正能改变适用边界的最小 contradiction core，并在检索时一并提供。", "Among ten trajectories, eight support 'look before opening the fridge' while two are counterexamples in special states. A normal summary may retain only the majority rule; this method stores the rule plus the minimal contradiction core that changes its applicability and retrieves them together."),
        "method_logic": bi("1) 冻结 raw episodic store；2) 生成 candidate rule，但不得删除 raw evidence；3) 对代表支持/反证做 deletion intervention，测规则结论或 hidden prediction 是否改变；4) 找最小 conclusion-changing evidence core；5) 固定 context/storage 预算比较 rule+core 与 episodic-only；6) 只有有净收益才发布 consolidated artifact。", "1) Freeze the raw episodic store; 2) propose candidate rules without deleting raw evidence; 3) run deletion interventions on representative support/counterevidence and measure conclusion or hidden-prediction changes; 4) find a minimal conclusion-changing evidence core; 5) compare rule+core against episodic-only under fixed context/storage budget; 6) publish only with net benefit."),
        "comparative_advantage": bi("与 ReMe/Nemori 的‘什么值得记’不同，这里把 episodic-only 设为强 baseline，并要求 consolidation artifact 自带可推翻它的最小证据 core。", "Unlike ReMe/Nemori's memory-value selection, this treats episodic-only as a strong baseline and requires every consolidated artifact to carry a minimal evidence core capable of overturning it."),
        "strongest_baseline": bi("Episodic-only：完全不做 consolidation，在相同 context token/storage 字节预算下检索原始轨迹。", "Episodic-only: no consolidation, retrieve raw trajectories under the same context-token and storage-byte budget."),
        "pilot": bi("固定 40–60 条 raw episodes 和 8–12 个候选 rule；比较 forced summary、utility refinement、episodic-only、rule+contradiction-core。hidden tasks 从未参与 consolidation。", "Freeze 40–60 raw episodes and 8–12 candidate rules; compare forced summaries, utility refinement, episodic-only, and rule+contradiction-core. Hidden tasks never participate in consolidation."),
        "metric": bi("hidden success、over-generalization error、counterexample recall、context/storage cost、删除关键证据后的 conclusion flip rate。", "Hidden success, over-generalization error, counterexample recall, context/storage cost, and conclusion-flip rate after deleting critical evidence."),
        "stop": bi("若 episodic-only 在同 context/storage 预算下匹配或优于 rule+core，或 deletion core 对 hidden behavior 无预测力，则停止 consolidation 主张。", "Stop the consolidation claim if episodic-only matches or beats rule+core at equal context/storage budget, or if deletion cores do not predict hidden behavior."),
        "persistent_update_object": bi("规则、不可变 raw-evidence 引用和最小 contradiction/support core 组成的持久 consolidation artifact。", "A persistent consolidation artifact containing the rule, immutable raw-evidence references, and minimal contradiction/support core."),
        "learning_signal": bi("删除某条原始证据后规则结论/适用边界和 hidden prediction 是否发生变化。", "Whether deleting a raw evidence item changes the rule conclusion/applicability or hidden prediction."),
        "independent_truth": bi("最终正确性由 hidden environment/program truth 判断；LLM 生成的摘要或 deletion score 不充当最终标签。", "Final correctness is judged by hidden environment/program truth; LLM summaries or deletion scores are not final labels."),
        "collision_boundary": bi("2026 的连续 memory consolidation 研究已发现 consolidation 可把有用经验变坏；ReMe/Nemori 已覆盖 utility/refinement。新边界是 raw episodes 作为一等证据 + conclusion-changing contradiction core + episodic-only 强对照。", "2026 work shows continuous memory consolidation can corrupt useful experience, while ReMe/Nemori cover utility/refinement. The new boundary is raw episodes as first-class evidence plus conclusion-changing contradiction cores and an episodic-only strong control."),
        "nearest_work": ["Useful Memories Become Faulty When Continuously Updated by LLMs", "ReMe", "Nemori"],
        "fresh_reducibility_check": fresh("不能默认 consolidation 是正贡献；必须赢过 episodic-only，并保存能推翻规则的原始证据。", "Consolidation cannot be assumed beneficial; it must beat episodic-only and preserve raw evidence capable of falsifying the rule.", [
            {"title": "Useful Memories Become Faulty When Continuously Updated by LLMs", "url": "https://arxiv.org/abs/2605.12978"},
            {"title": "Remember Me, Refine Me", "url": "https://aclanthology.org/2026.findings-acl.829/"},
            {"title": "What Deserves Memory: Adaptive Memory Distillation for LLM Agents", "url": "https://aclanthology.org/2026.acl-long.1607/"},
        ]),
        "redesign_iteration": {"round": "2026-08-10", "verdict": "pilot-candidate-after-recheck", "summary": bi("把‘保留少数反证’升级为 raw evidence 不可覆盖 + conclusion-changing contradiction core，并把 episodic-only 设成必须打赢的 baseline。", "Upgraded from preserving minority counterexamples to immutable raw evidence plus conclusion-changing contradiction cores, with episodic-only as the baseline that must be beaten.")},
    },
    "retrieval-interference-auditor": {
        "title": bi("共检索交互排斥图", "Co-Retrieval Interaction Exclusion Graph"),
        "purpose": bi("单条 memory 的 causal usefulness 已有直接方法；剩下的真实失败是两条单独无害/有益的 memory 同时被检索后相互误导，而 per-item score 看不见这种 interaction。", "Direct methods already estimate causal usefulness of individual memories. The remaining failure is interaction: two memories may each be harmless or useful alone yet become harmful when co-retrieved, which per-item scores cannot detect."),
        "core_idea": bi("先用 per-item causal selector 得到候选集，再只对高频共检索 pair 做 2×2 intervention：none、A、B、A+B。学习稀疏 interaction edge（synergy/harm/exclusion/order），形成持久 co-retrieval graph；运行时在不增加 replay 的情况下先应用 exclusion/ordering，再交给普通检索器。", "Start from a per-item causal selector, then run 2×2 interventions only for frequent co-retrieval pairs: none, A, B, A+B. Learn sparse interaction edges (synergy/harm/exclusion/order) as a persistent co-retrieval graph; at runtime apply exclusion/ordering before the normal retriever with no extra replay."),
        "core_intuition": bi("相关性和单条 causal effect 都是一级项；真正难的是 A×B 交互项。", "Relevance and single-memory causal effects are first-order terms; the missing quantity is the A×B interaction."),
        "concrete_example": bi("一条 memory 说‘API 失败先重试’，另一条说‘遇到 429 改备用 endpoint’，单独都可能有益；一起检索时却先反复重试再切换导致预算耗尽。2×2 replay 能识别 A+B 的额外负效应，并写入互斥/优先级 edge。", "One memory says retry an API failure; another says switch endpoints on 429. Each can help alone, yet together they may exhaust budget by repeated retry before switching. A 2×2 replay identifies the extra A+B harm and stores an exclusion/precedence edge."),
        "method_logic": bi("1) 冻结 per-item selector 与 top-M memory；2) 从真实检索日志筛高频 pair；3) 每个 pair 做 matched 2×2 intervention；4) 估计 interaction residual ΔAB−ΔA−ΔB；5) 只保存显著、跨任务重复的稀疏 edge；6) 测试时 graph 只做 exclude/order，不重新 replay。", "1) Freeze the per-item selector and top-M memories; 2) select frequent pairs from real retrieval logs; 3) run matched 2×2 interventions; 4) estimate interaction residual ΔAB−ΔA−ΔB; 5) persist only significant recurring sparse edges; 6) at test time the graph only excludes/orders without replay."),
        "comparative_advantage": bi("CMI 已做 per-memory causal selection；本方法必须证明 pair interaction residual 在 CMI 已选好的 memory 上还有额外价值。", "CMI already performs per-memory causal selection; this method must show pairwise interaction residual adds value after CMI has selected the memories."),
        "strongest_baseline": bi("CMI/per-item causal selector：同 memory pool、同 replay 总预算，把全部干预预算花在单条 memory utility，不建 interaction graph。", "CMI/per-item causal selector: same memory pool and total replay budget, spending all interventions on single-memory utility with no interaction graph."),
        "pilot": bi("固定 20–30 个 memory 和 top co-retrieval pairs；在相同 replay 总数下比较 per-item causal、随机 pair、共现阈值、interaction graph。hidden tasks 不参与 edge 学习。", "Freeze 20–30 memories and top co-retrieval pairs; compare per-item causal selection, random pairs, co-occurrence thresholds, and the interaction graph under the same replay count. Hidden tasks never train edges."),
        "metric": bi("hidden task success、harmful co-retrieval rate、额外排斥率、保留单条 memory 收益、interaction edge precision。", "Hidden-task success, harmful co-retrieval rate, exclusion rate, retained single-memory gain, and interaction-edge precision."),
        "stop": bi("若 CMI/per-item selector 或简单共现互斥在同 replay 预算下等效，或 pair edge 不能跨任务复用，则并入普通 memory selection，不单独成方法。", "If CMI/per-item selection or simple co-occurrence exclusion matches at equal replay budget, or pair edges do not transfer across tasks, merge into ordinary memory selection."),
        "persistent_update_object": bi("跨 episode 保存的稀疏 co-retrieval interaction/exclusion graph。", "A sparse co-retrieval interaction/exclusion graph persisted across episodes."),
        "learning_signal": bi("matched 2×2 replay 得到的二阶 interaction residual，而非单条 memory utility。", "Second-order interaction residual from matched 2×2 replay rather than single-memory utility."),
        "independent_truth": bi("环境/程序任务结果直接计算四臂效用；LLM relevance 或 interaction score 不作为真值。", "Environment/program outcomes directly compute four-arm utility; LLM relevance or interaction scores are not truth."),
        "collision_boundary": bi("Causal Memory Intervention 已直接按受控 intervention 选择有用/有害 memory，因此旧三臂 auditor 已碰撞。只保留 per-item causal selection 之后的 co-retrieval interaction residual。", "Causal Memory Intervention already selects useful/harmful memories via controlled interventions, colliding with the old auditor. The surviving variable is co-retrieval interaction residual after per-item causal selection."),
        "nearest_work": ["Causal Memory Intervention", "ReMe", "Memory-induced tool drift"],
        "fresh_reducibility_check": fresh("单条 causal usefulness 已被覆盖；二阶共检索 interaction 是剩余可识别变量。", "Single-memory causal usefulness is covered; second-order co-retrieval interaction is the remaining identifiable variable.", [
            {"title": "Causal Intervention-Based Memory Selection for Long-Horizon LLM Agents", "url": "https://arxiv.org/abs/2605.17641"},
            {"title": "Remember Me, Refine Me", "url": "https://aclanthology.org/2026.findings-acl.829/"},
        ]),
        "redesign_iteration": {"round": "2026-08-10", "verdict": "parent-simplification-check", "summary": bi("旧 auditor 与 CMI 直接碰撞；本轮只保留 A×B 共检索交互项。若 per-item CMI 或简单共现互斥等效，就并回普通 memory selection。", "The old auditor collides with CMI. This round keeps only A×B co-retrieval interactions; merge back into ordinary memory selection if per-item CMI or simple co-occurrence exclusion matches.")},
    },
}
