"""Primary-source research cards for Skill security, round 1 (2026-09-27).

Bibliographic and source review only. Author-reported measurements are not our
reproductions; documented behavior, issue reports and confirmed advisories differ.
"""
from __future__ import annotations

CUTOFF = '2026-09-27'
OPENCLAW_COMMIT = '6fb2c424e8ad2084bbf6054856f6af544a267745'

def card(sid,title,url,kind,level,stages,support,boundary,**extra):
    return dict(id=sid,title=title,url=url,kind=kind,read_level=level,stages=stages,
                supports=support,does_not_establish=boundary,checked_on=CUTOFF,
                primary_source=True,reproduced_by_us=False,**extra)

def paper(pid,title,arxiv,stages,support,boundary,*,level='ABSTRACT_REVIEWED',version='v1',role='ATTACK_OR_MEASUREMENT',**extra):
    return card(pid,title,'https://arxiv.org/abs/'+arxiv+version,'PAPER',level,stages,support,boundary,
                arxiv_id=arxiv,version=version,role=role,venue='PREPRINT_UNLESS_EXPLICITLY_VERIFIED',**extra)

SOURCES = [
 card('D01','Agent Skills specification','https://agentskills.io/specification','SPECIFICATION','RELEVANT_SECTIONS_REVIEWED',['package','discovery','activation','authorization'],
      'Skill目录含元数据、指令及可选脚本/资源；渐进加载。allowed-tools是实验性预批准字段，支持随实现变化。',
      '格式兼容不等于统一隔离保证；allowed-tools不能无条件解读为能力上限。',locator='Frontmatter; allowed-tools; Progressive disclosure'),
 card('D02','Claude Code: Extend Claude with skills','https://code.claude.com/docs/en/skills','RUNTIME_DOC','RELEVANT_SECTIONS_REVIEWED',['activation','authorization','execution','persistence'],
      '当前文档区分持续留在上下文的Skill内容与只在调用turn有效的工具预批准；动态上下文可在内容送入模型之前求值。',
      '不能把文档明确允许的行为称作未披露漏洞；全局deny/ask、版本和安装来源必须一起核对。',locator='Skill content lifecycle; Pre-approve tools; dynamic context injection; permission behavior'),
 card('D03','OpenClaw: Skills','https://docs.openclaw.ai/tools/skills','RUNTIME_DOC','RELEVANT_SECTIONS_REVIEWED',['discovery','activation','authorization','secrets','update'],
      '有效Skill先按gating/allowlist确定；env/apiKey按宿主run注入再恢复；宿主注入不自动进入sandbox。支持安装策略和固定revision等控制。',
      '宿主共享权限不是每个Skill天然隔离；不能把已配置能力的使用直接叫提权。',locator='Security; Gating; Environment injection; Snapshots and refresh'),
 card('D04','Gemini CLI: Agent Skills','https://geminicli.com/docs/cli/skills/','RUNTIME_DOC','RELEVANT_SECTIONS_REVIEWED',['discovery','activation','authorization'],
      '发现、激活、用户同意与资源访问有明确阶段；同意后Skill内容和目录结构进入历史，目录加入可读路径；命名冲突按层级处理。',
      '授权目录不等于授权任何后续副作用；不能以其他客户端字段的含义推断该宿主。',locator='How it works; Discovery tiers; Precedence and aliases'),
 card('D05','MCP Security Best Practices, 2026-07-28','https://modelcontextprotocol.io/docs/2026-07-28/tutorials/security/security_best_practices','SPECIFICATION','RELEVANT_SECTIONS_REVIEWED',['tool_boundary','authorization','secrets'],
      'MCP侧的授权、混淆代理与令牌边界是Skill调用工具时需要保持的相邻信任边界。',
      'MCP不是Skill格式，已有MCP漏洞不能只换名称就成为新的Skill论文。'),
 card('D06','OpenClaw skill environment implementation','https://github.com/openclaw/openclaw/blob/'+OPENCLAW_COMMIT+'/src/skills/runtime/env-overrides.ts','SOURCE_CODE','SELECTED_SOURCE_READ',['secrets','delegation'],
      '读取的固定版本包含危险环境变量过滤、active-key引用计数及子进程过滤接口注释；广义环境继承并非未研究的新问题。',
      '未在本轮执行该实现，未验证全部调用路径；源码片段不是当前可利用性证据。',commit=OPENCLAW_COMMIT,
      content_sha256='d2afe96761c17e87dd546554029e0c18c5565c8b5ce3618f3a6bb6b4260e8f48',locator='src/skills/runtime/env-overrides.ts; selected first ~220 lines; 249 total'),
 card('D07','OpenClaw SECURITY.md: operator and execution trust boundaries','https://github.com/openclaw/openclaw/blob/'+OPENCLAW_COMMIT+'/SECURITY.md','THREAT_MODEL','SELECTED_SOURCE_READ',['authorization','execution','delegation','disclosure'],
      '固定版本明确区分可信operator/本地代码、非隔离的共享会话和真正auth/policy/sandbox边界；prompt-only或可信插件已有权限内行为不自动算漏洞。',
      '维护者报告范围不等于所有部署风险不存在；论文测量部署假设失配时要如实命名，不能伪报权限绕过。',commit=OPENCLAW_COMMIT,
      content_sha256='12dfbe925573cb1da636b54d7ef01c3f4fe4acf1643ef1700ffa84acbaf8e2b2',locator='Shared Agents; Out of Scope; Operator Trust Model; Agent/Model Trust'),
 card('A01','Skill env override host env injection — GHSA-82g8-464f-2mv7','https://github.com/openclaw/openclaw/security/advisories/GHSA-82g8-464f-2mv7','MAINTAINER_ADVISORY','RELEVANT_SECTIONS_REVIEWED',['secrets','execution'],
      '历史公告：本地配置env覆盖未应用宿主安全策略；需要修改本地可信配置；公告给出受影响和已修复版本。',
      '不是任意第三方Skill零权限攻击；不是本轮新漏洞；不应默认在最新版本仍然存在。',reported_date='2026-02-21',affected='<=2026.2.19-2',fixed='>=2026.2.21'),
 card('A02','OpenClaw issue #36280: Skill API key inherited by ACP child process','https://github.com/openclaw/openclaw/issues/36280','ISSUE_REPORT','ISSUE_AND_LINKED_SOURCE_REVIEWED',['secrets','delegation'],
      '公开issue记录Skill密钥被子进程继承导致认证/计费来源变化；当前env模块注释明确引用该issue并提供移除key的接口。',
      'issue不是已确认安全公告；未追完所有修复调用链；不能把相同现象当原创发现。'),
 paper('P01','Agent Skills in the Wild: An Empirical Study of Security Vulnerabilities at Scale','2601.10338',['package','execution','secrets'],
       '大规模SkillScan静态/语义审计形成注入、泄露、提权和供应链分类。',
       '扫描标记比例不是动态确认的在野利用率；作者统计未由我们复现。',author_measurement={'collected':42447,'analyzed':31132,'flagged_percent':26.1,'interpretation':'scanner-derived flags, not independently reproduced exploit prevalence'}),
 paper('P02','Do Not Mention This to the User: Detecting and Understanding Malicious Agent Skills in the Wild','2602.06547',['package','execution','secrets','disclosure'],
       '在野恶意Skill测量及动态确认，是区分风险特征与恶意行为的直接最近邻。',
       '样本和确认规则决定统计范围，不能和另一篇扫描率直接相减；不是当前registry全体的普查。',version='v4',author_measurement={'audited':98380,'dynamically_confirmed_malicious':157,'interpretation':'author-reported'},verified_venue='USENIX Security 2026 (arXiv comments)'),
 paper('P03','Skill-Inject: Measuring Agent Vulnerability to Skill File Attacks','2602.20156',['package','activation','execution','secrets'],
       '202个注入—任务配对，包括显式和上下文依赖指令，同时评价安全与正常任务效用。',
       '再造一批恶意SKILL.md或泛称情境重要，不足以构成新问题。',author_measurement={'injection_task_pairs':202,'interpretation':'benchmark cardinality, not our executions'},artifact_url='https://github.com/aisa-group/skill-inject'),
 paper('P04','Supply-Chain Poisoning Attacks Against LLM Coding Agent Skill Ecosystems','2604.03081',['package','execution'],
       'DDIPE研究文档示例/配置被编码Agent复用后形成执行危害。',
       '文档到代码的污染与模板内隐载荷已被研究；论文报告的漏洞不能当本轮发现。'),
 paper('P05','BadSkill: Backdoor Attacks on Agent Skills via Model-in-Skill Poisoning','2604.09378',['package','execution'],
       'Skill携带的学习模型可以成为隐蔽后门载体，实验使用OpenClaw-inspired受控环境。',
       '不是原生OpenClaw所有版本的漏洞证明；内嵌分类器后门不是空白方向。'),
 paper('P06','HarmfulSkillBench: How Do Harmful Skills Weaponize Your Agents?','2604.15415',['package','execution'],
       '区分有害能力及其被用户使用的风险，提供200个harmful skills的评测材料。',
       'harmful capability不等于第三方劫持良性用户任务；仅有害样本集不能计算benign FPR。'),
 paper('P07','Under the Hood of SKILL.md: Semantic Supply-chain Attacks on AI Agent Skill Registry','2605.11418',['discovery','selection','governance'],
       'Skill描述/语义元数据影响检索选择及registry治理。',
       '描述优化、语义伪装、抢占选择率不宜作为新的独立主题。'),
 paper('P08','Exploiting LLM Agent Supply Chains via Payload-less Skills','2605.14460',['activation','execution'],
       '研究不含直接恶意代码而借任务合规理由诱导Agent生成偏离行为。',
       '没有显式payload不意味着该路径没人研究；需要额外的宿主边界差异。'),
 paper('P09','SkillMutator: Benchmarking and Defending Language-and-Code Cross-modal Attacks on LLM Agent Skills','2606.14154',['package','execution','audit'],
       '语言与代码联合决定风险，含扫描反馈驱动变体的测试。',
       '跨模态拼接、普通扫描器规避不再当作新颖性；本轮不实现规避攻击器。'),
 paper('P10','PhantomSkill: Malicious Code Injection in Agent Skill Ecosystems','2606.19191',['package','execution','audit'],
       '辅助脚本/资源中的代码注入与伪装成实现缺陷的路径。',
       '只扫描SKILL.md而遗漏资源不是新的核心发现；需具体未覆盖机制。'),
 paper('P11','Agent Skill Security: Threat Models, Attacks, Defenses, and Evaluation (SkillSec-Eval)','2607.13987',['package','discovery','selection','execution','update','persistence'],
       '327个真实Skill构成受控生命周期评测，覆盖准入、检索、规划、组合、执行和演化。',
       '完整生命周期分类已存在；受控框架结果不证明原生产品同样可利用；长期历史与跨宿主语义尚需单独验证。',level='THREAT_MODEL_METHOD_LIMITATIONS_REVIEWED',locator='Sections 3–4 and 7; not claiming independent reproduction'),
 paper('P12','When Experience Becomes Instruction: Trajectory Poisoning in Self-Evolving Agent Skill Systems','2608.05563',['authoring','persistence','update'],
       'PoisonedEvolution研究受污染成功轨迹被写成持久Skill；用可控指令/无害标记刻画继承。',
       '指令进入Skill不等于发生真实执行危害；普通轨迹投毒已碰撞。'),
 paper('P13','Convergent Detour Hijacking: Task-Preserving Resource Amplification in Skill-Based LLM Agents','2608.12273',['selection','execution','availability'],
       '在完成原任务同时增加不必要流程和资源消耗的Skill攻击。',
       '正常任务仍成功但成本增加，已有专门工作；不能重新命名为新漏洞。'),
 paper('P14','MaliciousSkillBench: A Comprehensive Benchmark for Malicious Agent Skill Detection','2608.19901',['package','audit'],
       '跨13来源整理，核心集9740个Skill；强调结构/来源不相交评测与正常样本误报。',
       '随机切分好成绩不表示跨来源有效；来源分布偏移的检测基准已被研究。',author_measurement={'skills':9740,'malicious':7505,'benign':2235,'interpretation':'author-reported normalized primary benchmark'},artifact_url='https://protectskills.github.io/MaliciousSkillBench/'),
 paper('P15','SkillGuard: A Permission-Centric Framework for Agent Skill Security','2606.03024',['authorization','delegation','execution'],
       '权限中心的静态与运行时治理，涉及最小权限和委托；是权限类题目的强最近邻。',
       '本轮不再提出泛化permission manifest或通用reference monitor作为攻击论文创新。',version='v2',role='DEFENSE_NEAREST_NEIGHBOR',level='METHOD_SECTIONS_REVIEWED'),
 paper('P16','Versioned Transitive Dependency-Closure Binding and Operation-Time Effect Governance for Agent Skills: ClosureBound','2609.05920',['package','update','authorization','execution'],
       '对递归/延迟依赖闭包、版本、用途、权限及效果路径绑定；声明一组假设下的性质与无provider内核验证。',
       '依赖TOCTOU与授权沿旧版本转移已被明确提出；其证明不等同完整原生生态部署验证。',role='DEFENSE_NEAREST_NEIGHBOR'),
 paper('P17','OBLIVION: Workflow-Level Operational Skill Unlearning for Deployed Agents','2608.08264',['revocation','persistence'],
       '删除registry条目后从档案、会话或memory重建被撤销Skill的工作流；含受控基准与缓解。',
       '卸载后复活不是新发现；不能仅换一个残留载体重复该问题。',role='ATTACK_AND_DEFENSE_NEAREST_NEIGHBOR',level='PRIMARY_ABSTRACT_SEARCH_REVIEWED'),
 paper('P18','After the Party: Growth, Governance, and Security Scanning in the OpenClaw Agent Skill Ecosystem','2609.17274',['package','governance','audit'],
       '对当前Skill生态的增长、治理与扫描能力开展测量；是近期生态审计碰撞项。',
       '再爬一次ClawHub加普通扫描统计不自动形成独立研究；需额外识别对象。'),
 paper('P19','Safety in Self-Evolving LLM Agent Systems: Threats, Amplification, and Case Studies','2606.23075',['authoring','persistence','update'],
       '跨模块生命周期分析持久化和放大风险，比较自进化系统案例。',
       '普通安全债务或污染跨代传播并非未研究；个案不能推广所有Agent。'),
 paper('P20','SkillSentry: Adaptive Honey Worlds for Dynamic Safety Testing of Agent Skills','2608.03485',['execution','audit'],
       'LLM模拟honey worlds中有/无Skill配对、实际效果验证和双重用途复核，而非只凭可疑文本下结论。',
       '动态诱发、无害标记、因果差分与context-aware安全判断已有方法；原生宿主遥测覆盖不能由模拟器假定。',level='METHOD_AND_EVALUATION_SECTIONS_REVIEWED',role='DEFENSE_AND_EVALUATION_NEAREST_NEIGHBOR',artifact_url='https://github.com/nizhangli062-jpg/SkillSentry-Adaptive-Honey-Worlds-for-Dynamic-Safety-Testing-of-Agent-Skills'),
 paper('P21','AgentDojo: A Dynamic Environment to Evaluate Prompt Injection Attacks and Defenses for LLM Agents','2406.13352',['tool_boundary','execution','audit'],
       '状态化任务、非可信工具输出与安全/效用分开评价的可复用环境。',
       '它不是原生Skill安装器、权限和生命周期的完整复现。',role='ADJACENT_BENCHMARK',artifact_url='https://github.com/ethz-spylab/agentdojo',verified_venue='NeurIPS 2024 Datasets and Benchmarks (official repository citation)'),
 card('T01','Cisco AI Defense skill-scanner','https://github.com/cisco-ai-defense/skill-scanner','TOOL','README_REVIEWED',['package','audit'],
      '可作为已有静态/语义/数据流扫描基线；支持不同分析配置和可集成输出。',
      '本轮仅查看，未安装、未扫描恶意包、未得到复现分数。',role='BASELINE_CANDIDATE',artifact_status='PUBLIC_REPO_VERIFIED_NOT_RUN'),
 card('T02','SKILL-INJECT implementation','https://github.com/aisa-group/skill-inject','BENCHMARK_REPO','README_REVIEWED',['package','execution','audit'],
      '官方公开实现可用于有来源的攻击—良性任务匹配与既有基线比较。',
      '数据中有危险样本，不能把仓库直接加载为本机Skill；先只读隔离审计。',artifact_status='PUBLIC_REPO_VERIFIED_NOT_RUN'),
 card('T03','AgentDojo implementation','https://github.com/ethz-spylab/agentdojo','BENCHMARK_REPO','README_REVIEWED',['tool_boundary','execution','audit'],
      '官方任务环境可复用安全与正常任务效用的分离评分接口。',
      '尚未审查依赖与许可证适配；不宣称已运行或可替代原生宿主。',artifact_status='PUBLIC_REPO_VERIFIED_NOT_RUN'),
 card('T04','MaliciousSkillBench project page','https://protectskills.github.io/MaliciousSkillBench/','BENCHMARK_PROJECT','PROJECT_PAGE_REVIEWED',['package','audit'],
      '可追溯整合数据及来源/结构分组切分的官方入口。',
      '本轮没下载或执行载荷；访问页面不等于所有数据许可证和样本完整性通过。',artifact_status='PROJECT_PAGE_VERIFIED_NOT_RUN'),
 card('I01','Cisco: Personal AI Agents like OpenClaw Are a Security Nightmare','https://blogs.cisco.com/ai/personal-ai-agents-like-openclaw-are-a-security-nightmare','RESEARCHER_REPORT','SEARCH_AND_ARTICLE_SECTIONS_REVIEWED',['package','secrets','execution'],
      '研究者报告说明流行度和Skill供应链风险不能等同可信度，提供现实生态动机。',
      '单个研究者案例不是完整生态恶意比例；优先以原生版本和维护者边界确认实际影响。'),
]

SOURCES.extend([
 card('D08','OpenAI: Build skills — Codex invocation and loading','https://learn.chatgpt.com/docs/build-skills','RUNTIME_DOC','RELEVANT_SECTIONS_REVIEWED',['discovery','activation','update'],
      '官方页面描述显式/隐式调用、仓库/用户/管理/系统加载位置、同名Skill不合并，以及agents/openai.yaml中的调用策略和工具依赖。',
      '调用策略和依赖声明不是逐Skill权限沙箱保证；本轮没有检查Codex所有平台实现。',locator='How ChatGPT and Codex use skills; Where Codex loads local skills; Optional metadata'),
 paper('P22','Agent Skills Enable a New Class of Realistic and Trivially Simple Prompt Injections','2510.26328',['package','execution','authorization','secrets'],
       '早期直接研究Skill指令/脚本中的注入和任务批准被延伸到相邻有害动作；必须作为基础最近邻。',
       '泛称恶意SKILL.md、长文藏指令或一次批准后复用，并非2026年的全新问题。',artifact_url='https://github.com/aisa-group/promptinject-agent-skills'),
 paper('P23','Context Matters: Repository-Aware Security Analysis of the Agent Skill Ecosystem','2603.16572',['package','audit','governance'],
       '加入所属仓库上下文后重新判断可疑Skill，区分误报并研究废弃仓库劫持；版本v2标题与v1不同。',
       '“检测要加上下文”、泛化供应链劫持或重新计算扫描率都已有工作；remaining suspicious不是confirmed malicious。',version='v2',
       verified_venue='AgentSkills 2026 workshop at CAIS, Best Paper Award (author arXiv comments; not a main-track security-conference acceptance)'),
 paper('P24','GitSkills: A Dataset of Agent Skills on GitHub','2608.10906',['package','discovery','update','audit'],
       '以仓库、路径、内容hash和部分历史组织大规模Skill语料，可做去重和来源/版本分组取样的参考。',
       '数据体量不是安全标签；本轮未下载SQLite、未验证所有样本许可、不得自动执行其中代码。',version='v3',role='CORPUS_CANDIDATE',
       verified_venue='MSR 2027 to appear per author arXiv comments; not yet treated as a published proceedings record'),
])

NATIVE_OBSERVATIONS = [
 {'id':'N01','sources':['D01','D02','D04'],'observation':'同一SKILL.md规范并未定义统一的权限沙箱；不同宿主的激活、同意和权限生效方式明确不同。','status':'DOCUMENTED_SEMANTIC_DIFFERENCE','not_a_vulnerability_receipt':True},
 {'id':'N02','sources':['D02'],'observation':'技能内容与授权有不同生命周期，且动态上下文求值早于把内容发给模型。','status':'DOCUMENTED_STAGE_DIFFERENCE','not_a_vulnerability_receipt':True},
 {'id':'N03','sources':['D03','D06','D07','A02'],'observation':'密钥按宿主run注入是已说明的行为；源码已有引用计数和子进程过滤相关接口，不能再以无条件继承作为新颖性。','status':'CANDIDATE_DOWNGRADED_BY_SOURCE','not_a_vulnerability_receipt':True},
 {'id':'N04','sources':['A01'],'observation':'危险宿主环境变量注入为已修复历史公告，且攻击前提包含本地配置写权限。','status':'KNOWN_FIXED_ADVISORY','not_a_vulnerability_receipt':True},
]
