window.NAV_GROUPS = [
  { title:{en:"Next Paper",zh:"下一篇论文"}, open:true, pages:[
    ["paper-problem.html",{en:"Problem Formulation",zh:"问题定义"}],
    ["paper-ideas.html",{en:"Candidate Ideas",zh:"候选方向"}],
    ["paper-experiments.html",{en:"Benchmark & Experiments",zh:"基准与实验"}],
    ["paper-roadmap.html",{en:"Thesis & Roadmap",zh:"论文主线与路线图"}],
    ["review-log.html",{en:"Review & Iteration Log",zh:"评审与迭代记录"}],
  ]},
  { title:{en:"Foundations",zh:"基础"}, pages:[
    ["foundations.html",{en:"Definitions & History",zh:"定义与历史"}],
    ["taxonomy.html",{en:"Knowledge Map & Taxonomy",zh:"知识地图与分类"}],
  ]},
  { title:{en:"Evolution Mechanisms",zh:"进化机制"}, pages:[
    ["model-improvement.html",{en:"Foundation-model Improvement",zh:"基础模型更新"}],
    ["prompt-evolution.html",{en:"Prompt & Context Evolution",zh:"提示词与上下文进化"}],
    ["memory-evolution.html",{en:"Memory Evolution",zh:"记忆进化"}],
    ["tool-evolution.html",{en:"Tool & Skill Evolution",zh:"工具与技能进化"}],
    ["workflow-evolution.html",{en:"Workflow & Architecture",zh:"工作流与架构进化"}],
  ]},
  { title:{en:"Visual & Interactive Agents",zh:"视觉与交互 Agent"}, pages:[
    ["visual-multimodal.html",{en:"Visual & Multimodal",zh:"视觉与多模态"}],
    ["gui-web.html",{en:"GUI & Web Agents",zh:"GUI 与 Web Agent"}],
    ["embodied-world.html",{en:"Embodied Agents & World Models",zh:"具身 Agent 与世界模型"}],
  ]},
  { title:{en:"Evaluation & Reliability",zh:"评测与可靠性"}, pages:[
    ["evaluation-safety.html",{en:"Evaluation, Safety & Governance",zh:"评测、安全与治理"}],
    ["coverage-method.html",{en:"Coverage & Search Protocol",zh:"覆盖范围与检索协议"}],
  ]},
  { title:{en:"Resources",zh:"资源"}, pages:[
    ["bibliography.html",{en:"Live Bibliography",zh:"动态文献库"}],
    ["index.html",{en:"Observatory Home",zh:"研究站首页"}],
  ]},
];

window.SUPPLEMENTAL_PAPERS = [
  {year:2026,title:"Self-Improvements in Modern Agentic Systems: A Survey",venue:"arXiv",url:"https://arxiv.org/abs/2607.13104",repo:"https://github.com/selfimproving-agent/Awesome-Self-Improving-Agents",category:"Survey",subcategory:"System-level framework",updateTarget:"workflow/scaffold",signal:"experience and feedback",vision:false,source:"curated",summary:"Defines a foundation-model-plus-scaffold abstraction and organizes persistent self-improvement by update target and feedback signal.",summaryZh:"以“基础模型 + scaffold”为统一抽象，按更新对象和反馈信号组织持久自进化。"},
  {year:2025,title:"A Comprehensive Survey of Self-Evolving AI Agents: A New Paradigm Bridging Foundation Models and Lifelong Agentic Systems",venue:"arXiv",url:"https://arxiv.org/abs/2508.07407",category:"Survey",subcategory:"Lifelong agents",updateTarget:"workflow/scaffold",signal:"environment feedback",vision:false,source:"curated",summary:"Surveys the input-agent-environment-optimizer loop and domain-specific evolution strategies.",summaryZh:"从输入、Agent、环境与优化器闭环出发，梳理通用与领域化自进化策略。"},
  {year:2025,title:"A Survey of Self-Evolving Agents: What, When, How, and Where to Evolve",venue:"arXiv",url:"https://arxiv.org/abs/2507.21046",category:"Survey",subcategory:"Unified taxonomy",updateTarget:"workflow/scaffold",signal:"multiple feedback types",vision:false,source:"curated"},
  {year:2026,title:"Self-evolving Embodied AI",venue:"arXiv",url:"https://arxiv.org/abs/2602.04411",category:"Embodied",subcategory:"Embodiment adaptation",updateTarget:"world model",signal:"closed-loop interaction",vision:true,source:"curated",summary:"Separates memory updating, task switching, environment prediction, embodiment adaptation, and model evolution.",summaryZh:"把具身自进化拆分为记忆更新、任务切换、环境预测、具身适应与模型更新。"},
  {year:2026,title:"VisPlay: Self-Evolving Vision-Language Models",venue:"CVPR 2026",url:"https://openaccess.thecvf.com/content/CVPR2026/html/He_VisPlay_Self-Evolving_Vision-Language_Models_CVPR_2026_paper.html",category:"Visual & Multimodal",subcategory:"Questioner-solver self-play",updateTarget:"model parameters",signal:"difficulty and diversity rewards",vision:true,source:"curated",summary:"Jointly trains an image-conditioned questioner and multimodal reasoner on unlabeled images.",summaryZh:"在无标注图像上联合训练图像条件提问者与多模态推理器。"},
  {year:2026,title:"RISE: Reliable Improvement in Self-Evolving Vision-Language Models",venue:"arXiv",url:"https://arxiv.org/abs/2605.20914",repo:"https://github.com/AMAP-ML/RISE",category:"Visual & Multimodal",subcategory:"Reliable curriculum",updateTarget:"model parameters",signal:"quality supervision and skill balancing",vision:true,source:"curated"},
  {year:2026,title:"EvoGround: Self-Evolving Video Agents for Video Temporal Grounding",venue:"arXiv",url:"https://arxiv.org/abs/2605.13803",category:"Visual & Multimodal",subcategory:"Proposer-solver co-evolution",updateTarget:"model parameters",signal:"mutual reinforcement",vision:true,source:"curated"},
  {year:2026,title:"META: Meta Evolution of Tool Trajectory Adaptation for Long-Video Understanding",venue:"CVPR 2026",url:"https://openaccess.thecvf.com/content/CVPR2026/html/Huang_META_Meta_Evolution_of_Tool_Trajectory_Adaptation_for_Long-Video_Understanding_CVPR_2026_paper.html",category:"Visual & Multimodal",subcategory:"Macro-tool consolidation",updateTarget:"tool/skill",signal:"trajectory success and failure",vision:true,source:"curated"},
  {year:2026,title:"EvoGraph-R1: Self-Evolving Multimodal Knowledge Hypergraphs for Agentic Retrieval",venue:"CVPR 2026",url:"https://openaccess.thecvf.com/content/CVPR2026/html/Lin_EvoGraph-R1_Self-Evolving_Multimodal_Knowledge_Hypergraphs_for_Agentic_Retrieval_CVPR_2026_paper.html",category:"Visual & Multimodal",subcategory:"Dynamic GraphRAG",updateTarget:"memory",signal:"retrieval and graph-edit feedback",vision:true,source:"curated"},
  {year:2026,title:"JarvisEvo: Towards a Self-Evolving Photo Editing Agent with Synergistic Editor-Evaluator Optimization",venue:"CVPR 2026",url:"https://openaccess.thecvf.com/content/CVPR2026/html/Lin_JarvisEvo_Towards_a_Self-Evolving_Photo_Editing_Agent_with_Synergistic_Editor-Evaluator_CVPR_2026_paper.html",category:"Visual & Multimodal",subcategory:"Editor-evaluator co-optimization",updateTarget:"model parameters",signal:"self-evaluation",vision:true,source:"curated"},
  {year:2026,title:"OctoT2I: A Self-Evolving Agentic Text-to-Image Router",venue:"CVPR 2026",url:"https://openaccess.thecvf.com/content/CVPR2026/html/Jiang_OctoT2I_A_Self-Evolving_Agentic_Text-to-Image_Router_CVPR_2026_paper.html",category:"Visual & Multimodal",subcategory:"Tool capability discovery",updateTarget:"tool/skill",signal:"propose-solve-evaluate-learn",vision:true,source:"curated"},
  {year:2026,title:"VISTA: A Test-Time Self-Improving Video Generation Agent",venue:"CVPR 2026",url:"https://openaccess.thecvf.com/content/CVPR2026/html/Long_VISTA_A_Test-Time_Self-Improving_Video_Generation_Agent_CVPR_2026_paper.html",category:"Visual & Multimodal",subcategory:"Prompt refinement",updateTarget:"prompt",signal:"multi-agent critique",vision:true,source:"curated"},
  {year:2026,title:"OVOD-Agent: A Markov-Bandit Framework for Proactive Visual Reasoning and Self-Evolving Detection",venue:"CVPR 2026",url:"https://openaccess.thecvf.com/content/CVPR2026/html/Wang_OVOD-Agent_A_Markov-Bandit_Framework_for_Proactive_Visual_Reasoning_and_Self-Evolving_CVPR_2026_paper.html",category:"Visual & Multimodal",subcategory:"Detection query evolution",updateTarget:"prompt",signal:"bandit feedback",vision:true,source:"curated"},
  {year:2026,title:"Learning to Adapt: Self-Improving Web Agent via Cognitive-Aware Exploration",venue:"CVPR 2026",url:"https://openaccess.thecvf.com/content/CVPR2026/html/Chen_Learning_to_Adapt_Self-Improving_Web_Agent_via_Cognitive-Aware_Exploration_CVPR_2026_paper.html",category:"GUI & Web",subcategory:"Autonomous exploration",updateTarget:"model parameters",signal:"selector-predictor-judger feedback",vision:true,source:"curated"},
  {year:2026,title:"History to Future: Evolving Agent with Experience and Thought for Zero-shot Vision-and-Language Navigation",venue:"CVPR 2026",url:"https://openaccess.thecvf.com/content/CVPR2026/html/Dai_History_to_Future_Evolving_Agent_with_Experience_and_Thought_for_CVPR_2026_paper.html",category:"Embodied",subcategory:"Experience and future thought",updateTarget:"memory",signal:"navigation history",vision:true,source:"curated"},
  {year:2026,title:"VisualClaw: A Real-Time, Personalized Agent for the Physical World",venue:"arXiv",url:"https://arxiv.org/abs/2606.16295",category:"Visual & Multimodal",subcategory:"Streaming skill evolution",updateTarget:"tool/skill",signal:"failure-conditioned memory",vision:true,source:"curated"},
  {year:2025,title:"SE-VLN: A Self-Evolving Vision-Language Navigation Framework Based on Multimodal Large Language Models",venue:"arXiv",url:"https://arxiv.org/abs/2507.13152",category:"Embodied",subcategory:"Hierarchical memory",updateTarget:"memory",signal:"success and failure reflection",vision:true,source:"curated"},
  {year:2025,title:"Self-Evolving Visual Concept Library using Vision-Language Critics",venue:"CVPR 2025",url:"https://openaccess.thecvf.com/content/CVPR2025/html/Sehgal_Self-Evolving_Visual_Concept_Library_using_Vision-Language_Critics_CVPR_2025_paper.html",category:"Visual & Multimodal",subcategory:"Concept library evolution",updateTarget:"memory",signal:"VLM critique and downstream accuracy",vision:true,source:"curated"},
  {year:2025,title:"VISCO: Benchmarking Fine-Grained Critique and Correction towards Self-Improvement in Visual Reasoning",venue:"CVPR 2025",url:"https://openaccess.thecvf.com/content/CVPR2025/html/Wu_VISCO_Benchmarking_Fine-Grained_Critique_and_Correction_Towards_Self-Improvement_in_Visual_CVPR_2025_paper.html",category:"Visual & Multimodal",subcategory:"Visual critique",updateTarget:"prompt",signal:"fine-grained critique",vision:true,source:"curated"},
  {year:2025,title:"Critic-V: VLM Critics Help Catch VLM Errors in Multimodal Reasoning",venue:"CVPR 2025",url:"https://openaccess.thecvf.com/content/CVPR2025/html/Zhang_Critic-V_VLM_Critics_Help_Catch_VLM_Errors_in_Multimodal_Reasoning_CVPR_2025_paper.html",category:"Visual & Multimodal",subcategory:"Independent critic",updateTarget:"model parameters",signal:"critic supervision",vision:true,source:"curated"},
  {year:2025,title:"Can Large Vision-Language Models Correct Semantic Grounding Errors By Themselves?",venue:"CVPR 2025",url:"https://openaccess.thecvf.com/content/CVPR2025/html/Liao_Can_Large_Vision-Language_Models_Correct_Semantic_Grounding_Errors_By_Themselves_CVPR_2025_paper.html",category:"Visual & Multimodal",subcategory:"Grounding correction",updateTarget:"prompt",signal:"iterative self-correction",vision:true,source:"curated"},
  {year:2025,title:"Phoenix: A Motion-based Self-Reflection Framework for Fine-grained Robotic Action Correction",venue:"CVPR 2025",url:"https://openaccess.thecvf.com/content/CVPR2025/html/Xia_Phoenix_A_Motion-based_Self-Reflection_Framework_for_Fine-grained_Robotic_Action_Correction_CVPR_2025_paper.html",category:"Embodied",subcategory:"Action correction",updateTarget:"prompt",signal:"motion-conditioned reflection",vision:true,source:"curated"},
  {year:2024,title:"CLOVA: A Closed-Loop Visual Assistant with Tool Usage and Update",venue:"CVPR 2024",url:"https://openaccess.thecvf.com/content/CVPR2024/html/Gao_CLOVA_A_Closed-LOop_Visual_Assistant_with_Tool_Usage_and_Update_CVPR_2024_paper.html",category:"Visual & Multimodal",subcategory:"Visual tool update",updateTarget:"tool/skill",signal:"human feedback and reflection",vision:true,source:"curated"},
  {year:2024,title:"Self-Training Large Language Models for Improved Visual Program Synthesis with Visual Reinforcement",venue:"CVPR 2024",url:"https://openaccess.thecvf.com/content/CVPR2024/html/Khan_Self-Training_Large_Language_Models_for_Improved_Visual_Program_Synthesis_With_CVPR_2024_paper.html",category:"Visual & Multimodal",subcategory:"Visual program synthesis",updateTarget:"model parameters",signal:"task-derived visual reward",vision:true,source:"curated"},
  {year:2025,title:"Visual Agentic AI for Spatial Reasoning with a Dynamic API",venue:"CVPR 2025",url:"https://openaccess.thecvf.com/content/CVPR2025/html/Marsili_Visual_Agentic_AI_for_Spatial_Reasoning_with_a_Dynamic_API_CVPR_2025_paper.html",category:"Visual & Multimodal",subcategory:"Dynamic API",updateTarget:"tool/skill",signal:"execution correctness",vision:true,source:"curated"},
  {year:2025,title:"WebRL: Training LLM Web Agents via Self-Evolving Online Curriculum Reinforcement Learning",venue:"ICLR 2025",url:"https://proceedings.iclr.cc/paper_files/paper/2025/hash/c66e1fcc9691aae706250638f36f681b-Abstract-Conference.html",category:"GUI & Web",subcategory:"Online curriculum RL",updateTarget:"model parameters",signal:"environment reward",vision:true,source:"curated"},
  {year:2025,title:"Automated Design of Agentic Systems",venue:"ICLR 2025",url:"https://proceedings.iclr.cc/paper_files/paper/2025/hash/36b7acf6f6010652b3f2a433774a66fe-Abstract-Conference.html",category:"Workflow",subcategory:"Agent code search",updateTarget:"workflow/scaffold",signal:"archive-based performance",vision:false,source:"curated"},
  {year:2025,title:"AFlow: Automating Agentic Workflow Generation",venue:"ICLR 2025 Oral",url:"https://proceedings.iclr.cc/paper_files/paper/2025/hash/5492ecbce4439401798dcd2c90be94cd-Abstract-Conference.html",category:"Workflow",subcategory:"Workflow MCTS",updateTarget:"workflow/scaffold",signal:"execution feedback",vision:false,source:"curated"},
  {year:2025,title:"Multi-agent Architecture Search via Agentic Supernet",venue:"ICML 2025 Oral",url:"https://proceedings.mlr.press/v267/zhang25bi.html",category:"Workflow",subcategory:"Topology search",updateTarget:"workflow/scaffold",signal:"accuracy-cost objective",vision:false,source:"curated"},
  {year:2026,title:"EVE-Agent: Evidence-Verifiable Self-Evolving Agents",venue:"arXiv",url:"https://arxiv.org/abs/2605.22905",category:"Safety & Verification",subcategory:"Evidence verification",updateTarget:"model parameters",signal:"question-answer-evidence verification",vision:false,source:"curated"},
  {year:2026,title:"VASO: Formally Verifiable Self-Evolving Skills for Physical AI Agents",venue:"arXiv",url:"https://arxiv.org/abs/2606.05395",category:"Safety & Verification",subcategory:"Formal skill contracts",updateTarget:"tool/skill",signal:"counterexample traces",vision:true,source:"curated"},
  {year:2026,title:"Hidden Forgetting in Continual Multimodal Learning: When Accuracy Survives but Grounding Fails",venue:"arXiv",url:"https://arxiv.org/abs/2607.02020",category:"Evaluation",subcategory:"Evidence reliance",updateTarget:"model parameters",signal:"counterfactual interventions",vision:true,source:"curated"},
  {year:2026,title:"MemEye: Visual-Centric Evaluation for Multimodal Agent Memory",venue:"arXiv",url:"https://arxiv.org/abs/2605.15128",category:"Evaluation",subcategory:"Visual memory benchmark",updateTarget:"memory",signal:"visual evidence necessity",vision:true,source:"curated"},
  {year:2026,title:"MemLens: Benchmarking Multimodal Long-Term Memory",venue:"arXiv",url:"https://arxiv.org/abs/2605.14906",category:"Evaluation",subcategory:"Multi-session memory",updateTarget:"memory",signal:"visual evidence retention",vision:true,source:"curated"},
];

window.PAGE_CONTENT = {
"home":{
  eyebrow:{en:"Agent Self-Evolution Observatory",zh:"Agent 自进化研究站"},
  title:{en:"From retrying to learning: a mechanism-first map of self-evolving agents",zh:"从“多试几次”到“真正学会”：Agent 自进化机制地图"},
  lead:{en:"A bilingual, continuously synchronized research observatory covering foundation-model updates, prompts, memory, tools, workflows, visual agents, embodied systems, evaluation, and a CVPR-oriented paper workspace.",zh:"一个持续同步的双语研究站，覆盖基础模型更新、提示词、记忆、工具、工作流、视觉 Agent、具身系统、评测，以及面向 CVPR 的论文工作区。"},
  callout:{en:"Core rule: an agent is self-evolving only when experience is converted into a persistent update and the update is evaluated on future tasks. More retries, longer context, or a larger inference budget are not sufficient.",zh:"核心判据：只有当经验被转化为持久更新，并在未来任务上验证时，才称为 Agent 自进化。增加重试、上下文长度或推理预算并不充分。"},
  ideaCount:4,
  featured:[
    {href:"paper-problem.html",paper:true,title:{en:"Next Paper · Problem",zh:"下一篇论文 · 问题"},desc:{en:"Why unverified visual experience causes spurious self-evolution.",zh:"为什么未经验证的视觉经验会导致伪进化。"}},
    {href:"paper-ideas.html",paper:true,title:{en:"Candidate Ideas",zh:"候选方向"},desc:{en:"GroundEvo, EgoShift, ViMEvo, and MetaEvolve-V after collision review.",zh:"经过文献碰撞审查后的四个候选方向。"}},
    {href:"taxonomy.html",title:{en:"Knowledge Map",zh:"知识地图"},desc:{en:"Update target × feedback source × timescale × commitment gate.",zh:"更新对象 × 反馈来源 × 时间尺度 × 提交门控。"}},
    {href:"model-improvement.html",title:{en:"Foundation-model Improvement",zh:"基础模型更新"},desc:{en:"Self-generated demonstrations, self-reward, environment RL, and test-time learning.",zh:"自生成示范、自奖励、环境强化学习与测试时学习。"}},
    {href:"memory-evolution.html",title:{en:"Memory Evolution",zh:"记忆进化"},desc:{en:"Memory objects, structures, processing, consolidation, and contamination.",zh:"记忆对象、结构、处理、整合与污染。"}},
    {href:"visual-multimodal.html",title:{en:"Visual & Multimodal Agents",zh:"视觉与多模态 Agent"},desc:{en:"VLM self-play, video agents, visual tools, critics, editing, and generation.",zh:"VLM 自博弈、视频 Agent、视觉工具、critic、编辑与生成。"}},
    {href:"evaluation-safety.html",title:{en:"Evaluation & Reliability",zh:"评测与可靠性"},desc:{en:"Persistent gain, transfer, forgetting, harmful updates, cost, and autonomy.",zh:"持久收益、迁移、遗忘、有害更新、成本与自主性。"}},
    {href:"bibliography.html",title:{en:"Live Bibliography",zh:"动态文献库"},desc:{en:"Live synchronization with the survey-maintained Awesome list plus a curated visual supplement.",zh:"实时同步综述配套 Awesome 列表，并补充人工核验的视觉论文。"}},
  ],
  sections:[
    {title:{en:"What this observatory adds",zh:"这个研究站解决什么"},body:{en:`<div class="property-grid"><div class="property-card"><b>Strict scope</b><span>Separates self-correction, test-time search, scaffold evolution, and parameter evolution.</span></div><div class="property-card"><b>Mechanism-first taxonomy</b><span>Classifies the committed update instead of trusting the word “evolving” in a title.</span></div><div class="property-card"><b>Living coverage</b><span>Synchronizes the survey-maintained catalog and deduplicates a CVPR-focused visual supplement.</span></div><div class="property-card"><b>Paper workspace</b><span>Tracks idea collisions, falsifiable hypotheses, experiments, stop conditions, and reviewer objections.</span></div></div>`,zh:`<div class="property-grid"><div class="property-card"><b>严格范围</b><span>区分自纠错、测试时搜索、scaffold 进化与参数进化。</span></div><div class="property-card"><b>机制优先分类</b><span>依据实际提交的更新分类，而不是相信标题中的 evolving。</span></div><div class="property-card"><b>动态覆盖</b><span>同步综述维护的文献目录，并与面向 CVPR 的视觉补充集去重。</span></div><div class="property-card"><b>论文工作区</b><span>记录 idea 碰撞、可证伪假设、实验、停止条件与审稿质疑。</span></div></div>`}},
    {title:{en:"Recommended reading paths",zh:"推荐阅读路径"},body:{en:`<table class="matrix"><thead><tr><th>Goal</th><th>Path</th></tr></thead><tbody><tr><td>Understand the field</td><td>Definitions → Taxonomy → Mechanism pages → Evaluation</td></tr><tr><td>Prepare a CVPR paper</td><td>Problem → Candidate Ideas → Experiments → Roadmap → Review Log</td></tr><tr><td>Find a specific method</td><td>Use the top search box or the live bibliography filters</td></tr><tr><td>Audit completeness</td><td>Coverage & Search Protocol → Bibliography → Review Log</td></tr></tbody></table>`,zh:`<table class="matrix"><thead><tr><th>目标</th><th>路径</th></tr></thead><tbody><tr><td>理解领域</td><td>定义 → 分类 → 各机制页面 → 评测</td></tr><tr><td>准备 CVPR 论文</td><td>问题 → 候选方向 → 实验 → 路线图 → 评审记录</td></tr><tr><td>查找具体方法</td><td>使用顶部检索或动态文献库筛选器</td></tr><tr><td>核查覆盖完整性</td><td>覆盖与检索协议 → 文献库 → 评审记录</td></tr></tbody></table>`}}
  ]
},
"foundations":{
  eyebrow:{en:"Foundations · Definitions",zh:"基础 · 定义"},
  title:{en:"What counts as agent self-evolution?",zh:"什么才算 Agent 自进化？"},
  lead:{en:"A precise boundary between inference-time correction, persistent scaffold updates, parameter learning, continual adaptation, and open-ended recursive improvement.",zh:"严格区分推理时纠错、持久 scaffold 更新、参数学习、持续适应与开放式递归改进。"},
  callout:{en:"The independent unit is the committed agent version. A better answer after another retry is evidence of search; a reusable change that improves later tasks is evidence of evolution.",zh:"独立单位是“已提交的 Agent 版本”。多重试一次得到更好答案，只证明搜索；可复用变化在后续任务上继续有效，才证明进化。"},
  sections:[
    {title:{en:"Formal abstraction",zh:"形式化抽象"},body:{en:`<div class="equation">A_t = (M_t, P_t, \mathcal{M}_t, \mathcal{T}_t, W_t, R_t)</div><p>An agent version contains a foundation model <em>M</em>, prompts or policies <em>P</em>, memory <em>𝓜</em>, tools and skills <em>𝓣</em>, workflow/control logic <em>W</em>, and evaluators or rewards <em>R</em>. Experience <em>E_t</em> is converted by an update operator:</p><div class="equation">A_{t+1}=U(A_t,E_t), \qquad \Delta_{future}=J(A_{t+1};D_{future})-J(A_t;D_{future}).</div><p>Self-evolution requires a nontrivial committed update and evaluation on future or held-out tasks. The update may affect model parameters or scaffold components.</p>`,zh:`<div class="equation">A_t = (M_t, P_t, \mathcal{M}_t, \mathcal{T}_t, W_t, R_t)</div><p>一个 Agent 版本由基础模型 <em>M</em>、提示词或策略 <em>P</em>、记忆 <em>𝓜</em>、工具与技能 <em>𝓣</em>、工作流或控制逻辑 <em>W</em>、评价器或奖励 <em>R</em> 构成。经验 <em>E_t</em> 经更新算子转化：</p><div class="equation">A_{t+1}=U(A_t,E_t), \qquad \Delta_{future}=J(A_{t+1};D_{future})-J(A_t;D_{future}).</div><p>自进化要求发生非平凡的持久更新，并在未来或留出任务上验证。更新可以作用于模型参数，也可以作用于 scaffold。</p>`}},
    {title:{en:"Five neighboring concepts",zh:"五个相邻概念"},body:{en:`<table class="matrix"><thead><tr><th>Concept</th><th>Persistent update?</th><th>Future-task evidence?</th><th>Recommended label</th></tr></thead><tbody><tr><td>Retry / beam search / tree search</td><td>No</td><td>No</td><td>Inference-time search</td></tr><tr><td>Self-critique followed by one revised answer</td><td>Usually no</td><td>No</td><td>Self-correction</td></tr><tr><td>Writing reusable experience or skills</td><td>Yes</td><td>Required</td><td>Scaffold evolution</td></tr><tr><td>SFT, DPO, RL, LoRA, or online adaptation</td><td>Yes</td><td>Required</td><td>Model evolution</td></tr><tr><td>Agent rewrites its optimizer or source code</td><td>Yes</td><td>Required plus safety gate</td><td>Recursive / open-ended evolution</td></tr></tbody></table>`,zh:`<table class="matrix"><thead><tr><th>概念</th><th>持久更新？</th><th>后续任务证据？</th><th>推荐称呼</th></tr></thead><tbody><tr><td>重试、束搜索、树搜索</td><td>否</td><td>否</td><td>推理时搜索</td></tr><tr><td>自我批评后重答一次</td><td>通常否</td><td>否</td><td>自纠错</td></tr><tr><td>写入可复用经验或技能</td><td>是</td><td>必须</td><td>Scaffold 进化</td></tr><tr><td>SFT、DPO、RL、LoRA 或在线适应</td><td>是</td><td>必须</td><td>模型进化</td></tr><tr><td>Agent 重写优化器或源代码</td><td>是</td><td>必须且需安全门控</td><td>递归／开放式进化</td></tr></tbody></table>`}},
    {title:{en:"Historical progression",zh:"历史演化"},body:{en:`<div class="timeline"><div class="timeline-item"><b>2022–2023</b><span>Self-generated instructions, verbal reflection, external-tool critique, and early open-ended skill libraries.</span></div><div class="timeline-item"><b>2024</b><span>Prompt optimizers, textual gradients, agent graphs, automatic agent design, visual tool update, and self-updatable memory.</span></div><div class="timeline-item"><b>2025</b><span>Online curriculum RL, workflow search, co-evolving world models, memory systems, GUI/web learning, and broad domain specialization.</span></div><div class="timeline-item"><b>2026</b><span>VLM self-play, visual causal evaluation, self-evolving skills, recursive harnesses, multimodal memory benchmarks, and formal verification.</span></div></div>`,zh:`<div class="timeline"><div class="timeline-item"><b>2022–2023</b><span>自生成指令、语言反思、外部工具批评，以及早期开放式技能库。</span></div><div class="timeline-item"><b>2024</b><span>提示词优化器、文本梯度、Agent 图、自动 Agent 设计、视觉工具更新与可自更新记忆。</span></div><div class="timeline-item"><b>2025</b><span>在线课程 RL、工作流搜索、共进化世界模型、记忆系统、GUI/Web 学习与领域化应用。</span></div><div class="timeline-item"><b>2026</b><span>VLM 自博弈、视觉因果评测、自进化技能、递归 harness、多模态记忆基准与形式化验证。</span></div></div>`}},
    {title:{en:"Minimum evidence for a valid claim",zh:"有效主张的最低证据"},body:{en:`<ol><li>Specify exactly which component changed.</li><li>Freeze a pre-update baseline and matched inference budget.</li><li>Evaluate later tasks that were not used to select the update.</li><li>Report forward transfer, backward transfer, worst-case regression, and cost.</li><li>Separate model-level replication from repeated prompts or generations.</li><li>Document external teachers, human labels, environment resets, and hidden APIs.</li></ol>`,zh:`<ol><li>明确说明更新了哪个组件。</li><li>冻结更新前基线，并匹配推理预算。</li><li>在未用于选择更新的后续任务上评测。</li><li>报告前向迁移、后向迁移、最坏回退与成本。</li><li>区分独立模型复现与重复提示／重复生成。</li><li>记录外部教师、人类标签、环境重置与隐藏 API。</li></ol>`}}
  ]
},
"taxonomy":{
  eyebrow:{en:"Foundations · Knowledge Map",zh:"基础 · 知识地图"},
  title:{en:"A four-axis taxonomy of self-evolving agents",zh:"Agent 自进化的四轴分类体系"},
  lead:{en:"Flat labels such as reflection, memory, or RL mix together different scientific questions. The map separates what changes, what drives it, when it changes, and how the change is accepted.",zh:"反思、记忆或 RL 等平面标签混合了不同科学问题。知识地图分别描述更新什么、由什么驱动、何时更新，以及如何接受更新。"},
  sections:[
    {title:{en:"Axis I · Update surface",zh:"轴一 · 更新对象"},body:{en:`<table class="matrix"><thead><tr><th>Surface</th><th>Typical mechanisms</th><th>Main failure</th></tr></thead><tbody><tr><td>Foundation-model parameters</td><td>SFT, DPO, RL, LoRA, model merging, test-time learning</td><td>Forgetting, reward hacking, high cost</td></tr><tr><td>Prompt and context</td><td>OPRO, textual gradients, reflection, population search</td><td>Benchmark overfitting, context bloat</td></tr><tr><td>Memory</td><td>Experience rules, graphs, consolidation, parametric memory</td><td>Pollution, staleness, retrieval failure</td></tr><tr><td>Tools and skills</td><td>Routing, refinement, macro-tools, autonomous creation</td><td>Unsafe code, incompatibility, skill explosion</td></tr><tr><td>Workflow and architecture</td><td>Agent graph search, MCTS, topology search, source rewriting</td><td>Search cost, evaluator overfitting</td></tr><tr><td>World / embodiment model</td><td>Predictive models, calibration, dynamics adaptation</td><td>Model bias, unsafe exploration</td></tr></tbody></table>`,zh:`<table class="matrix"><thead><tr><th>更新对象</th><th>典型机制</th><th>主要失败</th></tr></thead><tbody><tr><td>基础模型参数</td><td>SFT、DPO、RL、LoRA、模型合并、测试时学习</td><td>遗忘、奖励投机、成本高</td></tr><tr><td>提示词与上下文</td><td>OPRO、文本梯度、反思、种群搜索</td><td>基准过拟合、上下文膨胀</td></tr><tr><td>记忆</td><td>经验规则、图结构、整合、参数化记忆</td><td>污染、过期、检索失败</td></tr><tr><td>工具与技能</td><td>路由、改进、宏工具、自动创建</td><td>不安全代码、不兼容、技能爆炸</td></tr><tr><td>工作流与架构</td><td>Agent 图搜索、MCTS、拓扑搜索、源码重写</td><td>搜索成本、评价器过拟合</td></tr><tr><td>世界／具身模型</td><td>预测模型、标定、动力学适应</td><td>模型偏差、不安全探索</td></tr></tbody></table>`}},
    {title:{en:"Axis II · Learning signal",zh:"轴二 · 学习信号"},body:{en:`<div class="property-grid"><div class="property-card"><b>Intrinsic generation</b><span>Self-generated instructions, questions, demonstrations, traces, or synthetic tasks.</span></div><div class="property-card"><b>Intrinsic evaluation</b><span>Self-reward, critique, uncertainty, consistency, debate, or learned judges.</span></div><div class="property-card"><b>Extrinsic environment</b><span>Task success, tests, simulators, websites, robots, games, and tools.</span></div><div class="property-card"><b>Population feedback</b><span>Peer agents, tournaments, quality-diversity archives, and co-evolving evaluators.</span></div><div class="property-card"><b>Human or provider feedback</b><span>Labels, preferences, demonstrations, policies, and private telemetry.</span></div><div class="property-card"><b>Counterfactual verification</b><span>Intervene on evidence or state to test whether a proposed lesson is causal.</span></div></div>`,zh:`<div class="property-grid"><div class="property-card"><b>内生生成</b><span>自生成指令、问题、示范、轨迹或合成任务。</span></div><div class="property-card"><b>内生评价</b><span>自奖励、批评、不确定性、一致性、辩论或学习型评价器。</span></div><div class="property-card"><b>外部环境</b><span>任务成功、测试、模拟器、网站、机器人、游戏和工具。</span></div><div class="property-card"><b>群体反馈</b><span>同伴 Agent、锦标赛、质量多样性档案与共进化评价器。</span></div><div class="property-card"><b>人类或提供方反馈</b><span>标签、偏好、示范、政策与私有遥测。</span></div><div class="property-card"><b>反事实验证</b><span>干预证据或状态，检验拟写入经验是否具有因果作用。</span></div></div>`}},
    {title:{en:"Axis III · Timescale",zh:"轴三 · 时间尺度"},body:{en:`<table class="matrix"><thead><tr><th>Timescale</th><th>State lifetime</th><th>Correct evaluation</th></tr></thead><tbody><tr><td>Intra-episode</td><td>Current context only</td><td>Self-correction, not persistent evolution</td></tr><tr><td>Inter-episode</td><td>Reusable memory or skill</td><td>Future tasks in the same stream</td></tr><tr><td>Offline iteration</td><td>New checkpoint or scaffold release</td><td>Untouched development and test sets</td></tr><tr><td>Online continual</td><td>Repeated commits after deployment</td><td>Longitudinal transfer and forgetting</td></tr><tr><td>Open-ended recursive</td><td>Update rule or source code changes</td><td>Held-out selection, safety constraints, and provenance</td></tr></tbody></table>`,zh:`<table class="matrix"><thead><tr><th>时间尺度</th><th>状态寿命</th><th>正确评测</th></tr></thead><tbody><tr><td>单回合内</td><td>仅当前上下文</td><td>自纠错，不是持久进化</td></tr><tr><td>跨回合</td><td>可复用记忆或技能</td><td>同一任务流中的后续任务</td></tr><tr><td>离线迭代</td><td>新检查点或 scaffold 版本</td><td>未触碰的开发集和测试集</td></tr><tr><td>在线持续</td><td>部署后反复提交</td><td>纵向迁移与遗忘</td></tr><tr><td>开放式递归</td><td>更新规则或源码变化</td><td>留出选择、安全约束与溯源</td></tr></tbody></table>`}},
    {title:{en:"Axis IV · Commitment gate",zh:"轴四 · 提交门控"},body:{en:`<div class="steps"><div class="step"><b>Validity</b><p>Is the artifact executable, syntactically valid, and compatible with the current agent?</p></div><div class="step"><b>Activation</b><p>Does the proposed update change behavior on the cases it claims to address?</p></div><div class="step"><b>Significance</b><p>Does the gain survive matched budgets, repeated seeds, and hard controls?</p></div><div class="step"><b>Generalization</b><p>Does it improve future tasks rather than only the development trajectory?</p></div><div class="step"><b>Safety and rollback</b><p>Do old-task, evidence-reliance, and policy probes remain within limits?</p></div></div>`,zh:`<div class="steps"><div class="step"><b>有效性</b><p>更新产物是否可执行、语法正确，并与当前 Agent 兼容？</p></div><div class="step"><b>激活性</b><p>拟议更新是否确实改变了它声称解决的行为？</p></div><div class="step"><b>显著性</b><p>收益能否经受预算匹配、重复随机种子和困难对照？</p></div><div class="step"><b>泛化性</b><p>是否改进未来任务，而不是只改进开发轨迹？</p></div><div class="step"><b>安全与回滚</b><p>旧任务、证据依赖和政策探针是否仍在允许范围内？</p></div></div>`}}
  ]
},

};
