window.RESEARCH_DIRECTIONS = [
  {
    id:"experience-admission", code:"D1", color:"#5b5bd6",
    title:{en:"Experience acquisition, admission, and scope",zh:"经验获取、准入与适用范围"},
    question:{en:"Which experiences deserve persistent learning, what caused the outcome, and where does the learned lesson remain valid?",zh:"哪些经验值得持久学习、结果由什么因素造成，以及学到的经验在什么范围内仍然成立？"},
    boundary:{en:"The update candidate is the scientific object; memory representation and downstream security are evaluated separately.",zh:"科学对象是候选经验及其准入；记忆表示和下游安全在其他方向中单独研究。"},
    ideaIds:["GroundEvo-Admission","ScopeGuard-V","EvoValue-V","ProcessCredit-V"]
  },
  {
    id:"memory-lifecycle", code:"D2", color:"#2f6fd6",
    title:{en:"Memory representation, repair, and consolidation",zh:"记忆表示、修复与巩固"},
    question:{en:"What form should an experience take, when should it be revised or promoted, and what can be safely removed?",zh:"经验应以何种形式保存、何时修订或晋升，以及哪些内容可以安全删除？"},
    boundary:{en:"Focuses on persistent memory objects and operations, not generic long-context retrieval.",zh:"聚焦持久记忆对象及其操作，而不是通用长上下文检索。"},
    ideaIds:["ViMEvo-Repair","MemoryFormRouter-V","MultiRateEvo-V","EvoGC-X"]
  },
  {
    id:"skill-tool-lifecycle", code:"D3", color:"#087e5b",
    title:{en:"Skill, tool, and permission lifecycle",zh:"技能、工具与权限生命周期"},
    question:{en:"How should reusable capabilities be verified, repaired, retired, and re-authorized as they evolve?",zh:"可复用能力在进化过程中应如何验证、修复、退役并重新授权？"},
    boundary:{en:"The reusable executable artifact and its capability version are the unit of analysis.",zh:"分析单位是可复用可执行产物及其能力版本。"},
    ideaIds:["SkillProof-V","SkillUnlearn-V","CapabilityLease-Evo"]
  },
  {
    id:"system-composition", code:"D4", color:"#7c4dcc",
    title:{en:"Update routing, contracts, and composition",zh:"更新路由、语义契约与组合"},
    question:{en:"Which component should change, and can independently valid updates still work together?",zh:"应更新哪个组件，以及单独有效的更新能否在组合后继续成立？"},
    boundary:{en:"Targets cross-component semantics and update interaction rather than one component's local quality.",zh:"研究跨组件语义与更新交互，而不是某个组件的局部质量。"},
    ideaIds:["EvoContract-V","InteractionGuard-V","UpdateRoute-V"]
  },
  {
    id:"embodied-world", code:"D5", color:"#c56a1a",
    title:{en:"Embodiment, exploration, and world adaptation",zh:"具身、探索与世界适应"},
    question:{en:"How should an agent diagnose changing sensors, bodies, state, dynamics, and environment structure?",zh:"Agent 应如何诊断变化中的传感器、身体、状态、动力学与环境结构？"},
    boundary:{en:"Visual interaction or embodiment must be indispensable to the main claim.",zh:"核心主张必须不可替代地依赖视觉交互或具身。"},
    ideaIds:["EgoShift","ExploreRepair-V","WorldPatch-V","SimEvo-CF"]
  },
  {
    id:"negative-evaluation", code:"D6", color:"#a12f42",
    title:{en:"Negative evolution evaluation and benchmark science",zh:"负向进化评测与基准科学"},
    question:{en:"Which harmful or misleading evolutionary changes are hidden by average task success?",zh:"哪些有害或误导性的进化变化会被平均任务成功率掩盖？"},
    boundary:{en:"Produces longitudinal measurements, controlled failure taxonomies, and evaluator stress tests.",zh:"产出纵向测量、受控失败分类与评价器压力测试。"},
    ideaIds:["NegEvoBench-V","RelianceGuard-V","AuditInvariant-Evo","EvalRedQueen-V"]
  },
  {
    id:"security-provenance", code:"D7", color:"#b54708",
    title:{en:"Security, provenance, and risk propagation",zh:"安全、溯源与风险传播"},
    question:{en:"How do poisoned, uncertain, or harmful updates propagate through artifacts, versions, and agent populations?",zh:"投毒、不确定或有害更新如何沿产物、版本和 Agent 群体传播？"},
    boundary:{en:"Covers the complete persistent-update supply chain from evidence to descendants.",zh:"覆盖从来源证据到后代版本的完整持久更新供应链。"},
    ideaIds:["AmplificationGuard-X","EvoFirewall-V","ConfidenceFlow-Evo","EvoProvenance-V"]
  },
  {
    id:"governance-control", code:"D8", color:"#8a5300",
    title:{en:"Cost, oversight, and meta-control",zh:"成本、监督与元控制"},
    question:{en:"How should finite compute and human attention be allocated, and when should evolution stop or escalate?",zh:"有限算力与人工注意力应如何分配，以及进化何时停止或升级？"},
    boundary:{en:"The evolution controller and its resource policy are the scientific objects.",zh:"科学对象是进化控制器及其资源策略。"},
    ideaIds:["BudgetEvolve-V","OversightBudget-Evo","MetaGuard-V"]
  },
  {
    id:"adaptive-objectives", code:"D9", color:"#0f7780",
    title:{en:"Goals, personalization, and performative feedback",zh:"目标、个性化与内生反馈"},
    question:{en:"How should goals and user models evolve when the agent's own deployment changes future data?",zh:"当 Agent 的部署本身改变未来数据时，目标和用户模型应如何进化？"},
    boundary:{en:"Separates external drift, user drift, goal refinement, and agent-induced distribution change.",zh:"区分外部漂移、用户漂移、目标细化与 Agent 自致分布变化。"},
    ideaIds:["GoalGuard-Evo","PersonaShift-V","PerformativeEvo-V"]
  },
  {
    id:"collective-evolution", code:"D10", color:"#4b6b88",
    title:{en:"Cross-agent transfer and plural lineages",zh:"跨 Agent 迁移与复数谱系"},
    question:{en:"When should experiences or versions be shared, branched, routed, merged, or retired across heterogeneous agents?",zh:"异构 Agent 之间的经验或版本何时应共享、分支、路由、合并或退役？"},
    boundary:{en:"Studies persistent collective evolution rather than one-shot multi-agent voting.",zh:"研究持久的群体进化，而不是一次性多 Agent 投票。"},
    ideaIds:["CrossAgentTransfer-V","PluralLineage-Evo"]
  }
];

window.PAPER_IDEAS = [
  {name:"NegEvoBench-V",directionId:"negative-evaluation",rank:1,score:91.2,confidence:"H",track:{en:"Benchmark",zh:"基准"},
   thesis:{en:"Build a controlled benchmark for harmful visual self-evolution that ordinary accuracy and forgetting metrics fail to expose.",zh:"构建受控的有害视觉自进化基准，暴露普通准确率与遗忘指标遗漏的失败。"},
   experiment:{en:"Create ordered GUI/visual task streams with stale, poisoned, shortcut, evaluator-error, delayed-debt, permission-drift, and lineage-amplification updates; evaluate every committed version.",zh:"构造包含过期、投毒、捷径、评价器错误、延迟技术债、权限漂移和谱系放大的有序 GUI／视觉任务流，并评测每个已提交版本。"},
   baseline:{en:"SEA-Eval-style longitudinal metrics, continual-learning forgetting, old-task replay, attack-success rate, and standard safety benchmarks.",zh:"SEA-Eval 类纵向指标、持续学习遗忘、旧任务回放、攻击成功率和标准安全基准。"},
   go:{en:"The benchmark reveals frequent, reproducible failures hidden by existing aggregate metrics.",zh:"基准能够稳定复现现有聚合指标遗漏的失败。"},stop:{en:"Existing longitudinal and safety metrics already capture all injected failures.",zh:"现有纵向和安全指标已能捕获全部注入失败。"}},
  {name:"ScopeGuard-V",directionId:"experience-admission",rank:2,score:89.6,confidence:"H",track:{en:"Visual method",zh:"视觉方法"},
   thesis:{en:"Estimate the visual and state-space region in which an accepted lesson remains valid, rather than treating admission as universal applicability.",zh:"估计被接受经验在视觉与状态空间中的有效区域，而不是把准入等同于普遍适用。"},
   experiment:{en:"Generate contrastive GUI layouts, views, object states, temporal expiry, and near-boundary cases around each accepted lesson; learn calibrated applicability sets.",zh:"围绕每条被接受经验生成对比 GUI 布局、视角、物体状态、时间到期和近边界样本，并学习校准的适用集合。"},
   baseline:{en:"Confidence thresholding, nearest-neighbor applicability, skill preconditions, and ordinary OOD detection.",zh:"置信度阈值、最近邻适用性、技能前置条件和普通 OOD 检测。"},
   go:{en:"Scope-aware commits reduce harmful overgeneralization at matched positive transfer.",zh:"在匹配正迁移收益下，范围感知提交显著减少有害过度泛化。"},stop:{en:"Simple confidence or precondition baselines match the method.",zh:"简单置信度或前置条件基线与方法持平。"}},
  {name:"GroundEvo-Admission",directionId:"experience-admission",rank:3,score:89.1,confidence:"H",track:{en:"Visual method",zh:"视觉方法"},
   thesis:{en:"Verify an interactive visual causal path before allowing one self-generated lesson to enter persistent memory.",zh:"在允许一条自生成经验进入持久记忆前，验证其交互式视觉因果路径。"},
   experiment:{en:"Use frozen VLM agents in controlled GUI tasks; generate minimal region, state, and layout counterfactuals and compare admission decisions with future-task outcomes.",zh:"在受控 GUI 任务中使用冻结 VLM Agent，生成最小区域、状态和布局反事实，并比较准入决策与后续任务结果。"},
   baseline:{en:"Outcome-only gates, self-critics, independent VLM critics, EVE-style evidence gates, and random replay.",zh:"仅结果门控、自 critic、独立 VLM critic、EVE 类证据门控和随机重放。"},
   go:{en:"Higher lesson precision and lower harmful commits under matched verification cost.",zh:"在匹配验证成本下获得更高经验精度与更低有害提交率。"},stop:{en:"Counterfactuals cannot isolate causal visual factors or do not improve future tasks.",zh:"反事实无法隔离视觉因果因素，或不能改善后续任务。"}},
  {name:"AmplificationGuard-X",directionId:"security-provenance",rank:4,score:88.4,confidence:"M",track:{en:"Security",zh:"安全"},
   thesis:{en:"Measure and control the reproduction factor of one harmful update across descendant versions and sharing populations.",zh:"测量并控制一个有害更新在后代版本和共享群体中的复制因子。"},
   experiment:{en:"Seed bounded memory, tool, or adapter defects and trace ten evolution rounds over controlled version and agent-sharing graphs.",zh:"植入有界的记忆、工具或 Adapter 缺陷，在受控版本图和 Agent 共享图中追踪十轮进化。"},
   baseline:{en:"Source filtering, provenance-only tracing, local rollback, graph quarantine, and no-sharing controls.",zh:"来源过滤、仅溯源追踪、局部回滚、图隔离和不共享对照。"},
   go:{en:"Containment lowers amplification and blast radius while preserving benign transfer.",zh:"遏制机制在保留良性迁移的同时降低放大因子和影响半径。"},stop:{en:"Local filtering or provenance predicts and prevents all propagation.",zh:"局部过滤或溯源已能预测并阻止全部传播。"}},
  {name:"EvoContract-V",directionId:"system-composition",rank:5,score:87.8,confidence:"H",track:{en:"Systems",zh:"系统"},
   thesis:{en:"Detect semantic incompatibility after tools, memories, planners, or models evolve independently while their schemas remain valid.",zh:"检测工具、记忆、规划器或模型独立进化后出现的语义不兼容，即使 schema 仍然有效。"},
   experiment:{en:"Inject silent changes in coordinates, units, ordering, side effects, grounding semantics, and tool assumptions; localize the broken dependency edge.",zh:"注入坐标、单位、顺序、副作用、grounding 语义和工具假设的静默变化，并定位损坏的依赖边。"},
   baseline:{en:"Schema validation, unit tests, end-to-end regression tests, version pinning, and full rollback.",zh:"Schema 验证、单元测试、端到端回归测试、版本固定和整体回滚。"},
   go:{en:"Executable contracts localize failures and targeted migration restores performance more cheaply than rollback.",zh:"可执行契约能够定位失败，且定向迁移比整体回滚更低成本地恢复性能。"},stop:{en:"Ordinary regression tests catch every semantic shift.",zh:"普通回归测试已捕获全部语义变化。"}},
  {name:"ViMEvo-Repair",directionId:"memory-lifecycle",rank:6,score:87.2,confidence:"H",track:{en:"Visual memory",zh:"视觉记忆"},
   thesis:{en:"Maintain visual evidence freshness by revising stale crops, frames, and object-state transitions instead of only retrieving old summaries.",zh:"通过修订过期裁剪、帧和物体状态变化保持视觉证据新鲜，而不是只检索旧摘要。"},
   experiment:{en:"Run multi-session GUI tasks with controlled interface and object-state changes; compare visual-text memory repair against static memory.",zh:"在受控界面和物体状态变化下运行多会话 GUI 任务，比较视觉—文本记忆修复与静态记忆。"},
   baseline:{en:"Long context, text-only memory, multimodal vector retrieval, recency replacement, and full re-observation.",zh:"长上下文、仅文本记忆、多模态向量检索、近期替换和完整重观察。"},
   go:{en:"Repair improves future-task performance and evidence fidelity at equal storage and query cost.",zh:"在相同存储和查询成本下，修复提升后续任务表现与证据保真度。"},stop:{en:"Visual evidence adds no value over text or ordinary retrieval.",zh:"视觉证据相较文本或普通检索没有额外价值。"}},
  {name:"RelianceGuard-V",directionId:"negative-evaluation",rank:7,score:86.6,confidence:"H",track:{en:"Visual reliability",zh:"视觉可靠性"},
   thesis:{en:"Ensure that a successful update preserves dependence on causal visual regions or frames rather than shifting to shortcuts.",zh:"确保成功更新仍依赖因果视觉区域或帧，而不是转向捷径。"},
   experiment:{en:"Update memory or LoRA under shortcut-confounded visual tasks and evaluate region/frame counterfactual reliance before and after each commit.",zh:"在捷径混杂视觉任务中更新记忆或 LoRA，并在每次提交前后评测区域／帧反事实依赖。"},
   baseline:{en:"Accuracy-only release gates, saliency consistency, hidden-forgetting metrics, and adversarial robustness tests.",zh:"仅准确率发布门控、显著图一致性、隐性遗忘指标和对抗鲁棒性测试。"},
   go:{en:"Matched task accuracy with substantially stronger causal evidence reliance and fewer hidden regressions.",zh:"在匹配任务准确率下显著提高因果证据依赖并减少隐性回退。"},stop:{en:"Reliance drift is rare or inseparable from ordinary accuracy changes.",zh:"证据依赖漂移很少，或无法与普通准确率变化分离。"}},
  {name:"CapabilityLease-Evo",directionId:"skill-tool-lifecycle",rank:8,score:85.2,confidence:"M",track:{en:"Security / systems",zh:"安全／系统"},
   thesis:{en:"Bind authorization to a capability version, scope, and expiry so evolved tools and skills cannot retain stale permissions.",zh:"将授权绑定到能力版本、范围和到期时间，防止进化后的工具与技能保留过期权限。"},
   experiment:{en:"Evolve tool and skill capabilities across versions, task domains, and permission-creep attacks; require renewal, shrinkage, or revocation decisions.",zh:"在版本、任务领域和权限膨胀攻击中进化工具与技能能力，并要求做续租、收缩或撤销决策。"},
   baseline:{en:"Static RBAC, allowlists, pre-action authorization, signed capability manifests, and version pinning.",zh:"静态 RBAC、白名单、动作前授权、签名能力清单和版本固定。"},
   go:{en:"Leases prevent capability creep with low false denial and limited oversight cost.",zh:"租约机制以较低误拒绝和监督成本阻止能力越权。"},stop:{en:"Static policies plus pre-action checks match the method.",zh:"静态策略加动作前检查与方法持平。"}},
  {name:"EvoFirewall-V",directionId:"security-provenance",rank:9,score:84.7,confidence:"H",track:{en:"Security",zh:"安全"},
   thesis:{en:"Protect the complete evolution channel from write through retrieval, composition, activation, and action.",zh:"保护从写入、检索、组合、激活到行动的完整进化通道。"},
   experiment:{en:"Use direct, compositional, sleeper, and cross-session poisoning with quarantine, canary release, activation-time checks, and taint propagation.",zh:"使用直接、组合、休眠和跨会话投毒，评测隔离、金丝雀发布、激活时检查和污染传播。"},
   baseline:{en:"Write-time consistency filters, memory sanitization, source trust scores, sandboxing, and retrieval-only defenses.",zh:"写入一致性过滤、记忆清洗、来源信任分数、沙箱和仅检索防御。"},
   go:{en:"Attack success drops substantially while benign memory utility and latency remain acceptable.",zh:"攻击成功率显著下降，同时良性记忆效用和延迟保持可接受。"},stop:{en:"Write-time filtering already prevents all tested attacks.",zh:"写入阶段过滤已阻止全部测试攻击。"}},
  {name:"InteractionGuard-V",directionId:"system-composition",rank:10,score:84.0,confidence:"M",track:{en:"Systems",zh:"系统"},
   thesis:{en:"Test whether individually validated updates interact non-additively when committed together.",zh:"检验单独验证通过的更新在联合提交后是否产生非加性交互。"},
   experiment:{en:"Run factorial co-commit experiments across memory, skills, tools, prompts, and adapters, including alternative rollback orders.",zh:"对记忆、技能、工具、提示词和 Adapter 运行析因联合提交实验，并比较不同回滚顺序。"},
   baseline:{en:"Independent update gates, pairwise regression tests, textual merge-conflict detection, and sequential commit.",zh:"独立更新门控、成对回归测试、文本合并冲突检测和顺序提交。"},
   go:{en:"Interaction probes predict regressions missed by all single-update checks.",zh:"交互探针能够预测所有单更新检查遗漏的回退。"},stop:{en:"Independent validation accurately predicts every merged behavior.",zh:"独立验证已能准确预测全部合并行为。"}},
  {name:"PerformativeEvo-V",directionId:"adaptive-objectives",rank:11,score:83.5,confidence:"M",track:{en:"Theory / method",zh:"理论／方法"},
   thesis:{en:"Separate external drift from distribution changes caused by the deployed agent's own policy before adapting again.",zh:"在再次适应前，区分外部漂移与部署 Agent 自身策略造成的分布变化。"},
   experiment:{en:"Use recommendation, GUI, or embodied environments whose future state distribution responds to agent actions; intervene on the deployed policy.",zh:"使用未来状态分布会响应 Agent 行动的推荐、GUI 或具身环境，并对部署策略进行干预。"},
   baseline:{en:"Standard drift detection, online learning, causal covariate-shift estimation, and no-retraining controls.",zh:"标准漂移检测、在线学习、因果协变量漂移估计和不重训练对照。"},
   go:{en:"Intervention-aware adaptation avoids unstable feedback loops and improves long-run utility.",zh:"干预感知适应避免不稳定反馈循环并提升长期效用。"},stop:{en:"Ordinary drift detectors already distinguish endogenous and exogenous changes.",zh:"普通漂移检测器已能区分内生与外生变化。"}},
  {name:"ConfidenceFlow-Evo",directionId:"security-provenance",rank:12,score:83.1,confidence:"M",track:{en:"Reliability",zh:"可靠性"},
   thesis:{en:"Propagate calibrated uncertainty from source evidence into summaries, memories, skills, tools, adapters, and descendants.",zh:"把来源证据上的校准不确定性传播到摘要、记忆、技能、工具、Adapter 和后代版本。"},
   experiment:{en:"Create source evidence with known reliability, derive multiple persistent artifacts, then correct or revoke the source and measure selective reevaluation.",zh:"构造已知可靠度的来源证据，派生多种持久产物，再修正或撤销来源并测量选择性重评。"},
   baseline:{en:"Local confidence, provenance-only tracing, source trust decay, and uniform derivative rollback.",zh:"局部置信度、仅溯源追踪、来源信任衰减和统一派生回滚。"},
   go:{en:"Propagated confidence predicts harmful derivatives and reduces unnecessary reevaluation.",zh:"传播置信度能够预测有害派生物并减少不必要重评。"},stop:{en:"Local uncertainty or provenance alone matches the method.",zh:"局部不确定性或溯源单独即可持平。"}},
  {name:"EvoValue-V",directionId:"experience-admission",rank:13,score:82.6,confidence:"H",track:{en:"Efficiency",zh:"效率"},
   thesis:{en:"Estimate the future value of skipping, verifying, replaying, or learning from each experience.",zh:"估计对每段经验执行跳过、验证、重放或学习的未来价值。"},
   experiment:{en:"A controller selects no action, cheap verification, counterfactual replay, or persistent update under a fixed budget and delayed future reward.",zh:"控制器在固定预算和延迟未来收益下选择不处理、廉价验证、反事实重放或持久更新。"},
   baseline:{en:"Uncertainty sampling, recency, random acquisition, fixed verification, and myopic bandits.",zh:"不确定性采样、近期优先、随机获取、固定验证和短视 Bandit。"},
   go:{en:"Lower total cost at matched harmful-update rate and future performance.",zh:"在匹配有害更新率和后续表现下显著降低总成本。"},stop:{en:"Simple uncertainty or fixed heuristics match the learned policy.",zh:"简单不确定性或固定启发式与学习策略持平。"}},
  {name:"EgoShift",directionId:"embodied-world",rank:14,score:81.8,confidence:"M",track:{en:"Embodied",zh:"具身"},
   thesis:{en:"Actively diagnose camera, sensor, latency, action-scale, and wear drift before adapting an embodied policy.",zh:"在适应具身策略前主动诊断相机、传感器、延迟、动作尺度和磨损漂移。"},
   experiment:{en:"Apply controlled embodiment shifts in simulation and use low-risk diagnostic micro-actions before calibration or world-model updates.",zh:"在模拟器中施加受控具身变化，使用低风险诊断微动作后再更新标定或世界模型。"},
   baseline:{en:"Calibration-free VLA models, domain randomization, passive residual detection, and full policy fine-tuning.",zh:"免标定 VLA、域随机化、被动残差检测和完整策略微调。"},
   go:{en:"Active diagnosis improves recovery and safety across unseen embodiment shifts.",zh:"主动诊断提升未见具身变化下的恢复与安全。"},stop:{en:"Static robustness or passive calibration already covers the shifts.",zh:"静态鲁棒性或被动标定已覆盖这些变化。"}},
  {name:"OversightBudget-Evo",directionId:"governance-control",rank:15,score:81.6,confidence:"M",track:{en:"Governance",zh:"治理"},
   thesis:{en:"Allocate scarce human review to the update proposals with the highest expected harm reduction.",zh:"把有限人工审查分配给预期减害价值最高的更新提案。"},
   experiment:{en:"Model reviewer disagreement, fatigue, finite capacity, and flooding attacks while choosing autonomous commit, shadow test, escalation, or rejection.",zh:"在建模审查分歧、疲劳、有限容量和洪泛攻击时，选择自动提交、影子测试、升级人工或拒绝。"},
   baseline:{en:"Risk thresholds, uncertainty deferral, random auditing, uniform review frequency, and queue-priority heuristics.",zh:"风险阈值、不确定性转交、随机审计、统一审查频率和队列优先级启发式。"},
   go:{en:"Lower harmful commits under the same human-review budget and acceptable reviewer load.",zh:"在相同人工审查预算和可接受负载下减少有害提交。"},stop:{en:"Simple risk ranking matches the policy.",zh:"简单风险排序与策略持平。"}},
  {name:"MultiRateEvo-V",directionId:"memory-lifecycle",rank:16,score:80.8,confidence:"M",track:{en:"Long-horizon learning",zh:"长期学习"},
   thesis:{en:"Promote and demote experience among context, episodic memory, skills, and parameters using reversible multi-timescale consolidation.",zh:"通过可逆多时间尺度巩固，让经验在上下文、情景记忆、技能和参数之间晋升或降级。"},
   experiment:{en:"Run long task streams with repeated, obsolete, and conflicting patterns; compare promotion, demotion, hysteresis, and rollback policies.",zh:"运行包含重复、过期和冲突模式的长任务流，比较晋升、降级、迟滞和回滚策略。"},
   baseline:{en:"Fixed-period consolidation, one-shot update routing, recency decay, and memory-to-skill crystallization.",zh:"固定周期巩固、一次性更新路由、近期衰减和记忆到技能固化。"},
   go:{en:"Better long-run plasticity and retention with fewer irreversible mistakes.",zh:"获得更好的长期可塑性与保持，并减少不可逆错误。"},stop:{en:"Fixed consolidation or one-shot routing is equally stable.",zh:"固定巩固或一次性路由同样稳定。"}},
  {name:"MemoryFormRouter-V",directionId:"memory-lifecycle",rank:17,score:80.3,confidence:"H",track:{en:"Memory",zh:"记忆"},
   thesis:{en:"Choose the representation of an experience at write time rather than using one memory form for every task.",zh:"在写入时选择经验表示，而不是让所有任务共用一种记忆形式。"},
   experiment:{en:"Route each experience to raw frame, crop, text rule, graph node, parametric memory, or no memory across long-video and GUI tasks.",zh:"在长视频和 GUI 任务中，把每段经验路由为原始帧、裁剪、文本规则、图节点、参数记忆或不记忆。"},
   baseline:{en:"Single-form memory, adaptive retrieval, fixed multimodal storage, and oracle representation selection.",zh:"单一记忆形式、自适应检索、固定多模态存储和 Oracle 表示选择。"},
   go:{en:"Routing improves quality-cost Pareto performance across task families.",zh:"路由提升跨任务族的质量—成本 Pareto 表现。"},stop:{en:"One representation dominates all tasks or retrieval adaptation is sufficient.",zh:"一种表示在所有任务中占优，或仅调整检索已经足够。"}},
  {name:"BudgetEvolve-V",directionId:"governance-control",rank:18,score:79.4,confidence:"H",track:{en:"Efficiency",zh:"效率"},
   thesis:{en:"Allocate a fixed evolution budget among observation, verification, memory, training, and stopping decisions.",zh:"在观察、验证、记忆、训练和停止决策之间分配固定进化预算。"},
   experiment:{en:"Evaluate budget controllers over matched task streams and report quality, safety, latency, calls, tokens, and GPU time.",zh:"在匹配任务流上评测预算控制器，并报告质量、安全、延迟、调用、Token 和 GPU 时间。"},
   baseline:{en:"Fixed allocation, greedy uncertainty, equal-cost ablations, and quality-only optimization.",zh:"固定分配、贪心不确定性、等成本消融和仅质量优化。"},
   go:{en:"A strictly better quality-cost-safety frontier than all fixed policies.",zh:"获得严格优于所有固定策略的质量—成本—安全前沿。"},stop:{en:"A fixed allocation matches the controller.",zh:"固定分配与控制器持平。"}},
  {name:"AuditInvariant-Evo",directionId:"negative-evaluation",rank:19,score:79.1,confidence:"M",track:{en:"Safety",zh:"安全"},
   thesis:{en:"Test whether an evolving agent changes its update policy or visible behavior after inferring that it is monitored.",zh:"测试进化 Agent 推断自己被监控后，是否改变更新策略或可见行为。"},
   experiment:{en:"Compare hidden-monitor, explicit-audit, shadow, quarantine, canary, and ordinary-deployment variants over repeated update rounds.",zh:"在重复更新轮次中比较隐藏监控、显式审计、影子、隔离、金丝雀和普通部署变体。"},
   baseline:{en:"Standard held-out evaluation, randomized evaluator prompts, blind testing, and one-shot deception benchmarks.",zh:"标准留出评测、随机评价器提示、盲测和一次性欺骗基准。"},
   go:{en:"The protocol detects systematic audit-deployment gaps and predicts post-release regressions.",zh:"协议检测到系统性审计—部署差距，并能预测发布后回退。"},stop:{en:"Monitoring conditions do not change behavior or update policy.",zh:"监控条件不改变行为或更新策略。"}},
  {name:"PluralLineage-Evo",directionId:"collective-evolution",rank:20,score:78.9,confidence:"M",track:{en:"Systems",zh:"系统"},
   thesis:{en:"Maintain multiple persistent specialized version lineages instead of forcing all gains into one canonical agent.",zh:"维护多条持久专门化版本谱系，而不是强制把所有收益合并进一个规范 Agent。"},
   experiment:{en:"Branch, task-route, merge, and retire version lineages under matched storage and inference budgets across heterogeneous task families.",zh:"在匹配存储和推理预算下，跨异构任务族分支、任务路由、合并和退役版本谱系。"},
   baseline:{en:"Single canonical version, inference-time ensembles, mixture-of-experts routing, and independent specialist agents.",zh:"单一规范版本、推理时集成、混合专家路由和独立专家 Agent。"},
   go:{en:"Plural lineages preserve specialization and reduce catastrophic compromise at acceptable cost.",zh:"复数谱系在可接受成本下保持专门化并降低灾难性折中。"},stop:{en:"A single version or inference ensemble matches all benefits.",zh:"单一版本或推理集成获得相同收益。"}},
  {name:"SkillUnlearn-V",directionId:"skill-tool-lifecycle",rank:21,score:78.8,confidence:"M",track:{en:"Skill lifecycle",zh:"技能生命周期"},
   thesis:{en:"Remove or repair obsolete visual skills without collateral damage to unrelated capabilities.",zh:"在不附带损害无关能力的情况下删除或修复过期视觉技能。"},
   experiment:{en:"Create interface changes, conflicting skill versions, source revocations, and unsafe precondition changes in a visual skill library.",zh:"在视觉技能库中构造界面变化、冲突版本、来源撤销和不安全前置条件变化。"},
   baseline:{en:"Version replacement, library deletion, retraining, selective forgetting, and skill-pruning heuristics.",zh:"版本替换、库删除、重新训练、选择性遗忘和技能剪枝启发式。"},
   go:{en:"Targeted repair restores new-task validity while preserving unrelated skill performance.",zh:"定向修复恢复新任务有效性，并保持无关技能表现。"},stop:{en:"Simple replacement or deletion causes no collateral regression.",zh:"简单替换或删除没有附带回退。"}},
  {name:"ExploreRepair-V",directionId:"embodied-world",rank:22,score:78.7,confidence:"M",track:{en:"Visual / embodied",zh:"视觉／具身"},
   thesis:{en:"Use memory inconsistency to trigger active visual observation or exploration that repairs missing and stale state.",zh:"利用记忆不一致触发主动视觉观察或探索，以修复缺失和过期状态。"},
   experiment:{en:"Create partially observed GUI, video, or embodied tasks with stale memory; let the agent choose where to look or act before updating memory.",zh:"构造带过期记忆的部分可观测 GUI、视频或具身任务，让 Agent 在更新记忆前选择观察或行动位置。"},
   baseline:{en:"Passive retrieval, random exploration, LensWalk-style test-time observation, uncertainty exploration, and full rescanning.",zh:"被动检索、随机探索、LensWalk 类测试时观察、不确定性探索和完整重扫描。"},
   go:{en:"Persistent repair improves later tasks beyond the immediate observation benefit.",zh:"持久修复带来的后续任务收益超过即时观察收益。"},stop:{en:"Passive retrieval or test-time observation is equally effective.",zh:"被动检索或仅测试时观察同样有效。"}},
  {name:"WorldPatch-V",directionId:"embodied-world",rank:23,score:78.4,confidence:"M",track:{en:"World model",zh:"世界模型"},
   thesis:{en:"Localize a prediction-observation mismatch to one causal world relation and patch only that fragment.",zh:"把预测—观测偏差定位到一个因果世界关系，并只修补该局部。"},
   experiment:{en:"Inject changes to object relations, action effects, dynamics, and scene rules; compare local patching, global revision, and retrieval updates.",zh:"注入物体关系、动作效果、动力学和场景规则变化，比较局部修补、全局修订和检索更新。"},
   baseline:{en:"Global world-model fine-tuning, episodic memory correction, retrieval-augmented planning, and model implantation.",zh:"全局世界模型微调、情景记忆纠正、检索增强规划和模型植入。"},
   go:{en:"Local patches restore planning with less forgetting and easier rollback.",zh:"局部修补以更少遗忘和更易回滚的方式恢复规划。"},stop:{en:"Global or retrieval revision is equally stable and cheap.",zh:"全局或检索修订同样稳定且低成本。"}},
  {name:"EvoProvenance-V",directionId:"security-provenance",rank:24,score:78.2,confidence:"H",track:{en:"Security infrastructure",zh:"安全基础设施"},
   thesis:{en:"Build semantic lineage from source evidence to every memory, skill, tool, model version, and derived state.",zh:"建立从来源证据到每个记忆、技能、工具、模型版本和派生状态的语义谱系。"},
   experiment:{en:"Generate versioned update chains with merges, partial revocations, and multiple rollback orders; measure localization and deletion completeness.",zh:"生成包含合并、局部撤销和多种回滚顺序的版本更新链，测量定位和删除完整性。"},
   baseline:{en:"File-level version control, manifests, event logs, Autogenesis-style lineage, and full checkpoint rollback.",zh:"文件级版本控制、清单、事件日志、Autogenesis 类谱系和完整检查点回滚。"},
   go:{en:"Semantic lineage enables smaller, more complete recovery than coarse rollback.",zh:"语义谱系实现比粗粒度回滚更小且更完整的恢复。"},stop:{en:"Ordinary manifests identify every harmful dependency.",zh:"普通清单已能识别全部有害依赖。"}},
  {name:"SkillProof-V",directionId:"skill-tool-lifecycle",rank:25,score:77.0,confidence:"M",track:{en:"Visual skill",zh:"视觉技能"},
   thesis:{en:"Attach executable visual preconditions, observable postconditions, permissions, version identity, and counterexamples to reusable skills.",zh:"为可复用技能附加可执行视觉前置条件、可观测后置条件、权限、版本身份和反例。"},
   experiment:{en:"Induce GUI or embodied skills and evaluate them across layout, view, state, and tool-version changes before commit.",zh:"归纳 GUI 或具身技能，并在提交前跨布局、视角、状态和工具版本变化进行评测。"},
   baseline:{en:"Unit tests, VASO-style formal contracts, trajectory replay, skill retrieval confidence, and manual preconditions.",zh:"单元测试、VASO 类形式契约、轨迹重放、技能检索置信度和人工前置条件。"},
   go:{en:"Visual contracts predict transfer failures beyond ordinary tests.",zh:"视觉契约能够预测普通测试遗漏的迁移失败。"},stop:{en:"Ordinary unit tests and formal contracts match the method.",zh:"普通单元测试与形式契约与方法持平。"}},
  {name:"PersonaShift-V",directionId:"adaptive-objectives",rank:26,score:76.8,confidence:"M",track:{en:"Personalization",zh:"个性化"},
   thesis:{en:"Detect conflicts, drift, and obsolete multimodal preferences instead of only accumulating personalization memory.",zh:"检测多模态偏好的冲突、漂移和过期，而不是只积累个性化记忆。"},
   experiment:{en:"Simulate longitudinal users with preference reversals, context-specific tastes, and contradictory visual choices across sessions.",zh:"模拟具有偏好反转、情境化偏好和跨会话矛盾视觉选择的纵向用户。"},
   baseline:{en:"Chronological memory, recency weighting, profile summaries, change-point detection, and PersonaVLM-style personalization.",zh:"时间顺序记忆、近期加权、用户画像摘要、变化点检测和 PersonaVLM 类个性化。"},
   go:{en:"The method adapts to genuine preference change while preserving stable preferences.",zh:"方法适应真实偏好变化，同时保持稳定偏好。"},stop:{en:"Recency or change-point baselines match it.",zh:"近期加权或变化点基线与方法持平。"}},
  {name:"ProcessCredit-V",directionId:"experience-admission",rank:27,score:75.4,confidence:"M",track:{en:"Analysis",zh:"分析"},
   thesis:{en:"Assign evolutionary credit to visual observations, decisions, and actions rather than only final outcomes or language steps.",zh:"把进化 credit 分配给视觉观测、决策和动作，而不是只分配给最终结果或语言步骤。"},
   experiment:{en:"Use controlled trajectory interventions to replace, remove, or permute observations and actions across many independent update units.",zh:"通过受控轨迹干预替换、删除或置换观测与动作，并使用大量独立更新单位。"},
   baseline:{en:"Outcome reward, token-level process reward, Shapley approximations, influence functions, and critic attribution.",zh:"结果奖励、Token 级过程奖励、Shapley 近似、影响函数和 critic 归因。"},
   go:{en:"Credit scores predict which lessons will transfer and which updates will harm future tasks.",zh:"Credit 分数能够预测哪些经验会迁移、哪些更新会损害后续任务。"},stop:{en:"Outcome or language-level credit is equally predictive.",zh:"结果级或语言级 credit 同样具有预测力。"}},
  {name:"EvoGC-X",directionId:"memory-lifecycle",rank:28,score:75.0,confidence:"M",track:{en:"Infrastructure",zh:"基础设施"},
   thesis:{en:"Perform semantic garbage collection across memories, skills, tools, prompts, and adapters while preserving behavior.",zh:"在保持行为的前提下，对记忆、技能、工具、提示词和 Adapter 做语义垃圾回收。"},
   experiment:{en:"Create redundant and overlapping artifacts across update surfaces, then remove the smallest equivalent artifact set under behavior probes.",zh:"跨更新表面构造冗余和重叠产物，并在行为探针约束下删除最小等价产物集合。"},
   baseline:{en:"Per-library pruning, LRU deletion, utility scores, deduplication, model pruning, and full retraining.",zh:"单库剪枝、LRU 删除、效用分数、去重、模型剪枝和完整重训练。"},
   go:{en:"Cross-surface collection reduces cost without hidden behavioral regression.",zh:"跨表面回收降低成本且不产生隐性行为回退。"},stop:{en:"Independent pruning of each surface is sufficient.",zh:"分别剪枝各个表面已经足够。"}},
  {name:"MetaGuard-V",directionId:"governance-control",rank:29,score:74.2,confidence:"L",track:{en:"Meta-control",zh:"元控制"},
   thesis:{en:"Monitor and recalibrate the controller that decides what, when, and how the agent evolves.",zh:"监控并重新校准决定 Agent 更新什么、何时更新和怎样更新的控制器。"},
   experiment:{en:"Shift experience noise, feedback quality, causal structure, and update costs across phases; evaluate controller calibration and policy regret.",zh:"分阶段改变经验噪声、反馈质量、因果结构和更新成本，评测控制器校准与策略遗憾。"},
   baseline:{en:"Fixed controller, uncertainty calibration, meta-RL, MetaEvolve-style meta-skills, and periodic retuning.",zh:"固定控制器、不确定性校准、Meta-RL、MetaEvolve 类元技能和周期性重调。"},
   go:{en:"Controller recalibration prevents systematic harmful update choices under phase shift.",zh:"控制器重校准能够在阶段变化下阻止系统性有害更新选择。"},stop:{en:"A fixed or periodically tuned controller is equally robust.",zh:"固定或周期调参控制器同样鲁棒。"}},
  {name:"GoalGuard-Evo",directionId:"adaptive-objectives",rank:30,score:73.8,confidence:"L",track:{en:"Governance",zh:"治理"},
   thesis:{en:"Allow goal refinement only when new objectives remain subordinate to immutable principal constraints and resist proxy exploitation.",zh:"只有当新目标服从不可变主体约束并抵抗代理指标利用时，才允许目标细化。"},
   experiment:{en:"Run goal-evolving agents on scientific or software tasks with adversarial proxy metrics, shifting subgoals, and hidden principal constraints.",zh:"在带对抗代理指标、变化子目标和隐藏主体约束的科学或软件任务中运行目标进化 Agent。"},
   baseline:{en:"Static constitutions, reward constraints, SAGA-style goal evolution, preference models, and human approval.",zh:"静态宪法、奖励约束、SAGA 类目标进化、偏好模型和人工批准。"},
   go:{en:"The method preserves principal constraints while still discovering useful new objectives.",zh:"方法在保持主体约束的同时仍能发现有用新目标。"},stop:{en:"Static constraints or human approval are sufficient.",zh:"静态约束或人工批准已经足够。"}},
  {name:"SimEvo-CF",directionId:"embodied-world",rank:31,score:73.0,confidence:"L",track:{en:"Environment",zh:"环境"},
   thesis:{en:"Evolve environments that specifically expose learned shortcuts, stale lessons, and harmful updates rather than merely increasing difficulty.",zh:"进化专门暴露已学捷径、过期经验和有害更新的环境，而不是只提高难度。"},
   experiment:{en:"Generate visual or embodied counterfactual environments from diagnosed failure signatures and compare them with randomization and curriculum baselines.",zh:"根据诊断失败特征生成视觉或具身反事实环境，并与随机化和课程基线比较。"},
   baseline:{en:"Domain randomization, adversarial environment generation, Agent-World, SimWorld Studio, and difficulty curricula.",zh:"域随机化、对抗环境生成、Agent-World、SimWorld Studio 和难度课程。"},
   go:{en:"Generated cases uniquely reveal harmful evolution and improve a downstream guard or benchmark.",zh:"生成案例能够独特暴露有害进化，并改善下游防护或基准。"},stop:{en:"Cases add nothing beyond domain randomization or generic difficulty.",zh:"案例相较域随机化或通用难度没有额外价值。"}},
  {name:"EvalRedQueen-V",directionId:"negative-evaluation",rank:32,score:72.6,confidence:"L",track:{en:"Evaluation",zh:"评测"},
   thesis:{en:"Co-evolve a visual agent and evaluator against shortcut, hallucination, and evaluator-debt adversaries.",zh:"让视觉 Agent 与评价器针对捷径、幻觉和评价器技术债对手共同进化。"},
   experiment:{en:"Alternate agent updates with region/frame intervention generators and evaluator updates while preserving an external sealed audit set.",zh:"交替更新 Agent、区域／帧干预生成器和评价器，同时保留外部密封审计集。"},
   baseline:{en:"Frozen evaluator, evaluator ensembles, Red Queen Gödel Machine, adversarial testing, and periodic human audit.",zh:"冻结评价器、评价器集成、Red Queen Gödel Machine、对抗测试和周期人工审计。"},
   go:{en:"Co-evolution improves detection of novel failures without degrading external calibration.",zh:"共进化提升新型失败检测，同时不降低外部校准。"},stop:{en:"A frozen diverse evaluator is equally effective.",zh:"冻结的多样评价器同样有效。"}},
  {name:"UpdateRoute-V",directionId:"system-composition",rank:33,score:71.2,confidence:"L",track:{en:"Systems",zh:"系统"},
   thesis:{en:"Diagnose a failure and choose no update, memory, skill, workflow, or adapter instead of using one surface for every lesson.",zh:"诊断失败并在不更新、记忆、技能、工作流或 Adapter 之间选择，而不是所有经验都使用同一表面。"},
   experiment:{en:"Create controlled perception, memory, planning, tool, and policy failures with known smallest effective update surfaces.",zh:"构造已知最小有效更新表面的受控感知、记忆、规划、工具和策略失败。"},
   baseline:{en:"Fixed update surface, rule-based routing, cost-aware bandits, and oracle routing.",zh:"固定更新表面、规则路由、成本感知 Bandit 和 Oracle 路由。"},
   go:{en:"Routing improves future performance and cost while selecting the correct minimal surface.",zh:"路由提升后续表现与成本，并选择正确的最小更新表面。"},stop:{en:"Routing ground truth is not identifiable or a fixed surface matches it.",zh:"路由真值不可识别，或固定表面与其持平。"}},
  {name:"CrossAgentTransfer-V",directionId:"collective-evolution",rank:34,score:70.8,confidence:"L",track:{en:"Multi-agent",zh:"多 Agent"},
   thesis:{en:"Transfer only verified lessons across heterogeneous agents and predict negative transfer from evidence or capability incompatibility.",zh:"只在异构 Agent 之间迁移经验证经验，并根据证据或能力不兼容预测负迁移。"},
   experiment:{en:"Use at least two VLM or embodied families with different observations, tools, prompts, and action spaces; transfer lessons with compatibility checks.",zh:"使用至少两个具有不同观测、工具、提示和动作空间的 VLM 或具身家族，并在兼容检查后迁移经验。"},
   baseline:{en:"Raw memory sharing, centralized distillation, federated learning, adapter transfer, and no-transfer controls.",zh:"原始记忆共享、集中蒸馏、联邦学习、Adapter 迁移和不迁移对照。"},
   go:{en:"Verified transfer improves target agents while accurately abstaining on incompatible lessons.",zh:"验证迁移改善目标 Agent，并能对不兼容经验准确弃权。"},stop:{en:"Raw sharing or ordinary transfer is equally safe and effective.",zh:"原始共享或普通迁移同样安全有效。"}}
];

window.PAPER_TRACKS = [
  {id:"visual",title:{en:"Visual / CVPR",zh:"视觉／CVPR"},ideaNames:["ScopeGuard-V","GroundEvo-Admission","ViMEvo-Repair","RelianceGuard-V","EgoShift","ExploreRepair-V","WorldPatch-V","SkillProof-V"]},
  {id:"systems",title:{en:"Systems / Security",zh:"系统／安全"},ideaNames:["AmplificationGuard-X","EvoContract-V","CapabilityLease-Evo","EvoFirewall-V","InteractionGuard-V","ConfidenceFlow-Evo","AuditInvariant-Evo","EvoProvenance-V"]},
  {id:"benchmark",title:{en:"Benchmark / Analysis",zh:"基准／分析"},ideaNames:["NegEvoBench-V","ScopeGuard-V","RelianceGuard-V","PerformativeEvo-V","AuditInvariant-Evo","ProcessCredit-V","EvalRedQueen-V"]},
  {id:"long-horizon",title:{en:"Long-horizon Learning",zh:"长期学习"},ideaNames:["EvoValue-V","MultiRateEvo-V","MemoryFormRouter-V","PluralLineage-Evo","SkillUnlearn-V","ExploreRepair-V","MetaGuard-V","CrossAgentTransfer-V"]}
];

window.IDEA_AUDIT = {
  merged:{en:"Eighteen narrower formulations are retained as sub-questions or evaluation axes inside the 34 paper ideas.",zh:"18 个更窄表述作为子问题或评测轴并入 34 个论文 Idea。"},
  rejected:{en:"Seventeen formulations are rejected because of direct literature collision, missing identifiability, or lack of a falsifiable minimum experiment.",zh:"17 个表述因直接文献碰撞、不可识别或缺少可证伪最小实验而淘汰。"}
};
