#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
HERE=Path(__file__).resolve().parent;REPO=HERE.parents[1]
REV='ICLR-WORKING-MEMORY-LOCALIZATION-B11-20260824'; PAPER='D2-PAPER-PROXY-REWARD-MEMORY-VARIANCE'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def load(p):return json.loads(Path(p).read_text())
q=load(HERE/'manuscript-qa.json');b=load(HERE/'b11-working-memory-localization-evidence.json');raw=load(HERE/'b11-working-memory-attribution.json')
if q.get('status')!='PASS' or q.get('revision')!=REV or not all(q['checks'].values()):raise RuntimeError('B11 QA not pass')
if b.get('status')!='B11_WORKING_MEMORY_LOCALIZATION_COMPLETE_STOP' or b['provider_calls']!=0 or b['stop_decision']['B12_provider_experiment_authorized'] is not False:raise RuntimeError('B11 boundary drift')
a=b['branch_specific_uptake'];g=b['generic_common_core_tendency'];link=b['transport_linkage']
if abs(a['mean_pair_relative_shift']-.0033469072206773693)>1e-12 or abs(a['posthoc_permutation_p']-.2051979480205198)>1e-12:raise RuntimeError('B11 branch metric drift')
receipt={'schema_version':'1.0','artifact_type':'working-memory-localization-revision-receipt','paper_id':PAPER,'status':'WORKING_MEMORY_LOCALIZATION_INTEGRATED_QA_PASS','revision':REV,'title':'Reward Errors Become Persistent State: Write-Time Causality and Transport Boundaries in Agent Memory','paper_pdf_sha256':sha(HERE/'paper.pdf'),'manuscript_qa_sha256':sha(HERE/'manuscript-qa.json'),'b11_working_memory_localization_evidence_sha256':sha(HERE/'b11-working-memory-localization-evidence.json'),'b11_working_memory_attribution_sha256':sha(HERE/'b11-working-memory-attribution.json'),'prior_transport_localization_evidence_sha256':sha(HERE/'transport-localization-evidence.json'),'prior_transport_localization_receipt_sha256':sha(HERE/'transport-localization-revision-receipt.json'),'paper_story_sha256':sha(REPO/'paper-story-reward-memory.js'),'paper_reader_data_sha256':sha(REPO/'paper-reader-data.js'),'qa_checks_passed':sum(q['checks'].values()),'qa_checks_total':len(q['checks']),'main_text_pages':q['main_text_pages'],'references_begin_page':q['references_begin_page'],'pdf_pages_total':q['pdf_pages_total'],'branch_specific_uptake':a,'generic_common_core_tendency':g,'transport_linkage':link,'simple_similarity_falsifier':b['simple_similarity_falsifier'],'stop_decision':b['stop_decision'],'current_revision_new_provider_calls':0,'current_revision_new_rollouts':0,'full_paper_observable_provider_posts_lower_bound':1915,'scientific_values_changed':True,'scientific_claims_expanded':False,'external_review_calls_current_revision':0,'external_review_deferred_to_evening':True,'canonical_stable_registry_overwritten':False,'canonical_note':'B11 is a zero-call daytime diagnostic candidate. Stable PaperRegistry/acceptance projection remains unchanged pending external review.','scientific_authority':False,'experiment_authority':False,'claim_expansion_authority':False,'submission_authority':False}
out=HERE/'working-memory-localization-revision-receipt.json';out.write_text(json.dumps(receipt,indent=2,sort_keys=True)+'\n');print(json.dumps({'status':receipt['status'],'qa':f"{receipt['qa_checks_passed']}/{receipt['qa_checks_total']}",'pdf_sha256':receipt['paper_pdf_sha256'],'new_provider_calls':0,'full_lower_bound':1915,'B12_provider_experiment_authorized':False},indent=2))
