#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
HERE=Path(__file__).resolve().parent;REPO=HERE.parents[1]
PAPER='D2-PAPER-PROXY-REWARD-MEMORY-VARIANCE';REV='ICLR-STAGE-RESOLVED-B12-CROSSDOMAIN-20260824'
def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p:Path):
 d=json.loads(p.read_text(encoding='utf-8'))
 if not isinstance(d,dict):raise RuntimeError(f'not object:{p}')
 return d
def req(x:bool,m:str):
 if not x:raise RuntimeError(m)
def main():
 q=load(HERE/'manuscript-qa.json');b12=load(HERE/'b12-crossdomain-reddit-evidence.json');s4=load(HERE/'story-v4-argument-search-20260824.json');s5=load(HERE/'story-v5-crossdomain-adjudication-20260824.json');wm=load(HERE/'b11-working-memory-localization-evidence.json')
 req(q.get('status')=='PASS' and q.get('revision')==REV and all(q['checks'].values()),'QA not pass');req(sum(q['checks'].values())==len(q['checks'])==47,'QA geometry drift');req(b12.get('status')=='B12_REDDIT_CROSSDOMAIN_REPLICATION_COMPLETE','B12 drift');req(wm.get('status')=='B11_WORKING_MEMORY_LOCALIZATION_COMPLETE_STOP' and wm.get('provider_calls')==0 and abs(wm['branch_specific_uptake']['mean_pair_relative_shift']-.0033469072206773693)<1e-12 and abs(wm['branch_specific_uptake']['posthoc_permutation_p']-.2051979480205198)<1e-12,'working-memory drift')
 w=b12['writer_stage'];t=b12['terminal_stage'];a=b12['execution_accounting'];c=b12['claim_boundary']
 req(w['complete_pairs']==4 and w['exact_content_change_pairs']==4 and w['title_set_change_pairs']==4 and abs(w['mean_token_jaccard_distance']-.652342)<1e-9,'writer drift');req(t['scientific_calls']==64 and abs(t['mean_absolute_success_rate_difference']-.125)<1e-12 and abs(t['permutation_p']-.225268)<1e-9 and t['gate_pass'] is False and t['zero_effect_tasks']==6 and t['all_leave_one_task_out_means_below_floor'] is True,'terminal drift');req(a['b12_observable_provider_posts_total']==80 and a['b12_scientifically_usable_calls']==72 and a['full_paper_observable_provider_posts_lower_bound_after_b12']==2159,'accounting drift');req(c['crossdomain_write_divergence_supported_on_four_required_reddit_sources'] is True and c['crossdomain_reddit_native_practical_transport_supported'] is False and c['shopping_native_magnitude_is_universal_supported'] is False,'boundary drift');req(s4['winner']['id']=='S1-WRITE-TO-UPTAKE-BOTTLENECK' and s5['story_adjudication']['winner_changes'] is False and s5['story_adjudication']['new_story_role']=='E5 generalization and failure boundary','story drift')
 wmproj={'provider_calls':0,'mean_pair_relative_shift':wm['branch_specific_uptake']['mean_pair_relative_shift'],'permutation_p':wm['branch_specific_uptake']['posthoc_permutation_p'],'paired_dz':wm['branch_specific_uptake']['paired_dz'],'common_centroid_uptake':wm['generic_common_core_tendency']['mean_common_centroid_uptake'],'common_centroid_p':wm['generic_common_core_tendency']['posthoc_signflip_p'],'first_action_linkage_r':wm['transport_linkage']['pearson_working_memory_shift_vs_first_action_tv'],'terminal_linkage_r':wm['transport_linkage']['pearson_working_memory_shift_vs_terminal_effect'],'role':'post-hoc supporting localization only; no provider accounting increment'}
 r={'schema_version':'1.1','artifact_type':'stage-resolved-b12-revision-receipt','paper_id':PAPER,'status':'STAGE_RESOLVED_B12_INTEGRATED_QA_PASS','revision':REV,'title':'Reward Errors Change Memory Before They Change Policy','paper_pdf_sha256':sha(HERE/'paper.pdf'),'manuscript_qa_sha256':sha(HERE/'manuscript-qa.json'),'b12_crossdomain_reddit_evidence_sha256':sha(HERE/'b12-crossdomain-reddit-evidence.json'),'working_memory_posthoc_evidence_sha256':sha(HERE/'b11-working-memory-localization-evidence.json'),'story_v4_sha256':sha(HERE/'story-v4-argument-search-20260824.json'),'story_v5_sha256':sha(HERE/'story-v5-crossdomain-adjudication-20260824.json'),'paper_story_sha256':sha(REPO/'paper-story-reward-memory.js'),'paper_reader_data_sha256':sha(REPO/'paper-reader-data.js'),'qa_checks_passed':sum(q['checks'].values()),'qa_checks_total':len(q['checks']),'abstract_words_approx':q['abstract_words_approx'],'main_text_pages':q['main_text_pages'],'references_begin_page':q['references_begin_page'],'pdf_pages_total':q['pdf_pages_total'],'b12_writer_stage':w,'b12_terminal_stage':{k:v for k,v in t.items() if k not in {'cell_results','leave_one_task_out'}},'b12_execution_repair':b12['execution_repair'],'working_memory_posthoc':wmproj,'cross_domain_synthesis':b12['cross_domain_synthesis'],'claim_boundary':c,'execution_accounting':a,'current_revision_observable_provider_posts':80,'current_revision_scientifically_usable_calls':72,'current_revision_scientifically_usable_writer_calls':8,'current_revision_scientifically_usable_terminal_rollouts':64,'full_paper_observable_provider_posts_lower_bound':2159,'scientific_values_changed':True,'scientific_claims_expanded':False,'story_winner_changed':False,'external_review_calls_current_revision':0,'external_review_deferred_to_evening':True,'canonical_stable_registry_overwritten':False,'canonical_note':'Integrated candidate preserves the zero-call working-memory diagnostic as post-hoc supporting localization and adds the bounded Reddit second-domain replication. Stable PaperRegistry/acceptance projection remains unchanged pending external-review adjudication.','scientific_authority':False,'experiment_authority':False,'claim_expansion_authority':False,'submission_authority':False}
 out=HERE/'stage-resolved-b12-revision-receipt.json';out.write_text(json.dumps(r,ensure_ascii=False,indent=2,sort_keys=True)+'\n',encoding='utf-8');print(json.dumps({'status':r['status'],'qa':f"{r['qa_checks_passed']}/{r['qa_checks_total']}",'title':r['title'],'pdf_sha256':r['paper_pdf_sha256'],'b12_observable_posts':80,'b12_usable':72,'working_memory_provider_calls':0,'full_lower_bound':2159,'story_winner_changed':False,'external_review_calls':0},indent=2))
if __name__=='__main__':main()
