#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json, os
from datetime import datetime, timezone
from pathlib import Path
PAPER='D2-PAPER-PROXY-REWARD-MEMORY-VARIANCE';EXP='D2-PROXY-B6-CROSS-POLICY-RETRIEVAL-MATCHED-R1-2200';MASTER_SHA='ddc5bd50487ed431f5d24ee84cda4e422f36216b4191a02db21db18ae821161f';PARENT_CONTRACT_SHA='e82181c8a09559830cb9b72fe6968b9efdbc447d0b00c08d311130f8a24b719e'
MODEL={'requested':'deepseek-v4-flash','expected_resolved':'deepseek-v4-flash-ga-260731','temperature':0.2,'max_output_tokens':2200,'thinking':None,'provider_retries':0,'store':True,'allow_thinking_compatibility_fallback':False,'substitution_allowed':False}
def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p:Path):return json.loads(p.read_text())
def req(x,msg):
 if not x:raise RuntimeError(msg)
def writej(p:Path,d):p.parent.mkdir(parents=True,exist_ok=True);t=p.with_suffix(p.suffix+'.tmp');t.write_text(json.dumps(d,indent=2,sort_keys=True)+'\n');os.replace(t,p)
def main():
 ap=argparse.ArgumentParser();
 for n in ['master_authority','parent_contract','parent_result','program','repair_addendum','runner','env_file','run_root']:ap.add_argument('--'+n.replace('_','-'),required=True,type=Path)
 a=ap.parse_args();req(sha(a.master_authority)==MASTER_SHA,'master drift');req(sha(a.parent_contract)==PARENT_CONTRACT_SHA,'parent contract drift');master=load(a.master_authority);pc=load(a.parent_contract);pr=load(a.parent_result);prog=load(a.program);add=load(a.repair_addendum)
 req(master.get('paper_id')==PAPER and master.get('decision')=='approve' and master.get('provider_credential_use_authorized_if_required_by_a_frozen_subcontract') is True,'authority invalid');f=master.get('future_repair_experiments') or {};req(f.get('human_program_authorized') is True and f.get('requires_per_experiment_preregistration') is True and f.get('automatic_execution_without_frozen_subcontract') is False,'program authority invalid');req(master.get('claim_expansion_authorized') is False,'claim expansion drift')
 req(pc['experiment_id']=='D2-PROXY-B6-CROSS-POLICY-RETRIEVAL-MATCHED' and pc['model']['max_output_tokens']==900,'parent contract identity drift');req(pr['status']=='B6_EXECUTION_PARTIAL' and pr['summary']['provider_calls_attempted_total']==1 and pr['summary']['provider_calls_complete']==0 and pr['summary']['provider_failures']==1,'parent result pattern drift');req(len(pr['failures'])==1 and pr['failures'][0]['stage']=='terminal-26-source-25-success-r1' and (pr['failures'][0].get('provider_receipt') or {}).get('incomplete_reason')=='length','parent failure not pure first-unit length censoring')
 req(prog['status']=='FROZEN_BEFORE_B6_PROVIDER_CALLS' and prog['B6']['provider_call_ceiling']==288 and prog['B7']['provider_call_ceiling']==144,'program drift');req(add['status']=='FROZEN_BEFORE_B6_R1_PROVIDER_CALLS' and add['repair']['B6_fresh_provider_calls']==288 and add['repair']['B7_provider_calls']==144 and '2200' in add['repair']['only_execution_change'],'repair addendum drift');req(a.runner.is_file() and a.env_file.is_file(),'runner/env missing')
 contract={'schema_version':'1.0','experiment_id':EXP,'paper_id':PAPER,'status':'FROZEN_BEFORE_PROVIDER_CALLS','frozen_at':datetime.now(timezone.utc).replace(microsecond=0).isoformat(),'repair_class':'UNIFORM_DEEPSEEK_OUTPUT_CAP_RECOVERY','question':pc['question'],'relationship_to_parent':'fresh full rerun after first-unit no-text length censoring; parent has zero scientific authority','parent_contract':{'path':str(a.parent_contract.resolve()),'sha256':PARENT_CONTRACT_SHA},'parent_result':{'path':str(a.parent_result.resolve()),'sha256':sha(a.parent_result)},'cross_policy_program':{'path':str(a.program.resolve()),'sha256':sha(a.program)},'repair_addendum':{'path':str(a.repair_addendum.resolve()),'sha256':sha(a.repair_addendum)},'human_authority':{'path':str(a.master_authority.resolve()),'sha256':MASTER_SHA},'task_units':pc['task_units'],'future_task_count':36,'conditions':['success','failure'],'rollouts_per_task_per_condition':4,'expected_provider_calls':288,'model':MODEL,'source_artifacts':pc['source_artifacts'],'memory_manifest':pc['memory_manifest'],'b4_contract':pc['b4_contract'],'b4_result':pc['b4_result'],'vendor_path':pc['vendor_path'],'provider_env_file':str(a.env_file.resolve()),'code':{'runner':{'path':str(a.runner.resolve()),'sha256':sha(a.runner)}},'primary_gate':pc['primary_gate'],'secondary_descriptives':pc['secondary_descriptives'],'missingness_policy':pc['missingness_policy'],'execution_guards':pc['execution_guards'],'freshness':{'reuse_parent_outputs':False,'fresh_provider_calls_if_complete':288},'only_execution_change':{'max_output_tokens':{'from':900,'to':2200}},'scope_boundary':{**pc['scope_boundary'],'B7_must_execute_if_R1_complete_regardless_of_R1_gate':True,'no_further_output_cap_repairs_allowed':True},'authority':pc['authority']}
 raw=dict(contract);contract['contract_sha256']=hashlib.sha256(json.dumps(raw,sort_keys=True,separators=(',',':')).encode()).hexdigest();cp=a.run_root/'b6-r1-contract.json';writej(cp,contract);rec={'schema_version':'1.0','receipt_type':'scoped-experiment-authorization','paper_id':PAPER,'experiment_id':EXP,'status':'B6_R1_2200_AUTHORIZED','contract_file_sha256':sha(cp),'parent_result_sha256':sha(a.parent_result),'repair_addendum_sha256':sha(a.repair_addendum),'runner_sha256':contract['code']['runner']['sha256'],'provider_call_ceiling':288,'only_execution_change':'max_output_tokens 900 -> 2200 uniformly across all 288 fresh units','B7_commitment':True,'no_further_cap_repair':True,'primary_gate':contract['primary_gate'],'authority':contract['authority']};writej(a.run_root/'b6-r1-authorization-receipt.json',rec);print(json.dumps({'status':rec['status'],'contract_file_sha256':rec['contract_file_sha256'],'provider_call_ceiling':288,'only_execution_change':rec['only_execution_change'],'B7_commitment':True,'no_further_cap_repair':True},indent=2))
if __name__=='__main__':main()
