#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json, os
from datetime import datetime, timezone
from pathlib import Path

PAPER='D2-PAPER-PROXY-REWARD-MEMORY-VARIANCE'; EXP='D2-PROXY-B5-NO-MEMORY-NATIVE-SUPPORT'
MASTER_SHA='ddc5bd50487ed431f5d24ee84cda4e422f36216b4191a02db21db18ae821161f'; B4_CONTRACT_SHA='eb86231b4afe2143e59fa8d322a42a5bb236a09aefcb506fe2d7bb7d8dbaaa11'; B4_RESULT_SHA='fb3fef89a38806e9a3b13efd8413b920f81b132390818403f4d5be957f42feeb'
MODEL={'requested':'doubao-seed-2.0-mini','expected_resolved':'doubao-seed-2-0-mini-260215','temperature':0.2,'max_output_tokens':900,'thinking':'disabled','provider_retries':0,'store':True,'allow_thinking_compatibility_fallback':False,'substitution_allowed':False}

def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p:Path):return json.loads(p.read_text())
def req(x,msg):
 if not x:raise RuntimeError(msg)
def writej(p:Path,d):p.parent.mkdir(parents=True,exist_ok=True);t=p.with_suffix(p.suffix+'.tmp');t.write_text(json.dumps(d,indent=2,sort_keys=True)+'\n');os.replace(t,p)
def main():
 ap=argparse.ArgumentParser();
 for n in ['master_authority','b4_contract','b4_result','runner','env_file','run_root']:ap.add_argument('--'+n.replace('_','-'),required=True,type=Path)
 a=ap.parse_args();req(sha(a.master_authority)==MASTER_SHA,'master drift');req(sha(a.b4_contract)==B4_CONTRACT_SHA,'B4 contract drift');req(sha(a.b4_result)==B4_RESULT_SHA,'B4 result drift');m=load(a.master_authority);c4=load(a.b4_contract);r4=load(a.b4_result)
 req(m.get('paper_id')==PAPER and m.get('decision')=='approve' and m.get('provider_credential_use_authorized_if_required_by_a_frozen_subcontract') is True,'authority invalid');f=m.get('future_repair_experiments') or {};req(f.get('human_program_authorized') is True and f.get('requires_per_experiment_preregistration') is True and f.get('automatic_execution_without_frozen_subcontract') is False,'program authority invalid');req(m.get('claim_expansion_authorized') is False,'claim expansion drift')
 req(r4['status']=='B4_EXECUTION_COMPLETE' and r4['summary']['provider_calls_complete']==288 and r4['summary']['provider_failures']==0,'B4 incomplete');req(c4['future_task_count']==36 and len(c4['task_units'])==36,'B4 support drift');req(a.runner.is_file() and a.env_file.is_file(),'runner/env missing')
 contract={'schema_version':'1.0','experiment_id':EXP,'paper_id':PAPER,'status':'FROZEN_BEFORE_PROVIDER_CALLS','frozen_at':datetime.now(timezone.utc).replace(microsecond=0).isoformat(),'question':'On the exact 36-task retrieval-matched support used in B4, does either reward-conditioned memory state move terminal success relative to literal no-memory omission?','relationship_to_B4':'same future tasks, fixed evidence, model, evaluator, and rollout depth; only omit the native ReasoningBank memory message','human_authority':{'path':str(a.master_authority.resolve()),'sha256':MASTER_SHA},'b4_contract':{'path':str(a.b4_contract.resolve()),'sha256':B4_CONTRACT_SHA},'b4_result':{'path':str(a.b4_result.resolve()),'sha256':B4_RESULT_SHA},'task_units':c4['task_units'],'future_task_count':36,'rollouts_per_task':4,'expected_provider_calls':144,'model':MODEL,'source_artifacts':c4['source_artifacts'],'vendor_path':c4['vendor_path'],'provider_env_file':str(a.env_file.resolve()),'code':{'runner':{'path':str(a.runner.resolve()),'sha256':sha(a.runner)}},'primary_gate':{'statistic':'mean over 36 tasks of 0.5*(|p_success_memory-p_no_memory|+|p_failure_memory-p_no_memory|)','min_mean_absolute_memory_presence_effect':0.15,'omnibus_permutation_p_lt':0.05,'permutation_repetitions':100000,'permutation_seed':20260824},'secondary_descriptives':['success-memory minus no-memory per task','failure-memory minus no-memory per task','three-arm point-estimate geometry','joint floor/ceiling changes relative to omission'],'missingness_policy':{'provider_retries':0,'stop_after_first_no_text_provider_failure':True,'top_up_failed_units':False,'replace_future_tasks':False},'execution_guards':{'single_writer_transaction_lock_required':True,'response_first_archival_required':True,'resumable_stage_cache':True,'fixed_order_chunking_allowed':True,'chunking_cannot_depend_on_outcomes':True},'scope_boundary':{'no_live_browser_claim':True,'no_population_causal_effect_claim':True,'no_threshold_relaxation':True,'B4_success_vs_failure_negative_boundary_preserved':True,'no_outcome_driven_task_selection':True},'authority':{'scientific_reopen_authority':True,'experiment_authority':True,'provider_call_authority':True,'gpu_authority':False,'claim_expansion_authority':False,'submission_authority':False}}
 raw=dict(contract);contract['contract_sha256']=hashlib.sha256(json.dumps(raw,sort_keys=True,separators=(',',':')).encode()).hexdigest();cp=a.run_root/'b5-contract.json';writej(cp,contract);rec={'schema_version':'1.0','receipt_type':'scoped-experiment-authorization','paper_id':PAPER,'experiment_id':EXP,'status':'B5_NO_MEMORY_NATIVE_SUPPORT_AUTHORIZED','contract_file_sha256':sha(cp),'runner_sha256':contract['code']['runner']['sha256'],'future_task_count':36,'provider_call_ceiling':144,'primary_gate':contract['primary_gate'],'authority':contract['authority']};writej(a.run_root/'b5-authorization-receipt.json',rec);print(json.dumps({'status':rec['status'],'contract_file_sha256':rec['contract_file_sha256'],'provider_call_ceiling':144,'primary_gate':rec['primary_gate']},indent=2))
if __name__=='__main__':main()
