#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from collections import Counter
from datetime import datetime,timezone,timedelta
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];GEN=ROOT/'generated';PID='D2-PAPER-TEMPORAL-SKILL-CAUSAL-BOTTLENECK';OUT=GEN/'research-timeline.json';JS=GEN/'research-timeline.js'
REVIEW=GEN/'temporal-skill-r14-stanford-review-result-20260824.json';FINAL=GEN/'temporal-skill-r15-ledger-finalization-20260824.json'
def cdate(x):
 try:return datetime.fromisoformat(x).astimezone(timezone(timedelta(hours=8))).date().isoformat()
 except:return x[:10]
def src(p):return {'path':str(p.relative_to(ROOT)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'public':True}
def eid(when,state,path):return hashlib.sha256('|'.join((when,'paper',PID,state,path.name)).encode()).hexdigest()[:16]
def main():
 t=json.loads(OUT.read_text());reg=json.loads((GEN/'paper-registry.json').read_text());p=next(x for x in reg['papers'] if x.get('paper_id')==PID);r=json.loads(REVIEW.read_text());f=json.loads(FINAL.read_text())
 refs={'research_items':[],'experiments':[],'papers':[{'paper_id':PID,'source_research_item':p.get('source_research_item_id',''),'paper_stage':p.get('paper_stage') or p.get('current_state'),'scientific_status':p.get('scientific_status'),'submission_ready':p.get('submission_ready')}],'categories':[]};links=[{'label':'论文','href':f'selected-paper.html?paper={PID}'}];auth={'scientific':False,'scope':'read-only paper/review history','scope_zh':'只读论文/外审历史；无科研、实验、GPU 或投稿授权。','projection_can_change_state':False}
 review_at=str(r['review_date'])+('' if '+' in str(r['review_date']) or str(r['review_date']).endswith('Z') else '+00:00')
 events_new=[
 {'event_id':eid(review_at,'EXTERNAL_REVIEW_ACCEPT',REVIEW),'occurred_at':review_at,'time_precision':'exact','event_class':'paper','importance':'key','origin':'artifact_full_history','research_id':PID,'research_label_zh':'E2 · Temporal Skill · R14','title':'Stanford post-repair review: 6.0 / Accept','title_zh':'E2 R14 Stanford 外审结果：6.0 / Accept','state_before':'SUBMITTED_FOR_EXTERNAL_REVIEW','state_after':'EXTERNAL_REVIEW_ACCEPT','summary':{'en':'The fresh Stanford Agentic Reviewer returns 6.0 / Accept for R14. The score is advisory and not an official ICLR score.','zh':'R14 新一轮 Stanford Agentic Reviewer 返回 6.0 / Accept；该数值是外部 AI advisory score，不是官方 ICLR 分数。'},'why':{'en':'The reviewer explicitly accepts the four-contrast attribution audit and requests targeted clarification/analysis rather than a new experiment for the current narrow claim.','zh':'Reviewer 明确认可四 contrast attribution audit；对当前窄 claim 的剩余要求以解释/现有数据分析为主，而非必须新开实验。'},'limitation':{'en':'The review does not grant scientific or submission authority.','zh':'外审不授予科研或投稿权限。'},'next_action':'Apply paper/analysis-only targeted repair; keep broader benign-generic/non-ceiling experiments future-only.','next_action_zh':'只做 paper/analysis targeted repair；benign generic / 更多 non-ceiling 等新实验保留 future-only。','reopen_condition':'','reopen_condition_zh':'未来扩大 claim 时才按独立 scientific gate 重开。','evidence':[{'label':'score','value':'6.0 (non-official)'},{'label':'textual verdict','value':'Accept'},{'label':'reviewed revision','value':'R14'}],'authority':auth,'sources':[src(REVIEW)],'links':links,'canonical_refs':refs},
 {'event_id':eid('2026-08-24T07:20:33+00:00','R15_TARGETED_REPAIR_COMPLETE',FINAL),'occurred_at':'2026-08-24T07:20:33+00:00','time_precision':'exact','event_class':'paper','importance':'key','origin':'artifact_full_history','research_id':PID,'research_label_zh':'E2 · Temporal Skill · R15','title':'R15 targeted repair complete after external Accept','title_zh':'E2 R15：Accept 后 targeted repair 已完成','state_before':'SUBMISSION_READY','state_after':'R15_TARGETED_REPAIR_COMPLETE','summary':{'en':'R15 closes the seven external-review questions with paper/existing-data analysis, keeps the scientific contract unchanged, and adds zero new model/provider calls.','zh':'R15 用文稿与现有数据分析闭合 7 个新外审问题；scientific contract 完全不变，新增模型/provider call 为 0。'},'why':{'en':'The accepted narrow claim does not require score-chasing experiments.','zh':'当前已获 Accept 的窄 claim 不需要为追分扩实验。'},'limitation':{'en':'Benign-generic, powered non-ceiling, prospective cross-domain, and multi-turn studies remain future scientific-reopen objects.','zh':'benign generic、powered non-ceiling、prospective cross-domain、multi-turn 仍是未来 scientific-reopen 对象。'},'next_action':'Keep R15 frozen for human submission/signoff.','next_action_zh':'保持 R15 冻结，进入人工投稿/签字环节。','reopen_condition':'Broaden only under a new scientific contract.','reopen_condition_zh':'只有未来扩大 scientific claim 时才以新合同重开。','evidence':[{'label':'Claim Audit','value':'15/15'},{'label':'scientific contract','value':'UNCHANGED'},{'label':'new experiment','value':'0'}],'authority':auth,'sources':[src(FINAL)],'links':links,'canonical_refs':refs}]
 paths={s['path'] for e in events_new for s in e['sources']};old=t.get('events',[]);already=sum(any(s.get('path') in paths for s in e.get('sources',[]) if isinstance(s,dict)) for e in old);events=[e for e in old if not any(s.get('path') in paths for s in e.get('sources',[]) if isinstance(s,dict))]+events_new;events.sort(key=lambda x:(x.get('occurred_at',''),x.get('importance')=='key',x.get('event_id','')),reverse=True)
 classes=Counter(e.get('event_class') for e in events);dates=Counter(cdate(e.get('occurred_at','')) for e in events);summary=dict(t.get('summary') or {});summary.update({'events':len(events),'dated_structured_artifacts_projected':int(summary.get('dated_structured_artifacts_projected',0))+max(0,2-already),'key_events':sum(e.get('importance')=='key' for e in events),'canonical_paper_bound_events':sum(bool((e.get('canonical_refs') or {}).get('papers')) for e in events),'canonical_papers_with_events':len({r.get('paper_id') for e in events for r in (e.get('canonical_refs') or {}).get('papers',[]) if r.get('paper_id')}),'days':len(dates),'class_counts':dict(sorted(classes.items())),'date_counts':dict(sorted(dates.items(),reverse=True))});t['generated_at']=max(e.get('occurred_at','') for e in events);t['summary']=summary;t['events']=events;OUT.write_text(json.dumps(t,ensure_ascii=False,indent=2)+'\n');JS.write_text('window.RESEARCH_TIMELINE = '+json.dumps(t,ensure_ascii=False,separators=(',',':'))+';\n');print(json.dumps({'events':len(events),'added':2,'review_event':events_new[0]['event_id'],'r15_event':events_new[1]['event_id']},indent=2))
if __name__=='__main__':main()
