#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from collections import Counter
from datetime import datetime,timezone,timedelta
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];GEN=ROOT/'generated';PID='D2-PAPER-TEMPORAL-SKILL-CAUSAL-BOTTLENECK';OUT=GEN/'research-timeline.json';JS=GEN/'research-timeline.js'
ADJ=GEN/'temporal-skill-extension-adjudication-20260824.json';FINAL=GEN/'temporal-skill-r16-ledger-finalization-20260824.json'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def cdate(x):return datetime.fromisoformat(x).astimezone(timezone(timedelta(hours=8))).date().isoformat()
def eid(when,state,path):return hashlib.sha256('|'.join((when,'paper',PID,state,path.name)).encode()).hexdigest()[:16]
def src(p):return {'path':str(p.relative_to(ROOT)),'sha256':sha(p),'public':True}
def main():
 t=json.loads(OUT.read_text());reg=json.loads((GEN/'paper-registry.json').read_text());p=next(x for x in reg['papers'] if x.get('paper_id')==PID)
 refs={'research_items':[],'experiments':[],'papers':[{'paper_id':PID,'source_research_item':p.get('source_research_item_id',''),'paper_stage':p.get('paper_stage') or p.get('current_state'),'scientific_status':p.get('scientific_status'),'submission_ready':p.get('submission_ready')}],'categories':[]};links=[{'label':'论文','href':f'selected-paper.html?paper={PID}'}];auth={'scientific':False,'scope':'read-only extension/paper history','scope_zh':'只读扩展实验/论文历史；不新增科研、实验、GPU 或投稿授权。','projection_can_change_state':False}
 events_new=[
 {'event_id':eid('2026-08-24T08:33:15+00:00','R16_EXTENSION_ADJUDICATED',ADJ),'occurred_at':'2026-08-24T08:33:15+00:00','time_precision':'exact','event_class':'paper','importance':'key','origin':'artifact_full_history','research_id':PID,'research_label_zh':'E2 · Temporal Skill · R16 extension','title':'Temporal extension adjudicated: appendix integration, planning spin-off stopped','title_zh':'E2 扩展实验裁决：附录吸收，planning 新论文候选停止','state_before':'SUBMISSION_READY','state_after':'R16_EXTENSION_ADJUDICATED','summary':{'en':'Fresh EIA gives N/B/T=.375/1/1, BLS gives .375/.75/1, and real multi-turn TOOL−CONTEXT leaves no residual. Exploratory planning gains on EIA/BLS fail the prospectively frozen Fed falsifier (25% vs 25%), so the planning spin-off is stopped.','zh':'fresh EIA 的 N/B/T=.375/1/1，BLS=.375/.75/1；真实 multi-turn TOOL−CONTEXT 无 residual。EIA/BLS 上 exploratory planning 增益未通过 outcome 前冻结的 Fed falsifier（25% vs 25%），因此 planning 新论文候选停止。'},'why':{'en':'The extension is routed by evidence rather than by a requirement to create a new paper.','zh':'按证据分流，而不是为了必须产生下一篇论文。'},'limitation':{'en':'Each new substrate has four endpoints; follow-up evidence is appendix robustness/boundary and does not rewrite the primary claim.','zh':'每个新 substrate 只有 4 个 endpoint；follow-up 只作为 appendix robustness/boundary，不重写主 claim。'},'next_action':'Integrate EIA/BLS/multi-turn evidence into the same paper appendix; do not create a planning paper.','next_action_zh':'EIA/BLS/multi-turn 进入同篇论文附录；不创建 planning 新论文。','reopen_condition':'A new prospectively frozen independent substrate must show a stable planning-over-single-turn residual under the same-information contract.','reopen_condition_zh':'只有新的 prospectively frozen 独立 substrate 在 same-information contract 下稳定显示 planning>single-turn residual 才重开 planning scientific object。','evidence':[{'label':'fresh EIA N/B/T','value':'.375 / 1.00 / 1.00'},{'label':'BLS N/B/T','value':'.375 / .750 / 1.00'},{'label':'multi-turn','value':'BASE=CONTEXT=TOOL=4/4; TOOL called 2/4'},{'label':'Fed prospective planning','value':'25% vs 25%; 1 win each + 2 ties'}],'authority':auth,'sources':[src(ADJ)],'links':links,'canonical_refs':refs},
 {'event_id':eid('2026-08-24T08:44:31+00:00','R16_EXTENSION_APPENDIX_SUBMISSION_READY',FINAL),'occurred_at':'2026-08-24T08:44:31+00:00','time_precision':'exact','event_class':'paper','importance':'key','origin':'artifact_full_history','research_id':PID,'research_label_zh':'E2 · Temporal Skill · R16','title':'R16 extension appendix finalized on the same E2 scientific contract','title_zh':'E2 R16：同篇论文扩展附录完成，scientific contract 不变','state_before':'SUBMISSION_READY','state_after':'R16_EXTENSION_APPENDIX_SUBMISSION_READY','summary':{'en':'R16 integrates the extension as an appendix without creating a new PaperState or revising the core scientific contract; the paper remains READY / SUBMISSION_READY / NO_INTERNAL_ACTION.','zh':'R16 将扩展实验整合为同篇论文附录，没有创建新 PaperState，也没有修改核心 scientific contract；状态保持 READY / SUBMISSION_READY / NO_INTERNAL_ACTION。'},'why':{'en':'Benign-generic and cross-domain results strengthen attribution boundaries; the failed planning spin-off remains a visible negative result.','zh':'benign-generic 与 cross-domain 结果增强 attribution boundary；失败的 planning spin-off 作为负结果保留。'},'limitation':{'en':'R14 6.0 / Accept remains the latest external review; R16 has not been externally rescored.','zh':'R14 的 6.0 / Accept 仍是最近一次外审；R16 尚未重新外审。'},'next_action':'Freeze R16 for human submission/review; no additional internal experiment is required.','next_action_zh':'冻结 R16，进入人工检查/投稿；当前不再需要内部新增实验。','reopen_condition':'Broaden only under a new scientific contract or a satisfied future reopen condition.','reopen_condition_zh':'只有未来扩大 claim 或满足明确 reopen condition 时再重开。','evidence':[{'label':'Claim Audit','value':'13/13'},{'label':'Paper Preparation','value':'8/8'},{'label':'PDF','value':'17 pages; Conclusion p9; References p10'},{'label':'new paper created','value':'NO'}],'authority':auth,'sources':[src(FINAL)],'links':links,'canonical_refs':refs}
 ]
 paths={s['path'] for e in events_new for s in e['sources']};old=t.get('events',[]);events=[e for e in old if not any(s.get('path') in paths for s in e.get('sources',[]) if isinstance(s,dict))]+events_new;events.sort(key=lambda x:(x.get('occurred_at',''),x.get('importance')=='key',x.get('event_id','')),reverse=True)
 classes=Counter(e.get('event_class') for e in events);dates=Counter(cdate(e.get('occurred_at','')) for e in events);summary=dict(t.get('summary') or {});summary.update({'events':len(events),'dated_structured_artifacts_projected':int(summary.get('dated_structured_artifacts_projected',0))+max(0,2-(len(old)+2-len(events))),'key_events':sum(e.get('importance')=='key' for e in events),'canonical_paper_bound_events':sum(bool((e.get('canonical_refs') or {}).get('papers')) for e in events),'canonical_papers_with_events':len({r.get('paper_id') for e in events for r in (e.get('canonical_refs') or {}).get('papers',[]) if r.get('paper_id')}),'days':len(dates),'class_counts':dict(sorted(classes.items())),'date_counts':dict(sorted(dates.items(),reverse=True))});t['generated_at']=max(e.get('occurred_at','') for e in events);t['summary']=summary;t['events']=events;OUT.write_text(json.dumps(t,ensure_ascii=False,indent=2)+'\n');JS.write_text('window.RESEARCH_TIMELINE = '+json.dumps(t,ensure_ascii=False,separators=(',',':'))+';\n');print(json.dumps({'events_before':len(old),'events_after':len(events),'new_events':[(e['state_after'],e['title_zh']) for e in events_new]},ensure_ascii=False,indent=2))
if __name__=='__main__':main()
