#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p:Path)->dict[str,Any]:return json.loads(p.read_text(encoding='utf-8'))
def req(c:bool,m:str)->None:
    if not c:raise RuntimeError(m)
def atomic(p:Path,d:dict[str,Any])->None:p.parent.mkdir(parents=True,exist_ok=True);t=p.with_suffix(p.suffix+'.tmp');t.write_text(json.dumps(d,ensure_ascii=False,indent=2,sort_keys=True)+'\n',encoding='utf-8');t.replace(p)
def main()->int:
    ap=argparse.ArgumentParser();ap.add_argument('--contract',type=Path,required=True);ap.add_argument('--preflight',type=Path,required=True);ap.add_argument('--output',type=Path,required=True);a=ap.parse_args();req(not a.output.exists(),'recovery2 authorization exists');c=load(a.contract);p=load(a.preflight);cs=sha(a.contract);req(c.get('status')=='FROZEN_E2_R17_SINGLE_CASE_CONSTRAINED_STATE_MICRO','contract drift');req(p.get('status')=='PASS_CONSTRAINED_STATE_MICRO_ZERO_PROVIDER_PREFLIGHT' and p.get('contract_sha256')==cs,'preflight drift');req(int(p.get('parent_completed_measurements',-1))==45 and int(p.get('new_measurements',-1))==27,'preflight cardinality drift');req(int(p.get('child_provider_total_limit',-1))==123,'preflight budget drift');req(p.get('scientific_outcomes_read') is False,'preflight outcome leak');req(not Path(c['run_root']).exists() and not Path(c['lineage_lease_path']).exists(),'child root/lease no longer fresh')
    payload={'schema_version':'1.0','artifact_type':'e2-r17-constrained-state-micro-recovery2-measurement-authorization','created_at_utc':datetime.now(timezone.utc).isoformat(timespec='seconds'),'status':'AUTHORIZED_E2_R17_SINGLE_CASE_CONSTRAINED_STATE_MICRO_MEASUREMENT','contract_path':str(a.contract.resolve()),'contract_sha256':cs,'preflight_path':str(a.preflight.resolve()),'preflight_sha256':sha(a.preflight),'mindmemos_commit':c['mindmemos']['commit'],'single_use':True,'authority':{'scientific_experiment':True,'measurement_only':True,'provider_io':True,'updater':False,'analyzer':False,'second_backbone':False,'public_benchmark':False,'e3_confirmation':False,'paper_promotion':False,'submission':False},'execution_scope':{'measurement_child':'E2-R17-SINGLE-CASE-CONSTRAINED-STATE-MICRO','allowed_modes':['e1'],'allowed_task_ids':c['heldout_task_ids'],'exact_k':1,'allow_noninitial_skill':True,'state_arms':[x['arm'] for x in c['states']],'state_skill_sha256':{x['arm']:x['skill_sha256'] for x in c['states']},'required_resolved_model':c['actor']['resolved_model'],'identity_artifact_sha256':c['model_identity']['sha256'],'suite_manifest_sha256':c['suite']['suite_manifest_sha256'],'split_manifest_sha256':c['suite']['split_manifest_sha256'],'max_turns':c['actor']['max_turns'],'max_output_tokens':c['actor']['max_output_tokens'],'provider_budget':{'required':True,'total_limit':123,'per_unit_limit':11},'exactly_once':True,'automatic_retry':False,'partial_effect_read':False,'lineage_lease_path':c['lineage_lease_path']},'interpretation_boundary':'Recovery2 completes only the 27 unresolved deterministic-state measurements while inheriting 45 parent-completed measurements. No updater calls or completed-unit replay.'};atomic(a.output,payload);print(json.dumps(payload,ensure_ascii=False,indent=2,sort_keys=True));return 0
if __name__=='__main__':raise SystemExit(main())
