#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; sys.path.insert(0,str(ROOT))
from research_pipeline.paper_acceptance import *
from research_pipeline.paper_acceptance_ledger import (_append,_digest,advance_paper_ledger,build_paper_ledger_index,load_paper_ledger,record_claim_audit,record_manuscript_ci,record_mock_review,record_prebuttal,record_story_search,record_submission_readiness,reopen_ready_paper_contract,validate_paper_ledger)
PID="D2-PAPER-TEMPORAL-SKILL-CAUSAL-BOTTLENECK"; OLD="a3942d3f7bb384893faf3649ce966419b5729dd6108c7b7b8d5fe76d3ad3025c"; TITLE="When Do Reusable Temporal Procedures Actually Repair Agents?"
PDF="80580931de3e85b5fc68756772a8b5186cbf50c1d29d77dd6935e8fa3b9290de"; SRC="1b6a85d3942af1899b9f52df368c00ac981861c048b3fcd8760bc8d4d8da5a8c"; SUP="710ebd1b56fdec3c984572c68b19d0cf86c368cd55eb15df69beaf45cde705d9"
CA="4aee386e93495dd02053eaf1bfb33aee5d1d1d7ae59d881f1d26f91955942707"; VR="2927462c2464ca426022b3a8779027edf1010d225b207c122e55d7affdffdc24"; PM="922947d1153a5851ffd8b2bf9e59cc3960b572a505b9271f254040651af97341"; O4="43ea0646c8343474e586b4139b44ea0877464bc1229f817496eb1905f2631c5e"; O5="796c10e89d8f8e584e9f78270d801bc51974f36785cc95b779c59619fd035bde"; A2="210681be63752e7bb87978edbe15bb471ad27d5067d600c08cffe9b6d3f7cc39"; KG="5f9700fc6d414e546a631482dc3ccd9c409f3bb5b9210323762a7543beba8bff"; OD="88e544558d6432a5dce6fd33e3fb7317b29055e187470c076d9ad975e668220f"; OK="afcfd902c2880ff055feab1e6ebc6ad45939bd2cce28c7cdbaa75b01ab19ea70"
A=lambda x:f"artifact:sha256:{x}"
def sf(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def contract(prev):
 refs=tuple(dict.fromkeys([*(prev.get('evidence_refs') or []),*[A(x) for x in (O4,O5,A2,KG,OD,OK)]]))
 return PaperContract(PID,TITLE,"When does a reusable temporal operation repair a recurring failure, and is callable skill state necessary once operation content and evidence are fixed?",{
  "C1":prev['supported_claims']['C1'],
  "C2":"TimeSage-1.0 reports aggregate skill-library gains and a 0.82x token-cost ratio, but that source-level comparison does not identify operation value or callable-container value.",
  "C3":"On the source-native BEA/NOAA/EIA replay, reusable temporal operations are binding repairs in specific non-ceiling model-task regimes after original-agent and behavior-neutral-helper controls; the effect is not universal and Kimi same-domain grounding is not positive under the stronger fresh control.",
  "C4":"On 18 pre-frozen DeepSeek load-bearing endpoints, operation-matched retrieval/context construction has T-R=0.0 points with 90% CI [-5.6,5.6]; three held-out Kimi alignment endpoints also tie, so no material callable-container advantage is supported."
 },{"U1":"All recurring temporal failures are caused by missing reusable procedures.","U2":"Callable skill state is necessary or superior to operation-matched retrieval/context construction.","U3":"The temporal-procedure effect is model-invariant or generally cross-domain."},(
  "The frozen TimeSage-EV evaluated snapshot remains unavailable, so BEA/NOAA/EIA is independent source-native evidence rather than an exact rerun.",
  "The 35 endpoint units have uneven resolution; Kimi alignment has three endpoints, Kimi same-domain grounding has two, and cross-domain grounding is null.",
  "G0 neutrality holds only under the frozen +/-10-point rule on the tested DeepSeek and Kimi tracks; it does not make historical G neutral.",
  "R is a strong same-information integration control for the exact frozen operation output, not an exhaustive equivalence result for all learned retrievers or context budgets.",
  "Endpoints are independent scientific units; repeats characterize runtime robustness only."
 ),("Reopen callable-container value only if a prospectively matched same-information comparison yields a reproducible material T-R residual beyond 10 points.","Treat a future first-party TimeSage-EV evaluated snapshot as an external replication target."),refs,ScientificPaperStatus.READY)
def stories(): return [StoryCandidate("R13-OPERATION-FIRST","Operation-first identification ladder","Lead with the two-arm false positive, then N, G0, and operation-matched R; positive and downgrade cells define the boundary.",( "C3","C4","C1","C2"),("C3","C4","C1","C2")),StoryCandidate("R13-REGIME-FIRST","Regime boundary first","Lead with binding versus ceiling/null regimes, then separate operation value from helper and container effects.",( "C3","C1","C4","C2"),("C3","C4"))]
def reviews():
 b=[ReviewerObjection("B1","causal-identification","Preserve N/G0 anchors so generic-helper harm is not called repair.",True,ObjectionEvidenceState.EXISTING_EVIDENCE,("C3",)),ReviewerObjection("B2","scope","Fresh Kimi grounding removes earlier cross-model grounding support.",True,ObjectionEvidenceState.EXISTING_EVIDENCE,("C3",)),ReviewerObjection("B3","external-validity","Do not imply exact TimeSage-EV rerun.",False,ObjectionEvidenceState.EXISTING_EVIDENCE,("C1","C3"))]
 a=[ReviewerObjection("A1","statistics","Do not pool inconclusive A1 with frozen A2 to manufacture equivalence.",True,ObjectionEvidenceState.EXISTING_EVIDENCE,("C3",)),ReviewerObjection("A2","treatment-parity","R must preserve candidates and exact frozen operation output.",True,ObjectionEvidenceState.EXISTING_EVIDENCE,("C4",)),ReviewerObjection("A3","reproducibility","Preserve raw/CSV/JSONL/checkpoint unit receipts.",False,ObjectionEvidenceState.EXISTING_EVIDENCE,("C3","C4"))]; return b,a
def trans(root,c,s,refs):
 r=advance_paper_ledger(root,c,s,actor="temporal-r13-gate",artifact_refs=refs)['receipt']
 if r.get('allowed') is not True: raise RuntimeError(f"blocked {s.value}: {r.get('blockers')}")
def v(root,c,t,p):
 x={"event_type":t,"schema_version":"1.0","paper_id":PID,"revision":"r13",**p,"scientific_authority":False,"experiment_authority":False,"gpu_authority":False,"submission_authority":False}; x['receipt_sha256']=_digest({k:v for k,v in x.items() if k!='receipt_sha256'}); _append(root,c,"temporal-r13-finalization",x)
def finalize(root,out):
 binds={ROOT/'downloads/E2-Temporal-Skill-r13-20260824.pdf':PDF,ROOT/'downloads/E2-Temporal-Skill-r13-20260824-source.zip':SRC,ROOT/'downloads/E2-Temporal-Skill-r13-20260824-supplement.zip':SUP,ROOT/'generated/temporal-skill-r13-claim-audit-20260824.json':CA,ROOT/'generated/temporal-skill-r13-verification-20260824.json':VR,ROOT/'generated/temporal-skill-r13-package-manifest-20260824.json':PM,ROOT/'generated/temporal-skill-g0-temp-o4-closure-20260824.json':O4,ROOT/'generated/temporal-skill-temp-o5-closure-20260824.json':O5}
 for p,h in binds.items():
  if not p.exists() or sf(p)!=h: raise RuntimeError(f"artifact mismatch {p}")
 before=load_paper_ledger(root,PID); bh=_digest(before)
 if (before.get('contract') or {}).get('title')==TITLE and any(e.get('event_type')=='source-native-r13-finalization' for e in before.get('events') or [] if isinstance(e,dict)):
  if validate_paper_ledger(before): raise RuntimeError('existing R13 ledger invalid')
  return {"status":"ALREADY_FINALIZED","after_sha256":bh,"current_state":before.get('current_state')}
 if before.get('contract_sha256')!=OLD or before.get('current_state')!='SUBMISSION_READY': raise RuntimeError('unexpected pre-R13 ledger state')
 c=contract(before['contract']); reopen_ready_paper_contract(root,c,reopen_evidence_refs=(A(O4),A(O5),A(A2),A(OD)),superseded_claims={"C2":"The source aggregate remains factual but cannot identify operation or container value after G0/R."},reason="Fresh G0/R evidence resolves C3/C4 debt, downgrades Kimi grounding, and changes the supported identification boundary.",actor="temporal-r13-reopen")
 pref=(A(PDF),A(O4),A(O5),A(VR)); trans(root,c,PaperState.PAPER_DESIGN,pref); record_story_search(root,c,stories(),actor="temporal-r13-story"); trans(root,c,PaperState.MANUSCRIPT,(A(PDF),)); trans(root,c,PaperState.MOCK_PC,(A(PDF),))
 b,a=reviews(); record_mock_review(root,c,MockReviewMode.BLIND_MANUSCRIPT,b,actor="temporal-r13-blind"); record_mock_review(root,c,MockReviewMode.ARTIFACT_AWARE,a,actor="temporal-r13-artifact"); trans(root,c,PaperState.TARGETED_REPAIR,pref); trans(root,c,PaperState.CLAIM_AUDIT,(A(PDF),A(CA)))
 record_claim_audit(root,c,manuscript_ref=A(PDF),claimed_ids=("C1","C2","C3","C4"),evidence_bound_claim_ids=("C1","C2","C3","C4"),limitations_preserved=True,actor="temporal-r13-claim"); trans(root,c,PaperState.PDF_QA,(A(PDF),A(VR)))
 record_manuscript_ci(root,c,{k:True for k in MANDATORY_MANUSCRIPT_CI_CHECKS},actor="temporal-r13-ci"); trans(root,c,PaperState.PREBUTTAL,(A(PDF),A(VR)))
 obs=[*b,*a]; rr={"B1":(A(O4),),"B2":(A(KG),A(O4)),"A1":(A(A2),A(O4)),"A2":(A(OD),A(O5))}; record_prebuttal(root,c,obs,[PrebuttalResolution(o.objection_id,True,rr.get(o.objection_id,(A(VR),))) for o in obs],actor="temporal-r13-prebuttal"); record_submission_readiness(root,c,actor="temporal-r13-ready"); trans(root,c,PaperState.SUBMISSION_READY,(A(PDF),A(VR)))
 v(root,c,"claim-audit-r13",{"pass":True,"checks":31,"passed":31,"blockers":[],"claim_audit_sha256":CA,"artifact_ref":A(CA),"claim_expansion":False,"TEMP_O4_resolved":True,"TEMP_O5_resolved":True,"TEMP_O6_permanent_claim_boundary":True})
 v(root,c,"paper-preparation-r13",{"receipt_type":"paper-preparation","protocol_version":"1.0+r13-g0-retrieval-closure","pass":True,"required_gates":8,"passed_gates":8,"gate_pass":{k:True for k in ("hierarchical-rubric","verification-refinement","citation-integrity","visual-story","reproducibility-bundle","agent-native-artifact","reader-simulation","submission-package")},"blockers":[],"paper_pdf_sha256":PDF,"source_zip_sha256":SRC,"supplement_zip_sha256":SUP,"new_external_reviewer_run":False})
 v(root,c,"prebuttal-r13",{"receipt_type":"prebuttal","pass":True,"decision_critical":4,"unresolved_decision_critical":0,"blockers":[],"new_external_reviewer_run":False,"internal_blind_and_artifact_modes_rerun":True})
 v(root,c,"submission-readiness-r13",{"receipt_type":"submission-readiness","submission_ready":True,"manuscript_ci_pass":True,"paper_preparation_pass":True,"prebuttal_pass":True,"blockers":[],"paper_pdf_sha256":PDF,"source_zip_sha256":SRC,"supplement_zip_sha256":SUP})
 v(root,c,"submission-readiness-context-r13",{"receipt_type":"submission-readiness-context","artifact_submission_ready":True,"current_state":"SUBMISSION_READY","scientific_status":"READY","support_blocker":"","recommended_immediate_submission":"READY_FOR_HUMAN_SUBMISSION","external_human_submission_authority_required":True,"external_human_submission_authority_required_for_SUBMITTED":True,"paper_pdf_sha256":PDF,"source_zip_sha256":SRC,"supplement_zip_sha256":SUP,"exact_timesage_replication_debt":"ACTIVE_EXTERNAL_REPLICATION_DEBT_NOT_SUBSTITUTED","TEMP_O4":"RESOLVED_WITH_KIMI_GROUNDING_DOWNGRADE","TEMP_O5":"RESOLVED_NO_MATERIAL_CALLABLE_CONTAINER_ADVANTAGE","TEMP_O6":"PERMANENT_CLAIM_BOUNDARY","new_external_reviewer_run":False})
 v(root,c,"source-native-r13-finalization",{"receipt_type":"source-native-finalization","artifact_ref":A(PM),"title":TITLE,"paper_pdf_sha256":PDF,"source_zip_sha256":SRC,"supplement_zip_sha256":SUP,"source_native_runtime_valid_rows":2056,"distinct_endpoints":35,"institutional_systems":3,"exact_timesage_replication_debt":"ACTIVE_EXTERNAL_REPLICATION_DEBT_NOT_SUBSTITUTED","recommended_immediate_action":"READY_FOR_HUMAN_SUBMISSION","new_formal_model_calls":730,"failed_auto_route_calls_zero_scientific_authority":1,"TEMP_O4_resolved":True,"TEMP_O5_resolved":True,"Kimi_grounding_downgraded":True,"callable_container_advantage_supported":False,"claim_expansion":False})
 after=load_paper_ledger(root,PID); errs=validate_paper_ledger(after)
 if errs: raise RuntimeError('ledger invalid: '+';'.join(errs))
 idx=build_paper_ledger_index(root); pub=next(x for x in idx['entries'] if x.get('paper_id')==PID)
 if pub.get('title')!=TITLE or (pub.get('source_native_evidence') or {}).get('runtime_valid_rows')!=2056: raise RuntimeError('public projection stale')
 res={"schema_version":"1.0","receipt_type":"temporal-r13-canonical-ledger-finalization","paper_id":PID,"status":"FINALIZED_R13_SUBMISSION_READY","before_sha256":bh,"after_sha256":_digest(after),"previous_contract_sha256":OLD,"current_contract_sha256":after.get('contract_sha256'),"current_state":after.get('current_state'),"title":pub.get('title'),"runtime_valid_rows":2056,"TEMP_O4":"RESOLVED_WITH_KIMI_GROUNDING_DOWNGRADE","TEMP_O5":"RESOLVED_NO_MATERIAL_CALLABLE_CONTAINER_ADVANTAGE","TEMP_O6":"PERMANENT_CLAIM_BOUNDARY","submission_authority":False,"scientific_authority":False}; res['receipt_sha256']=_digest(res); out.parent.mkdir(parents=True,exist_ok=True); out.write_text(json.dumps(res,ensure_ascii=False,indent=2)+'\n'); return res
def main():
 p=argparse.ArgumentParser(); p.add_argument('--root',type=Path,default=Path('/data/wyt/agent-self-evolution-observatory')); p.add_argument('--output',type=Path,default=ROOT/'generated/temporal-skill-r13-ledger-finalization-20260824.json'); a=p.parse_args(); print(json.dumps(finalize(a.root,a.output),ensure_ascii=False,indent=2))
if __name__=='__main__': main()
