#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; sys.path.insert(0,str(ROOT))
from research_pipeline.paper_acceptance import *
from research_pipeline.paper_acceptance_ledger import (_append,_digest,advance_paper_ledger,build_paper_ledger_index,load_paper_ledger,record_claim_audit,record_manuscript_ci,record_mock_review,record_prebuttal,record_story_search,record_submission_readiness,reopen_ready_paper_contract,validate_paper_ledger)
PID="D2-PAPER-TEMPORAL-SKILL-CAUSAL-BOTTLENECK"; OLD="11b28d21ca311b04f2de9a0f312dd45e4b71c809c019c271cb9dab2612e96be5"; TITLE="Do Temporal Skills Really Repair Agents? An Intervention Audit of Repair and Attribution"
PDF="0fef51f15bb188fc669411be8d6dedaeae7d83389cec3f5d917f9a120fe2906e"; SRC="809fd3a52b5263bc8944b361ebc5bafcc2da7d615fec2b4a900a39127f485c0f"; SUP="0cd9aee6f5a23bc0d5818bb42300c437a8c12df822d03230510e6073af127b0d"
CA="ea1a875bd82e70ae49feea7b676920c7c95a3d6ee978370af2e4998a3daa2e23"; VR="61496383d625464666a8888e237592364f8dd8f63ae54b34dbc07a0d305f638e"; PM="d7cea3b17b4c89ea65e292de1a8730dcaa0f08c93f7fc43121e0f10083bbabfc"; IA="50149a98ee9f09d84807975cf8c36458866a82af9590341ac4f53bf57222d27a"; RC="0ad428f6158f40f26f04fb8a8780400ed2ff76da8cec861f87fb7cf08fb5fca9"; CD="c9ee7d56612fe90af1c0cbe470ba5988a19a10670ba2828b05f6e36d4bace84e"
A=lambda x:f"artifact:sha256:{x}"
def sf(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def contract(prev):
 refs=tuple(dict.fromkeys([*(prev.get('evidence_refs') or []),A(IA),A(CA),A(RC),A(PM),A(CD)]))
 return PaperContract(PID,TITLE,"When does an apparent reusable temporal-skill effect represent net repair, surface perturbation, or an integration-surface effect under matched evidence?",{
  "C1":"A targeted-versus-mechanism-misaligned stress-helper comparison can look positive without net repair: on DeepSeek C3 cutoff T=100%, G=72%, N=100%, with endpoint means T-G=4 wins/1 tie/0 losses and T-N=0 wins/5 ties/0 losses.",
  "C2":"Net repair (T-N), the same-surface operation-output contrast (T-G0), and placebo/surface perturbation (G0-N) must remain separate; when G0-N is nonzero, T-G0 is not a pure operation effect. The EIA post-hoc compatibility probe illustrates +37.5 = +62.5 - 25 points and is classified as net repair with surface interaction.",
  "C3":"After stronger controls, positive repair evidence is bounded and low-resolution: fresh DeepSeek C3/C4 grounding is directional on five endpoints per cell, Kimi same-domain grounding is downgraded, cross-domain grounding is null, and EIA is only a post-hoc compatibility probe rather than prospective cross-domain confirmation.",
  "C4":"On 18 pre-frozen DeepSeek endpoints, exact-output R_surf gives mean T-R_surf=0 with a passing TOST at the frozen +/-10-point portfolio margin, but the check has about 53% observed-variance sensitivity, a ceiling-heavy portfolio, and an unresolved four-endpoint strictly non-ceiling subset; it does not establish multi-turn callable-state or temporal-retrieval equivalence."
 },{"U1":"G0 is behaviorally neutral in every load-bearing stratum.","U2":"T-G0 is a pure operation effect when G0-N is nonzero.","U3":"EIA is prospective or independently sampled cross-domain confirmation.","U4":"R_surf is an independent temporal-retrieval baseline or establishes general skill-versus-retrieval equivalence.","U5":"Callable state is irrelevant in adaptive multi-turn deployment.","U6":"The TimeSage-EV evaluated snapshot has been exactly replicated."},(
  "The TimeSage-EV evaluated snapshot remains unavailable; the source-native replay is independent mechanistic evidence, not an exact rerun.",
  "DeepSeek grounding has five endpoints per cell; Kimi alignment has three endpoints and Kimi grounding two, so small cells are directional/descriptive rather than high-resolution.",
  "G0 is a same-surface placebo, not a universally neutral control; full-track equivalence does not transport to every stratum.",
  "EIA is a post-hoc compatibility probe selected for a dated-release structure compatible with the cutoff mechanism.",
  "R_surf is a forced-one-answer exact-output surface check; its passing +/-10-point portfolio TOST has low observed-variance sensitivity and does not resolve the strictly non-ceiling subset.",
  "Adaptive multi-turn callable interfaces and independently designed temporal retrievers are outside the experiment."
 ),("Treat a future first-party TimeSage-EV evaluated snapshot as an external replication target.","Reopen broader integration-surface claims only with prospectively powered non-ceiling endpoints or an adaptive multi-turn interface test.","Reopen temporal-retrieval equivalence only with an independently implemented retriever/reranker receiving the same raw candidate evidence."),refs,ScientificPaperStatus.READY)
def stories(): return [StoryCandidate("R14-AUDIT-FIRST","Verdict-changing intervention audit","Lead with the T>G but T=N false positive, then the T-N/T-G0/G0-N decomposition, bounded positive cells, and the low-sensitivity R_surf surface check.",("C1","C2","C3","C4"),("C1","C2","C4")),StoryCandidate("R14-ATTRIBUTION-FIRST","Attribution layers before skill credit","Lead with the four contrasts and show how stronger controls preserve, narrow, or reverse apparent skill effects.",("C2","C1","C4","C3"),("C2","C1","C4"))]
def reviews():
 b=[ReviewerObjection("B1","attribution","Do not call T-G0 a pure operation effect when G0-N is nonzero.",True,ObjectionEvidenceState.EXISTING_EVIDENCE,("C2",)),ReviewerObjection("B2","scope","Treat EIA only as a post-hoc compatibility probe and keep small DeepSeek/Kimi cells low-resolution.",True,ObjectionEvidenceState.EXISTING_EVIDENCE,("C3",)),ReviewerObjection("B3","surface-scope","Do not turn R_surf into a general callable-state or temporal-retrieval equivalence claim.",True,ObjectionEvidenceState.EXISTING_EVIDENCE,("C4",))]
 a=[ReviewerObjection("A1","statistics","Keep the passing TOST paired with the 53% sensitivity and unresolved non-ceiling subset.",True,ObjectionEvidenceState.EXISTING_EVIDENCE,("C4",)),ReviewerObjection("A2","reproducibility","Preserve raw/CSV/JSONL/checkpoint evidence and exact-output R_surf parity receipts.",False,ObjectionEvidenceState.EXISTING_EVIDENCE,("C2","C4")),ReviewerObjection("A3","external-replication","Do not imply exact TimeSage-EV replication.",False,ObjectionEvidenceState.EXISTING_EVIDENCE,("C3",))]; return b,a
def trans(root,c,s,refs):
 r=advance_paper_ledger(root,c,s,actor="temporal-r14-gate",artifact_refs=refs)['receipt']
 if r.get('allowed') is not True: raise RuntimeError(f"blocked {s.value}: {r.get('blockers')}")
def v(root,c,t,p):
 x={"event_type":t,"schema_version":"1.0","paper_id":PID,"revision":"r14",**p,"scientific_authority":False,"experiment_authority":False,"gpu_authority":False,"submission_authority":False}; x['receipt_sha256']=_digest({k:v for k,v in x.items() if k!='receipt_sha256'}); _append(root,c,"temporal-r14-finalization",x)
def finalize(root,out):
 binds={ROOT/'downloads/E2-Temporal-Skill-r14-20260824.pdf':PDF,ROOT/'downloads/E2-Temporal-Skill-r14-20260824-source.zip':SRC,ROOT/'downloads/E2-Temporal-Skill-r14-20260824-supplement.zip':SUP,ROOT/'generated/temporal-skill-r14-claim-audit-20260824.json':CA,ROOT/'generated/temporal-skill-r14-verification-20260824.json':VR,ROOT/'generated/temporal-skill-r14-package-manifest-20260824.json':PM,ROOT/'generated/temporal-skill-r14-identification-audit-20260824.json':IA,ROOT/'generated/temporal-skill-r14-review-closure-20260824.json':RC,ROOT/'generated/temporal-skill-r14-contrast-decomposition-20260824.csv':CD}
 for p,h in binds.items():
  if not p.exists() or sf(p)!=h: raise RuntimeError(f"artifact mismatch {p}")
 before=load_paper_ledger(root,PID); bh=_digest(before)
 if (before.get('contract') or {}).get('title')==TITLE and any(e.get('event_type')=='source-native-r14-finalization' for e in before.get('events') or [] if isinstance(e,dict)):
  if validate_paper_ledger(before): raise RuntimeError('existing R14 ledger invalid')
  return {"status":"ALREADY_FINALIZED","after_sha256":bh,"current_state":before.get('current_state')}
 if before.get('contract_sha256')!=OLD or before.get('current_state')!='SUBMISSION_READY': raise RuntimeError('unexpected pre-R14 ledger state')
 c=contract(before['contract']); reopen_ready_paper_contract(root,c,reopen_evidence_refs=(A(IA),A(CA),A(RC),A(PM)),superseded_claims={k:"R14 internal-review falsification narrows attribution and scope; replace the R13 supported claim with the auditable R14 formulation." for k in ("C1","C2","C3","C4")},reason="R14 adds no scientific outcomes; it re-adjudicates existing G0/R_surf evidence, removes transported G0-neutrality and independent-retrieval interpretations, and narrows EIA/non-ceiling claims.",actor="temporal-r14-reopen")
 pref=(A(PDF),A(IA),A(CA),A(RC)); trans(root,c,PaperState.PAPER_DESIGN,pref); record_story_search(root,c,stories(),actor="temporal-r14-story"); trans(root,c,PaperState.MANUSCRIPT,(A(PDF),)); trans(root,c,PaperState.MOCK_PC,(A(PDF),))
 b,a=reviews(); record_mock_review(root,c,MockReviewMode.BLIND_MANUSCRIPT,b,actor="temporal-r14-blind"); record_mock_review(root,c,MockReviewMode.ARTIFACT_AWARE,a,actor="temporal-r14-artifact"); trans(root,c,PaperState.TARGETED_REPAIR,pref); trans(root,c,PaperState.CLAIM_AUDIT,(A(PDF),A(CA)))
 record_claim_audit(root,c,manuscript_ref=A(PDF),claimed_ids=("C1","C2","C3","C4"),evidence_bound_claim_ids=("C1","C2","C3","C4"),limitations_preserved=True,actor="temporal-r14-claim"); trans(root,c,PaperState.PDF_QA,(A(PDF),A(VR)))
 record_manuscript_ci(root,c,{k:True for k in MANDATORY_MANUSCRIPT_CI_CHECKS},actor="temporal-r14-ci"); trans(root,c,PaperState.PREBUTTAL,(A(PDF),A(VR)))
 obs=[*b,*a]; rr={"B1":(A(IA),A(CD)),"B2":(A(IA),A(CA)),"B3":(A(CA),A(RC)),"A1":(A(IA),A(CA)),"A2":(A(SUP),A(VR)),"A3":(A(CA),)}; record_prebuttal(root,c,obs,[PrebuttalResolution(o.objection_id,True,rr[o.objection_id]) for o in obs],actor="temporal-r14-prebuttal"); record_submission_readiness(root,c,actor="temporal-r14-ready"); trans(root,c,PaperState.SUBMISSION_READY,(A(PDF),A(VR)))
 v(root,c,"claim-audit-r14",{"receipt_type":"claim-audit","pass":True,"checks":13,"passed":13,"blockers":[],"claim_audit_sha256":CA,"artifact_ref":A(CA),"new_scientific_execution":False,"new_experiment_required_by_final_internal_panel":False})
 v(root,c,"paper-preparation-r14",{"receipt_type":"paper-preparation","protocol_version":"1.0+r14-intervention-audit","pass":True,"required_gates":8,"passed_gates":8,"gate_pass":{k:True for k in ("hierarchical-rubric","verification-refinement","citation-integrity","visual-story","reproducibility-bundle","agent-native-artifact","reader-simulation","submission-package")},"blockers":[],"paper_pdf_sha256":PDF,"source_zip_sha256":SRC,"supplement_zip_sha256":SUP,"new_external_reviewer_run":False})
 v(root,c,"prebuttal-r14",{"receipt_type":"prebuttal","pass":True,"decision_critical":4,"unresolved_decision_critical":0,"blockers":[],"internal_review_final_scores":[6,6,5],"final_review_new_experiment_required":False,"new_external_reviewer_run":False})
 v(root,c,"submission-readiness-r14",{"receipt_type":"submission-readiness","submission_ready":True,"manuscript_ci_pass":True,"paper_preparation_pass":True,"prebuttal_pass":True,"blockers":[],"paper_pdf_sha256":PDF,"source_zip_sha256":SRC,"supplement_zip_sha256":SUP})
 v(root,c,"submission-readiness-context-r14",{"receipt_type":"submission-readiness-context","artifact_submission_ready":True,"current_state":"SUBMISSION_READY","scientific_status":"READY","support_blocker":"","recommended_immediate_submission":"READY_FOR_HUMAN_SUBMISSION","external_human_submission_authority_required":True,"external_human_submission_authority_required_for_SUBMITTED":True,"paper_pdf_sha256":PDF,"source_zip_sha256":SRC,"supplement_zip_sha256":SUP,"exact_timesage_replication_debt":"ACTIVE_EXTERNAL_REPLICATION_DEBT_NOT_SUBSTITUTED","new_experiment_required_for_current_narrow_claim":False,"R14_claim_boundary":"INTERVENTION_AUDIT_LOW_RESOLUTION_NO_GENERAL_RETRIEVAL_OR_MULTI_TURN_EQUIVALENCE","new_external_reviewer_run":False})
 v(root,c,"source-native-r14-finalization",{"receipt_type":"source-native-finalization","artifact_ref":A(PM),"title":TITLE,"paper_pdf_sha256":PDF,"source_zip_sha256":SRC,"supplement_zip_sha256":SUP,"source_native_runtime_valid_rows":2056,"distinct_endpoints":35,"institutional_systems":3,"exact_timesage_replication_debt":"ACTIVE_EXTERNAL_REPLICATION_DEBT_NOT_SUBSTITUTED","recommended_immediate_action":"READY_FOR_HUMAN_SUBMISSION","new_scientific_model_calls":0,"internal_zero_authority_review_calls":9,"claim_expansion":False})
 after=load_paper_ledger(root,PID); errs=validate_paper_ledger(after)
 if errs: raise RuntimeError('ledger invalid: '+';'.join(errs))
 idx=build_paper_ledger_index(root); pub=next(x for x in idx['entries'] if x.get('paper_id')==PID)
 if pub.get('title')!=TITLE or (pub.get('source_native_evidence') or {}).get('runtime_valid_rows')!=2056: raise RuntimeError('public projection stale')
 res={"schema_version":"1.0","receipt_type":"temporal-r14-canonical-ledger-finalization","paper_id":PID,"status":"FINALIZED_R14_SUBMISSION_READY","before_sha256":bh,"after_sha256":_digest(after),"previous_contract_sha256":OLD,"current_contract_sha256":after.get('contract_sha256'),"current_state":after.get('current_state'),"title":pub.get('title'),"runtime_valid_rows":2056,"new_scientific_execution":False,"new_experiment_required_for_current_narrow_claim":False,"submission_authority":False,"scientific_authority":False}; res['receipt_sha256']=_digest(res); out.parent.mkdir(parents=True,exist_ok=True); out.write_text(json.dumps(res,ensure_ascii=False,indent=2)+'\n'); return res
def main():
 p=argparse.ArgumentParser(); p.add_argument('--root',type=Path,default=Path('/data/wyt/agent-self-evolution-observatory')); p.add_argument('--output',type=Path,default=ROOT/'generated/temporal-skill-r14-ledger-finalization-20260824.json'); a=p.parse_args(); print(json.dumps(finalize(a.root,a.output),ensure_ascii=False,indent=2))
if __name__=='__main__': main()
