#!/usr/bin/env python3
from __future__ import annotations
import argparse,hashlib,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from research_pipeline.paper_acceptance import PaperContract,ScientificPaperStatus
from research_pipeline.paper_acceptance_ledger import _append,_digest,build_paper_ledger_index,load_paper_ledger,validate_paper_ledger
PID='D2-PAPER-TEMPORAL-SKILL-CAUSAL-BOTTLENECK';CONTRACT='6d992c931f076f805a0aa0bc24edd731b3b668ab37710a7befe313d8c31e0dae';TITLE='Do Temporal Skills Really Repair Agents? An Intervention Audit of Repair and Attribution'
PDF='b660df039bf5b431eab7855a17c2fc2e19df405e06dde1cf59802351e4f48f4c';SRC='79346dd8dc45fa8ae6bbc971781aed15050b6ffc37c5cb724ad63f56561380a2';SUP='c78ced1f9031593ac49afca11c0fff1fefb3677210ed1a568de51851e5e6bb13'
REVIEW='9a0fe9e07677a763e0a5f112cfe4b29257b71f0a0a775bf0169d162ec3d36890';ADJ='0208f83d5c55a891c95e21f795f4ceaceb6593b3af643167e3e9d89cf55db8d5';POWER='8f7e486568c29b1a6ee04827fc8e2fbbbacecfd9e9bd19ef4dff41d9376e7445';CLOSURE='054aa83f7dd472c0561a6a6a64617d01f89b8b43ed1cfc81cb56ba0f67b33d89';CA='6d955f687b0b8efaa6c68dc17110c1812dcb6b9a3d155d284310235d8cd9420b';VR='adfdeb1b856a89aa910a2c40fcabd9a4bf8bdfa2324989d8b540cf2e0e2318c0';PM='0759a99bd5ccd4cbe45ae2cf50ad0a227fcc6b362f1059c3f0373fa91a414237'
A=lambda x:f'artifact:sha256:{x}'
def sha(p:Path):return hashlib.sha256(p.read_bytes()).hexdigest()
def contract(raw):return PaperContract(PID,raw['title'],raw['central_question'],raw['supported_claims'],raw.get('unsupported_claims') or {},tuple(raw.get('limitations') or ()),tuple(raw.get('reopen_conditions') or ()),tuple(raw.get('evidence_refs') or ()),ScientificPaperStatus(raw['scientific_status']))
def event(root,c,kind,payload):
 x={'event_type':kind,'schema_version':'1.0','paper_id':PID,'revision':'r15',**payload,'scientific_authority':False,'experiment_authority':False,'gpu_authority':False,'submission_authority':False};x['receipt_sha256']=_digest({k:v for k,v in x.items() if k!='receipt_sha256'});_append(root,c,'temporal-r15-targeted-repair',x);return x
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--root',type=Path,default=Path('/data/wyt/agent-self-evolution-observatory'));ap.add_argument('--output',type=Path,default=ROOT/'generated/temporal-skill-r15-ledger-finalization-20260824.json');a=ap.parse_args()
 binds={ROOT/'downloads/E2-Temporal-Skill-r15-20260824.pdf':PDF,ROOT/'downloads/E2-Temporal-Skill-r15-20260824-source.zip':SRC,ROOT/'downloads/E2-Temporal-Skill-r15-20260824-supplement.zip':SUP,ROOT/'generated/temporal-skill-r14-stanford-review-result-20260824.json':REVIEW,ROOT/'generated/temporal-skill-r14-stanford-adjudication-20260824.json':ADJ,ROOT/'generated/temporal-skill-r14-rsurf-power-planning-20260824.json':POWER,ROOT/'generated/temporal-skill-r15-stanford-closure-20260824.json':CLOSURE,ROOT/'generated/temporal-skill-r15-claim-audit-20260824.json':CA,ROOT/'generated/temporal-skill-r15-verification-20260824.json':VR,ROOT/'generated/temporal-skill-r15-package-manifest-20260824.json':PM}
 for p,h in binds.items():
  if not p.exists() or sha(p)!=h:raise RuntimeError(f'artifact mismatch {p}')
 before=load_paper_ledger(a.root,PID);before_sha=_digest(before)
 if any(e.get('event_type')=='source-native-r15-finalization' for e in before.get('events') or [] if isinstance(e,dict)):
  if validate_paper_ledger(before):raise RuntimeError('existing R15 ledger invalid')
  print(json.dumps({'status':'ALREADY_FINALIZED','contract_sha256':before.get('contract_sha256'),'current_state':before.get('current_state')},indent=2));return
 if before.get('current_state')!='SUBMISSION_READY' or before.get('scientific_status')!='READY' or before.get('contract_sha256')!=CONTRACT:raise RuntimeError('unexpected pre-R15 canonical state')
 c=contract(before['contract'])
 if _digest(before['contract'])==CONTRACT: pass
 # R15 is paper/analysis repair only: do not revise scientific contract or state machine.
 event(a.root,c,'external-review-r14-result',{'receipt_type':'external-review','service':'Stanford Agentic Reviewer · paperreview.ai','reviewed_revision':'R14','numerical_score':6.0,'numeric_score_is_official_iclr_score':False,'textual_verdict':'Accept','artifact_ref':A(REVIEW),'adjudication_ref':A(ADJ),'decision':'ACCEPT_NO_SCIENTIFIC_REOPEN_FOR_CURRENT_NARROW_CLAIM'})
 event(a.root,c,'claim-audit-r15',{'receipt_type':'claim-audit','pass':True,'checks':15,'passed':15,'blockers':[],'claim_audit_sha256':CA,'artifact_ref':A(CA),'claim_expansion':False,'contract_revision':False,'new_scientific_execution':False})
 event(a.root,c,'paper-preparation-r15',{'receipt_type':'paper-preparation','protocol_version':'1.0+r15-stanford-accept-targeted-repair','pass':True,'required_gates':8,'passed_gates':8,'gate_pass':{k:True for k in ('hierarchical-rubric','verification-refinement','citation-integrity','visual-story','reproducibility-bundle','agent-native-artifact','reader-simulation','submission-package')},'blockers':[],'paper_pdf_sha256':PDF,'source_zip_sha256':SRC,'supplement_zip_sha256':SUP,'external_review_textual_verdict':'Accept','external_review_numeric_nonofficial':6.0})
 event(a.root,c,'prebuttal-r15',{'receipt_type':'prebuttal','pass':True,'decision_critical':7,'unresolved_decision_critical':0,'blockers':[],'review_questions':7,'paper_or_existing_data_resolved':6,'future_scientific_reopen_only':1,'new_experiment_now':False,'external_review_textual_verdict':'Accept'})
 event(a.root,c,'submission-readiness-r15',{'receipt_type':'submission-readiness','submission_ready':True,'manuscript_ci_pass':True,'paper_preparation_pass':True,'prebuttal_pass':True,'blockers':[],'paper_pdf_sha256':PDF,'source_zip_sha256':SRC,'supplement_zip_sha256':SUP})
 event(a.root,c,'submission-readiness-context-r15',{'receipt_type':'submission-readiness-context','artifact_submission_ready':True,'current_state':'SUBMISSION_READY','scientific_status':'READY','support_blocker':'','recommended_immediate_submission':'READY_FOR_HUMAN_SUBMISSION','external_human_submission_authority_required':True,'external_human_submission_authority_required_for_SUBMITTED':True,'paper_pdf_sha256':PDF,'source_zip_sha256':SRC,'supplement_zip_sha256':SUP,'exact_timesage_replication_debt':'ACTIVE_EXTERNAL_REPLICATION_DEBT_NOT_SUBSTITUTED','external_review_textual_verdict':'Accept','external_review_numeric_nonofficial':6.0,'new_experiment_required_for_current_narrow_claim':False,'benign_generic':'FUTURE_SCIENTIFIC_REOPEN_ONLY','non_ceiling_expansion':'FUTURE_POWERED_REPLICATION_ONLY'})
 event(a.root,c,'source-native-r15-finalization',{'receipt_type':'source-native-finalization','artifact_ref':A(PM),'title':TITLE,'paper_pdf_sha256':PDF,'source_zip_sha256':SRC,'supplement_zip_sha256':SUP,'source_native_runtime_valid_rows':2056,'distinct_endpoints':35,'institutional_systems':3,'exact_timesage_replication_debt':'ACTIVE_EXTERNAL_REPLICATION_DEBT_NOT_SUBSTITUTED','recommended_immediate_action':'READY_FOR_HUMAN_SUBMISSION','new_scientific_model_calls':0,'new_provider_calls':0,'external_review_textual_verdict':'Accept','external_review_numeric_nonofficial':6.0,'claim_expansion':False,'contract_revision':False})
 after=load_paper_ledger(a.root,PID);errs=validate_paper_ledger(after)
 if errs:raise RuntimeError('ledger invalid: '+';'.join(errs))
 if after.get('contract_sha256')!=CONTRACT or after.get('current_state')!='SUBMISSION_READY' or after.get('scientific_status')!='READY':raise RuntimeError('R15 changed scientific contract/state unexpectedly')
 pub=next(x for x in build_paper_ledger_index(a.root)['entries'] if x.get('paper_id')==PID)
 if (pub.get('latest_claim_audit') or {}).get('checks')!=15 or not (pub.get('latest_submission_readiness') or {}).get('submission_ready'):raise RuntimeError('R15 versioned projection stale')
 result={'schema_version':'1.0','receipt_type':'temporal-r15-canonical-ledger-finalization','paper_id':PID,'status':'FINALIZED_R15_TARGETED_REPAIR_SUBMISSION_READY','before_sha256':before_sha,'after_sha256':_digest(after),'contract_sha256_before':CONTRACT,'contract_sha256_after':after.get('contract_sha256'),'contract_unchanged':after.get('contract_sha256')==CONTRACT,'current_state':after.get('current_state'),'scientific_status':after.get('scientific_status'),'external_review_textual_verdict':'Accept','external_review_numeric_nonofficial':6.0,'new_scientific_execution':False,'new_experiment_now':False,'submission_authority':False,'scientific_authority':False};result['receipt_sha256']=_digest(result);a.output.write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n');print(json.dumps(result,ensure_ascii=False,indent=2))
if __name__=='__main__':main()
