#!/usr/bin/env python3
from __future__ import annotations
import argparse,hashlib,json,subprocess,sys
from datetime import datetime,timezone
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
def sha(p:Path)->str: return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p:Path)->dict[str,Any]: return json.loads(p.read_text(encoding='utf-8'))
def req(x:bool,m:str)->None:
 if not x: raise RuntimeError(m)
def atomic(p:Path,d:dict[str,Any])->None:
 p.parent.mkdir(parents=True,exist_ok=True); t=p.with_suffix(p.suffix+'.tmp'); t.write_text(json.dumps(d,ensure_ascii=False,indent=2,sort_keys=True)+'\n',encoding='utf-8'); t.replace(p)
def bind_state(root:Path,arm:str,parent_contract:str,parent_auth:str)->dict[str,Any]:
 cp=root/'checkpoints/update_completed.json'; req(cp.is_file(),'missing update checkpoint'); row=load(cp); receipt=Path(row['update_receipt_path']); skill=Path(row['skill_post_path']); req(receipt.is_file() and sha(receipt)==row['update_receipt_sha256'],'receipt drift'); req(skill.is_file() and sha(skill)==row['skill_post_sha256'],'skill drift'); ur=load(receipt); req(ur.get('status')=='COMPLETED' and ur.get('contract_sha256')==parent_contract and ur.get('authorization_sha256')==parent_auth,'updater provenance drift'); return {'arm':arm,'state_root':str(root),'skill_post_path':str(skill),'skill_post_sha256':sha(skill),'update_receipt_path':str(receipt),'update_receipt_sha256':sha(receipt)}
def main()->int:
 ap=argparse.ArgumentParser(); ap.add_argument('--v1-contract',type=Path,required=True); ap.add_argument('--v1-authorization',type=Path,required=True); ap.add_argument('--u2-contract',type=Path,required=True); ap.add_argument('--u2-authorization',type=Path,required=True); ap.add_argument('--u2-summary',type=Path,required=True); ap.add_argument('--output',type=Path,required=True); a=ap.parse_args(); req(not a.output.exists(),'measurement contract exists')
 v1=load(a.v1_contract); u2=load(a.u2_contract); us=load(a.u2_summary); v1c=sha(a.v1_contract); v1a=sha(a.v1_authorization); u2c=sha(a.u2_contract); u2a=sha(a.u2_authorization); req(us.get('status')=='COMPLETED_UPDATER_RECOVERY_V2' and us.get('contract_sha256')==u2c and us.get('authorization_sha256')==u2a and us.get('scientific_outcomes_read') is False,'U2 summary drift')
 v1run=Path(v1['run_root']); u2run=Path(u2['run_root']); groups=[]
 for name,rep,run,pc,pa in [('rep1',1,v1run,v1c,v1a),('rep2',2,u2run,u2c,u2a)]:
  states=[bind_state(run/f'states/e1-tsr-00/replicate_{rep}/{arm}',arm,pc,pa) for arm in ('win_c','first_fail')]; groups.append({'group':name,'replicate':rep,'parent_contract_path':str(a.v1_contract if rep==1 else a.u2_contract),'parent_contract_sha256':pc,'parent_authorization_path':str(a.v1_authorization if rep==1 else a.u2_authorization),'parent_authorization_sha256':pa,'learned_states':states})
 code={'actor_wrapper':'scripts/run_e2_r17_actor_pool_first_fail_exact_replay_measurement.py','preflight_authorizer':'scripts/authorize_e2_r17_first_fail_exact_replay_measurement_preflight.py','actual_path_preflight':'scripts/preflight_e2_r17_first_fail_exact_replay_measurement_actual_path.py','authorizer':'scripts/authorize_e2_r17_first_fail_exact_replay_measurement.py','runner':'scripts/run_e2_r17_first_fail_exact_replay_measurement.py','audit':'scripts/audit_e2_r17_first_fail_exact_replay_measurement_completion.py','analysis_authorizer':'scripts/authorize_e2_r17_first_fail_exact_replay_measurement_analysis.py','analyzer':'scripts/analyze_e2_r17_first_fail_exact_replay_measurement.py','measurement_compat':'scripts/run_e2_r17_actor_pool_measurement_compat_v1.py','provider_budget':'research_pipeline/e2_r17_provider_budget.py'}; bound={k:{'path':v,'sha256':sha(ROOT/v)} for k,v in code.items()}
 p={'schema_version':'1.0','artifact_type':'e2-r17-first-fail-exact-replay-measurement-contract','created_at_utc':datetime.now(timezone.utc).isoformat(timespec='seconds'),'status':'FROZEN_E2_R17_FIRST_FAIL_EXACT_REPLAY_MEASUREMENT','scientific_object':'E2-R17-SINGLE-CASE-FIRST-FAIL-EXACT-REPLAY-MEASUREMENT-20260902','authority':{'scientific_experiment':False,'provider_io':False,'updater':False,'heldout_evaluation':False,'analyzer':False,'paper_promotion':False,'submission':False},'case_stream':'e1-tsr-00','state_groups':groups,'heldout_task_ids':v1['heldout_task_ids'],'suite':v1['suite'],'mindmemos':v1['mindmemos'],'model_identity':v1['model_identity'],'actor_runtime':v1['actor_runtime'],'actor':v1['actor'],'env_file':v1['env_file'],'budget':{'total_limit':191,'per_unit_limit':11},'scientific_scope':{'new_learned_states':0,'measurement_states':4,'heldout_units':72,'replicates':[1,2]},'replication_gate':v1['replication_gate'],'bound_code':bound,'preflight_root':'/data/wyt/e2-r17-search-projection/runs/single-case-first-fail-exact-replay-measurement-preflight-20260902','run_root':'/data/wyt/e2-r17-search-projection/runs/single-case-first-fail-exact-replay-measurement-20260902','lineage_lease_path':'/data/wyt/e2-r17-search-projection/lineage-leases/e2-r17-first-fail-exact-replay-measurement-v1.json','git_commit_at_freeze':subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip()}; atomic(a.output,p); print(json.dumps({'status':p['status'],'sha256':sha(a.output),'groups':2,'heldout':72},indent=2)); return 0
if __name__=='__main__': raise SystemExit(main())
