#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json, sqlite3, subprocess, sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from scripts.run_e2_r17_e1_a_pool_support import validate_runtime as validate_actor_runtime
ARMS=("g0_base","g1_verify","g2_complete","g3_complete_recover")
def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p:Path)->dict[str,Any]:return json.loads(p.read_text(encoding='utf-8'))
def req(c:bool,m:str)->None:
    if not c:raise RuntimeError(m)
def rows(p:Path)->list[dict[str,Any]]:return [json.loads(x) for x in p.read_text(encoding='utf-8').splitlines() if x.strip()]
def atomic(p:Path,d:dict[str,Any])->None:p.parent.mkdir(parents=True,exist_ok=True);t=p.with_suffix(p.suffix+'.tmp');t.write_text(json.dumps(d,ensure_ascii=False,indent=2,sort_keys=True)+'\n',encoding='utf-8');t.replace(p)
def main()->int:
    ap=argparse.ArgumentParser();ap.add_argument('--contract',type=Path,required=True);ap.add_argument('--output',type=Path,required=True);a=ap.parse_args();req(not a.output.exists(),'recovery2 preflight exists');c=load(a.contract);req(c.get('status')=='FROZEN_E2_R17_SINGLE_CASE_CONSTRAINED_STATE_MICRO','contract drift');req(not any((c.get('authority') or {}).values()),'contract grants authority');rec=c['recovery2'];parent=Path(rec['parent_run_root']);lease=Path(rec['parent_lease_path']);req(parent.is_dir() and lease.is_file(),'parent root/lease missing');req(load(lease).get('status')=='FAIL_CLOSED_CONSTRAINED_STATE_MICRO','parent not fail-closed');fp=parent/rec['parent_failure_relpath'];req(fp.is_file() and sha(fp)==rec['parent_failure_sha256'],'failure drift');fd=load(fp);req(fd.get('arm')=='g2_complete' and fd.get('task_id')=='r17-b4-msp-p8' and 'weekly usage quota' in str(fd.get('stderr_tail','')),'not explicit weekly 429');req(not Path(c['run_root']).exists() and not Path(c['lineage_lease_path']).exists(),'child root/lease exists')
    held=c['heldout_task_ids'];states={s['arm']:s for s in c['states']};req(tuple(states)==ARMS,'state order drift');counts={};claims={};remaining=[]
    for arm in ARMS:
        s=states[arm];sp=Path(s['skill_path']);req(sp.is_file() and sha(sp)==s['skill_sha256'],f'skill drift {arm}');pm=Path(rec['parent_manifests'][arm]['path']);req(pm.is_file() and sha(pm)==rec['parent_manifests'][arm]['sha256'],f'parent manifest drift {arm}');pr=rows(pm);ids=[r['task_id'] for r in pr];req(len(ids)==len(set(ids)),f'parent duplicate {arm}');counts[arm]=len(ids);remaining.extend((arm,t) for t in held if t not in set(ids));db=parent/'measurement'/arm/'provider_budget.sqlite3';req(db.is_file(),f'parent ledger missing {arm}');con=sqlite3.connect(f'file:{db}?mode=ro',uri=True);claims[arm]=con.execute('select count(*) from claims').fetchone()[0];con.close()
    req(counts=={'g0_base':11,'g1_verify':11,'g2_complete':11,'g3_complete_recover':12},'parent completion counts drift');req(claims=={'g0_base':55,'g1_verify':60,'g2_complete':65,'g3_complete_recover':65},'parent claim counts drift');req(len(remaining)==27 and ('g2_complete','r17-b4-msp-p8') in remaining,'remaining set drift');orig=rec['original_failed_lineage'];odb=Path(orig['provider_ledger_path']);req(odb.is_file(),'original failed ledger missing');con=sqlite3.connect(f'file:{odb}?mode=ro',uri=True);oc=con.execute('select count(*) from claims').fetchone()[0];con.close();req(oc==3,'original failed claims drift');cumulative=dict(claims);cumulative['g3_complete_recover']+=oc;req(max(cumulative.values())==68 and int(rec['child_provider_total_limit'])==123,'residual budget drift');req(all(v+123<=191 for v in cumulative.values()),'cumulative budget breach')
    for label,item in c['bound_code'].items():p=ROOT/item['path'];req(p.is_file() and sha(p)==item['sha256'],f'bound code drift {label}')
    suite=Path(c['suite']['root']);req(sha(suite/'suite_manifest.json')==c['suite']['suite_manifest_sha256'],'suite drift');req(sha(suite/'r17_split_manifest.json')==c['suite']['split_manifest_sha256'],'split drift');py,_=validate_actor_runtime({'runtime':c['actor_runtime']});req(py.is_file(),'actor runtime missing');identity=ROOT/c['model_identity']['path'];req(identity.is_file() and sha(identity)==c['model_identity']['sha256'],'identity drift');mind=Path(c['mindmemos']['root']);head=subprocess.check_output(['git','-C',str(mind),'rev-parse','HEAD'],text=True).strip();req(head==c['mindmemos']['commit'],'MindMemOS drift')
    out={'schema_version':'1.0','artifact_type':'e2-r17-constrained-state-micro-recovery2-zero-provider-preflight','created_at_utc':datetime.now(timezone.utc).isoformat(timespec='seconds'),'status':'PASS_CONSTRAINED_STATE_MICRO_ZERO_PROVIDER_PREFLIGHT','contract_path':str(a.contract),'contract_sha256':sha(a.contract),'parent_completed_measurements':45,'new_measurements':27,'explicit_429_recovery_units':1,'never_started_measurements':26,'parent_claims_by_arm':claims,'original_failed_claims_g3':3,'cumulative_claims_before_child':cumulative,'child_provider_total_limit':123,'provider_calls':0,'provider_claims':0,'scientific_outcomes_read':False,'partial_effect_read':False,'analyzer_run':False,'next_gate':'MINT_RECOVERY2_MEASUREMENT_AUTHORIZATION'};atomic(a.output,out);print(json.dumps(out,ensure_ascii=False,indent=2,sort_keys=True));return 0
if __name__=='__main__':raise SystemExit(main())
