/* Published contract checks; browser interactions are tested separately. */
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const site = fs.existsSync(path.join(root, '_site')) ? path.join(root, '_site') : root;
const read = p => fs.readFileSync(path.join(site, p), 'utf8');
const data = JSON.parse(read('generated/agent-safety-atlas.json'));
assert.equal(data.problems.length, 24);
assert.equal(data.themes.length, 8);
assert.equal(data.sources.filter(s=>s.kind==='paper').length, 576);
assert.equal(data.publication_counts.published_verified,46);
assert.equal(data.publication_counts.published_2026,14);
assert.equal(data.curated_publication_counts.preprint,10);
assert.equal(data.curated_publication_counts.indexed_unverified,1);
assert.equal(data.publication_counts.documentation,4);
assert.equal(data.human_workflow.problem_confirmation, false);
assert.equal(data.human_workflow.solution_confirmation, false);
assert.equal(data.human_workflow.experiment_count, 0);
const ids = new Set(data.sources.map(s=>s.id));
for (const p of data.problems) {
  assert.ok(p.example && p.why_it_matters && p.existing_progress && p.open_question);
  assert.ok(p.source_refs.every(id=>ids.has(id)));
  assert.equal(p.human_confirmed, false);
}
const html = read('agent-safety-atlas.html');
for (const text of ['主题地图','逐项阅读','证据覆盖','并排比较','复制给聊天确认','不是服务器确认']) assert.ok(html.includes(text), text);
for (const name of ['agent-safety-atlas.css','agent-safety-atlas.js','agent-safety-industry.css','agent-safety-industry.js']) assert.ok(fs.existsSync(path.join(site,name)));
assert.ok(read('data.js').includes('agent-safety-atlas.html'));
assert.ok(read('page-architecture-data.js').includes('links:["agent-safety-atlas.html"'));
assert.ok(read('app.js').includes('["agent-safety-atlas.html","挑选安全研究难点"]'));
assert.ok(read('skill-security-research.html').includes('agent-safety-atlas.html'));
const script = read('agent-safety-atlas.js');
assert.ok(script.includes('REVIEW_DRAFT_NOT_CONFIRMATION'));
assert.ok(script.includes('saved?.revision===data.revision'));
assert.ok(!script.includes('method: \'POST\''));
assert.ok(html.includes('source-status'));
assert.ok(html.includes('已核验正式发表'));
assert.ok(read('bibliography.html').includes('generated/agent-safety-literature.js'));
const vm=require('node:vm');const context={window:{}};
vm.runInNewContext(read('generated/agent-safety-literature.js'),context,{timeout:1000});
const rows=context.window.AGENT_SAFETY_LITERATURE;
assert.equal(rows.length,576);
assert.equal(rows.filter(r=>r.publicationStatus==='published_verified').length,46);
assert.equal(rows.find(r=>r.atlasSourceId==='S04').year,2025);
assert.equal(rows.find(r=>r.atlasSourceId==='P109').publicationTrack,'iaai');
assert.equal(rows.find(r=>r.atlasSourceId==='P137').publicationStatus,'indexed_unverified');
assert.ok(read('app.js').includes('window.AGENT_SAFETY_LITERATURE'));
assert.equal(data.frontier_collection.retained_new_records,519);
assert.equal(data.industry_counts.companies,6);
assert.equal(data.industry_counts.signals,8);
assert.ok(data.industry.signals.every(s=>s.already_addressed && s.boundary && !s.human_confirmed));
assert.ok(html.includes('大厂公开难点'));
assert.ok(html.includes('source-depth'));
assert.ok(html.includes('<option value="papers">全部论文与arXiv'));
assert.ok(read('app.js').includes('function discoveryPaperCard'));
assert.equal(rows.find(r=>r.atlasSourceId==='AX-2608-25512').publicationShort,'arXiv’26');
assert.equal(rows.filter(r=>r.evidenceRole==='discovery_only').length,519);
console.log('PASS inclusive arXiv and industry map: 576 indexed papers,46 verified,519 discovery-only;6 organizations/8 leads; no confirmations');
