/* Offline behavior contract, not a claim of final-size human visual review. */
const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const data=JSON.parse(read('generated/figure-curated.json'));
assert.equal(data.entries.length,6);assert.equal(data.summary.original_entries,2081);
assert.equal(data.summary.archived_entries,2075);assert.equal(data.policy.archive_loaded_by_default,false);
assert.equal(data.entries.find(e=>e.id==='f4p-f1e5ddbcc161b3').chart,'line');
assert(data.entries.every(e=>e.source_name==='Figures4Papers'&&e.reference_only&&e.review.human_approved===false));
const audit=JSON.parse(read('generated/figure-curation-audit.json'));
assert.equal(audit.items.length,2081);assert.equal(new Set(audit.items.map(e=>e.id)).size,2081);
assert.equal(Object.values(audit.counts).reduce((a,b)=>a+b,0),2081);
const html=read('figure-knowledge-base.html');
assert(html.includes('generated/figure-curated.js'));assert(!html.includes('generated/figure-knowledge-base.js'));
assert(!html.includes('src="figure-knowledge-base.js"'));
assert(read('figure-source-archive.html').includes('generated/figure-knowledge-base.js'));
assert(!read('experiment-data-preparation.html').includes('figure-knowledge-summary.js'));
const nodes={};for(const id of ['curated-grid','curated-search','curated-group','selection-status','selection-count','gallery-title','gallery-intro','references-title','selection-heading','selection-help','question-label','reader-question','export-brief','curated-metrics','audit-counts','figure-detail','figure-dialog','language-toggle','close-dialog','result-count'])nodes[id]={value:'',innerHTML:'',textContent:'',addEventListener(n,f){this[n]=f},querySelectorAll(){return []},showModal(){this.open=true},close(){this.open=false}};
let exported;const storage={};
const box={window:{FIGURE_CURATED:data},document:{getElementById:id=>nodes[id],documentElement:{},addEventListener(){},createElement(){return {click(){}}}},localStorage:{getItem:k=>storage[k],setItem:(k,v)=>storage[k]=v},URL,Blob,setTimeout:f=>f()};
box.URL=class extends URL{static createObjectURL(b){exported=b;return 'blob:test'}static revokeObjectURL(){}};
vm.createContext(box);vm.runInContext(read('figure-curated.js'),box);const ui=box.window.curatedFigureUI;
assert.equal(ui.getVisible().length,6);assert.equal((nodes['curated-grid'].innerHTML.match(/class="reference-card/g)||[]).length,6);
const ids=data.entries.map(e=>e.id);ui.toggle(ids[0]);ui.toggle(ids[1]);ui.toggle(ids[2]);assert.equal(ui.getSelected().length,2);
assert.equal(ui.exportBrief(),null);nodes['reader-question'].value='Which component changes measured performance?';
const brief=ui.exportBrief();assert.equal(brief.entries.length,2);assert.equal(brief.reference_scope,'curated_only');assert.equal(brief.visual_review,'NOT_RUN');assert.equal(brief.scientific_authority,false);
assert(!JSON.stringify(brief).includes('SUPPORT_ASSET'));assert.equal(brief.catalog_version,data.catalog_version);
nodes['curated-group'].value='matrix';nodes['curated-group'].change();assert.equal(ui.getVisible().length,1);
nodes['curated-group'].value='';nodes['curated-search'].value='training';nodes['curated-search'].input();assert.equal(ui.getVisible().length,1);
nodes['language-toggle'].onclick();assert.equal(box.document.documentElement.lang,'en');
console.log('PASS: six curated examples; 2081 accounted; raw archive not loaded; corrected chart identity; 2-reference bounded export; filters and bilingual controls');
